// Refonte visuelle console 2026-08 — chantier icônes.
//
// Registre NOM D'EXPORT lucide-react → composant, pour les 135 items de
// `buildAdminNav()` (src/lib/admin-nav.ts). Le SSOT nav garde un champ
// `icon: string` (frontière RSC : le layout serveur passe `items` en prop au
// client — une référence de composant ne se sérialise pas) ; les consommateurs
// CLIENT (`<AdminSidebarNav>`, `<AdminCommandPalette>`) résolvent le nom via
// `navIcon()` au rendu.
//
// Contrat (verrouillé par admin-nav-icons.test.ts, tolérance zéro) :
//   - chaque `item.icon` du SSOT résout ici (pas de repli FolderOpen muet) ;
//   - aucune entrée orpheline (icône enregistrée mais utilisée nulle part).
// Toute icône ajoutée/retirée dans admin-nav.ts doit donc être propagée ici.
//
// NB noms : `AlertTriangle`, `BarChart3`, `HelpCircle` sont des alias d'export
// lucide (canoniques `TriangleAlert`, `ChartColumn`, `CircleQuestionMark`) —
// conservés car déjà en usage dans la console avant cette refonte.

import {
  Activity,
  AlertTriangle,
  Antenna,
  AudioLines,
  BadgeCheck,
  BadgePercent,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  BookOpenText,
  BookUser,
  Briefcase,
  Building2,
  Calculator,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  ChartColumnBig,
  ChartGantt,
  ChartLine,
  ChartNoAxesCombined,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  ClipboardCheck,
  ClipboardList,
  Coins,
  Compass,
  Contact,
  Copy,
  Cpu,
  DatabaseBackup,
  ExternalLink,
  Eye,
  Factory,
  FileCode,
  FilePlus,
  FileSearch,
  FileText,
  FlaskConical,
  FolderKanban,
  FolderOpen,
  Folders,
  Funnel,
  Globe,
  Hammer,
  Handshake,
  HelpCircle,
  IdCard,
  Image,
  Images,
  Inbox,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  ListOrdered,
  Lock,
  LogIn,
  Mail,
  MailCheck,
  MailWarning,
  Map,
  MessagesSquare,
  Mic,
  Network,
  Newspaper,
  OctagonAlert,
  Package,
  Printer,
  PackagePlus,
  Palette,
  Paperclip,
  PenLine,
  PhoneCall,
  Presentation,
  Projector,
  QrCode,
  Quote,
  Radar,
  RadioTower,
  Receipt,
  RefreshCw,
  Repeat,
  Rocket,
  Rss,
  Ruler,
  Scale,
  ScanSearch,
  ScrollText,
  Send,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Siren,
  SquareKanban,
  Star,
  Table,
  Tag,
  Tags,
  Target,
  Telescope,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserPen,
  UserPlus,
  UserSearch,
  Users,
  WandSparkles,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Registre exhaustif des icônes réellement utilisées par la nav admin. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  Activity,
  AlertTriangle,
  Antenna,
  AudioLines,
  BadgeCheck,
  BadgePercent,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  BookOpenText,
  BookUser,
  Briefcase,
  Building2,
  Calculator,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  ChartColumnBig,
  ChartGantt,
  ChartLine,
  ChartNoAxesCombined,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  ClipboardCheck,
  ClipboardList,
  Coins,
  Compass,
  Contact,
  Copy,
  Cpu,
  DatabaseBackup,
  ExternalLink,
  Eye,
  Factory,
  FileCode,
  FilePlus,
  FileSearch,
  FileText,
  FlaskConical,
  FolderKanban,
  FolderOpen,
  Folders,
  Funnel,
  Globe,
  Hammer,
  Handshake,
  HelpCircle,
  IdCard,
  Image,
  Images,
  Inbox,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  ListOrdered,
  Lock,
  LogIn,
  Mail,
  MailCheck,
  MailWarning,
  Map,
  MessagesSquare,
  Mic,
  Network,
  Newspaper,
  OctagonAlert,
  Package,
  Printer,
  PackagePlus,
  Palette,
  Paperclip,
  PenLine,
  PhoneCall,
  Presentation,
  Projector,
  QrCode,
  Quote,
  Radar,
  RadioTower,
  Receipt,
  RefreshCw,
  Repeat,
  Rocket,
  Rss,
  Ruler,
  Scale,
  ScanSearch,
  ScrollText,
  Send,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Siren,
  SquareKanban,
  Star,
  Table,
  Tag,
  Tags,
  Target,
  Telescope,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserPen,
  UserPlus,
  UserSearch,
  Users,
  WandSparkles,
  Workflow,
  Wrench,
  Zap,
};

/**
 * Résout un nom d'icône du SSOT nav en composant lucide.
 * Repli `FolderOpen` par sécurité runtime UNIQUEMENT — le test structurel
 * interdit qu'un item du SSOT en dépende.
 */
export function navIcon(name: string): LucideIcon {
  return NAV_ICONS[name] ?? FolderOpen;
}
