/**
 * SEO — détection des routes pSEO en stub (anti-doorway HCU 2024).
 *
 * Edge-safe : utilisé par `middleware.ts` pour émettre `X-Robots-Tag: noindex, follow`
 * en en-tête HTTP. Le `<meta robots noindex>` HTML reste posé par `generateMetadata()`
 * côté Server Component ; le header HTTP en doublon permet à Googlebot de voir le
 * `noindex` SANS rendre le HTML complet → gain crawl budget x5 sur ~17 K stubs.
 *
 * Whitelist hardcodée (pas d'import des datas 2 157 villes pour éviter le bundle
 * Edge bloat). Sync garantie par `seo-noindex-routes.test.ts` qui compare à
 * `getIndexableVilles()` / `getIndexableRegions()`.
 */
import type { Locale } from "@/i18n/routing";

const LOCALES: ReadonlyArray<Locale> = ["fr", "en"];

/**
 * Villes pilotes (= avec `copy/<slug>.ts` éditorial substantiel).
 * Sortent en index dès qu'elles sont ici. Sync test : `seo-noindex-routes.test.ts`.
 */
const INDEXABLE_VILLE_SLUGS: ReadonlySet<string> = new Set([
  "abbeville",
  "acheres",
  "agde",
  "agen",
  "aix-en-provence",
  "aix-les-bains",
  "ajaccio",
  "albi",
  "alencon",
  "ales",
  "alfortville",
  "allauch",
  "amiens",
  "angers",
  "anglet",
  "angouleme",
  "annecy",
  "annemasse",
  "antibes",
  "antony",
  "arcueil",
  "argenteuil",
  "arles",
  "armentieres",
  "arras",
  "asnieres-sur-seine",
  "athis-mons",
  "aubagne",
  "aubervilliers",
  "auch",
  "aulnay-sous-bois",
  "aurillac",
  "auxerre",
  "avignon",
  "bagneux",
  "bagnolet",
  "bastia",
  "bayonne",
  "beaune",
  "beaupreau-en-mauges",
  "beaurepaire",
  "beauvais",
  "begles",
  "belfort",
  "bergerac",
  "besancon",
  "bethune",
  "beziers",
  "bezons",
  "biarritz",
  "blagnac",
  "blois",
  "bobigny",
  "bois-colombes",
  "bondy",
  "bordeaux",
  "bouguenais",
  "boulogne-billancourt",
  "boulogne-sur-mer",
  "bourg-de-peage",
  "bourg-en-bresse",
  "bourg-la-reine",
  "bourg-les-valence",
  "bourges",
  "bourgoin-jallieu",
  "brest",
  "bretigny-sur-orge",
  "brive-la-gaillarde",
  "bron",
  "bruay-la-buissiere",
  "bruges",
  "brunoy",
  "bussy-saint-georges",
  "cachan",
  "caen",
  "cagnes-sur-mer",
  "cahors",
  "calais",
  "caluire-et-cuire",
  "cambrai",
  "cannes",
  "carcassonne",
  "carpentras",
  "carquefou",
  "carrieres-sous-poissy",
  "castelnau-le-lez",
  "castres",
  "cavaillon",
  "cenon",
  "cergy",
  "chabeuil",
  "challans",
  "chalon-sur-saone",
  "chalons-en-champagne",
  "chambery",
  "champigny-sur-marne",
  "champs-sur-marne",
  "charenton-le-pont",
  "charleville-mezieres",
  "chartres",
  "charvieu-chavagneux",
  "chasse-sur-rhone",
  "chateauroux",
  "chatellerault",
  "chatenay-malabry",
  "chatillon",
  "chatou",
  "chatuzange-le-goubet",
  "chaumont",
  "chavanoz",
  "chaville",
  "chelles",
  "chemille-en-anjou",
  "cherbourg-en-cotentin",
  "chilly-mazarin",
  "choisy-le-roi",
  "cholet",
  "claix",
  "clamart",
  "clermont-ferrand",
  "clichy",
  "clichy-sous-bois",
  "colmar",
  "colombes",
  "colomiers",
  "combs-la-ville",
  "compiegne",
  "concarneau",
  "conflans-sainte-honorine",
  "corbeil-essonnes",
  "cormeilles-en-parisis",
  "coublevie",
  "coudekerque-branche",
  "coueron",
  "courbevoie",
  "creil",
  "crest",
  "creteil",
  "croix",
  "crolles",
  "cugnaux",
  "dammarie-les-lys",
  "dax",
  "decines-charpieu",
  "denain",
  "deuil-la-barre",
  "dieppe",
  "dijon",
  "dole",
  "domene",
  "donzere",
  "douai",
  "draguignan",
  "drancy",
  "draveil",
  "dreux",
  "dunkerque",
  "eaubonne",
  "echirolles",
  "elancourt",
  "epernay",
  "epinal",
  "epinay-sur-seine",
  "ermont",
  "etampes",
  "evreux",
  "evry-courcouronnes",
  "eybens",
  "eysines",
  "fleury-les-aubrais",
  "fontaine",
  "fontenay-aux-roses",
  "fontenay-sous-bois",
  "forbach",
  "fougeres",
  "franconville",
  "frejus",
  "fresnes",
  "frontignan",
  "gagny",
  "gap",
  "gardanne",
  "garges-les-gonesse",
  "gennevilliers",
  "gieres",
  "gif-sur-yvette",
  "givors",
  "gonesse",
  "goussainville",
  "gradignan",
  "grande-synthe",
  "grasse",
  "grenoble",
  "grigny",
  "gujan-mestras",
  "guyancourt",
  "haguenau",
  "halluin",
  "hazebrouck",
  "henin-beaumont",
  "herblay-sur-seine",
  "herouville-saint-clair",
  "houilles",
  "hyeres",
  "illkirch-graffenstaden",
  "issy-les-moulineaux",
  "istres",
  "ivry-sur-seine",
  "joinville-le-pont",
  "joue-les-tours",
  "l-hay-les-roses",
  "l-isle-d-abeau",
  "l-isle-sur-la-sorgue",
  "la-celle-saint-cloud",
  "la-chapelle-sur-erdre",
  "la-ciotat",
  "la-courneuve",
  "la-garde",
  "la-garenne-colombes",
  "la-madeleine",
  "la-roche-sur-yon",
  "la-rochelle",
  "la-seyne-sur-mer",
  "la-teste-de-buch",
  "la-tour-du-pin",
  "la-tronche",
  "la-valette-du-var",
  "la-verpilliere",
  "lagny-sur-marne",
  "lambersart",
  "lanester",
  "lannion",
  "laon",
  "laval",
  "le-blanc-mesnil",
  "le-bouscat",
  "le-cannet",
  "le-chesnay-rocquencourt",
  "le-creusot",
  "le-grand-quevilly",
  "le-havre",
  "le-kremlin-bicetre",
  "le-mans",
  "le-peage-de-roussillon",
  "le-perreux-sur-marne",
  "le-petit-quevilly",
  "le-plessis-robinson",
  "le-plessis-trevise",
  "le-pont-de-claix",
  "lens",
  "les-abrets-en-dauphine",
  "les-avenieres-veyrins-thuellin",
  "les-lilas",
  "les-mureaux",
  "les-pavillons-sous-bois",
  "les-pennes-mirabeau",
  "les-sables-d-olonne",
  "les-ulis",
  "levallois-perret",
  "libourne",
  "lievin",
  "lille",
  "limeil-brevannes",
  "limoges",
  "lingolsheim",
  "livron-sur-drome",
  "livry-gargan",
  "longjumeau",
  "loos",
  "lorient",
  "loriol-sur-drome",
  "lormont",
  "lunel",
  "lyon",
  "macon",
  "maisons-alfort",
  "maisons-laffitte",
  "malakoff",
  "mandelieu-la-napoule",
  "manosque",
  "mantes-la-jolie",
  "mantes-la-ville",
  "marcq-en-bar-ul",
  "marignane",
  "marseille",
  "martigues",
  "massy",
  "maubeuge",
  "maurepas",
  "meaux",
  "melun",
  "menton",
  "merignac",
  "metz",
  "meudon",
  "meylan",
  "meyzieu",
  "millau",
  "miramas",
  "mitry-mory",
  "moirans",
  "mons-en-bar-ul",
  "mont-de-marsan",
  "mont-saint-aignan",
  "montaigu-vendee",
  "montauban",
  "montbeliard",
  "montbonnot-saint-martin",
  "montelimar",
  "montereau-fault-yonne",
  "montfermeil",
  "montgeron",
  "montigny-le-bretonneux",
  "montigny-les-cormeilles",
  "montigny-les-metz",
  "montlucon",
  "montmorency",
  "montpellier",
  "montreuil",
  "montrouge",
  "morsang-sur-orge",
  "mulhouse",
  "muret",
  "nancy",
  "nanterre",
  "nantes",
  "narbonne",
  "neuilly-plaisance",
  "neuilly-sur-marne",
  "neuilly-sur-seine",
  "nevers",
  "nice",
  "nimes",
  "niort",
  "nogent-sur-marne",
  "nogent-sur-oise",
  "noisy-le-grand",
  "noisy-le-sec",
  "nyons",
  "olivet",
  "orange",
  "orleans",
  "orly",
  "orvault",
  "oullins-pierre-benite",
  "oyonnax",
  "ozoir-la-ferriere",
  "palaiseau",
  "pantin",
  "paris",
  "pau",
  "perigueux",
  "perpignan",
  "pessac",
  "pierrelatte",
  "plaisance-du-touch",
  "plaisir",
  "poissy",
  "poitiers",
  "pont-de-cheruy",
  "pont-eveque",
  "pontault-combault",
  "pontcharra",
  "pontoise",
  "portes-les-valence",
  "puteaux",
  "quimper",
  "rambouillet",
  "reims",
  "rennes",
  "reze",
  "rillieux-la-pape",
  "ris-orangis",
  "rives",
  "roanne",
  "rochefort",
  "rodez",
  "roissy-en-brie",
  "romainville",
  "romans-sur-isere",
  "rosny-sous-bois",
  "roubaix",
  "rouen",
  "roussillon",
  "rueil-malmaison",
  "saint-brieuc",
  "saint-chamond",
  "saint-cloud",
  "saint-cyr-l-ecole",
  "saint-denis",
  "saint-dizier",
  "saint-egreve",
  "saint-etienne",
  "saint-etienne-du-rouvray",
  "saint-genis-laval",
  "saint-germain-en-laye",
  "saint-gratien",
  "saint-herblain",
  "saint-ismier",
  "saint-jean-de-braye",
  "saint-laurent-du-var",
  "saint-louis",
  "saint-malo",
  "saint-mande",
  "saint-marcel-les-valence",
  "saint-marcellin",
  "saint-martin-d-heres",
  "saint-martin-d-uriage",
  "saint-martin-le-vinoux",
  "saint-maur-des-fosses",
  "saint-maurice-l-exil",
  "saint-medard-en-jalles",
  "saint-michel-sur-orge",
  "saint-nazaire",
  "saint-ouen-l-aumone",
  "saint-ouen-sur-seine",
  "saint-paul-trois-chateaux",
  "saint-priest",
  "saint-quentin",
  "saint-quentin-fallavier",
  "saint-rambert-d-albon",
  "saint-raphael",
  "saint-sebastien-sur-loire",
  "sainte-foy-les-lyon",
  "sainte-genevieve-des-bois",
  "saintes",
  "salon-de-provence",
  "sannois",
  "sarcelles",
  "sarreguemines",
  "sartrouville",
  "sassenage",
  "saumur",
  "savigny-le-temple",
  "savigny-sur-orge",
  "sceaux",
  "schiltigheim",
  "sens",
  "sete",
  "sevran",
  "sevremoine",
  "sevres",
  "seyssinet-pariset",
  "seyssins",
  "six-fours-les-plages",
  "soissons",
  "sotteville-les-rouen",
  "stains",
  "strasbourg",
  "sucy-en-brie",
  "suresnes",
  "tain-l-hermitage",
  "talence",
  "tarbes",
  "tassin-la-demi-lune",
  "taverny",
  "thiais",
  "thionville",
  "thonon-les-bains",
  "tignieu-jameyzieu",
  "torcy",
  "toulon",
  "toulouse",
  "tourcoing",
  "tournefeuille",
  "tours",
  "trappes",
  "tremblay-en-france",
  "troyes",
  "tullins",
  "valence",
  "valenciennes",
  "vallauris",
  "vand-uvre-les-nancy",
  "vannes",
  "vanves",
  "varces-allieres-et-risset",
  "vaulx-en-velin",
  "velizy-villacoublay",
  "venissieux",
  "vernon",
  "versailles",
  "vertou",
  "vichy",
  "vienne",
  "vierzon",
  "vif",
  "vigneux-sur-seine",
  "villard-bonnot",
  "villefontaine",
  "villefranche-sur-saone",
  "villejuif",
  "villemomble",
  "villenave-d-ornon",
  "villeneuve-d-ascq",
  "villeneuve-la-garenne",
  "villeneuve-le-roi",
  "villeneuve-saint-georges",
  "villeneuve-sur-lot",
  "villeparisis",
  "villepinte",
  "villette-d-anthon",
  "villeurbanne",
  "villiers-le-bel",
  "villiers-sur-marne",
  "vincennes",
  "viry-chatillon",
  "vitrolles",
  "vitry-sur-seine",
  "vizille",
  "voiron",
  "voreppe",
  "wasquehal",
  "wattrelos",
  "yerres",
]);

/**
 * Villes pilotes avec `copy.services.<service>` substantiel — par service.
 * V1 : Paris seul porte les 3 services. Étendu quand un autre `copy/<ville>.ts`
 * ajoute `services.<service>`. Sync test : `seo-noindex-routes.test.ts`.
 */
const ALL_SERVICE_VILLE_SLUGS: ReadonlyArray<string> = [
  "aix-en-provence",
  "amiens",
  "angers",
  "annecy",
  "argenteuil",
  "besancon",
  "bordeaux",
  "boulogne-billancourt",
  "brest",
  "caen",
  "clermont-ferrand",
  "dijon",
  "grenoble",
  "le-havre",
  "le-mans",
  "lille",
  "limoges",
  "lyon",
  "marseille",
  "metz",
  "montpellier",
  "montreuil",
  "mulhouse",
  "nancy",
  "nantes",
  "nice",
  "nimes",
  "orleans",
  "paris",
  "perpignan",
  "reims",
  "rennes",
  "rouen",
  "saint-denis",
  "saint-etienne",
  "strasbourg",
  "toulon",
  "toulouse",
  "tours",
  "villeurbanne",
];

const INDEXABLE_SERVICE_VILLE_SLUGS: Record<
  "audit" | "interventions" | "implementation",
  ReadonlySet<string>
> = {
  audit: new Set(ALL_SERVICE_VILLE_SLUGS),
  interventions: new Set(ALL_SERVICE_VILLE_SLUGS),
  implementation: new Set(ALL_SERVICE_VILLE_SLUGS),
};

/**
 * Régions indexables. 13 métropole + 5 DROM en V1 (Will 2026-05-26 — DROM
 * réintégrés avec pages SEO dédiées hand-crafted : metaTitleFr, metaDescFr,
 * audienceLocalFr, pitchFr, parité avec les 13 régions métropolitaines).
 * Sync test : `seo-noindex-routes.test.ts`.
 */
const INDEXABLE_REGION_SLUGS: ReadonlySet<string> = new Set([
  "auvergne-rhone-alpes",
  "bourgogne-franche-comte",
  "bretagne",
  "centre-val-de-loire",
  "corse",
  "grand-est",
  "guadeloupe",
  "guyane",
  "hauts-de-france",
  "ile-de-france",
  "la-reunion",
  "martinique",
  "mayotte",
  "normandie",
  "nouvelle-aquitaine",
  "occitanie",
  "pays-de-la-loire",
  "provence-alpes-cote-d-azur",
]);

const SERVICE_PATH_TO_KEY: Record<string, "audit" | "interventions" | "implementation"> = {
  audit: "audit",
  interventions: "interventions",
  implementation: "implementation",
};

const SERVICE_VILLE_SEGMENTS: ReadonlySet<string> = new Set(["par-ville", "by-city"]);
const IMPLANTATIONS_SEGMENTS: ReadonlySet<string> = new Set(["implantations", "locations"]);

/**
 * Retourne `true` si le pathname est une route stub anti-doorway qui doit
 * recevoir `X-Robots-Tag: noindex, follow` en plus du `<meta robots>` HTML.
 *
 * Patterns détectés :
 *   - `/[locale]/implantations/<region>` quand region pas indexable (Corse)
 *   - `/[locale]/implantations/<region>/<ville>` quand ville pas pilote
 *   - `/[locale]/<service>/par-ville/<ville>` quand ville sans copy.services
 *
 * Faux négatifs OK (laisser passer une vraie page indexable) : pas de régression.
 * Faux positifs CRITIQUE (mettre noindex sur une page indexable) : audit obligatoire.
 *
 * Toute modification doit passer le test `seo-noindex-routes.test.ts` (sync vs
 * `getIndexableVilles()` / `getIndexableRegions()`).
 */
export function isNoindexStubRoute(pathname: string): boolean {
  const parts = pathname.split("/").filter(Boolean);
  if (parts.length < 3) return false;

  const [locale, section, ...rest] = parts;
  if (!locale || !LOCALES.includes(locale as Locale)) return false;
  if (!section) return false;

  // `/[locale]/implantations/...` ou `/[locale]/locations/...`
  if (IMPLANTATIONS_SEGMENTS.has(section)) {
    const region = rest[0];
    const ville = rest[1];
    if (!region) return false;
    // Région non indexable → noindex
    if (!INDEXABLE_REGION_SLUGS.has(region)) return true;
    // Région indexable mais ville présente → check ville
    if (ville && !INDEXABLE_VILLE_SLUGS.has(ville)) return true;
    return false;
  }

  // `/[locale]/<service>/par-ville/<ville>` ou `/[locale]/<service>/by-city/<ville>`
  const serviceKey = SERVICE_PATH_TO_KEY[section];
  if (serviceKey && rest.length >= 2) {
    const segment = rest[0];
    const ville = rest[1];
    if (segment && SERVICE_VILLE_SEGMENTS.has(segment) && ville) {
      return !INDEXABLE_SERVICE_VILLE_SLUGS[serviceKey].has(ville);
    }
  }

  return false;
}

/** Exposé pour les tests de sync uniquement. */
export const __INTERNAL = {
  INDEXABLE_VILLE_SLUGS,
  INDEXABLE_SERVICE_VILLE_SLUGS,
  INDEXABLE_REGION_SLUGS,
} as const;
