// Zone commerciale /memo-isere — communes OFFICIELLES du corridor
// Grenoble - Valence - Die - Lyon (demande Will 2026-08-12 : « toutes les
// communes entre, sans oublier les petites »).
//
// Source : geo.api.gouv.fr, 13 intercommunalités relevées le 2026-08-12
// (codes EPCI en commentaire de chaque bloc). NE PAS éditer à la main —
// re-relever l'API si un périmètre intercommunal change.
//
// `principales` = communes de 4 000 hab. et plus du bloc (au minimum son
// chef-lieu) : elles portent le JobPosting Google for Jobs (poids JSON-LD
// contenu) ; la liste complète, elle, est VISIBLE sur la page (SEO/AEO/GEO :
// les petites communes comptent).

export interface ZoneCluster {
  /** Libellé humain du territoire. */
  label: string;
  /** Toutes les communes du territoire (ordre alphabétique). */
  communes: readonly string[];
  /** Communes principales (ordre de population décroissant). */
  principales: readonly string[];
}

export const MEMO_ZONE_CLUSTERS: readonly ZoneCluster[] = [
  // EPCI 200040715
  {
    label: "Grenoble & agglomération",
    communes: [
      "Bresson",
      "Brié-et-Angonnes",
      "Champ-sur-Drac",
      "Champagnier",
      "Claix",
      "Corenc",
      "Domène",
      "Eybens",
      "Fontaine",
      "Fontanil-Cornillon",
      "Gières",
      "Grenoble",
      "Herbeys",
      "Jarrie",
      "La Tronche",
      "Le Gua",
      "Le Pont-de-Claix",
      "Le Sappey-en-Chartreuse",
      "Meylan",
      "Miribel-Lanchâtre",
      "Mont-Saint-Martin",
      "Montchaboud",
      "Murianette",
      "Notre-Dame-de-Commiers",
      "Notre-Dame-de-Mésage",
      "Noyarey",
      "Poisat",
      "Proveysieux",
      "Quaix-en-Chartreuse",
      "Saint-Barthélemy-de-Séchilienne",
      "Saint-Georges-de-Commiers",
      "Saint-Martin-d'Hères",
      "Saint-Martin-le-Vinoux",
      "Saint-Paul-de-Varces",
      "Saint-Pierre-de-Mésage",
      "Saint-Égrève",
      "Sarcenas",
      "Sassenage",
      "Seyssinet-Pariset",
      "Seyssins",
      "Séchilienne",
      "Varces-Allières-et-Risset",
      "Vaulnaveys-le-Bas",
      "Vaulnaveys-le-Haut",
      "Venon",
      "Veurey-Voroize",
      "Vif",
      "Vizille",
      "Échirolles",
    ],
    principales: [
      "Grenoble",
      "Saint-Martin-d'Hères",
      "Échirolles",
      "Fontaine",
      "Meylan",
      "Saint-Égrève",
      "Seyssinet-Pariset",
      "Sassenage",
      "Le Pont-de-Claix",
      "Eybens",
      "Varces-Allières-et-Risset",
      "Vif",
      "Seyssins",
      "Claix",
      "Gières",
      "Vizille",
      "Domène",
      "La Tronche",
      "Saint-Martin-le-Vinoux",
      "Corenc",
      "Vaulnaveys-le-Haut",
    ],
  },
  // EPCI 243800984
  {
    label: "Pays Voironnais",
    communes: [
      "Bilieu",
      "Charancieu",
      "Charavines",
      "Charnècles",
      "Chirens",
      "Coublevie",
      "La Buisse",
      "La Murette",
      "La Sure en Chartreuse",
      "Massieu",
      "Merlas",
      "Moirans",
      "Montferrat",
      "Rives",
      "Réaumont",
      "Saint-Aupre",
      "Saint-Blaise-du-Buis",
      "Saint-Bueil",
      "Saint-Cassien",
      "Saint-Geoire-en-Valdaine",
      "Saint-Jean-de-Moirans",
      "Saint-Nicolas-de-Macherin",
      "Saint-Sulpice-des-Rivoires",
      "Saint-Étienne-de-Crossey",
      "Tullins",
      "Velanne",
      "Villages du Lac de Paladru",
      "Voiron",
      "Voissant",
      "Voreppe",
      "Vourey",
    ],
    principales: ["Voiron", "Voreppe", "Moirans", "Tullins", "Rives", "Coublevie"],
  },
  // EPCI 200070431
  {
    label: "Sud-Grésivaudan",
    communes: [
      "Auberives-en-Royans",
      "Beaulieu",
      "Beauvoir-en-Royans",
      "Bessins",
      "Chantesse",
      "Chasselay",
      "Chatte",
      "Chevrières",
      "Choranche",
      "Châtelus",
      "Cognin-les-Gorges",
      "Cras",
      "Izeron",
      "L'Albenc",
      "La Rivière",
      "La Sône",
      "Malleval-en-Vercors",
      "Montagne",
      "Montaud",
      "Morette",
      "Murinais",
      "Notre-Dame-de-l'Osier",
      "Poliénas",
      "Pont-en-Royans",
      "Presles",
      "Quincieu",
      "Rencurel",
      "Rovon",
      "Saint Antoine l'Abbaye",
      "Saint-André-en-Royans",
      "Saint-Appolinard",
      "Saint-Bonnet-de-Chavagne",
      "Saint-Gervais",
      "Saint-Hilaire-du-Rosier",
      "Saint-Just-de-Claix",
      "Saint-Lattier",
      "Saint-Marcellin",
      "Saint-Pierre-de-Chérennes",
      "Saint-Quentin-sur-Isère",
      "Saint-Romans",
      "Saint-Sauveur",
      "Saint-Vérand",
      "Serre-Nerpol",
      "Têche",
      "Varacieux",
      "Vatilieu",
      "Vinay",
    ],
    principales: ["Saint-Marcellin", "Vinay"],
  },
  // EPCI 243801073
  {
    label: "Bièvre Est",
    communes: [
      "Apprieu",
      "Beaucroissant",
      "Bizonnes",
      "Burcin",
      "Bévenais",
      "Châbons",
      "Colombe",
      "Eydoche",
      "Flachères",
      "Izeaux",
      "Le Grand-Lemps",
      "Oyeu",
      "Renage",
      "Saint-Didier-de-Bizonnes",
    ],
    principales: ["Apprieu"],
  },
  // EPCI 200059392
  {
    label: "Bièvre Isère",
    communes: [
      "Artas",
      "Beaufort",
      "Beauvoir-de-Marc",
      "Bossieu",
      "Bressieux",
      "Brion",
      "Brézins",
      "Champier",
      "Châtenay",
      "Châtonnay",
      "Culin",
      "Faramans",
      "Gillonnay",
      "La Côte-Saint-André",
      "La Forteresse",
      "La Frette",
      "Lentiol",
      "Lieudieu",
      "Longechenal",
      "Marcilloles",
      "Marcollin",
      "Marnans",
      "Meyrieu-les-Étangs",
      "Montfalcon",
      "Mottier",
      "Ornacieux-Balbins",
      "Pajay",
      "Penol",
      "Plan",
      "Porte-des-Bonnevaux",
      "Royas",
      "Roybon",
      "Saint-Agnin-sur-Bion",
      "Saint-Clair-sur-Galaure",
      "Saint-Geoirs",
      "Saint-Hilaire-de-la-Côte",
      "Saint-Jean-de-Bournay",
      "Saint-Michel-de-Saint-Geoirs",
      "Saint-Paul-d'Izeaux",
      "Saint-Pierre-de-Bressieux",
      "Saint-Siméon-de-Bressieux",
      "Saint-Étienne-de-Saint-Geoirs",
      "Sainte-Anne-sur-Gervonde",
      "Sardieu",
      "Savas-Mépin",
      "Sillans",
      "Thodure",
      "Tramolé",
      "Villeneuve-de-Marc",
      "Viriville",
    ],
    principales: ["La Côte-Saint-André", "Saint-Jean-de-Bournay"],
  },
  // EPCI 243800604
  {
    label: "Nord-Isère — Bourgoin-Jallieu",
    communes: [
      "Bourgoin-Jallieu",
      "Châteauvilain",
      "Chèzeneuve",
      "Crachier",
      "Domarin",
      "Eclose-Badinières",
      "Four",
      "L'Isle-d'Abeau",
      "La Verpillière",
      "Les Éparres",
      "Maubec",
      "Meyrié",
      "Nivolas-Vermelle",
      "Ruy-Montceau",
      "Saint-Alban-de-Roche",
      "Saint-Quentin-Fallavier",
      "Saint-Savin",
      "Satolas-et-Bonce",
      "Succieu",
      "Sérézin-de-la-Tour",
      "Vaulx-Milieu",
      "Villefontaine",
    ],
    principales: [
      "Bourgoin-Jallieu",
      "Villefontaine",
      "L'Isle-d'Abeau",
      "La Verpillière",
      "Saint-Quentin-Fallavier",
      "Ruy-Montceau",
      "Saint-Savin",
    ],
  },
  // EPCI 200077014
  {
    label: "Vienne & vallée du Rhône",
    communes: [
      "Ampuis",
      "Chasse-sur-Rhône",
      "Chonas-l'Amballan",
      "Chuzelles",
      "Condrieu",
      "Estrablin",
      "Eyzin-Pinet",
      "Jardin",
      "Les Côtes-d'Arey",
      "Les Haies",
      "Loire-sur-Rhône",
      "Longes",
      "Luzinay",
      "Meyssiez",
      "Moidieu-Détourbe",
      "Pont-Évêque",
      "Reventin-Vaugris",
      "Saint-Cyr-sur-le-Rhône",
      "Saint-Romain-en-Gal",
      "Saint-Romain-en-Gier",
      "Saint-Sorlin-de-Vienne",
      "Sainte-Colombe",
      "Septème",
      "Serpaize",
      "Seyssuel",
      "Trèves",
      "Tupin-et-Semons",
      "Vienne",
      "Villette-de-Vienne",
      "Échalas",
    ],
    principales: ["Vienne", "Chasse-sur-Rhône", "Pont-Évêque"],
  },
  // EPCI 200085751
  {
    label: "Pays roussillonnais",
    communes: [
      "Agnin",
      "Anjou",
      "Assieu",
      "Auberives-sur-Varèze",
      "Beaurepaire",
      "Bellegarde-Poussieu",
      "Bougé-Chambalud",
      "Chalon",
      "Chanas",
      "Cheyssieu",
      "Clonas-sur-Varèze",
      "Cour-et-Buis",
      "Jarcieu",
      "La Chapelle-de-Surieu",
      "Le Péage-de-Roussillon",
      "Les Roches-de-Condrieu",
      "Moissieu-sur-Dolon",
      "Monsteroux-Milieu",
      "Montseveroux",
      "Pact",
      "Pisieu",
      "Pommier-de-Beaurepaire",
      "Primarette",
      "Revel-Tourdan",
      "Roussillon",
      "Sablons",
      "Saint-Alban-du-Rhône",
      "Saint-Barthélemy",
      "Saint-Clair-du-Rhône",
      "Saint-Julien-de-l'Herms",
      "Saint-Maurice-l'Exil",
      "Saint-Prim",
      "Saint-Romain-de-Surieu",
      "Salaise-sur-Sanne",
      "Sonnay",
      "Vernioz",
      "Ville-sous-Anjou",
    ],
    principales: [
      "Roussillon",
      "Saint-Maurice-l'Exil",
      "Le Péage-de-Roussillon",
      "Beaurepaire",
      "Salaise-sur-Sanne",
    ],
  },
  // EPCI 200068781
  {
    label: "Valence & Romans",
    communes: [
      "Alixan",
      "Barbières",
      "Barcelonne",
      "Beaumont-lès-Valence",
      "Beauregard-Baret",
      "Beauvallon",
      "Bourg-de-Péage",
      "Bourg-lès-Valence",
      "Bésayes",
      "Chabeuil",
      "Charpey",
      "Chatuzange-le-Goubet",
      "Châteaudouble",
      "Châteauneuf-sur-Isère",
      "Châtillon-Saint-Jean",
      "Clérieux",
      "Combovin",
      "Crépol",
      "Eymeux",
      "Geyssans",
      "Granges-les-Beaumont",
      "Génissieux",
      "Hostun",
      "Jaillans",
      "La Baume-Cornillane",
      "La Baume-d'Hostun",
      "Le Chalon",
      "Malissard",
      "Marches",
      "Montmeyran",
      "Montmiral",
      "Montvendre",
      "Montélier",
      "Montéléger",
      "Mours-Saint-Eusèbe",
      "Ourches",
      "Parnans",
      "Peyrins",
      "Peyrus",
      "Portes-lès-Valence",
      "Rochefort-Samson",
      "Romans-sur-Isère",
      "Saint-Bardoux",
      "Saint-Christophe-et-le-Laris",
      "Saint-Laurent-d'Onay",
      "Saint-Marcel-lès-Valence",
      "Saint-Michel-sur-Savasse",
      "Saint-Paul-lès-Romans",
      "Saint-Vincent-la-Commanderie",
      "Triors",
      "Upie",
      "Valence",
      "Valherbasse",
      "Étoile-sur-Rhône",
    ],
    principales: [
      "Valence",
      "Romans-sur-Isère",
      "Bourg-lès-Valence",
      "Portes-lès-Valence",
      "Bourg-de-Péage",
      "Chabeuil",
      "Chatuzange-le-Goubet",
      "Saint-Marcel-lès-Valence",
      "Étoile-sur-Rhône",
      "Beaumont-lès-Valence",
      "Montélier",
      "Châteauneuf-sur-Isère",
    ],
  },
  // EPCI 200067767
  {
    label: "Royans-Vercors",
    communes: [
      "Bouvante",
      "La Chapelle-en-Vercors",
      "La Motte-Fanjas",
      "Le Chaffal",
      "Léoncel",
      "Oriol-en-Royans",
      "Rochechinard",
      "Saint-Agnan-en-Vercors",
      "Saint-Jean-en-Royans",
      "Saint-Julien-en-Vercors",
      "Saint-Laurent-en-Royans",
      "Saint-Martin-en-Vercors",
      "Saint-Martin-le-Colonel",
      "Saint-Nazaire-en-Royans",
      "Saint-Thomas-en-Royans",
      "Sainte-Eulalie-en-Royans",
      "Vassieux-en-Vercors",
      "Échevis",
    ],
    principales: ["Saint-Jean-en-Royans"],
  },
  // EPCI 200040509
  {
    label: "Vallée de la Drôme — Crest",
    communes: [
      "Aouste-sur-Sye",
      "Aubenasson",
      "Aurel",
      "Chastel-Arnaud",
      "Crest",
      "Espenel",
      "La Chaudière",
      "Mirabel-et-Blacons",
      "Piégros-la-Clastre",
      "Rimon-et-Savel",
      "Saillans",
      "Saint-Benoit-en-Diois",
      "Saint-Sauveur-en-Diois",
      "Vercheny",
    ],
    principales: ["Crest"],
  },
  // EPCI 242600534
  {
    label: "Diois — Die",
    communes: [
      "Arnayon",
      "Aucelon",
      "Barnave",
      "Barsac",
      "Beaumont-en-Diois",
      "Beaurières",
      "Bellegarde-en-Diois",
      "Boulc",
      "Brette",
      "Chalancon",
      "Chamaloc",
      "Charens",
      "Châtillon-en-Diois",
      "Die",
      "Establet",
      "Glandage",
      "Gumiane",
      "Jonchères",
      "La Bâtie-des-Fonds",
      "La Motte-Chalancon",
      "Laval-d'Aix",
      "Les Prés",
      "Lesches-en-Diois",
      "Luc-en-Diois",
      "Lus-la-Croix-Haute",
      "Marignac-en-Diois",
      "Menglon",
      "Miscon",
      "Montlaur-en-Diois",
      "Montmaur-en-Diois",
      "Pennes-le-Sec",
      "Ponet-et-Saint-Auban",
      "Pontaix",
      "Poyols",
      "Pradelle",
      "Recoubeau-Jansac",
      "Rochefourchat",
      "Romeyer",
      "Rottier",
      "Saint-Andéol",
      "Saint-Dizier-en-Diois",
      "Saint-Julien-en-Quint",
      "Saint-Nazaire-le-Désert",
      "Saint-Roman",
      "Sainte-Croix",
      "Solaure en Diois",
      "Vachères-en-Quint",
      "Val-Maravel",
      "Valdrôme",
      "Volvent",
    ],
    principales: ["Die"],
  },
  // EPCI 200046977
  {
    label: "Lyon & métropole",
    communes: [
      "Albigny-sur-Saône",
      "Bron",
      "Cailloux-sur-Fontaines",
      "Caluire-et-Cuire",
      "Champagne-au-Mont-d'Or",
      "Charbonnières-les-Bains",
      "Charly",
      "Chassieu",
      "Collonges-au-Mont-d'Or",
      "Corbas",
      "Couzon-au-Mont-d'Or",
      "Craponne",
      "Curis-au-Mont-d'Or",
      "Dardilly",
      "Décines-Charpieu",
      "Feyzin",
      "Fleurieu-sur-Saône",
      "Fontaines-Saint-Martin",
      "Fontaines-sur-Saône",
      "Francheville",
      "Genay",
      "Givors",
      "Grigny-sur-Rhône",
      "Irigny",
      "Jonage",
      "La Mulatière",
      "La Tour-de-Salvagny",
      "Limonest",
      "Lissieu",
      "Lyon",
      "Marcy-l'Étoile",
      "Meyzieu",
      "Mions",
      "Montanay",
      "Neuville-sur-Saône",
      "Oullins-Pierre-Bénite",
      "Poleymieux-au-Mont-d'Or",
      "Quincieux",
      "Rillieux-la-Pape",
      "Rochetaillée-sur-Saône",
      "Saint-Cyr-au-Mont-d'Or",
      "Saint-Didier-au-Mont-d'Or",
      "Saint-Fons",
      "Saint-Genis-Laval",
      "Saint-Genis-les-Ollières",
      "Saint-Germain-au-Mont-d'Or",
      "Saint-Priest",
      "Saint-Romain-au-Mont-d'Or",
      "Sainte-Foy-lès-Lyon",
      "Sathonay-Camp",
      "Sathonay-Village",
      "Solaize",
      "Tassin-la-Demi-Lune",
      "Vaulx-en-Velin",
      "Vernaison",
      "Villeurbanne",
      "Vénissieux",
      "Écully",
    ],
    principales: [
      "Lyon",
      "Villeurbanne",
      "Vénissieux",
      "Vaulx-en-Velin",
      "Saint-Priest",
      "Caluire-et-Cuire",
      "Bron",
      "Oullins-Pierre-Bénite",
      "Meyzieu",
      "Rillieux-la-Pape",
      "Décines-Charpieu",
      "Tassin-la-Demi-Lune",
      "Sainte-Foy-lès-Lyon",
      "Givors",
      "Saint-Genis-Laval",
      "Saint-Fons",
      "Écully",
      "Francheville",
      "Mions",
      "Craponne",
      "Corbas",
      "Chassieu",
      "Feyzin",
      "Grigny-sur-Rhône",
      "Dardilly",
      "Irigny",
      "Neuville-sur-Saône",
      "Saint-Didier-au-Mont-d'Or",
      "Sathonay-Camp",
      "Fontaines-sur-Saône",
      "La Mulatière",
      "Saint-Cyr-au-Mont-d'Or",
      "Champagne-au-Mont-d'Or",
      "Jonage",
      "Genay",
      "Saint-Genis-les-Ollières",
      "Charbonnières-les-Bains",
      "Vernaison",
      "Charly",
      "Collonges-au-Mont-d'Or",
      "La Tour-de-Salvagny",
      "Limonest",
    ],
  },
];

/** Nombre total de communes couvertes (dédupliqué). */
export const MEMO_ZONE_TOTAL = new Set(MEMO_ZONE_CLUSTERS.flatMap((c) => c.communes)).size;

/** Communes principales dédupliquées — jobLocation du JobPosting. */
export const MEMO_ZONE_PRINCIPALES: readonly string[] = [
  ...new Set(MEMO_ZONE_CLUSTERS.flatMap((c) => c.principales)),
];
