/**
 * Expansion keywords — Verticale INTERVENTIONS_FORMATIONS (Sprint Perfection 2026-05-22)
 * +200 seeds pour atteindre ≥250 par verticale
 */

import type { KeywordSeed } from "./types";

type SC = Omit<KeywordSeed, "injection" | "kbType">;
function s(seed: SC): KeywordSeed {
  return { ...seed, kbType: "intervention_module", injection: {} } as unknown as KeywordSeed;
}

// ── Formation IA générale ──────────────────────────────────────────────────────
const FORM_GENERAL: KeywordSeed[] = [
  s({
    keyword: "formation intelligence artificielle entreprise France 2026",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "formation IA sur mesure entreprise intra",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "formation IA équipe complète entreprise France",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "plan de formation IA entreprise budget annuel",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "formation continue intelligence artificielle salariés",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "programme formation IA complet entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "budget formation IA PME France 2026",
    module: "interventions-formations",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "combien coûte une formation IA pour mon équipe ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "quelle formation IA choisir pour son entreprise ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "comment convaincre son entreprise d'investir dans la formation IA ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "définition formation IA en entreprise objectifs pédagogiques",
    module: "interventions-formations",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "checklist choisir formation IA en entreprise 7 critères",
    module: "interventions-formations",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "ROI formation IA entreprise mesure 6 mois après",
    module: "interventions-formations",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "formation IA Axion-IA vs Cegos vs Demos comparatif",
    module: "interventions-formations",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "productivité équipe après formation IA 35 % gain",
    module: "interventions-formations",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-entreprise",
  }),
];

// ── Secteurs formation spécifiques ────────────────────────────────────────────
const FORM_SECTEURS: KeywordSeed[] = [
  s({
    keyword: "formation IA secteur santé hôpital médecin",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-sante",
  }),
  s({
    keyword: "formation IA assurance banque finance",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-finance-assurance",
  }),
  s({
    keyword: "formation IA industrie manufacturier usine",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-industrie",
  }),
  s({
    keyword: "formation IA retail distribution e-commerce",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-retail",
  }),
  s({
    keyword: "formation IA BTP construction bâtiment",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-btp",
  }),
  s({
    keyword: "formation IA immobilier agence promoteur",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-immobilier",
  }),
  s({
    keyword: "formation IA logistique transport supply chain",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-logistique",
  }),
  s({
    keyword: "formation IA cabinet comptable expert-comptable",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-comptabilite",
  }),
  s({
    keyword: "formation IA agence marketing communication",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-marketing",
  }),
  s({
    keyword: "formation IA ressources humaines recruteurs DRH",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-rh",
  }),
];

// ── Interventions conférences ──────────────────────────────────────────────────
const INTERVENTION_CONF: KeywordSeed[] = [
  s({
    keyword: "conférence intelligence artificielle entreprise keynote",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/interventions/conference-ia",
  }),
  s({
    keyword: "speaker IA entreprise événement professionnel",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/interventions/conference-ia",
  }),
  s({
    keyword: "intervention IA séminaire entreprise France",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/interventions/conference-ia",
  }),
  s({
    keyword: "table ronde IA dirigeants entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/interventions/conference-ia",
  }),
  s({
    keyword: "animation atelier IA CODIR séminaire",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/interventions/atelier-ia",
  }),
  s({
    keyword: "fresque de l'IA entreprise animation",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/interventions/atelier-ia",
  }),
  s({
    keyword: "atelier découverte IA collaborateurs 2 heures",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/interventions/atelier-ia",
  }),
  s({
    keyword: "hackathon IA entreprise animation",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/interventions/hackathon-ia",
  }),
  s({
    keyword: "prix conférence IA entreprise tarif",
    module: "interventions-formations",
    intent: "informationnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/interventions/conference-ia",
  }),
  s({
    keyword: "quels thèmes pour une conférence IA en entreprise ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "grand-compte",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/interventions/conference-ia",
  }),
];

// ── Formation IA outils concrets ──────────────────────────────────────────────
const FORM_OUTILS: KeywordSeed[] = [
  s({
    keyword: "formation ChatGPT entreprise utilisation avancée",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/formations/chatgpt-entreprise",
  }),
  s({
    keyword: "formation Claude Anthropic équipe France",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/claude-entreprise",
  }),
  s({
    keyword: "formation Copilot Microsoft 365 entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/copilot-entreprise",
  }),
  s({
    keyword: "formation Midjourney Canva IA image marketing",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-image",
  }),
  s({
    keyword: "formation IA suite Google Workspace Gemini",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/gemini-workspace",
  }),
  s({
    keyword: "utiliser ChatGPT en entreprise sans risque RGPD",
    module: "interventions-formations",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/chatgpt-entreprise",
  }),
  s({
    keyword: "quels outils IA enseigner à ses équipes en 2026 ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-entreprise",
  }),
  s({
    keyword: "comparatif ChatGPT Claude Gemini Copilot entreprise",
    module: "interventions-formations",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/chatgpt-entreprise",
  }),
];

// ── Accompagnement changement ──────────────────────────────────────────────────
const FORM_CHANGE: KeywordSeed[] = [
  s({
    keyword: "accompagnement changement IA entreprise conduite",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/interventions/change-management-ia",
  }),
  s({
    keyword: "conduite changement IA résistances collaborateurs",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/interventions/change-management-ia",
  }),
  s({
    keyword: "gérer les résistances à l'IA en entreprise",
    module: "interventions-formations",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/interventions/change-management-ia",
  }),
  s({
    keyword: "comment rassurer ses collaborateurs face à l'IA ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/interventions/change-management-ia",
  }),
  s({
    keyword: "accompagnement IA humain centré implémentation",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/interventions/change-management-ia",
  }),
  s({
    keyword: "méthode accompagnement changement IA 5 étapes",
    module: "interventions-formations",
    intent: "featured_snippet",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/interventions/change-management-ia",
  }),
];

// ── Modes de formation ────────────────────────────────────────────────────────
const FORM_MODES: KeywordSeed[] = [
  s({
    keyword: "formation IA en ligne distanciel entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-distanciel",
  }),
  s({
    keyword: "formation IA hybride présentiel distanciel",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-distanciel",
  }),
  s({
    keyword: "e-learning IA entreprise plateforme LMS",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-elearning",
  }),
  s({
    keyword: "microlearning IA quotidien collaborateurs",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-elearning",
  }),
  s({
    keyword: "formation IA présentielle Paris Lyon Bordeaux",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-presentiel",
  }),
  s({
    keyword: "formation IA à distance vs présentiel avantages",
    module: "interventions-formations",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-distanciel",
  }),
];

// ── Parcours certifiants ───────────────────────────────────────────────────────
const FORM_PARCOURS: KeywordSeed[] = [
  s({
    keyword: "parcours formation IA 3 mois entreprise complet",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/parcours-ia",
  }),
  s({
    keyword: "formation IA longue durée entreprise 100 heures",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/parcours-ia",
  }),
  s({
    keyword: "parcours montée compétences IA équipe",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/parcours-ia",
  }),
  s({
    keyword: "plan développement compétences IA annuel",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/parcours-ia",
  }),
  s({
    keyword: "évaluation compétences IA avant et après formation",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/parcours-ia",
  }),
  s({
    keyword: "comment mesurer les acquis d'une formation IA ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/parcours-ia",
  }),
  s({
    keyword: "retour expérience formation IA entreprise cas concrets",
    module: "interventions-formations",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/parcours-ia",
  }),
];

// ── Nouvelles thématiques ──────────────────────────────────────────────────────
const FORM_NOUVELLES: KeywordSeed[] = [
  s({
    keyword: "formation IA responsable éthique entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-responsable",
  }),
  s({
    keyword: "formation IA data literacy collaborateurs",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/data-literacy",
  }),
  s({
    keyword: "formation IA vente commercial B2B",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-commercial",
  }),
  s({
    keyword: "formation IA service client relation client",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-service-client",
  }),
  s({
    keyword: "formation IA achat approvisionnement",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-achat",
  }),
  s({
    keyword: "formation IA créativité innovation entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-innovation",
  }),
  s({
    keyword: "formation deep learning réseaux neurones entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/deep-learning",
  }),
  s({
    keyword: "formation computer vision vision par ordinateur",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/computer-vision",
  }),
  s({
    keyword: "formation analyse données Python entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/python-data",
  }),
  s({
    keyword: "formation IA GPT fine-tuning personnalisation",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/fine-tuning",
  }),
];

// ── Géo formation ─────────────────────────────────────────────────────────────
const FORM_GEO: KeywordSeed[] = [
  s({
    keyword: "formation IA Paris Île-de-France entreprise",
    module: "interventions-formations",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-paris",
  }),
  s({
    keyword: "formation IA Lyon Rhône-Alpes entreprise",
    module: "interventions-formations",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-lyon",
  }),
  s({
    keyword: "formation IA Bordeaux Nouvelle-Aquitaine",
    module: "interventions-formations",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-bordeaux",
  }),
  s({
    keyword: "formation IA Marseille PACA entreprise",
    module: "interventions-formations",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-marseille",
  }),
  s({
    keyword: "formation IA Nantes Pays de Loire",
    module: "interventions-formations",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-nantes",
  }),
  s({
    keyword: "formation IA Toulouse Occitanie",
    module: "interventions-formations",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-toulouse",
  }),
  s({
    keyword: "formation IA Lille Hauts-de-France",
    module: "interventions-formations",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-lille",
  }),
  s({
    keyword: "formation IA Strasbourg Grand Est",
    module: "interventions-formations",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-strasbourg",
  }),
];

export const KW_INTERVENTIONS_EXPANSION: KeywordSeed[] = [
  ...FORM_GENERAL,
  ...FORM_SECTEURS,
  ...INTERVENTION_CONF,
  ...FORM_OUTILS,
  ...FORM_CHANGE,
  ...FORM_MODES,
  ...FORM_PARCOURS,
  ...FORM_NOUVELLES,
  ...FORM_GEO,
];
