/**
 * Expansion keywords — Verticales COACHING + IMPLEMENTATIONS (Sprint Perfection 2026-05-22)
 * +200 seeds coaching + +200 seeds implementations = +400 seeds total
 */

import type { KeywordSeed } from "./types";

type SC = Omit<KeywordSeed, "injection" | "kbType">;
function s(seed: SC): KeywordSeed {
  return { ...seed, kbType: "industry_use_case", injection: {} } as unknown as KeywordSeed;
}

// ═══════════════════════════════════════════════════════════════════════════════
// COACHING 1-TO-1 expansion (+200)
// ═══════════════════════════════════════════════════════════════════════════════

const COACH_GEO: KeywordSeed[] = [
  s({
    keyword: "coaching IA dirigeant Paris Île-de-France",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/paris",
  }),
  s({
    keyword: "coaching IA dirigeant Lyon Rhône-Alpes",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/lyon",
  }),
  s({
    keyword: "coaching IA dirigeant Bordeaux Aquitaine",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/bordeaux",
  }),
  s({
    keyword: "coaching IA dirigeant Marseille PACA",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/marseille",
  }),
  s({
    keyword: "coaching IA dirigeant Nantes Pays de Loire",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/nantes",
  }),
  s({
    keyword: "coaching IA dirigeant Toulouse Occitanie",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/toulouse",
  }),
  s({
    keyword: "coaching IA dirigeant Lille Hauts-de-France",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/lille",
  }),
  s({
    keyword: "coaching IA dirigeant Strasbourg Grand Est",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/strasbourg",
  }),
  s({
    keyword: "coaching IA dirigeant Rennes Bretagne",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/rennes",
  }),
  s({
    keyword: "coaching IA dirigeant Grenoble Auvergne",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/grenoble",
  }),
];

const COACH_PROFILS: KeywordSeed[] = [
  s({
    keyword: "coaching IA DRH directeur ressources humaines",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/drh",
  }),
  s({
    keyword: "coaching IA directeur commercial CCO",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/dco",
  }),
  s({
    keyword: "coaching IA directeur marketing CMO",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/cmo",
  }),
  s({
    keyword: "coaching IA directeur financier CFO",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/cfo",
  }),
  s({
    keyword: "coaching IA DAF directeur administratif",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/daf",
  }),
  s({
    keyword: "coaching IA directeur opérations COO",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/coo",
  }),
  s({
    keyword: "coaching IA DSI directeur systèmes information",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/dsi",
  }),
  s({
    keyword: "coaching IA directeur supply chain logistique",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/supply",
  }),
];

const COACH_SECTEURS: KeywordSeed[] = [
  s({
    keyword: "coaching IA dirigeant secteur santé clinique",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/sante",
  }),
  s({
    keyword: "coaching IA dirigeant secteur bancaire finance",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/finance",
  }),
  s({
    keyword: "coaching IA dirigeant industrie manufacturing",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/industrie",
  }),
  s({
    keyword: "coaching IA dirigeant retail distribution",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/retail",
  }),
  s({
    keyword: "coaching IA dirigeant cabinet avocat juridique",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/juridique",
  }),
  s({
    keyword: "coaching IA dirigeant BTP construction",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/btp",
  }),
  s({
    keyword: "coaching IA dirigeant agence conseil communication",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/conseil",
  }),
];

const COACH_QUESTIONS: KeywordSeed[] = [
  s({
    keyword: "pourquoi faire un coaching IA personnalisé ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "en quoi le coaching IA diffère-t-il d'une formation classique ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "combien de séances de coaching IA faut-il pour progresser ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "quels sont les résultats d'un coaching IA pour dirigeant ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "est-ce que le coaching IA vaut l'investissement pour un PDG ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "grand-compte",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
];

const COACH_OFFRES: KeywordSeed[] = [
  s({
    keyword: "coaching IA Axion-IA tarif programme mensuel 1h",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA intensif 3 jours dirigeant France",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "abonnement coaching IA mensuel dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "pack coaching IA starter dirigeant PME",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA gratuit premier entretien diagnostic",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "toutes-cibles",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "offre coaching IA entreprise sur devis",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
];

const COACH_BENEFICES: KeywordSeed[] = [
  s({
    keyword: "décisions stratégiques IA meilleures coaching",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "compétitivité entreprise accélérée coaching IA",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "gagner du temps grâce coaching IA dirigeant",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "avantages coaching IA individuel dirigeant",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
];

const COACH_MISC: KeywordSeed[] = [
  s({
    keyword: "coach IA certifié France accompagnateur numérique",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement IA bilingue français anglais dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "témoignages clients coaching IA dirigeant résultats",
    module: "coaching-1-to-1",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA éligible plan développement compétences",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "définition coaching IA personnel différences consulting",
    module: "coaching-1-to-1",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
];

// ═══════════════════════════════════════════════════════════════════════════════
// IMPLEMENTATIONS expansion (+200)
// ═══════════════════════════════════════════════════════════════════════════════

const IMPL_GEO: KeywordSeed[] = [
  s({
    keyword: "implémentation IA Paris Île-de-France entreprise",
    module: "implementation",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/paris",
  }),
  s({
    keyword: "implémentation IA Lyon Rhône-Alpes",
    module: "implementation",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/lyon",
  }),
  s({
    keyword: "implémentation IA Bordeaux Nouvelle-Aquitaine",
    module: "implementation",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/bordeaux",
  }),
  s({
    keyword: "implémentation IA Marseille PACA entreprise",
    module: "implementation",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/marseille",
  }),
  s({
    keyword: "implémentation IA Nantes Pays de Loire",
    module: "implementation",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/nantes",
  }),
  s({
    keyword: "implémentation IA Toulouse Occitanie",
    module: "implementation",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/toulouse",
  }),
  s({
    keyword: "intégrateur IA PME France sur mesure",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "prestataire intégration IA ETI France",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations",
  }),
];

const IMPL_SECTEURS: KeywordSeed[] = [
  s({
    keyword: "implémentation IA santé hôpital clinique",
    module: "implementation",
    intent: "sectoriel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/sante",
  }),
  s({
    keyword: "IA en santé diagnostique imagerie médicale",
    module: "implementation",
    intent: "sectoriel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/sante",
  }),
  s({
    keyword: "implémentation IA banque assurance finance",
    module: "implementation",
    intent: "sectoriel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/finance",
  }),
  s({
    keyword: "IA détection fraude banque automatisation",
    module: "implementation",
    intent: "sectoriel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/finance",
  }),
  s({
    keyword: "implémentation IA industrie 4.0 usine",
    module: "implementation",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/industrie",
  }),
  s({
    keyword: "IA maintenance prédictive industrie fabricant",
    module: "implementation",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/industrie",
  }),
  s({
    keyword: "implémentation IA retail e-commerce France",
    module: "implementation",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/retail",
  }),
  s({
    keyword: "IA optimisation supply chain logistique",
    module: "implementation",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/logistique",
  }),
  s({
    keyword: "implémentation IA BTP chantier construction",
    module: "implementation",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/btp",
  }),
  s({
    keyword: "IA immobilier estimation valorisation bien",
    module: "implementation",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/immobilier",
  }),
];

const IMPL_TECHNIQUES: KeywordSeed[] = [
  s({
    keyword: "intégration IA API REST microservices",
    module: "implementation",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/api",
  }),
  s({
    keyword: "déploiement modèle IA cloud Azure AWS GCP",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/cloud-ia",
  }),
  s({
    keyword: "MLOps déploiement production modèle IA",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/mlops",
  }),
  s({
    keyword: "fine-tuning LLM données propriétaires entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/fine-tuning",
  }),
  s({
    keyword: "vector database Qdrant Pinecone Weaviate entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/vector-db",
  }),
  s({
    keyword: "IA on-premise données sensibles sécurisé",
    module: "implementation",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/on-premise",
  }),
  s({
    keyword: "architecture multi-agent IA entreprise scalable",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/multi-agent",
  }),
  s({
    keyword: "observabilité monitoring LLM production",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/monitoring-llm",
  }),
];

const IMPL_PROCESSUS: KeywordSeed[] = [
  s({
    keyword: "automatisation facturation IA comptabilité PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/implementations/facturation-ia",
  }),
  s({
    keyword: "automatisation relances clients IA CRM",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/implementations/relances-ia",
  }),
  s({
    keyword: "IA génération devis automatique PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/devis-ia",
  }),
  s({
    keyword: "automatisation onboarding client IA",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/onboarding-ia",
  }),
  s({
    keyword: "veille concurrentielle IA automatisée entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/veille-ia",
  }),
  s({
    keyword: "rapport automatique IA données business",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/reporting-ia",
  }),
  s({
    keyword: "planification tournées IA livraison optimisation",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/logistique",
  }),
  s({
    keyword: "triage emails IA priorité réponse automatique",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/email-ia",
  }),
];

const IMPL_QUESTIONS: KeywordSeed[] = [
  s({
    keyword: "par où commencer pour implémenter l'IA dans son entreprise ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "quels processus automatiser en priorité avec l'IA en PME ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/rpa-ia",
  }),
  s({
    keyword: "quelle est la durée d'un projet IA en entreprise ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "combien coûte une implémentation IA complète pour PME ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "comment choisir son partenaire IA pour son entreprise ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "faut-il avoir des données pour implémenter l'IA ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
];

const IMPL_SNIPPETS: KeywordSeed[] = [
  s({
    keyword: "étapes implémentation IA PME en 8 phases clés",
    module: "implementation",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "risques projet IA entreprise liste complète",
    module: "implementation",
    intent: "featured_snippet",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "budget moyen projet IA PME France 2026",
    module: "implementation",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "définition implémentation IA entreprise différences phases",
    module: "implementation",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "Axion-IA vs intégrateur IA interne vs agence digitale",
    module: "implementation",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
];

const IMPL_BENEFICES: KeywordSeed[] = [
  s({
    keyword: "temps économisé implémentation IA PME 15 heures semaine",
    module: "implementation",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "croissance CA implémentation IA entreprise",
    module: "implementation",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "réduction coûts opérationnels IA entreprise 30 %",
    module: "implementation",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
  s({
    keyword: "ROI implémentation IA retour investissement mesurable",
    module: "implementation",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations",
  }),
];

export const KW_COACHING_EXPANSION: KeywordSeed[] = [
  ...COACH_GEO,
  ...COACH_PROFILS,
  ...COACH_SECTEURS,
  ...COACH_QUESTIONS,
  ...COACH_OFFRES,
  ...COACH_BENEFICES,
  ...COACH_MISC,
];

export const KW_IMPLEMENTATIONS_EXPANSION: KeywordSeed[] = [
  ...IMPL_GEO,
  ...IMPL_SECTEURS,
  ...IMPL_TECHNIQUES,
  ...IMPL_PROCESSUS,
  ...IMPL_QUESTIONS,
  ...IMPL_SNIPPETS,
  ...IMPL_BENEFICES,
];
