/**
 * Expansion keywords — Verticales AUDIT + WEB_AUGMENTE (Sprint Perfection 2026-05-22)
 * +150 seeds audit + +150 seeds web augmenté = +300 seeds total
 */

import type { KeywordSeed } from "./types";

type SC = Omit<KeywordSeed, "injection" | "kbType">;
function s(seed: SC): KeywordSeed {
  return { ...seed, kbType: "industry_use_case", injection: {} } as unknown as KeywordSeed;
}

// ═══════════════════════════════════════════════════════════════════════════════
// AUDIT expansion (+150)
// ═══════════════════════════════════════════════════════════════════════════════

const AUDIT_GEO: KeywordSeed[] = [
  s({
    keyword: "audit IA Paris Île-de-France cabinet",
    module: "audit",
    intent: "local",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/paris",
  }),
  s({
    keyword: "audit IA Lyon Rhône-Alpes cabinet conseil",
    module: "audit",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/lyon",
  }),
  s({
    keyword: "audit IA Bordeaux Nouvelle-Aquitaine",
    module: "audit",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/bordeaux",
  }),
  s({
    keyword: "audit IA Marseille PACA consultant",
    module: "audit",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/marseille",
  }),
  s({
    keyword: "audit IA Nantes Pays de Loire",
    module: "audit",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/nantes",
  }),
  s({
    keyword: "audit IA Toulouse Occitanie PME",
    module: "audit",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/toulouse",
  }),
  s({
    keyword: "audit IA Lille Hauts-de-France",
    module: "audit",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/lille",
  }),
  s({
    keyword: "audit IA Strasbourg Grand Est",
    module: "audit",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/strasbourg",
  }),
  s({
    keyword: "audit IA Rennes Bretagne cabinet",
    module: "audit",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/rennes",
  }),
  s({
    keyword: "audit IA Grenoble innovation entreprise",
    module: "audit",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/grenoble",
  }),
];

const AUDIT_SECTEURS: KeywordSeed[] = [
  s({
    keyword: "audit IA secteur santé hôpital France",
    module: "audit",
    intent: "sectoriel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/sante",
  }),
  s({
    keyword: "audit IA banque assurance fintech",
    module: "audit",
    intent: "sectoriel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/finance",
  }),
  s({
    keyword: "audit IA industrie manufacturing PME",
    module: "audit",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/industrie",
  }),
  s({
    keyword: "audit IA retail e-commerce France",
    module: "audit",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/retail",
  }),
  s({
    keyword: "audit IA immobilier agence promoteur",
    module: "audit",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/immobilier",
  }),
  s({
    keyword: "audit IA logistique transport supply chain",
    module: "audit",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/logistique",
  }),
  s({
    keyword: "audit IA cabinet expertise comptable",
    module: "audit",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/expertise-comptable",
  }),
  s({
    keyword: "audit IA hôtellerie restauration tourisme",
    module: "audit",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/tourisme",
  }),
  s({
    keyword: "audit IA agriculture agroalimentaire",
    module: "audit",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/agriculture",
  }),
  s({
    keyword: "audit IA éducation enseignement supérieur",
    module: "audit",
    intent: "sectoriel",
    cible: "universite-grande-ecole",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/education",
  }),
];

const AUDIT_TYPES: KeywordSeed[] = [
  s({
    keyword: "audit flash IA 1 journée entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/audit/tpe-1-jour",
  }),
  s({
    keyword: "audit approfondi IA 360 entreprise PME",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/approfondi",
  }),
  s({
    keyword: "audit IA en ligne à distance PME",
    module: "audit",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/en-ligne",
  }),
  s({
    keyword: "audit IA sur site présentiel entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/sur-site",
  }),
  s({
    keyword: "auto-audit IA dirigeant autonome test",
    module: "audit",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/auto-audit",
  }),
  s({
    keyword: "audit IA collaboratif équipe workshop",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/workshop",
  }),
];

const AUDIT_OFFRES: KeywordSeed[] = [
  s({
    keyword: "tarif audit IA PME France prix",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/tarif",
  }),
  s({
    keyword: "devis audit IA gratuit entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/audit/devis",
  }),
  s({
    keyword: "audit IA gratuit premier diagnostic",
    module: "audit",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/audit/gratuit",
  }),
  s({
    keyword: "forfait audit IA PME ETI grand compte",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/forfait",
  }),
  s({
    keyword: "combien coûte un audit IA pour une PME ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/tarif",
  }),
];

const AUDIT_QUESTIONS: KeywordSeed[] = [
  s({
    keyword: "qu'est-ce qu'un audit IA pour une entreprise ?",
    module: "audit",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit",
  }),
  s({
    keyword: "à quelle fréquence faire un audit IA en entreprise ?",
    module: "audit",
    intent: "voice_search",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit",
  }),
  s({
    keyword: "mon entreprise a-t-elle besoin d'un audit IA ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit",
  }),
  s({
    keyword: "audit IA vs conseil en stratégie IA différences",
    module: "audit",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit",
  }),
  s({
    keyword: "livrables d'un audit IA en entreprise liste",
    module: "audit",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit",
  }),
  s({
    keyword: "que contient un rapport d'audit IA entreprise ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit",
  }),
];

const AUDIT_MISC: KeywordSeed[] = [
  s({
    keyword: "cabinet conseil IA France indépendant expert",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit",
  }),
  s({
    keyword: "consultant IA freelance PME mission audit",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit",
  }),
  s({
    keyword: "expert IA certifié France diagnostic stratégie",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit",
  }),
  s({
    keyword: "audit IA B2B SaaS startup France",
    module: "audit",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/startup",
  }),
  s({
    keyword: "audit gouvernance IA entreprise France",
    module: "audit",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/gouvernance",
  }),
  s({
    keyword: "bénéfices audit IA PME avant projet",
    module: "audit",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit",
  }),
  s({
    keyword: "cas clients audit IA PME résultats concrets",
    module: "audit",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/cas-clients",
  }),
  s({
    keyword: "feuille de route IA livrée après audit Axion-IA",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit",
  }),
];

// ═══════════════════════════════════════════════════════════════════════════════
// WEB AUGMENTÉ expansion (+150)
// ═══════════════════════════════════════════════════════════════════════════════

const WEB_GEO_SEEDS: KeywordSeed[] = [
  s({
    keyword: "agence SEO IA Paris Île-de-France",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/paris",
  }),
  s({
    keyword: "agence SEO IA Lyon Rhône-Alpes",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/lyon",
  }),
  s({
    keyword: "agence web IA Bordeaux Nouvelle-Aquitaine",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/bordeaux",
  }),
  s({
    keyword: "agence web IA Marseille PACA",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/marseille",
  }),
  s({
    keyword: "agence SEO AEO Nantes Pays de Loire",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/nantes",
  }),
  s({
    keyword: "développement web IA Toulouse Occitanie",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/toulouse",
  }),
  s({
    keyword: "agence digitale IA Lille Hauts-de-France",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/lille",
  }),
  s({
    keyword: "agence web IA Strasbourg Grand Est",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/strasbourg",
  }),
];

const WEB_OFFRES: KeywordSeed[] = [
  s({
    keyword: "création site web optimisé AEO GEO France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "refonte site web IA AEO GEO PME",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "tarif site web IA SEO AEO France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "devis site web IA optimisé gratuit",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "pack site web IA complet SEO AEO PME",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "maintenance site web IA mensuel France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/maintenance",
  }),
];

const WEB_SECTEURS: KeywordSeed[] = [
  s({
    keyword: "site web IA cabinet conseil B2B France",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/b2b",
  }),
  s({
    keyword: "site web IA e-commerce boutique en ligne",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/ecommerce",
  }),
  s({
    keyword: "site web IA avocat cabinet juridique",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/juridique",
  }),
  s({
    keyword: "site web IA médecin cabinet santé",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/sante",
  }),
  s({
    keyword: "site web IA artisan commerçant TPE",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/artisan",
  }),
  s({
    keyword: "site web IA startup SaaS growth",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/saas",
  }),
];

const WEB_CONTENU: KeywordSeed[] = [
  s({
    keyword: "stratégie contenu IA site web 2026",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/strategie-contenu",
  }),
  s({
    keyword: "audit contenu site web IA SEO",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/audit-contenu",
  }),
  s({
    keyword: "optimisation maillage interne site IA",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/maillage-interne",
  }),
  s({
    keyword: "rédaction articles blog IA SEO France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/blog-ia",
  }),
  s({
    keyword: "création landing page IA conversion",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/landing-ia",
  }),
  s({
    keyword: "fiche produit IA SEO e-commerce",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/ecommerce",
  }),
  s({
    keyword: "contenu pilier topic cluster IA SEO",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/strategie-contenu",
  }),
  s({
    keyword: "comment créer une stratégie de contenu IA ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/strategie-contenu",
  }),
];

const WEB_TECHNIQUE: KeywordSeed[] = [
  s({
    keyword: "vitesse chargement site web IA performance",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/web-vitals",
  }),
  s({
    keyword: "Next.js React site web IA SEO SSR",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/nextjs",
  }),
  s({
    keyword: "architecture site web scalable IA 2026",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/architecture",
  }),
  s({
    keyword: "sécurité site web IA protection données",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/securite",
  }),
  s({
    keyword: "accessibilité site web RGAA IA France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "collectivite-mairie",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/accessibilite",
  }),
  s({
    keyword: "hébergement site web IA France cloud Hetzner",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/hebergement",
  }),
];

const WEB_QUESTIONS: KeywordSeed[] = [
  s({
    keyword: "pourquoi mon site web doit être optimisé pour les IA ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital",
  }),
  s({
    keyword: "comment Google IA change le référencement en 2026 ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "quelle est la différence entre SEO et AEO ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/aeo",
  }),
  s({
    keyword: "combien coûte une refonte SEO IA pour PME ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "définition site web augmenté IA différences classique",
    module: "codage-developpement",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital",
  }),
];

export const KW_AUDIT_EXPANSION: KeywordSeed[] = [
  ...AUDIT_GEO,
  ...AUDIT_SECTEURS,
  ...AUDIT_TYPES,
  ...AUDIT_OFFRES,
  ...AUDIT_QUESTIONS,
  ...AUDIT_MISC,
];

export const KW_WEB_EXPANSION: KeywordSeed[] = [
  ...WEB_GEO_SEEDS,
  ...WEB_OFFRES,
  ...WEB_SECTEURS,
  ...WEB_CONTENU,
  ...WEB_TECHNIQUE,
  ...WEB_QUESTIONS,
];
