/**
 * Phase 3 Sprint Keywords Perfection 2026-05-22 — Top-up équilibrage
 * Assure ≥ 250 seeds pour toutes les verticales (un_a_un + sites_web_augmentes)
 */

import type { KeywordSeed } from "./types";

type SC = Omit<KeywordSeed, "injection" | "kbType">;
function s(seed: SC): KeywordSeed {
  return { ...seed, kbType: "industry_use_case", injection: {} } as unknown as KeywordSeed;
}

// ── un_a_un top-up (+15 pour aller à ≥250 avec marge) ────────────────────────
const COACHING_TOPUP: KeywordSeed[] = [
  s({
    keyword: "accompagnement IA transformation digitale dirigeant PME 2026",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA résilience digitale entrepreneur",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "séance coaching IA dirigeant visio 1h France",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA premier entretien découverte gratuit",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "toutes-cibles",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA décideur public collectivité dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "collectivite-mairie",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement IA dirigeant femme entrepreneuse",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA partenaire CCI chambre métiers dirigeant",
    module: "coaching-1-to-1",
    intent: "partenaire",
    cible: "cci-chambre-metiers",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "bilan compétences IA dirigeant évaluation personnalisée",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA mind-set transformation culturelle",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA performance opérationnelle dirigeant",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "comment évaluer son niveau IA en tant que dirigeant ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "quel est le retour sur investissement d'un coaching IA ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA Axion-IA programme complet présentation",
    module: "coaching-1-to-1",
    intent: "informationnel",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "comparatif coaching IA France prestataires tarifs",
    module: "coaching-1-to-1",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "définition executive coaching IA différences formations",
    module: "coaching-1-to-1",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
];

// ── sites_web_augmentes top-up (+10 pour ≥250 avec marge) ────────────────────
const WEB_TOPUP: KeywordSeed[] = [
  s({
    keyword: "agence web IA France Axion-IA présentation offres",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital",
  }),
  s({
    keyword: "site web optimisé moteurs IA 2026 création",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "référencement naturel IA PME France stratégie",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "stratégie digitale IA PME ETI accompagnement",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital",
  }),
  s({
    keyword: "visibilité en ligne IA PME France 2026",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "trafic qualifié site web IA SEO AEO PME",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital",
  }),
  s({
    keyword: "comment augmenter son trafic naturel avec l'IA ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "quelle différence entre SEO classique et SEO IA 2026 ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "définition web augmenté IA AEO GEO complet",
    module: "codage-developpement",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital",
  }),
  s({
    keyword: "audit SEO IA gratuit site web PME France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/web-digital/audit-contenu",
  }),
];

export const KW_PHASE3_TOPUP: KeywordSeed[] = [...COACHING_TOPUP, ...WEB_TOPUP];
