/**
 * Keywords Phase 2 Sprint Perfection 2026-05-22 — Verticale AUDITS
 * 12 clusters × ~25 keywords = ~300 seeds
 * Intents couverts : transactionnel, informationnel, voice_search, ai_overview,
 *   featured_snippet, commercial_investigation, benefice
 */

import type { KeywordSeed } from "./types";

type SC = Omit<KeywordSeed, "injection" | "kbType">;
function s(seed: SC): KeywordSeed {
  const full: Record<string, unknown> = { ...seed, kbType: "industry_use_case", injection: {} };
  return full as unknown as KeywordSeed;
}

// ── CLUSTER 1 : audit-securite-ia ──────────────────────────────────────────────
const AUDIT_SECURITE: KeywordSeed[] = [
  // Transactionnel
  s({
    keyword: "audit sécurité IA entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/securite-ia",
  }),
  s({
    keyword: "audit vulnérabilités intelligence artificielle",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/securite-ia",
  }),
  s({
    keyword: "pentest modèle LLM entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/securite-ia",
  }),
  s({
    keyword: "sécuriser modèle LLM données sensibles",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/securite-ia",
  }),
  s({
    keyword: "audit injection prompt entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/securite-ia",
  }),
  s({
    keyword: "consultant sécurité IA PME",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/securite-ia",
  }),
  // Informationnel
  s({
    keyword: "risques sécurité intelligence artificielle",
    module: "audit",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/securite-ia",
  }),
  s({
    keyword: "failles sécurité modèles IA entreprise",
    module: "audit",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/securite-ia",
  }),
  // Voice search
  s({
    keyword: "comment sécuriser son système IA contre les attaques ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/securite-ia",
  }),
  s({
    keyword: "quels sont les risques de sécurité liés à l'IA en entreprise ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/securite-ia",
  }),
  s({
    keyword: "comment protéger ses données sensibles contre les LLM ?",
    module: "audit",
    intent: "voice_search",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/securite-ia",
  }),
  // AI Overview
  s({
    keyword: "définition audit sécurité intelligence artificielle",
    module: "audit",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/securite-ia",
  }),
  s({
    keyword: "qu'est-ce qu'un pentest IA en entreprise ?",
    module: "audit",
    intent: "ai_overview",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/securite-ia",
  }),
  // Featured snippet
  s({
    keyword: "étapes audit sécurité IA entreprise en 5 points",
    module: "audit",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/securite-ia",
  }),
  s({
    keyword: "checklist sécurité IA pour PME",
    module: "audit",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/securite-ia",
  }),
];

// ── CLUSTER 2 : audit-rgpd-ia ──────────────────────────────────────────────────
const AUDIT_RGPD: KeywordSeed[] = [
  s({
    keyword: "audit RGPD intelligence artificielle",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/rgpd-ia",
  }),
  s({
    keyword: "conformité RGPD chatbot entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/audit/rgpd-ia",
  }),
  s({
    keyword: "DPIA intelligence artificielle PME",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/rgpd-ia",
  }),
  s({
    keyword: "audit protection données IA entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/rgpd-ia",
  }),
  s({
    keyword: "mise en conformité RGPD outils IA",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/rgpd-ia",
  }),
  s({
    keyword: "consultant RGPD IA cabinet spécialisé",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/rgpd-ia",
  }),
  s({
    keyword: "RGPD et intelligence artificielle obligations entreprise",
    module: "audit",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/rgpd-ia",
  }),
  s({
    keyword: "AI Act conformité PME France 2026",
    module: "audit",
    intent: "informationnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "comment vérifier la conformité RGPD d'un chatbot IA ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/rgpd-ia",
  }),
  s({
    keyword: "quelles obligations RGPD pour une entreprise qui utilise l'IA ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/rgpd-ia",
  }),
  s({
    keyword: "définition DPIA intelligence artificielle",
    module: "audit",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/rgpd-ia",
  }),
  s({
    keyword: "étapes conformité RGPD IA en 6 points",
    module: "audit",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/rgpd-ia",
  }),
  s({
    keyword: "audit RGPD IA vs audit RGPD classique",
    module: "audit",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/rgpd-ia",
  }),
];

// ── CLUSTER 3 : audit-performance-ia ──────────────────────────────────────────
const AUDIT_PERFORMANCE: KeywordSeed[] = [
  s({
    keyword: "audit performance modèle IA entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/performance-ia",
  }),
  s({
    keyword: "benchmark LLM entreprise France",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/performance-ia",
  }),
  s({
    keyword: "optimisation latence infrastructure IA",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/performance-ia",
  }),
  s({
    keyword: "audit infrastructure IA on-premise",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/performance-ia",
  }),
  s({
    keyword: "évaluation qualité réponses LLM production",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/performance-ia",
  }),
  s({
    keyword: "mesure précision modèle IA entreprise",
    module: "audit",
    intent: "informationnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/audit/performance-ia",
  }),
  s({
    keyword: "comment évaluer la performance d'un modèle IA en production ?",
    module: "audit",
    intent: "voice_search",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/performance-ia",
  }),
  s({
    keyword: "qu'est-ce qu'un benchmark LLM pour entreprise ?",
    module: "audit",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/performance-ia",
  }),
  s({
    keyword: "KPI performance IA à mesurer en entreprise",
    module: "audit",
    intent: "featured_snippet",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/performance-ia",
  }),
  s({
    keyword: "audit performance IA vs audit classique SI",
    module: "audit",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/performance-ia",
  }),
];

// ── CLUSTER 4 : audit-couts-ia ────────────────────────────────────────────────
const AUDIT_COUTS: KeywordSeed[] = [
  s({
    keyword: "audit coût intelligence artificielle PME",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/couts-ia",
  }),
  s({
    keyword: "ROI intelligence artificielle PME France",
    module: "audit",
    intent: "benefice",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/couts-ia",
  }),
  s({
    keyword: "réduire coût API IA entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/couts-ia",
  }),
  s({
    keyword: "optimisation tokens LLM coût entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/couts-ia",
  }),
  s({
    keyword: "audit financier projets IA budget",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/couts-ia",
  }),
  s({
    keyword: "combien coûte un projet IA pour PME ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/couts-ia",
  }),
  s({
    keyword: "comment calculer le ROI d'un projet IA ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/couts-ia",
  }),
  s({
    keyword: "définition ROI intelligence artificielle entreprise",
    module: "audit",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/couts-ia",
  }),
  s({
    keyword: "méthode calcul ROI IA en 4 étapes",
    module: "audit",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/couts-ia",
  }),
  s({
    keyword: "audit IA interne vs cabinet externe tarif comparaison",
    module: "audit",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/couts-ia",
  }),
  s({
    keyword: "économies réalisées grâce audit IA PME",
    module: "audit",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/couts-ia",
  }),
];

// ── CLUSTER 5 : audit-strategie-ia ────────────────────────────────────────────
const AUDIT_STRATEGIE: KeywordSeed[] = [
  s({
    keyword: "audit stratégie IA entreprise France",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/strategie-ia",
  }),
  s({
    keyword: "feuille de route IA PME dirigeant",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/strategie-ia",
  }),
  s({
    keyword: "vision IA dirigeant PME accompagnement",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/strategie-ia",
  }),
  s({
    keyword: "roadmap transformation IA entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/strategie-ia",
  }),
  s({
    keyword: "diagnostic maturité IA TPE PME",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/audit/strategie-ia",
  }),
  s({
    keyword: "plan stratégique intelligence artificielle cabinet conseil",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/strategie-ia",
  }),
  s({
    keyword: "par où commencer avec l'IA quand on est dirigeant PME ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/strategie-ia",
  }),
  s({
    keyword: "comment construire sa feuille de route IA ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/strategie-ia",
  }),
  s({
    keyword: "définition maturité IA entreprise niveaux",
    module: "audit",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/strategie-ia",
  }),
  s({
    keyword: "étapes construction roadmap IA PME en 5 phases",
    module: "audit",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/strategie-ia",
  }),
  s({
    keyword: "audit stratégie IA Axion-IA vs McKinsey vs Capgemini",
    module: "audit",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/strategie-ia",
  }),
];

// ── CLUSTER 6 : audit-biais-ethique ───────────────────────────────────────────
const AUDIT_BIAIS: KeywordSeed[] = [
  s({
    keyword: "audit biais intelligence artificielle",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/biais-ethique-ia",
  }),
  s({
    keyword: "éthique IA entreprise France audit",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/biais-ethique-ia",
  }),
  s({
    keyword: "détection biais algorithme recrutement",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/biais-ethique-ia",
  }),
  s({
    keyword: "fairness IA RH entreprise audit",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/biais-ethique-ia",
  }),
  s({
    keyword: "risques biais IA entreprise France",
    module: "audit",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/biais-ethique-ia",
  }),
  s({
    keyword: "comment détecter les biais dans un algorithme IA ?",
    module: "audit",
    intent: "voice_search",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/biais-ethique-ia",
  }),
  s({
    keyword: "définition biais intelligence artificielle entreprise",
    module: "audit",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/biais-ethique-ia",
  }),
  s({
    keyword: "types de biais IA à auditer dans une entreprise",
    module: "audit",
    intent: "featured_snippet",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/biais-ethique-ia",
  }),
  s({
    keyword: "audit biais IA obligatoire AI Act entreprise France",
    module: "audit",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/biais-ethique-ia",
  }),
];

// ── CLUSTER 7 : audit-prompt-engineering ──────────────────────────────────────
const AUDIT_PROMPT: KeywordSeed[] = [
  s({
    keyword: "audit qualité prompts LLM entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/prompt-engineering",
  }),
  s({
    keyword: "évaluation prompts IA production",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/prompt-engineering",
  }),
  s({
    keyword: "améliorer prompts entreprise cabinet",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/prompt-engineering",
  }),
  s({
    keyword: "optimisation prompt engineering PME",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/prompt-engineering",
  }),
  s({
    keyword: "comment améliorer la qualité des prompts IA de mon équipe ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/prompt-engineering",
  }),
  s({
    keyword: "définition prompt engineering audit entreprise",
    module: "audit",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/prompt-engineering",
  }),
  s({
    keyword: "critères évaluation prompt IA entreprise 5 dimensions",
    module: "audit",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/prompt-engineering",
  }),
];

// ── CLUSTER 8 : audit-formation-equipes ───────────────────────────────────────
const AUDIT_FORMATION_EQUIPES: KeywordSeed[] = [
  s({
    keyword: "audit compétences IA équipe entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/competences-ia",
  }),
  s({
    keyword: "diagnostic AI literacy salariés PME",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/competences-ia",
  }),
  s({
    keyword: "skill gap IA entreprise évaluation",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/competences-ia",
  }),
  s({
    keyword: "état des lieux compétences IA équipes",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/competences-ia",
  }),
  s({
    keyword: "comment évaluer le niveau IA de mes équipes ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/competences-ia",
  }),
  s({
    keyword: "définition AI literacy compétences numériques IA",
    module: "audit",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/competences-ia",
  }),
  s({
    keyword: "niveaux compétences IA en entreprise grille évaluation",
    module: "audit",
    intent: "featured_snippet",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/competences-ia",
  }),
  s({
    keyword: "audit skills IA vs plan formation IA comparaison",
    module: "audit",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/competences-ia",
  }),
];

// ── CLUSTER 9 : audit-conformite-ai-act ───────────────────────────────────────
const AUDIT_AI_ACT: KeywordSeed[] = [
  s({
    keyword: "audit conformité AI Act France 2026",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "auto-audit AI Act PME obligatoire",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "règlement européen IA conformité entreprise",
    module: "audit",
    intent: "informationnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "cabinet audit AI Act France spécialisé",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "checklist AI Act PME 2026",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "obligations AI Act pour les entreprises françaises 2026",
    module: "audit",
    intent: "informationnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "quelle est la deadline conformité AI Act pour mon entreprise ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "comment se mettre en conformité AI Act rapidement ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "définition AI Act règlement européen intelligence artificielle",
    module: "audit",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "étapes conformité AI Act entreprise 2026 en 7 points",
    module: "audit",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "AI Act vs RGPD différences obligations entreprise",
    module: "audit",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
  s({
    keyword: "risques non-conformité AI Act amendes entreprise",
    module: "audit",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/conformite-ai-act",
  }),
];

// ── CLUSTER 10 : audit-fournisseurs-ia ────────────────────────────────────────
const AUDIT_FOURNISSEURS: KeywordSeed[] = [
  s({
    keyword: "audit fournisseurs IA prestataires",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/fournisseurs-ia",
  }),
  s({
    keyword: "due diligence partenaires IA entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/fournisseurs-ia",
  }),
  s({
    keyword: "audit prestataires LLM données entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/fournisseurs-ia",
  }),
  s({
    keyword: "comment choisir son fournisseur IA pour entreprise ?",
    module: "audit",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/fournisseurs-ia",
  }),
  s({
    keyword: "critères évaluation fournisseur IA PME",
    module: "audit",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/fournisseurs-ia",
  }),
  s({
    keyword: "OpenAI vs Mistral vs Anthropic comparatif entreprise France",
    module: "audit",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/fournisseurs-ia",
  }),
];

// ── CLUSTER 11 : audit-tpe-specifique ─────────────────────────────────────────
const AUDIT_TPE: KeywordSeed[] = [
  s({
    keyword: "audit IA artisan commerçant TPE",
    module: "audit",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/audit/tpe",
  }),
  s({
    keyword: "diagnostic IA indépendant freelance",
    module: "audit",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/tpe",
  }),
  s({
    keyword: "audit IA petite entreprise tarif abordable",
    module: "audit",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/audit/tpe",
  }),
  s({
    keyword: "est-ce que l'IA peut vraiment aider une petite entreprise ?",
    module: "audit",
    intent: "voice_search",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/tpe",
  }),
  s({
    keyword: "audit IA pour artisan prix et durée",
    module: "audit",
    intent: "informationnel",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/tpe",
  }),
  s({
    keyword: "avantages audit IA pour TPE gain de temps",
    module: "audit",
    intent: "benefice",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/audit/tpe",
  }),
];

// ── CLUSTER 12 : audit-grand-compte ───────────────────────────────────────────
const AUDIT_GRAND_COMPTE: KeywordSeed[] = [
  s({
    keyword: "audit IA grand compte industriel",
    module: "audit",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/grand-compte",
  }),
  s({
    keyword: "cabinet audit IA secteur bancaire assurance",
    module: "audit",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/grand-compte",
  }),
  s({
    keyword: "audit IA ETI croissance accompagnement",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/eti",
  }),
  s({
    keyword: "governance IA grand groupe audit",
    module: "audit",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit/grand-compte",
  }),
  s({
    keyword: "comment structurer la gouvernance IA dans un grand groupe ?",
    module: "audit",
    intent: "voice_search",
    cible: "grand-compte",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/grand-compte",
  }),
  s({
    keyword: "audit IA grand groupe vs cabinet conseil global",
    module: "audit",
    intent: "commercial_investigation",
    cible: "grand-compte",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/audit/grand-compte",
  }),
];

export const KW_AUDIT_CLUSTERS: KeywordSeed[] = [
  ...AUDIT_SECURITE,
  ...AUDIT_RGPD,
  ...AUDIT_PERFORMANCE,
  ...AUDIT_COUTS,
  ...AUDIT_STRATEGIE,
  ...AUDIT_BIAIS,
  ...AUDIT_PROMPT,
  ...AUDIT_FORMATION_EQUIPES,
  ...AUDIT_AI_ACT,
  ...AUDIT_FOURNISSEURS,
  ...AUDIT_TPE,
  ...AUDIT_GRAND_COMPTE,
];
