// src/content/keywords/g1m-audit-maturite.ts
// Module AUDIT — segmentation par MATURITÉ IA de la cible (2026-06-02).
//
// Axe complémentaire de g1-audit / g1c-audit-clusters (qui segmentent par
// taille/secteur), pensé comme g3g l'a fait pour l'implémentation (existant/neuf) :
//   - DÉCOUVERTE : aucun projet IA encore → formats d'entrée (audit 1 jour, ciblé)
//   - AVANCÉ     : un POC/projet IA est lancé → audits stratégiques (PME/ETI)
//   - TRANSVERSE : piliers anti-cannibalisation + AEO (audit vs formation, après audit)
//
// Garde-fous :
//   - DÉCOUVERTE et AVANCÉ ne partagent JAMAIS une urlCible (anti-cannibalisation).
//   - urlCible = routes audit RÉELLES uniquement (anti-soft-404) :
//     /fr/audit, /fr/audit/tpe-1-jour, /fr/audit/cible, /fr/audit/strategique-pme,
//     /fr/audit/strategique-eti, /fr/audit/demande.
//   - AUCUN claim de financement (Qualiopi/OPCO/CPF/aide/subvention) — Axion-IA
//     n'en a aucun (sinon publicité trompeuse) ; filtré aussi par isClean().

import type { KeywordSeed } from "./types";

const PILIER = "/fr/audit";

export const KW_AUDIT_MATURITE: KeywordSeed[] = [
  // ─── DÉCOUVERTE — pas encore de projet IA (entrée : 1 jour / ciblé / hub) ───
  {
    keyword: "par où commencer avec l'intelligence artificielle en entreprise",
    intent: "informationnel",
    module: "audit",
    cible: "pme",
    maturite_cible: "decouverte",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/audit/tpe-1-jour",
    canonicalParent: PILIER,
    note: "DÉCOUVERTE — entrée par l'audit flash 1 jour. Aucun projet IA en cours.",
  },
  {
    keyword: "audit IA pour une entreprise sans projet IA en cours",
    intent: "transactionnel",
    module: "audit",
    cible: "pme",
    maturite_cible: "decouverte",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/audit/tpe-1-jour",
    canonicalParent: PILIER,
  },
  {
    keyword: "comment savoir si mon entreprise est prête pour l'IA ?",
    intent: "aeo",
    module: "audit",
    cible: "pme",
    maturite_cible: "decouverte",
    niveau: 2,
    priorite: 2,
    urlCible: PILIER,
    canonicalParent: PILIER,
  },
  {
    keyword: "identifier les premiers cas d'usage IA de ma PME",
    intent: "transactionnel",
    module: "audit",
    cible: "pme",
    maturite_cible: "decouverte",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/audit/cible",
    canonicalParent: PILIER,
  },
  {
    keyword: "quels processus automatiser en premier avec l'IA ?",
    intent: "aeo",
    module: "audit",
    cible: "pme",
    maturite_cible: "decouverte",
    niveau: 2,
    priorite: 2,
    urlCible: "/fr/audit/cible",
    canonicalParent: PILIER,
  },
  {
    keyword: "évaluer le potentiel IA de mon entreprise avant de se lancer",
    intent: "transactionnel",
    module: "audit",
    cible: "pme",
    maturite_cible: "decouverte",
    niveau: 3,
    priorite: 2,
    urlCible: PILIER,
    canonicalParent: PILIER,
  },
  {
    keyword: "diagnostic IA pour un dirigeant qui débute sur le sujet",
    intent: "transactionnel",
    module: "audit",
    cible: "tpe",
    maturite_cible: "decouverte",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/audit/tpe-1-jour",
    canonicalParent: PILIER,
  },
  {
    keyword: "feuille de route IA pour une PME qui démarre dans l'IA",
    intent: "transactionnel",
    module: "audit",
    cible: "pme",
    maturite_cible: "decouverte",
    niveau: 2,
    priorite: 2,
    urlCible: "/fr/audit/cible",
    canonicalParent: PILIER,
  },

  // ─── AVANCÉ — un POC / projet IA est déjà lancé (audits stratégiques) ───────
  {
    keyword: "industrialiser un POC IA et le passer en production",
    intent: "transactionnel",
    module: "audit",
    cible: "eti",
    maturite_cible: "avance",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/audit/strategique-eti",
    canonicalParent: PILIER,
    note: "AVANCÉ — POC déjà démarré, enjeu de mise à l'échelle.",
  },
  {
    keyword: "audit IA après un POC qui n'a pas tenu ses promesses",
    intent: "transactionnel",
    module: "audit",
    cible: "pme",
    maturite_cible: "avance",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/audit/strategique-pme",
    canonicalParent: PILIER,
  },
  {
    keyword: "pourquoi mon projet IA n'avance pas ?",
    intent: "aeo",
    module: "audit",
    cible: "pme",
    maturite_cible: "avance",
    niveau: 2,
    priorite: 2,
    urlCible: "/fr/audit/strategique-pme",
    canonicalParent: PILIER,
  },
  {
    keyword: "passer d'un POC IA à un déploiement à l'échelle",
    intent: "transactionnel",
    module: "audit",
    cible: "eti",
    maturite_cible: "avance",
    niveau: 2,
    priorite: 2,
    urlCible: "/fr/audit/strategique-eti",
    canonicalParent: PILIER,
  },
  {
    keyword: "évaluer la maturité IA de mon organisation",
    intent: "transactionnel",
    module: "audit",
    cible: "eti",
    maturite_cible: "avance",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/audit/strategique-eti",
    canonicalParent: PILIER,
  },
  {
    keyword: "audit IA pour structurer une stratégie IA déjà lancée",
    intent: "transactionnel",
    module: "audit",
    cible: "eti",
    maturite_cible: "avance",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/audit/strategique-eti",
    canonicalParent: PILIER,
  },
  {
    keyword: "débloquer un projet IA enlisé dans mon entreprise",
    intent: "transactionnel",
    module: "audit",
    cible: "pme",
    maturite_cible: "avance",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/audit/strategique-pme",
    canonicalParent: PILIER,
  },
  {
    keyword: "comment prioriser plusieurs projets IA déjà en cours ?",
    intent: "aeo",
    module: "audit",
    cible: "eti",
    maturite_cible: "avance",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/audit/strategique-eti",
    canonicalParent: PILIER,
  },

  // ─── TRANSVERSE — piliers anti-cannibalisation + AEO ────────────────────────
  {
    keyword: "audit IA ou formation IA : par quoi commencer ?",
    intent: "aeo",
    module: "audit",
    cible: "pme",
    maturite_cible: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: PILIER,
    canonicalParent: PILIER,
    note: "Pilier anti-cannibalisation audit vs formation — arbitrage selon maturité.",
  },
  {
    keyword: "que se passe-t-il après un audit IA ?",
    intent: "aeo",
    module: "audit",
    cible: "pme",
    maturite_cible: "transverse",
    niveau: 2,
    priorite: 2,
    urlCible: PILIER,
    canonicalParent: PILIER,
    note: "Pont audit → implémentation (suite logique).",
  },
  {
    keyword: "à quoi sert concrètement un audit IA en entreprise",
    intent: "informationnel",
    module: "audit",
    cible: "pme",
    maturite_cible: "transverse",
    niveau: 2,
    priorite: 2,
    urlCible: PILIER,
    canonicalParent: PILIER,
  },
  {
    keyword: "audit IA pour PME ou pour ETI : quelles différences ?",
    intent: "comparatif",
    module: "audit",
    cible: "eti",
    maturite_cible: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: PILIER,
    canonicalParent: PILIER,
  },
  {
    keyword: "demander un audit IA adapté à la maturité de mon entreprise",
    intent: "transactionnel",
    module: "audit",
    cible: "pme",
    maturite_cible: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/audit/demande",
    canonicalParent: PILIER,
  },
];
