/**
 * Keywords Phase 2 Sprint Perfection 2026-05-22 — Verticale INTERVENTIONS_FORMATIONS
 * 12 clusters × ~25 keywords = ~290 seeds
 */

import type { KeywordSeed } from "./types";

type SC = Omit<KeywordSeed, "injection" | "kbType">;
function s(seed: SC): KeywordSeed {
  const full: Record<string, unknown> = { ...seed, kbType: "intervention_module", injection: {} };
  return full as unknown as KeywordSeed;
}

// ── CLUSTER 1 : formation-ia-dirigeants ───────────────────────────────────────
const FORM_DIRIGEANTS: KeywordSeed[] = [
  s({
    keyword: "formation IA pour dirigeants PME",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  s({
    keyword: "formation intelligence artificielle managers France",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  s({
    keyword: "sensibilisation IA comité de direction",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  s({
    keyword: "formation stratégique IA PDG DG ETI",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  s({
    keyword: "atelier IA pour dirigeants PME 1 journée",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  s({
    keyword: "formation IA décideur entreprise France 2026",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  s({
    keyword: "quelle formation IA choisir quand on est dirigeant ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  s({
    keyword: "comment former ses dirigeants à l'intelligence artificielle ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  s({
    keyword: "définition formation IA dirigeants contenu programme",
    module: "interventions-formations",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  s({
    keyword: "programme formation IA dirigeants en 3 modules",
    module: "interventions-formations",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  s({
    keyword: "formation IA dirigeants vs conférence IA vs coaching IA",
    module: "interventions-formations",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  s({
    keyword: "bénéfices formation IA dirigeants gains décisionnels",
    module: "interventions-formations",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
];

// ── CLUSTER 2 : formation-ia-debutants ────────────────────────────────────────
const FORM_DEBUTANTS: KeywordSeed[] = [
  s({
    keyword: "formation IA débutant sans prérequis",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/formations/ia-debutants",
  }),
  s({
    keyword: "initiation intelligence artificielle entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/formations/ia-debutants",
  }),
  s({
    keyword: "découverte IA pour non-techniciens entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/formations/ia-debutants",
  }),
  s({
    keyword: "formation IA accessible salarié sans bagage technique",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/formations/ia-debutants",
  }),
  s({
    keyword: "comment apprendre l'IA quand on n'est pas développeur ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-debutants",
  }),
  s({
    keyword: "peut-on se former à l'IA sans bagage informatique ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-debutants",
  }),
  s({
    keyword: "définition initiation IA entreprise contenu pédagogique",
    module: "interventions-formations",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-debutants",
  }),
  s({
    keyword: "points clés formation IA débutant en entreprise",
    module: "interventions-formations",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-debutants",
  }),
  s({
    keyword: "formation IA débutant Axion-IA vs OpenClassrooms vs Le Wagon",
    module: "interventions-formations",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-debutants",
  }),
];

// ── CLUSTER 3 : formation-ia-developpeurs ─────────────────────────────────────
const FORM_DEV: KeywordSeed[] = [
  s({
    keyword: "formation IA développeurs Python entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-developpeurs",
  }),
  s({
    keyword: "formation LLM API développeurs équipe technique",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-developpeurs",
  }),
  s({
    keyword: "atelier intégration IA développeurs web",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-developpeurs",
  }),
  s({
    keyword: "formation agents IA autonomes développeurs",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-developpeurs",
  }),
  s({
    keyword: "comment former ses développeurs aux API OpenAI Anthropic ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "startup-scaleup",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-developpeurs",
  }),
  s({
    keyword: "programme formation IA développeurs 3 jours",
    module: "interventions-formations",
    intent: "featured_snippet",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-developpeurs",
  }),
  s({
    keyword: "formation IA développeurs bootcamp vs formation intra-entreprise",
    module: "interventions-formations",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-developpeurs",
  }),
];

// ── CLUSTER 4 : formation-prompt-engineering ──────────────────────────────────
const FORM_PROMPT: KeywordSeed[] = [
  s({
    keyword: "formation prompt engineering entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/formations/prompt-engineering",
  }),
  s({
    keyword: "atelier prompts IA équipe commerciale",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/formations/prompt-engineering",
  }),
  s({
    keyword: "formation rédaction prompts ChatGPT Claude entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/formations/prompt-engineering",
  }),
  s({
    keyword: "maîtriser le prompting IA en entreprise formation",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/formations/prompt-engineering",
  }),
  s({
    keyword: "comment écrire de bons prompts pour son équipe ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/prompt-engineering",
  }),
  s({
    keyword: "qu'est-ce que le prompt engineering en entreprise ?",
    module: "interventions-formations",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/prompt-engineering",
  }),
  s({
    keyword: "techniques prompt engineering entreprise 5 méthodes",
    module: "interventions-formations",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/prompt-engineering",
  }),
  s({
    keyword: "gain productivité formation prompt engineering entreprise",
    module: "interventions-formations",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/prompt-engineering",
  }),
];

// ── CLUSTER 5 : formation-ia-marketing ────────────────────────────────────────
const FORM_MARKETING: KeywordSeed[] = [
  s({
    keyword: "formation IA marketing digital entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/formations/ia-marketing",
  }),
  s({
    keyword: "utiliser IA pour créer du contenu marketing formation",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/formations/ia-marketing",
  }),
  s({
    keyword: "formation IA rédaction web SEO équipe marketing",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-marketing",
  }),
  s({
    keyword: "atelier IA génération contenu entreprise marketing",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-marketing",
  }),
  s({
    keyword: "comment utiliser l'IA pour son marketing digital ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-marketing",
  }),
  s({
    keyword: "définition IA marketing contenu génération automatisée",
    module: "interventions-formations",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-marketing",
  }),
  s({
    keyword: "résultats formation IA marketing 30 % gain de temps",
    module: "interventions-formations",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-marketing",
  }),
];

// ── CLUSTER 6 : formation-ia-rh ───────────────────────────────────────────────
const FORM_RH: KeywordSeed[] = [
  s({
    keyword: "formation IA ressources humaines recrutement",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-rh",
  }),
  s({
    keyword: "utiliser IA pour le recrutement formation RH",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-rh",
  }),
  s({
    keyword: "formation IA gestion talents SIRH",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-rh",
  }),
  s({
    keyword: "comment l'IA peut aider les équipes RH ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-rh",
  }),
  s({
    keyword: "définition IA appliquée aux RH entreprise",
    module: "interventions-formations",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-rh",
  }),
  s({
    keyword: "formation IA RH vs logiciel RH classique comparatif",
    module: "interventions-formations",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-rh",
  }),
];

// ── CLUSTER 7 : formation-ia-finance ──────────────────────────────────────────
const FORM_FINANCE: KeywordSeed[] = [
  s({
    keyword: "formation IA finance comptabilité entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-finance",
  }),
  s({
    keyword: "utiliser IA pour automatiser la comptabilité PME",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-finance",
  }),
  s({
    keyword: "formation IA analyse financière directeur financier",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-finance",
  }),
  s({
    keyword: "comment utiliser l'IA pour automatiser sa comptabilité ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-finance",
  }),
  s({
    keyword: "gains automatisation IA finance PME 40 % de temps",
    module: "interventions-formations",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-finance",
  }),
];

// ── CLUSTER 8 : formation-ia-juridique ────────────────────────────────────────
const FORM_JURIDIQUE: KeywordSeed[] = [
  s({
    keyword: "formation IA juridique cabinet avocat",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-juridique",
  }),
  s({
    keyword: "utiliser IA pour contrats juridiques formation",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-juridique",
  }),
  s({
    keyword: "formation IA LegalTech droit des affaires",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-juridique",
  }),
  s({
    keyword: "comment les avocats utilisent l'IA pour gagner du temps ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "grand-compte",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-juridique",
  }),
  s({
    keyword: "définition LegalTech IA cabinet avocat",
    module: "interventions-formations",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-juridique",
  }),
];

// ── CLUSTER 9 : formation-ia-secteur-public ───────────────────────────────────
const FORM_PUBLIC: KeywordSeed[] = [
  s({
    keyword: "formation IA collectivité territoriale mairie",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "collectivite-mairie",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-secteur-public",
  }),
  s({
    keyword: "sensibilisation IA agents publics formation",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "collectivite-mairie",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/ia-secteur-public",
  }),
  s({
    keyword: "formation IA service public transformation digitale",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "collectivite-mairie",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/ia-secteur-public",
  }),
  s({
    keyword: "comment intégrer l'IA dans une collectivité publique ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "collectivite-mairie",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-secteur-public",
  }),
  s({
    keyword: "formation IA secteur public vs privé différences",
    module: "interventions-formations",
    intent: "commercial_investigation",
    cible: "collectivite-mairie",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/ia-secteur-public",
  }),
];

// ── CLUSTER 10 : formation-rag-vectoriel ──────────────────────────────────────
const FORM_RAG: KeywordSeed[] = [
  s({
    keyword: "formation RAG vectoriel entreprise technique",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/rag-vectoriel",
  }),
  s({
    keyword: "formation base vectorielle Pinecone Qdrant entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/rag-vectoriel",
  }),
  s({
    keyword: "atelier RAG chatbot documentation interne",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/rag-vectoriel",
  }),
  s({
    keyword: "qu'est-ce qu'un système RAG et pourquoi en avoir un ?",
    module: "interventions-formations",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/rag-vectoriel",
  }),
  s({
    keyword: "comment construire un RAG pour son entreprise en 5 étapes",
    module: "interventions-formations",
    intent: "featured_snippet",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/rag-vectoriel",
  }),
];

// ── CLUSTER 11 : formation-certifications ─────────────────────────────────────
const FORM_CERTIF: KeywordSeed[] = [
  s({
    keyword: "formation IA certification professionnelle France",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/certifications-ia",
  }),
  s({
    keyword: "certification intelligence artificielle managers",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formations/certifications-ia",
  }),
  s({
    keyword: "attestation formation IA entreprise intra",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/formations/certifications-ia",
  }),
  s({
    keyword: "quelle certification IA obtenir pour valoriser son profil ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/certifications-ia",
  }),
  s({
    keyword: "meilleures certifications IA France 2026 comparatif",
    module: "interventions-formations",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/formations/certifications-ia",
  }),
];

// ── CLUSTER 12 : intervention-sur-site ────────────────────────────────────────
const INTERVENTION_SITE: KeywordSeed[] = [
  s({
    keyword: "intervention formation IA sur site entreprise",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/interventions/sur-site",
  }),
  s({
    keyword: "formation IA intra-entreprise sur mesure",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/interventions/sur-site",
  }),
  s({
    keyword: "formation IA team building équipe PME",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/interventions/sur-site",
  }),
  s({
    keyword: "conférence IA entreprise keynote speaker",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/interventions/conference-ia",
  }),
  s({
    keyword: "comment organiser une formation IA en interne ?",
    module: "interventions-formations",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/interventions/sur-site",
  }),
  s({
    keyword: "formation IA intra-entreprise vs inter-entreprise avantages",
    module: "interventions-formations",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/interventions/sur-site",
  }),
  s({
    keyword: "ROI formation IA équipe entreprise 3 mois",
    module: "interventions-formations",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/interventions/sur-site",
  }),
];

export const KW_FORMATIONS_CLUSTERS: KeywordSeed[] = [
  ...FORM_DIRIGEANTS,
  ...FORM_DEBUTANTS,
  ...FORM_DEV,
  ...FORM_PROMPT,
  ...FORM_MARKETING,
  ...FORM_RH,
  ...FORM_FINANCE,
  ...FORM_JURIDIQUE,
  ...FORM_PUBLIC,
  ...FORM_RAG,
  ...FORM_CERTIF,
  ...INTERVENTION_SITE,
];
