// src/content/keywords/g2m-formation-clusters.ts
// Module INTERVENTIONS_FORMATIONS — intégration du CSV `axion_keywords_formation.csv`
// (taxonomie pilier → catégorie → landing → FAQ-AEO). 2026-06-02 (Will).
//
// Axe nouveau `formationFormat` (ponctuel / recurrent / transverse) — garde-fou
// anti-cannibalisation, calqué sur g1m (audit/maturité) et g3g (impl/existant-neuf) :
//   - PONCTUEL  : one-shot (demi-journée, 1 j, 2 j, séminaire).
//   - RECURRENT : abonnement / accompagnement dans la durée (différenciant Axion-IA).
//   - TRANSVERSE: par outil / fonction / format / public / géo / AEO.
//
// Garde-fous (cf. [[refonte-pages-intention]]) :
//   - PONCTUEL et RECURRENT ne partagent JAMAIS une urlCible (anti-cannibalisation).
//   - urlCible = routes formation planifiées `/fr/formations/*` (même convention que
//     g2c-formations-clusters ; annotation de génération, jamais émise au sitemap).
//   - AUCUN claim de financement (Qualiopi/OPCO/CPF/aide/subvention) — Axion-IA n'en
//     a aucun ; filtré aussi par isClean() de master.ts.
//   - Outils no-code de marque (Make / n8n) écartés (BANNED_TERMS) — les requêtes
//     "automatisation" sont couvertes sans marque ailleurs.
//   - keyword AEO reformulé en question (termine par "?").

import type { KeywordSeed } from "./types";

const PILIER = "/fr/formations";

type SC = Omit<KeywordSeed, "module" | "kbType" | "canonicalParent"> &
  Partial<Pick<KeywordSeed, "canonicalParent">>;
/** Injecte module + kbType + canonicalParent par défaut pour alléger chaque seed. */
function f(seed: SC): KeywordSeed {
  return {
    module: "interventions-formations",
    kbType: "intervention_module",
    canonicalParent: PILIER,
    ...seed,
  };
}

// ─── PONCTUEL — formats one-shot (jamais la même URL que RECURRENT) ────────────
const FORM_PONCTUEL: KeywordSeed[] = [
  f({
    keyword: "formation IA ponctuelle en entreprise",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "ponctuel",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/formations/ponctuelle",
    note: "Catégorie PONCTUEL (4h / 1j / 2j) — séparée strictement du cluster RECURRENT.",
  }),
  f({
    keyword: "formation IA d'une journée pour entreprise",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "ponctuel",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/une-journee",
  }),
  f({
    keyword: "formation IA sur deux jours en entreprise",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "ponctuel",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/formations/deux-jours",
  }),
  f({
    keyword: "formation IA en demi-journée découverte",
    intent: "transactionnel",
    cible: "tpe",
    formationFormat: "ponctuel",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/formations/demi-journee",
  }),
  f({
    keyword: "séminaire IA pour dirigeants sur plusieurs jours",
    intent: "transactionnel",
    cible: "eti",
    formationFormat: "ponctuel",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/seminaire-dirigeants",
  }),
  f({
    keyword: "quelle durée prévoir pour une formation IA ?",
    intent: "aeo",
    cible: "toutes-cibles",
    formationFormat: "ponctuel",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/ponctuelle",
  }),
];

// ─── RECURRENT — accompagnement dans la durée (différenciant Axion-IA) ─────────
const FORM_RECURRENT: KeywordSeed[] = [
  f({
    keyword: "formation IA régulière pour entreprise",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "recurrent",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/formations/recurrente",
    note: "Catégorie RECURRENT (abonnement mensuel/bimensuel) — peu de concurrents le proposent.",
  }),
  f({
    keyword: "formation IA mensuelle pour les équipes",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "recurrent",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/formations/mensuelle",
  }),
  f({
    keyword: "accompagnement IA continu en entreprise",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "recurrent",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/formations/accompagnement-continu",
  }),
  f({
    keyword: "formateur IA dédié à mon entreprise sur la durée",
    intent: "benefice",
    cible: "eti",
    formationFormat: "recurrent",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/formateur-dedie",
  }),
];

// ─── TRANSVERSE — par outil (territoire fort volume, sans no-code de marque) ───
const FORM_OUTILS: KeywordSeed[] = [
  f({
    keyword: "formation IA par outil pour les équipes",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/formations/par-outil",
    note: "Hub vers ChatGPT / Claude / Copilot / Mistral — gros volume.",
  }),
  f({
    keyword: "formation ChatGPT en entreprise",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/formations/chatgpt",
  }),
  f({
    keyword: "formation Claude pour les équipes",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/formations/claude",
  }),
  f({
    keyword: "formation Microsoft Copilot en entreprise",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/formations/copilot",
  }),
  f({
    keyword: "formation Mistral IA pour entreprise française",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/mistral",
    note: "Angle IA souveraine FR.",
  }),
  f({
    keyword: "formation Gemini de Google en entreprise",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/formations/gemini",
  }),
  f({
    keyword: "formation Midjourney pour la création visuelle",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/midjourney",
  }),
  f({
    keyword: "formation au prompt engineering pour les équipes",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/formations/prompt-engineering",
    note: "Compétence transverse, forte demande.",
  }),
  f({
    keyword: "formation ChatGPT pour la rédaction et la synthèse",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/formations/chatgpt",
  }),
  f({
    keyword: "formation Copilot pour Excel et la bureautique",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/copilot",
  }),
  f({
    keyword: "apprendre à écrire des prompts efficaces",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/prompt-engineering",
  }),
  f({
    keyword: "sur quels outils IA former mes équipes ?",
    intent: "aeo",
    cible: "toutes-cibles",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/formations/par-outil",
  }),
];

// ─── TRANSVERSE — par fonction métier ──────────────────────────────────────────
const FORM_FONCTIONS: KeywordSeed[] = [
  f({
    keyword: "formation IA par fonction métier en entreprise",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/formations/par-fonction",
    note: "Hub vers commercial / marketing / RH / finance.",
  }),
  f({
    keyword: "formation IA pour les équipes commerciales",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/ia-commerciale",
  }),
  f({
    keyword: "formation IA pour le marketing et la communication",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/formations/ia-marketing",
  }),
  f({
    keyword: "formation IA pour les RH et le recrutement",
    intent: "transactionnel",
    cible: "eti",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/ia-rh",
  }),
  f({
    keyword: "formation IA pour la finance et la comptabilité",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/ia-finance",
  }),
  f({
    keyword: "formation IA pour les managers d'équipe",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/ia-managers",
  }),
  f({
    keyword: "formation IA pour la productivité bureautique",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/ia-productivite",
  }),
  f({
    keyword: "formation IA pour le service client",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/formations/ia-service-client",
  }),
  f({
    keyword: "formation IA pour les réseaux sociaux et le contenu",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/formations/ia-marketing",
  }),
  f({
    keyword: "utiliser l'IA pour gagner du temps au quotidien",
    intent: "benefice",
    cible: "tpe",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/ia-productivite",
    note: "Angle bénéfice.",
  }),
];

// ─── TRANSVERSE — par format pédagogique & par public ──────────────────────────
const FORM_FORMAT_PUBLIC: KeywordSeed[] = [
  f({
    keyword: "formation IA par format pédagogique",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 2,
    urlCible: "/fr/formations/formats",
  }),
  f({
    keyword: "formation IA en présentiel sur site",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/formations/presentiel",
    note: "Différenciant Axion-IA — sur site.",
  }),
  f({
    keyword: "formation IA intra-entreprise personnalisée",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/formations/intra-entreprise",
  }),
  f({
    keyword: "formation IA à distance pour les équipes",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/a-distance",
  }),
  f({
    keyword: "formation IA par public cible en entreprise",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 2,
    urlCible: "/fr/formations/par-public",
  }),
  f({
    keyword: "formation IA pour dirigeants de TPE",
    intent: "transactionnel",
    cible: "tpe",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/ia-dirigeants",
  }),
  f({
    keyword: "formation IA pour les équipes de PME",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/formations/equipes-pme",
    note: "Cœur de cible.",
  }),
  f({
    keyword: "formation IA pour ETI multi-sites",
    intent: "transactionnel",
    cible: "eti",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/formations/eti-multisites",
  }),
  f({
    keyword: "formation IA pour artisans et TPE",
    intent: "transactionnel",
    cible: "tpe",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/formations/tpe-artisan",
  }),
  f({
    keyword: "vaut-il mieux une formation IA en présentiel ou à distance ?",
    intent: "aeo",
    cible: "toutes-cibles",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/formats",
  }),
];

// ─── TRANSVERSE — géo (keyword porte la ville ; URL = catégorie par-ville) ──────
const FORM_GEO: KeywordSeed[] = [
  f({
    keyword: "formation IA par région en France",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 2,
    urlCible: "/fr/formations/par-ville",
  }),
  f({
    keyword: "formation IA pour entreprise à Paris",
    intent: "local",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/par-ville",
  }),
  f({
    keyword: "formation IA pour entreprise à Lyon",
    intent: "local",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/par-ville",
  }),
  f({
    keyword: "formation IA pour entreprise à Marseille",
    intent: "local",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/formations/par-ville",
  }),
  f({
    keyword: "formation IA pour entreprise à Bordeaux",
    intent: "local",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/formations/par-ville",
  }),
  f({
    keyword: "formation IA pour entreprise à Toulouse",
    intent: "local",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/formations/par-ville",
  }),
];

// ─── TRANSVERSE — débutants / acculturation ────────────────────────────────────
const FORM_DECOUVERTE: KeywordSeed[] = [
  f({
    keyword: "acculturation à l'IA pour les équipes",
    intent: "informationnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 2,
    urlCible: "/fr/formations/ia-debutants",
    note: "Niveau débutant / sensibilisation.",
  }),
  f({
    keyword: "formation à l'IA pour grands débutants",
    intent: "transactionnel",
    cible: "tpe",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/ia-debutants",
  }),
  f({
    keyword: "sensibilisation des équipes à l'intelligence artificielle",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/sensibilisation",
  }),
  f({
    keyword: "comprendre les fondamentaux de l'intelligence artificielle",
    intent: "informationnel",
    cible: "toutes-cibles",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/connaissances",
    canonicalParent: "/fr/connaissances",
  }),
  f({
    keyword: "faut-il des prérequis pour suivre une formation IA ?",
    intent: "aeo",
    cible: "toutes-cibles",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/formations/ia-debutants",
    note: "Lève l'objection — aucun prérequis.",
  }),
];

// ─── TRANSVERSE — piliers de routage + AEO d'arbitrage ─────────────────────────
const FORM_PILIERS_AEO: KeywordSeed[] = [
  f({
    keyword: "formation IA sur mesure pour entreprise",
    intent: "transactionnel",
    cible: "pme",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 2,
    urlCible: PILIER,
    note: "Pilier — intra-entreprise personnalisé (cœur de l'offre).",
  }),
  f({
    keyword: "formation pour apprendre à créer des agents IA",
    intent: "transactionnel",
    cible: "startup-scaleup",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 2,
    urlCible: PILIER,
    note: "Pilier — ici on FORME à créer, on ne livre pas (vs Implementation).",
  }),
  f({
    keyword: "combien coûte une formation IA en entreprise ?",
    intent: "aeo",
    cible: "toutes-cibles",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: PILIER,
  }),
  f({
    keyword: "combien de participants par formation IA ?",
    intent: "aeo",
    cible: "toutes-cibles",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: PILIER,
  }),
  f({
    keyword: "comment former ses équipes à l'IA ?",
    intent: "aeo",
    cible: "toutes-cibles",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: PILIER,
    note: "Top funnel volume.",
  }),
  f({
    keyword: "formation IA classique ou formateur qui code, que choisir ?",
    intent: "aeo",
    cible: "toutes-cibles",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: PILIER,
    note: "Différenciant — formateurs qui déploient.",
  }),
  f({
    keyword: "formation IA ou audit IA, par où commencer ?",
    intent: "aeo",
    cible: "toutes-cibles",
    formationFormat: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: PILIER,
    note: "Arbitrage inter-modules (anti-cannibalisation formation vs audit).",
  }),
  f({
    keyword: "vaut-il mieux une formation IA ponctuelle ou régulière ?",
    intent: "aeo",
    cible: "toutes-cibles",
    formationFormat: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: PILIER,
    note: "Oppose PONCTUEL vs RECURRENT — page interne d'arbitrage.",
  }),
];

export const KW_FORMATION_CLUSTERS_V2: KeywordSeed[] = [
  ...FORM_PONCTUEL,
  ...FORM_RECURRENT,
  ...FORM_OUTILS,
  ...FORM_FONCTIONS,
  ...FORM_FORMAT_PUBLIC,
  ...FORM_GEO,
  ...FORM_DECOUVERTE,
  ...FORM_PILIERS_AEO,
];
