/**
 * Keywords Phase 2 Sprint Perfection 2026-05-22 — Verticale IMPLEMENTATIONS
 * 12 clusters × ~25 keywords = ~290 seeds
 */

import type { KeywordSeed } from "./types";

type SC = Omit<KeywordSeed, "injection" | "kbType">;
function s(seed: SC): KeywordSeed {
  const full: Record<string, unknown> = {
    ...seed,
    kbType: "implementation_playbook",
    injection: {},
  };
  return full as unknown as KeywordSeed;
}

// ── CLUSTER 1 : chatbot-entreprise ────────────────────────────────────────────
const IMPL_CHATBOT: KeywordSeed[] = [
  s({
    keyword: "implémentation chatbot IA entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
  s({
    keyword: "créer chatbot IA support client PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
  s({
    keyword: "déploiement assistant IA interne entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
  s({
    keyword: "chatbot IA service client automatisé France",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
  s({
    keyword: "intégration chatbot IA site web PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
  s({
    keyword: "prestataire chatbot IA entreprise France",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
  s({
    keyword: "comment créer un chatbot IA pour son entreprise ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
  s({
    keyword: "combien coûte un chatbot IA pour PME ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
  s({
    keyword: "définition chatbot IA entreprise vs bot classique",
    module: "implementation",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
  s({
    keyword: "étapes déploiement chatbot IA entreprise en 6 phases",
    module: "implementation",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
  s({
    keyword: "chatbot IA vs chatbot classique Crisp Intercom comparaison",
    module: "implementation",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
  s({
    keyword: "gain productivité chatbot IA support client 60 % automatisé",
    module: "implementation",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/chatbot-entreprise",
  }),
];

// ── CLUSTER 2 : integration-llm-saas ─────────────────────────────────────────
const IMPL_LLM_SAAS: KeywordSeed[] = [
  s({
    keyword: "intégration LLM dans logiciel SaaS entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/llm-saas",
  }),
  s({
    keyword: "ajouter IA dans son logiciel métier PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/llm-saas",
  }),
  s({
    keyword: "API OpenAI Anthropic intégration SaaS entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/llm-saas",
  }),
  s({
    keyword: "développement IA sur-mesure logiciel entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/llm-saas",
  }),
  s({
    keyword: "comment intégrer ChatGPT dans son logiciel métier ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/llm-saas",
  }),
  s({
    keyword: "qu'est-ce qu'une intégration LLM en entreprise ?",
    module: "implementation",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/llm-saas",
  }),
  s({
    keyword: "OpenAI vs Anthropic vs Mistral intégration SaaS comparatif",
    module: "implementation",
    intent: "commercial_investigation",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/llm-saas",
  }),
];

// ── CLUSTER 3 : deploiement-rag-interne ───────────────────────────────────────
const IMPL_RAG: KeywordSeed[] = [
  s({
    keyword: "déploiement RAG base documentaire interne",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/implementations/rag-documentaire",
  }),
  s({
    keyword: "chatbot RAG documentation interne entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/implementations/rag-documentaire",
  }),
  s({
    keyword: "base de connaissances IA interne entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/rag-documentaire",
  }),
  s({
    keyword: "implémentation RAG données propriétaires PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/rag-documentaire",
  }),
  s({
    keyword: "comment créer un chatbot sur sa documentation interne ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/rag-documentaire",
  }),
  s({
    keyword: "définition RAG Retrieval Augmented Generation entreprise",
    module: "implementation",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/rag-documentaire",
  }),
  s({
    keyword: "étapes déploiement RAG interne entreprise en 5 points",
    module: "implementation",
    intent: "featured_snippet",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/rag-documentaire",
  }),
  s({
    keyword: "productivité RAG interne entreprise gain 50 % recherche",
    module: "implementation",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/rag-documentaire",
  }),
];

// ── CLUSTER 4 : integration-ia-crm ────────────────────────────────────────────
const IMPL_CRM: KeywordSeed[] = [
  s({
    keyword: "intégration IA CRM Salesforce HubSpot",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/ia-crm",
  }),
  s({
    keyword: "automatiser relances clients IA CRM entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/ia-crm",
  }),
  s({
    keyword: "IA scoring prospects CRM PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/ia-crm",
  }),
  s({
    keyword: "comment utiliser l'IA pour améliorer son CRM ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/ia-crm",
  }),
  s({
    keyword: "gain commercial intégration IA CRM entreprise",
    module: "implementation",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/ia-crm",
  }),
  s({
    keyword: "intégration IA CRM Salesforce vs HubSpot comparatif",
    module: "implementation",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/ia-crm",
  }),
];

// ── CLUSTER 5 : integration-ia-erp ────────────────────────────────────────────
const IMPL_ERP: KeywordSeed[] = [
  s({
    keyword: "intégration intelligence artificielle ERP SAP",
    module: "implementation",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/ia-erp",
  }),
  s({
    keyword: "IA dans ERP automatisation processus métier",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/ia-erp",
  }),
  s({
    keyword: "connecteur IA ERP PME open source",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/ia-erp",
  }),
  s({
    keyword: "comment connecter l'IA à son ERP d'entreprise ?",
    module: "implementation",
    intent: "voice_search",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/ia-erp",
  }),
  s({
    keyword: "définition IA dans ERP bénéfices opérationnels",
    module: "implementation",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/ia-erp",
  }),
  s({
    keyword: "intégration IA ERP SAP vs Oracle vs Sage comparatif",
    module: "implementation",
    intent: "commercial_investigation",
    cible: "grand-compte",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/ia-erp",
  }),
];

// ── CLUSTER 6 : automation-rpa-ia ─────────────────────────────────────────────
const IMPL_RPA: KeywordSeed[] = [
  s({
    keyword: "automatisation RPA intelligence artificielle entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/rpa-ia",
  }),
  s({
    keyword: "RPA IA automatisation processus métier PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/rpa-ia",
  }),
  s({
    keyword: "automatiser processus répétitifs IA entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/implementations/rpa-ia",
  }),
  s({
    keyword: "quels processus automatiser en priorité avec l'IA ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/rpa-ia",
  }),
  s({
    keyword: "définition RPA vs IA automatisation différence",
    module: "implementation",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/rpa-ia",
  }),
  s({
    keyword: "économies automatisation RPA IA entreprise 8 h par semaine",
    module: "implementation",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/rpa-ia",
  }),
  s({
    keyword: "RPA classique vs RPA IA intelligent comparaison",
    module: "implementation",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/rpa-ia",
  }),
];

// ── CLUSTER 7 : agents-ia-autonomes ───────────────────────────────────────────
const IMPL_AGENTS: KeywordSeed[] = [
  s({
    keyword: "agents IA autonomes entreprise déploiement",
    module: "implementation",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/agents-ia",
  }),
  s({
    keyword: "développement agent IA autonome multi-tâches",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/agents-ia",
  }),
  s({
    keyword: "implémenter agent IA pour automatiser sa veille",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/agents-ia",
  }),
  s({
    keyword: "comment déployer un agent IA en production ?",
    module: "implementation",
    intent: "voice_search",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/agents-ia",
  }),
  s({
    keyword: "définition agent IA autonome capabilities",
    module: "implementation",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/agents-ia",
  }),
  s({
    keyword: "agents IA Axion-IA vs UiPath vs Automation Anywhere",
    module: "implementation",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/agents-ia",
  }),
];

// ── CLUSTER 8 : voice-ia-entreprise ───────────────────────────────────────────
const IMPL_VOICE: KeywordSeed[] = [
  s({
    keyword: "assistant vocal IA entreprise déploiement",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/voice-ia",
  }),
  s({
    keyword: "implémentation voice IA centre d'appels PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/voice-ia",
  }),
  s({
    keyword: "comment automatiser ses appels entrants avec l'IA ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/voice-ia",
  }),
  s({
    keyword: "définition voice IA assistant vocal entreprise",
    module: "implementation",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/voice-ia",
  }),
  s({
    keyword: "gain centre appels IA vocal 40 % appels automatisés",
    module: "implementation",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/voice-ia",
  }),
];

// ── CLUSTER 9 : analyse-predictive-ia ────────────────────────────────────────
const IMPL_PREDICTIVE: KeywordSeed[] = [
  s({
    keyword: "analyse prédictive IA ventes entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/analyse-predictive",
  }),
  s({
    keyword: "modèle prédictif churn clients IA PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/analyse-predictive",
  }),
  s({
    keyword: "prédiction stocks IA logistique entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/analyse-predictive",
  }),
  s({
    keyword: "comment utiliser l'IA pour prédire ses ventes ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/analyse-predictive",
  }),
  s({
    keyword: "définition analyse prédictive machine learning PME",
    module: "implementation",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/analyse-predictive",
  }),
  s({
    keyword: "gain analyse prédictive IA stocks réduction 25 %",
    module: "implementation",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/analyse-predictive",
  }),
];

// ── CLUSTER 10 : recommandation-ia-ecommerce ──────────────────────────────────
const IMPL_RECO: KeywordSeed[] = [
  s({
    keyword: "moteur de recommandation IA e-commerce",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/recommandation-ecommerce",
  }),
  s({
    keyword: "personnalisation IA boutique en ligne PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/recommandation-ecommerce",
  }),
  s({
    keyword: "comment augmenter son panier moyen avec l'IA ?",
    module: "implementation",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/recommandation-ecommerce",
  }),
  s({
    keyword: "définition moteur recommandation IA e-commerce",
    module: "implementation",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/recommandation-ecommerce",
  }),
  s({
    keyword: "panier moyen augmenté IA recommandation 30 %",
    module: "implementation",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/recommandation-ecommerce",
  }),
];

// ── CLUSTER 11 : nlp-ia-documentaire ─────────────────────────────────────────
const IMPL_NLP: KeywordSeed[] = [
  s({
    keyword: "traitement langage naturel NLP entreprise France",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/nlp-documentaire",
  }),
  s({
    keyword: "analyse automatique documents contrats IA",
    module: "implementation",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implementations/nlp-documentaire",
  }),
  s({
    keyword: "extraction données PDF IA automatique entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/nlp-documentaire",
  }),
  s({
    keyword: "comment automatiser la lecture de ses contrats avec l'IA ?",
    module: "implementation",
    intent: "voice_search",
    cible: "grand-compte",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/nlp-documentaire",
  }),
  s({
    keyword: "définition NLP traitement langage naturel application entreprise",
    module: "implementation",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/implementations/nlp-documentaire",
  }),
  s({
    keyword: "gain analyse NLP contrats juridiques 80 % plus rapide",
    module: "implementation",
    intent: "benefice",
    cible: "grand-compte",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/nlp-documentaire",
  }),
];

// ── CLUSTER 12 : implementation-tpe-specifique ────────────────────────────────
const IMPL_TPE: KeywordSeed[] = [
  s({
    keyword: "implémenter IA sans équipe technique TPE PME",
    module: "implementation",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/implementations/sans-technique",
  }),
  s({
    keyword: "solutions IA clé en main petite entreprise",
    module: "implementation",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/implementations/sans-technique",
  }),
  s({
    keyword: "IA sans code no-code pour TPE France",
    module: "implementation",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/sans-technique",
  }),
  s({
    keyword: "peut-on implémenter l'IA sans développeur dans une petite entreprise ?",
    module: "implementation",
    intent: "voice_search",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/sans-technique",
  }),
  s({
    keyword: "liste outils IA no-code pour TPE 2026",
    module: "implementation",
    intent: "featured_snippet",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/sans-technique",
  }),
  s({
    keyword: "temps gagné IA no-code TPE artisan 5 heures semaine",
    module: "implementation",
    intent: "benefice",
    cible: "tpe",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/implementations/sans-technique",
  }),
];

export const KW_IMPLEMENTATIONS_CLUSTERS: KeywordSeed[] = [
  ...IMPL_CHATBOT,
  ...IMPL_LLM_SAAS,
  ...IMPL_RAG,
  ...IMPL_CRM,
  ...IMPL_ERP,
  ...IMPL_RPA,
  ...IMPL_AGENTS,
  ...IMPL_VOICE,
  ...IMPL_PREDICTIVE,
  ...IMPL_RECO,
  ...IMPL_NLP,
  ...IMPL_TPE,
];
