/**
 * Keywords Phase 2 Sprint Perfection 2026-05-22 — Verticale SITES_WEB_AUGMENTES
 * 12 clusters × ~22 keywords = ~255 seeds
 */

import type { KeywordSeed } from "./types";

type SC = Omit<KeywordSeed, "injection" | "kbType">;
function s(seed: SC): KeywordSeed {
  const full: Record<string, unknown> = { ...seed, kbType: "guide", injection: {} };
  return full as unknown as KeywordSeed;
}

// ── CLUSTER 1 : seo-ia-2026 ───────────────────────────────────────────────────
const WEB_SEO_IA: KeywordSeed[] = [
  s({
    keyword: "SEO intelligence artificielle 2026 entreprise",
    module: "codage-developpement",
    intent: "informationnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "optimisation SEO avec IA site web PME",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "agence SEO IA France accompagnement",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "stratégie SEO IA 2026 PME croissance organique",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "audit SEO IA site web entreprise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "comment utiliser l'IA pour améliorer son référencement ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "définition SEO IA changements algorithmes 2026",
    module: "codage-developpement",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "5 changements SEO majeurs liés à l'IA en 2026",
    module: "codage-developpement",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
  s({
    keyword: "gain trafic organique SEO IA 40 % en 6 mois",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-ia-2026",
  }),
];

// ── CLUSTER 2 : aeo-answer-engine-optimization ────────────────────────────────
const WEB_AEO: KeywordSeed[] = [
  s({
    keyword: "AEO Answer Engine Optimization entreprise France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/aeo",
  }),
  s({
    keyword: "optimiser son site pour Perplexity SGE ChatGPT",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/web-digital/aeo",
  }),
  s({
    keyword: "agence AEO France spécialisée PME",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/aeo",
  }),
  s({
    keyword: "stratégie AEO 2026 entreprise B2B",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/aeo",
  }),
  s({
    keyword: "comment apparaître dans les réponses de Perplexity ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/aeo",
  }),
  s({
    keyword: "définition Answer Engine Optimization AEO stratégie",
    module: "codage-developpement",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/aeo",
  }),
  s({
    keyword: "6 techniques AEO pour apparaître dans les IA de recherche",
    module: "codage-developpement",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/aeo",
  }),
  s({
    keyword: "SEO vs AEO différences stratégie 2026",
    module: "codage-developpement",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/aeo",
  }),
];

// ── CLUSTER 3 : geo-generative-engine ─────────────────────────────────────────
const WEB_GEO: KeywordSeed[] = [
  s({
    keyword: "GEO Generative Engine Optimization France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/geo",
  }),
  s({
    keyword: "optimisation pour moteurs génératifs IA PME",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/web-digital/geo",
  }),
  s({
    keyword: "stratégie GEO 2026 ChatGPT Perplexity SGE",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/geo",
  }),
  s({
    keyword: "comment être cité par les IA génératives ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/geo",
  }),
  s({
    keyword: "définition GEO optimisation moteurs génératifs 2026",
    module: "codage-developpement",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/geo",
  }),
  s({
    keyword: "SEO vs AEO vs GEO comparatif stratégies 2026",
    module: "codage-developpement",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/geo",
  }),
  s({
    keyword: "7 facteurs GEO pour être référencé par les IA",
    module: "codage-developpement",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/geo",
  }),
];

// ── CLUSTER 4 : content-generation-ia ────────────────────────────────────────
const WEB_CONTENT_GEN: KeywordSeed[] = [
  s({
    keyword: "génération contenu IA site web entreprise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/generation-contenu-ia",
  }),
  s({
    keyword: "création contenu SEO IA automatisé PME",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/web-digital/generation-contenu-ia",
  }),
  s({
    keyword: "agence génération contenu IA France qualité",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/generation-contenu-ia",
  }),
  s({
    keyword: "comment produire plus de contenu SEO avec l'IA ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/generation-contenu-ia",
  }),
  s({
    keyword: "définition génération contenu IA qualité SEO",
    module: "codage-developpement",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/web-digital/generation-contenu-ia",
  }),
  s({
    keyword: "contenus IA vs contenus humains qualité SEO 2026",
    module: "codage-developpement",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/generation-contenu-ia",
  }),
  s({
    keyword: "gain contenu IA 10× plus rapide même qualité SEO",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/generation-contenu-ia",
  }),
];

// ── CLUSTER 5 : pseo-programmatique ───────────────────────────────────────────
const WEB_PSEO: KeywordSeed[] = [
  s({
    keyword: "SEO programmatique pSEO IA France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/seo-programmatique",
  }),
  s({
    keyword: "génération pages automatique IA SEO scale",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/seo-programmatique",
  }),
  s({
    keyword: "créer 1000 pages SEO avec IA automatiquement",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-programmatique",
  }),
  s({
    keyword: "comment faire du SEO programmatique avec l'IA ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-programmatique",
  }),
  s({
    keyword: "définition SEO programmatique différences SEO classique",
    module: "codage-developpement",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-programmatique",
  }),
  s({
    keyword: "pages pSEO IA vs contenus manuels performance comparatif",
    module: "codage-developpement",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/web-digital/seo-programmatique",
  }),
];

// ── CLUSTER 6 : personnalisation-site-ia ─────────────────────────────────────
const WEB_PERSONNALISATION: KeywordSeed[] = [
  s({
    keyword: "personnalisation site web IA visiteurs entreprise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/personnalisation-ia",
  }),
  s({
    keyword: "expérience personnalisée IA site B2B",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/personnalisation-ia",
  }),
  s({
    keyword: "comment personnaliser son site web avec l'IA ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/web-digital/personnalisation-ia",
  }),
  s({
    keyword: "gain taux conversion personnalisation IA site 25 %",
    module: "codage-developpement",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/personnalisation-ia",
  }),
];

// ── CLUSTER 7 : chatbot-site-web ──────────────────────────────────────────────
const WEB_CHATBOT: KeywordSeed[] = [
  s({
    keyword: "chatbot IA site web installation entreprise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/chatbot-site",
  }),
  s({
    keyword: "assistant IA site internet PME génération leads",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/web-digital/chatbot-site",
  }),
  s({
    keyword: "chatbot IA leads qualification site web",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/chatbot-site",
  }),
  s({
    keyword: "comment mettre un chatbot IA sur son site web ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/chatbot-site",
  }),
  s({
    keyword: "leads qualifiés chatbot IA site web 3× plus",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/chatbot-site",
  }),
  s({
    keyword: "chatbot IA site Crisp vs Intercom vs Axion-IA comparaison",
    module: "codage-developpement",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/chatbot-site",
  }),
];

// ── CLUSTER 8 : optimisation-ai-overviews ─────────────────────────────────────
const WEB_AI_OVERVIEWS: KeywordSeed[] = [
  s({
    keyword: "optimisation AI Overviews Google SGE France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/ai-overviews",
  }),
  s({
    keyword: "apparaître dans AI Overview Google entreprise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/web-digital/ai-overviews",
  }),
  s({
    keyword: "stratégie contenu AI Overviews Google 2026",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/ai-overviews",
  }),
  s({
    keyword: "comment être sélectionné dans les AI Overviews Google ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/ai-overviews",
  }),
  s({
    keyword: "définition AI Overviews Google Search Generative Experience",
    module: "codage-developpement",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/ai-overviews",
  }),
  s({
    keyword: "8 critères pour apparaître dans AI Overviews Google",
    module: "codage-developpement",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/ai-overviews",
  }),
];

// ── CLUSTER 9 : featured-snippets ─────────────────────────────────────────────
const WEB_FEATURED: KeywordSeed[] = [
  s({
    keyword: "stratégie featured snippet position zéro Google",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/featured-snippets",
  }),
  s({
    keyword: "optimiser contenu position 0 Google PME",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/featured-snippets",
  }),
  s({
    keyword: "comment obtenir une position 0 sur Google ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/featured-snippets",
  }),
  s({
    keyword: "définition featured snippet position zéro Google",
    module: "codage-developpement",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/web-digital/featured-snippets",
  }),
  s({
    keyword: "5 types de featured snippets à cibler pour PME",
    module: "codage-developpement",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/featured-snippets",
  }),
];

// ── CLUSTER 10 : schema-markup-ia ─────────────────────────────────────────────
const WEB_SCHEMA: KeywordSeed[] = [
  s({
    keyword: "balisage schéma schema.org IA AEO entreprise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/schema-markup",
  }),
  s({
    keyword: "implémenter schema.org JSON-LD site web PME",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/schema-markup",
  }),
  s({
    keyword: "structured data IA entreprise référencement",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/schema-markup",
  }),
  s({
    keyword: "comment ajouter des données structurées à son site ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/web-digital/schema-markup",
  }),
  s({
    keyword: "définition schema.org données structurées SEO",
    module: "codage-developpement",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/web-digital/schema-markup",
  }),
];

// ── CLUSTER 11 : web-vitals-ia ────────────────────────────────────────────────
const WEB_VITALS: KeywordSeed[] = [
  s({
    keyword: "web vitals optimisation LCP INP CLS entreprise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/web-vitals",
  }),
  s({
    keyword: "améliorer score LCP site web IA France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/web-vitals",
  }),
  s({
    keyword: "comment améliorer ses web vitals avec l'IA ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/web-digital/web-vitals",
  }),
  s({
    keyword: "définition Core Web Vitals LCP INP CLS Google 2026",
    module: "codage-developpement",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/web-digital/web-vitals",
  }),
  s({
    keyword: "gain taux conversion optimisation web vitals 20 %",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/web-vitals",
  }),
];

// ── CLUSTER 12 : site-web-ia-creation ─────────────────────────────────────────
const WEB_CREATION: KeywordSeed[] = [
  s({
    keyword: "création site web augmenté IA France agence",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "refonte site web IA SEO AEO optimisé PME",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "développement site Next.js IA SEO France",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "comment créer un site web optimisé pour l'IA générative ?",
    module: "codage-developpement",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "site web IA vs site web classique différences SEO 2026",
    module: "codage-developpement",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
  s({
    keyword: "trafic organique site web IA 3× plus en 6 mois",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/web-digital/creation-site-ia",
  }),
];

export const KW_WEB_AUGMENTE_CLUSTERS: KeywordSeed[] = [
  ...WEB_SEO_IA,
  ...WEB_AEO,
  ...WEB_GEO,
  ...WEB_CONTENT_GEN,
  ...WEB_PSEO,
  ...WEB_PERSONNALISATION,
  ...WEB_CHATBOT,
  ...WEB_AI_OVERVIEWS,
  ...WEB_FEATURED,
  ...WEB_SCHEMA,
  ...WEB_VITALS,
  ...WEB_CREATION,
];
