// src/content/keywords/g3g-implementation-existant-neuf.ts
// Module IMPLEMENTATION — split EXISTANT (brownfield) vs NEUF (greenfield) +
// différenciateurs « territoire bleu ». 2026-06-02 (Will).
//
// Garde-fou anti-cannibalisation : aucun keyword `existant` et `neuf` ne pointe
// vers la même urlCible. URLs = routes réelles (/fr/implementation/...).
// Aucun terme de marque (Zapier/Make/n8n) — sinon strippé par isClean() de
// master.ts ; les requêtes « alternative no-code » sont reformulées sans marque.

import type { KeywordSeed } from "./types";

const PILIER = "/fr/implementation";

export const KW_IMPL_EXISTANT_NEUF: KeywordSeed[] = [
  // ─── EXISTANT (brownfield) — greffer l'IA sur l'existant ───────────────────
  {
    keyword: "intégrer l'IA à mes outils existants",
    intent: "transactionnel",
    module: "implementation",
    cible: "pme",
    implementationType: "existant",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/implementation/integrations",
    canonicalParent: PILIER,
    note: "Cluster EXISTANT — greffe sur stack en place (CRM, ERP, site, e-mail).",
  },
  {
    keyword: "connecter l'IA à mon CRM",
    intent: "transactionnel",
    module: "implementation",
    cible: "pme",
    implementationType: "existant",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/implementation/crm-erp",
    canonicalParent: PILIER,
  },
  {
    keyword: "connecter l'IA à mon ERP",
    intent: "transactionnel",
    module: "implementation",
    cible: "eti",
    implementationType: "existant",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/implementation/crm-erp",
    canonicalParent: PILIER,
  },
  {
    keyword: "automatiser mes process existants avec l'IA",
    intent: "transactionnel",
    module: "implementation",
    cible: "pme",
    implementationType: "existant",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/implementation/processus",
    canonicalParent: PILIER,
  },
  {
    keyword: "ajouter l'IA à mon logiciel métier",
    intent: "transactionnel",
    module: "implementation",
    cible: "tpe",
    implementationType: "existant",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/implementation/integrations",
    canonicalParent: PILIER,
  },
  {
    keyword: "automatiser les tâches répétitives avec l'IA",
    intent: "transactionnel",
    module: "implementation",
    cible: "tpe",
    implementationType: "existant",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/implementation/processus",
    canonicalParent: PILIER,
  },
  {
    keyword: "traitement automatique des factures par IA",
    intent: "transactionnel",
    module: "implementation",
    cible: "pme",
    implementationType: "existant",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/implementation/documents",
    canonicalParent: PILIER,
  },
  {
    keyword: "comment intégrer l'IA dans mon entreprise ?",
    intent: "aeo",
    module: "implementation",
    cible: "toutes-cibles",
    implementationType: "existant",
    niveau: 2,
    priorite: 1,
    urlCible: PILIER,
    note: "AEO top-funnel — fort volume, question naturelle.",
  },
  {
    keyword: "mes données restent-elles chez moi avec l'IA ?",
    intent: "aeo",
    module: "implementation",
    cible: "toutes-cibles",
    implementationType: "existant",
    niveau: 3,
    priorite: 2,
    urlCible: PILIER,
    note: "AEO — lève l'objection RGPD / hébergement.",
  },

  // ─── NEUF (greenfield) — construire de A à Z ───────────────────────────────
  {
    keyword: "créer un agent IA sur mesure",
    intent: "transactionnel",
    module: "implementation",
    cible: "pme",
    implementationType: "neuf",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/implementation/agents",
    canonicalParent: PILIER,
    note: "Cluster NEUF — ne JAMAIS partager d'URL avec un keyword EXISTANT.",
  },
  {
    keyword: "développer une solution IA sur mesure",
    intent: "transactionnel",
    module: "implementation",
    cible: "eti",
    implementationType: "neuf",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/implementation/ia-custom",
    canonicalParent: PILIER,
  },
  {
    keyword: "développer une plateforme IA dédiée",
    intent: "transactionnel",
    module: "implementation",
    cible: "eti",
    implementationType: "neuf",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/implementation/ia-custom",
    canonicalParent: PILIER,
  },
  {
    keyword: "concevoir un agent IA autonome",
    intent: "transactionnel",
    module: "implementation",
    cible: "pme",
    implementationType: "neuf",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/implementation/agents",
    canonicalParent: PILIER,
  },
  {
    keyword: "système IA métier complet sur mesure",
    intent: "benefice",
    module: "implementation",
    cible: "grand-compte",
    implementationType: "neuf",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/implementation/ia-custom",
    canonicalParent: PILIER,
  },
  {
    keyword: "IA custom pour mon entreprise",
    intent: "transactionnel",
    module: "implementation",
    cible: "eti",
    implementationType: "neuf",
    niveau: 2,
    priorite: 2,
    urlCible: "/fr/implementation/ia-custom",
    canonicalParent: PILIER,
  },
  {
    keyword: "comment créer un agent IA sur mesure ?",
    intent: "aeo",
    module: "implementation",
    cible: "toutes-cibles",
    implementationType: "neuf",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/implementation/agents",
    note: "AEO — question greenfield.",
  },
  {
    keyword: "combien de temps pour développer une solution IA ?",
    intent: "aeo",
    module: "implementation",
    cible: "toutes-cibles",
    implementationType: "neuf",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/implementation/ia-custom",
  },

  // ─── TRANSVERSE — différenciateurs « territoire bleu » + pilier routage ─────
  {
    keyword: "implémentation IA sans abonnement",
    intent: "benefice",
    module: "implementation",
    cible: "toutes-cibles",
    implementationType: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: PILIER,
    note: "Différenciateur majeur Axion-IA — faible volume, conversion maxi.",
  },
  {
    keyword: "implémentation IA en forfait fixe",
    intent: "benefice",
    module: "implementation",
    cible: "toutes-cibles",
    implementationType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: PILIER,
    note: "Différenciateur — prix non affiché, positionnement sans dépassement.",
  },
  {
    keyword: "être propriétaire de son IA et de son code",
    intent: "benefice",
    module: "implementation",
    cible: "toutes-cibles",
    implementationType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: PILIER,
    note: "Différenciateur — code livré, à vous.",
  },
  {
    keyword: "alternative au no-code pour l'IA en entreprise",
    intent: "commercial_investigation",
    module: "implementation",
    cible: "pme",
    implementationType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: PILIER,
    note: "Reformulé SANS marque (Zapier/Make strippés par isClean). Cible switchers no-code.",
  },
  {
    keyword: "implémentation IA sur existant ou de bout en bout",
    intent: "commercial_investigation",
    module: "implementation",
    cible: "toutes-cibles",
    implementationType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: PILIER,
    note: "Pilier de routage EXISTANT vs NEUF — page de décision (cf. CSV ligne 5011).",
  },
  {
    keyword: "IA sur mesure ou solution existante, comment choisir ?",
    intent: "aeo",
    module: "implementation",
    cible: "toutes-cibles",
    implementationType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: PILIER,
    note: "AEO — oppose EXISTANT vs NEUF, route vers le bon cluster.",
  },
  {
    keyword: "combien de temps pour implémenter l'IA en entreprise ?",
    intent: "aeo",
    module: "implementation",
    cible: "toutes-cibles",
    implementationType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: PILIER,
  },
];
