// src/content/keywords/g3h-sites-saas-clusters.ts
// Module CODAGE_DEVELOPPEMENT — intégration du CSV `axion_keywords_sites_saas.csv`
// (taxonomie pilier → catégorie → landing → FAQ-AEO). 2026-06-02 (Will).
//
// Axe nouveau `siteProjectType` (augmentation / native / transverse) — garde-fou
// anti-cannibalisation, calqué sur g1m (audit/maturité) et g3g (impl/existant-neuf) :
//   - AUGMENTATION : greffer l'IA sur un site/app existant, sans refonte.
//   - NATIVE       : construire une plateforme / un SaaS IA-native de A à Z.
//   - TRANSVERSE   : briques / stacks / modèles / RGPD / géo / AEO.
//
// Garde-fous (cf. [[refonte-pages-intention]]) :
//   - AUGMENTATION et NATIVE ne partagent JAMAIS une urlCible (anti-cannibalisation).
//   - urlCible = routes planifiées sous le hub réel `/fr/sites-web-augmentes/*`
//     (distinct du prefix `/fr/web-digital/*` de g3f, qui couvre SEO/AEO/GEO web-
//     marketing ; annotation content-gen, jamais émise au sitemap).
//   - AUCUN claim de financement — filtré aussi par isClean() de master.ts.
//   - keyword AEO reformulé en question (termine par "?").

import type { KeywordSeed } from "./types";

const PILIER = "/fr/sites-web-augmentes";

type SC = Omit<KeywordSeed, "module" | "kbType" | "canonicalParent"> &
  Partial<Pick<KeywordSeed, "canonicalParent">>;
/** Injecte module + kbType + canonicalParent par défaut pour alléger chaque seed. */
function w(seed: SC): KeywordSeed {
  return {
    module: "codage-developpement",
    kbType: "guide",
    canonicalParent: PILIER,
    ...seed,
  };
}

// ─── AUGMENTATION — greffer l'IA sur l'existant (jamais la même URL que NATIVE) ─
const WEB_AUGMENTATION: KeywordSeed[] = [
  w({
    keyword: "augmenter un site existant avec l'IA",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "augmentation",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/augmentation",
    note: "Catégorie AUGMENTATION — greffe sur existant, séparée strictement de NATIVE.",
  }),
  w({
    keyword: "ajouter de l'IA à mon site sans refonte",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/sans-refonte",
    note: "Différenciant Axion-IA — zéro refonte.",
  }),
  w({
    keyword: "greffer un chatbot IA sur mon site",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/greffer-chatbot",
  }),
  w({
    keyword: "intégrer l'IA dans une application existante",
    intent: "transactionnel",
    cible: "eti",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/application-existante",
  }),
  w({
    keyword: "moderniser un site web avec l'IA",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/moderniser",
  }),
  w({
    keyword: "ajouter l'IA à un site via un widget JavaScript",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/widget-js",
  }),
  w({
    keyword: "intégrer l'IA sur un site via API",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/via-api",
  }),
  w({
    keyword: "peut-on ajouter de l'IA sans refondre son site ?",
    intent: "aeo",
    cible: "toutes-cibles",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/sans-refonte",
    note: "Lève l'objection clé.",
  }),
];

// ─── NATIVE — construire de A à Z (jamais la même URL que AUGMENTATION) ─────────
const WEB_NATIVE: KeywordSeed[] = [
  w({
    keyword: "développer une plateforme IA-native sur mesure",
    intent: "transactionnel",
    cible: "eti",
    siteProjectType: "native",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/plateforme-native",
    note: "Catégorie NATIVE — build from scratch, ne JAMAIS partager d'URL avec AUGMENTATION.",
  }),
  w({
    keyword: "créer un SaaS augmenté par l'IA sur mesure",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "native",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/creer-saas-ia",
  }),
  w({
    keyword: "développer une application web IA sur mesure",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "native",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/application-sur-mesure",
  }),
  w({
    keyword: "construire une plateforme B2B IA-native",
    intent: "transactionnel",
    cible: "grand-compte",
    siteProjectType: "native",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/plateforme-b2b",
  }),
  w({
    keyword: "qu'est-ce qu'une plateforme IA-native ?",
    intent: "ai_overview",
    cible: "toutes-cibles",
    siteProjectType: "native",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/plateforme-native",
  }),
];

// ─── TRANSVERSE — briques IA (chatbot / search / reco / perso / vision) ─────────
const WEB_BRIQUES: KeywordSeed[] = [
  w({
    keyword: "ajouter des briques IA à un site web",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/briques",
    note: "Hub vers les 4 briques (chatbot / search / reco / perso).",
  }),
  w({
    keyword: "chatbot RAG pour entreprise sur son site",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/chatbot-rag",
  }),
  w({
    keyword: "chatbot IA avec réponses sourcées sans hallucination",
    intent: "benefice",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/chatbot-rag",
    note: "Différenciant — réponses sourcées.",
  }),
  w({
    keyword: "chatbot IA branché sur ma documentation",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/chatbot-documentation",
  }),
  w({
    keyword: "chatbot IA pour répondre aux FAQ automatiquement",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/chatbot-faq",
  }),
  w({
    keyword: "recherche sémantique pour un site e-commerce",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/recherche-semantique",
  }),
  w({
    keyword: "recherche sémantique dans une documentation",
    intent: "transactionnel",
    cible: "eti",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/recherche-semantique",
  }),
  w({
    keyword: "recommandation de produits par IA sur un site",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/recommandation",
  }),
  w({
    keyword: "personnalisation dynamique d'un site par l'IA",
    intent: "transactionnel",
    cible: "eti",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/personnalisation",
  }),
  w({
    keyword: "personnalisation d'un site sans cookie tiers",
    intent: "transactionnel",
    cible: "eti",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/personnalisation",
    note: "Différenciant RGPD.",
  }),
  w({
    keyword: "génération de fiches produit par IA",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/generation-fiches-produit",
  }),
  w({
    keyword: "lecture de documents par vision IA sur un site",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/sites-web-augmentes/ocr-vision",
  }),
  w({
    keyword: "agent IA qui exécute un workflow sur le web",
    intent: "transactionnel",
    cible: "eti",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/agent-workflow",
  }),
  w({
    keyword: "scoring des leads d'un site web par IA",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/scoring-leads",
  }),
  w({
    keyword: "portail client en self-care propulsé par IA",
    intent: "transactionnel",
    cible: "eti",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/portail-client",
  }),
  w({
    keyword: "réduire les tickets de support grâce à l'IA",
    intent: "benefice",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/portail-client",
    note: "Angle bénéfice (moins de tickets support).",
  }),
];

// ─── TRANSVERSE — par stack technique (CMS = augmentation ; frameworks) ─────────
const WEB_STACK: KeywordSeed[] = [
  w({
    keyword: "intégration de l'IA par technologie de site",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/par-stack",
    note: "Hub par CMS / framework (switchers qualifiés).",
  }),
  w({
    keyword: "chatbot IA pour un site WordPress",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/wordpress",
  }),
  w({
    keyword: "intégration IA pour un site Webflow",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/webflow",
  }),
  w({
    keyword: "chatbot IA pour une boutique Shopify",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "augmentation",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/shopify",
  }),
  w({
    keyword: "intégration de l'IA dans une application Next.js",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/nextjs",
  }),
  w({
    keyword: "intégration de l'IA dans une application Laravel",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/laravel",
    note: "Stack maison Axion-IA.",
  }),
  w({
    keyword: "intégration de l'IA dans une application Django",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/sites-web-augmentes/django",
  }),
  w({
    keyword: "intégration de l'IA dans une application Symfony",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/sites-web-augmentes/symfony",
  }),
  w({
    keyword: "intégration de l'IA dans une application Node.js",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/sites-web-augmentes/nodejs",
  }),
];

// ─── TRANSVERSE — par modèle (LLM) ─────────────────────────────────────────────
const WEB_MODELES: KeywordSeed[] = [
  w({
    keyword: "intégrer un modèle d'IA dans mon outil",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/par-modele",
    note: "Hub par modèle (Claude / OpenAI / Mistral / Gemini).",
  }),
  w({
    keyword: "intégration de Claude sur un site web",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/integration-claude",
  }),
  w({
    keyword: "intégration de l'API OpenAI sur un site",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/integration-openai",
  }),
  w({
    keyword: "intégration de Mistral AI sur un site web",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/integration-mistral",
    note: "Angle souverain FR.",
  }),
  w({
    keyword: "intégration de Google Gemini sur un site",
    intent: "transactionnel",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/sites-web-augmentes/integration-gemini",
  }),
];

// ─── TRANSVERSE — RGPD / souveraineté + géo ────────────────────────────────────
const WEB_RGPD_GEO: KeywordSeed[] = [
  w({
    keyword: "chatbot IA conforme au RGPD pour entreprise",
    intent: "transactionnel",
    cible: "eti",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/rgpd-souverain",
    note: "Différenciant.",
  }),
  w({
    keyword: "IA web hébergée en Union européenne",
    intent: "transactionnel",
    cible: "eti",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/rgpd-souverain",
    note: "Différenciant — hébergement UE.",
  }),
  w({
    keyword: "IA souveraine française pour un site web",
    intent: "transactionnel",
    cible: "eti",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/rgpd-souverain",
  }),
  w({
    keyword: "intégration IA sur un site web à Paris",
    intent: "local",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/par-ville",
  }),
  w({
    keyword: "création de plateforme IA à Lyon",
    intent: "local",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/sites-web-augmentes/par-ville",
  }),
  w({
    keyword: "développement de SaaS IA à Bordeaux",
    intent: "local",
    cible: "startup-scaleup",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 3,
    urlCible: "/fr/sites-web-augmentes/par-ville",
  }),
];

// ─── TRANSVERSE — piliers de routage + AEO d'arbitrage ─────────────────────────
const WEB_PILIERS_AEO: KeywordSeed[] = [
  w({
    keyword: "intégration de l'IA dans un site web d'entreprise",
    intent: "transactionnel",
    cible: "pme",
    siteProjectType: "transverse",
    niveau: 2,
    priorite: 2,
    urlCible: PILIER,
    note: "Pilier ombrelle Sites web & SaaS IA.",
  }),
  w({
    keyword: "combien coûte l'intégration d'IA sur un site web ?",
    intent: "aeo",
    cible: "toutes-cibles",
    siteProjectType: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: PILIER,
  }),
  w({
    keyword: "qu'est-ce qu'un chatbot RAG ?",
    intent: "ai_overview",
    cible: "toutes-cibles",
    siteProjectType: "transverse",
    niveau: 2,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/chatbot-rag",
    note: "Définition forte demande.",
  }),
  w({
    keyword: "faut-il augmenter l'existant ou créer une plateforme native ?",
    intent: "aeo",
    cible: "toutes-cibles",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: PILIER,
    note: "Oppose AUGMENTATION vs NATIVE — page interne d'arbitrage clé.",
  }),
  w({
    keyword: "comment éviter les hallucinations d'un chatbot ?",
    intent: "aeo",
    cible: "toutes-cibles",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/chatbot-rag",
  }),
  w({
    keyword: "avec quelles technologies intégrez-vous l'IA ?",
    intent: "aeo",
    cible: "toutes-cibles",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/par-stack",
  }),
  w({
    keyword: "mes données restent-elles confidentielles avec l'IA ?",
    intent: "aeo",
    cible: "toutes-cibles",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: "/fr/sites-web-augmentes/rgpd-souverain",
  }),
  w({
    keyword: "qui est propriétaire du code et des données ?",
    intent: "aeo",
    cible: "toutes-cibles",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: PILIER,
    note: "Différenciant propriété (code livré).",
  }),
  w({
    keyword: "chatbot RAG ou chatbot classique, quelle différence ?",
    intent: "aeo",
    cible: "toutes-cibles",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 2,
    urlCible: "/fr/sites-web-augmentes/chatbot-rag",
  }),
  w({
    keyword: "intégration IA sur site ou implémentation IA, que choisir ?",
    intent: "aeo",
    cible: "toutes-cibles",
    siteProjectType: "transverse",
    niveau: 3,
    priorite: 1,
    urlCible: PILIER,
    note: "Arbitrage vs pilier Implementation (anti-cannibalisation inter-modules).",
  }),
];

export const KW_SITES_SAAS_CLUSTERS: KeywordSeed[] = [
  ...WEB_AUGMENTATION,
  ...WEB_NATIVE,
  ...WEB_BRIQUES,
  ...WEB_STACK,
  ...WEB_MODELES,
  ...WEB_RGPD_GEO,
  ...WEB_PILIERS_AEO,
];
