/**
 * Keyword Seeds — Mode G Phase 6 : Sectoriels (8 secteurs) + Coaching 1-to-1
 *
 * Généré 2026-05-20 · PROMPT-KEYWORD-STRATEGY-MASTER-V1 v1.2
 *
 * Exports :
 *   - KW_SECTORIELS_G6  (~75 seeds, intent="sectoriel")
 *   - KW_COACHING_G6    (~10 seeds, module="coaching-1-to-1")
 *
 * Slugs secteur : valeurs libres alignées sur `src/content/knowledge/sector-tags.ts`
 * Règle anti-cannibalisation R5 : h1 ≠ keyword brut.
 * Règle niveau/priorité : niveau 1 + priorite 1 = interdit (HEAD attaque).
 */

import type { KeywordSeed } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// SECTEUR 1 — JURIDIQUE (10 seeds)
// URL cible : /fr/secteurs/juridique | /fr/interventions-formations/juridique
// ─────────────────────────────────────────────────────────────────────────────

const KW_JURIDIQUE: KeywordSeed[] = [
  {
    keyword: "IA pour cabinet d'avocats France",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "interventions-formations",
    cible: "pme",
    secteur: "juridique",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Comment les cabinets d'avocats gagnent 8 h/semaine grâce à l'IA",
      metaTitle: "IA pour cabinet d'avocats — Axion-IA France",
      metaDescription:
        "Axion-IA déploie l'IA dans les cabinets d'avocats : rédaction, recherche juridique, conformité. Résultats mesurables dès 4 semaines.",
      h2Variants: [
        "Quels cas d'usage IA pour un cabinet d'avocats ?",
        "Formation IA pour juristes : ce que change Claude en pratique",
        "ROI de l'IA dans un cabinet juridique : chiffres réels",
      ],
    },
    variables: {
      process: "recherche et rédaction juridique",
      resultat: "-8 h/semaine/associé",
      chiffre: "8",
      unite: "heures/semaine",
      delai: "dès le 1er mois",
    },
    urlCible: "/fr/secteurs/juridique",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
    note: "schema.org: LegalService + FAQPage ; keyword secondaire : logiciel IA avocat",
  },
  {
    keyword: "automatiser rédaction contrats IA avocat",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "juridique",
    priorite: 1,
    niveau: 3,
    injection: {
      h1: "Rédiger vos contrats 5× plus vite avec l'IA — guide pratique avocat",
      metaTitle: "Automatiser rédaction contrats IA avocat — Axion-IA",
      metaDescription:
        "Pipeline IA pour rédiger, réviser et harmoniser vos contrats juridiques. Déploiement clé en main par Axion-IA, cabinet IA B2B France.",
      h2Variants: [
        "Étapes pour automatiser la rédaction de contrats avec l'IA",
        "Quels types de contrats passer en autopilote ?",
        "Risques et garde-fous : l'avocat garde le dernier mot",
      ],
    },
    variables: {
      process: "rédaction contrats",
      resultat: "5× plus rapide",
      chiffre: "5",
      unite: "× gain de vitesse",
      delai: "en 4 semaines",
    },
    urlCible: "/fr/secteurs/juridique",
    canonicalParent: "/fr/secteurs/juridique",
    source: "manuel",
    note: "automation_recipe ; mots secondaires : outil rédaction contrat IA, LLM juridique",
  },
  {
    keyword: "formation IA juriste",
    intent: "sectoriel",
    kbType: "intervention_module",
    module: "interventions-formations",
    cible: "pme",
    secteur: "juridique",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Formation IA pour juristes : maîtriser Claude et les LLM en cabinet",
      metaTitle: "Formation IA juriste — Axion-IA cabinet IA B2B",
      metaDescription:
        "Formation IA sur mesure pour juristes et avocats : prompting, recherche documentaire, conformité RGPD. Certifiée et déployable en présentiel.",
      h2Variants: [
        "Programme formation IA juriste — 1 jour intensif",
        "Ce que les juristes apprennent vraiment sur l'IA",
        "Attestation de formation IA et reconnaissance barreau",
      ],
    },
    variables: {
      process: "montée en compétence IA",
      resultat: "autonomie opérationnelle en 1 jour",
      chiffre: "1",
      unite: "jour",
      delai: "dès la formation",
    },
    urlCible: "/fr/interventions-formations/juridique",
    canonicalParent: "/fr/interventions-formations",
    source: "manuel",
    note: "schema.org: EducationEvent ; mots secondaires : formation IA équipe juridique",
  },
  {
    keyword: "formation IA équipe juridique",
    intent: "sectoriel",
    kbType: "intervention_module",
    module: "interventions-formations",
    cible: "eti",
    secteur: "juridique",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Déployer l'IA dans toute votre équipe juridique — formation collective Axion-IA",
      metaTitle: "Formation IA équipe juridique PME & ETI — Axion-IA",
      metaDescription:
        "Formez vos juristes, paralégaux et secrétaires juridiques à l'IA. Session sur site, cas concrets cabinet, suivi 30 jours inclus.",
      h2Variants: [
        "Pourquoi former l'équipe entière plutôt que 1 référent ?",
        "Modules adaptés : juriste, paralégal, secrétariat",
        "Suivi post-formation et ancrage des usages IA",
      ],
    },
    variables: {
      process: "formation collective",
      resultat: "adoption IA > 80 % équipe",
      chiffre: "80",
      unite: "% d'adoption",
      delai: "en 30 jours",
    },
    urlCible: "/fr/interventions-formations/juridique",
    canonicalParent: "/fr/interventions-formations",
    source: "manuel",
  },
  {
    keyword: "audit IA cabinet juridique",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "audit",
    cible: "pme",
    secteur: "juridique",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Audit IA pour cabinet juridique : identifier vos 3 gains rapides en 48 h",
      metaTitle: "Audit IA cabinet juridique — Axion-IA France",
      metaDescription:
        "Audit IA complet pour cabinets d'avocats et études notariales : cartographie des processus automatisables, ROI estimé, feuille de route 90 jours.",
      h2Variants: [
        "Déroulé de l'audit IA cabinet juridique en 48 h",
        "Processus les plus automatisables dans un cabinet",
        "Rapport d'audit : ce que vous recevez exactement",
      ],
    },
    variables: {
      process: "audit processus juridiques",
      resultat: "3 quick wins identifiés",
      chiffre: "3",
      unite: "quick wins",
      delai: "en 48 h",
    },
    urlCible: "/fr/audit/juridique",
    canonicalParent: "/fr/audit",
    source: "manuel",
  },
  {
    keyword: "IA pour notaire France",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "interventions-formations",
    cible: "pme",
    secteur: "juridique",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "L'IA dans l'étude notariale : cas d'usage concrets et gains mesurés",
      metaTitle: "IA pour notaire France — cabinet IA Axion-IA",
      metaDescription:
        "Axion-IA accompagne les notaires dans l'adoption de l'IA : actes, recherche cadastrale, accueil client automatisé. Conformité RGPD garantie.",
      h2Variants: [
        "3 usages IA immédiatement déployables en étude notariale",
        "Sécurité et confidentialité : l'IA dans le secret professionnel notarial",
        "Formation IA notaire : à quoi s'attendre ?",
      ],
    },
    variables: {
      process: "rédaction et recherche actes",
      resultat: "-40 % temps administratif",
      chiffre: "40",
      unite: "%",
      delai: "en 6 semaines",
    },
    urlCible: "/fr/secteurs/juridique",
    canonicalParent: "/fr/secteurs/juridique",
    source: "manuel",
  },
  {
    keyword: "agence IA juridique",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "transversal",
    cible: "pme",
    secteur: "juridique",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Axion-IA, l'agence IA spécialisée secteur juridique",
      metaTitle: "Agence IA juridique France — Axion-IA",
      metaDescription:
        "Axion-IA est le cabinet IA B2B de référence pour les professionnels du droit : audit, formation, implémentation et codage sur mesure.",
      h2Variants: [
        "Pourquoi choisir une agence IA spécialisée plutôt qu'un généraliste ?",
        "Nos références secteur juridique",
        "Services IA pour cabinets d'avocats, notaires et juristes d'entreprise",
      ],
    },
    urlCible: "/fr/secteurs/juridique",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
    note: "positionnement dual cabinet/agence IA",
  },
  {
    keyword: "intelligence artificielle droit des affaires",
    intent: "sectoriel",
    kbType: "industry_use_case",
    module: "interventions-formations",
    cible: "eti",
    secteur: "juridique",
    priorite: 2,
    niveau: 2,
    injection: {
      h1: "IA et droit des affaires : automatiser la veille, les contrats et la conformité",
      metaTitle: "Intelligence artificielle droit des affaires — Axion-IA",
      metaDescription:
        "Comment les équipes juridiques ETI utilisent l'IA pour la veille réglementaire, la M&A due diligence et la gestion contractuelle. Guide complet.",
      h2Variants: [
        "IA et due diligence M&A : gain de temps réel",
        "Veille réglementaire automatisée avec les LLM",
        "Conformité RGPD et AI Act pour les équipes juridiques",
      ],
    },
    variables: {
      process: "veille et conformité droit des affaires",
      resultat: "-60 % temps veille",
      chiffre: "60",
      unite: "%",
      delai: "dès le 1er mois",
    },
    urlCible: "/fr/secteurs/juridique",
    canonicalParent: "/fr/secteurs/juridique",
    source: "manuel",
  },
  {
    keyword: "résumé automatique documents juridiques IA",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "juridique",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Résumer automatiquement vos documents juridiques avec l'IA — guide technique",
      metaTitle: "Résumé automatique documents juridiques IA — Axion-IA",
      metaDescription:
        "Pipeline IA pour résumer contrats, décisions, actes et jurisprudence en secondes. Déploiement sécurisé, souveraineté des données garantie.",
      h2Variants: [
        "Quelle technologie pour résumer les documents juridiques ?",
        "Précision et risques : comment valider les résumés IA",
        "Intégration dans votre workflow cabinet existant",
      ],
    },
    variables: {
      process: "lecture et synthèse documents",
      resultat: "100 pages résumées en 30 s",
      chiffre: "30",
      unite: "secondes",
      delai: "dès le déploiement",
    },
    urlCible: "/fr/secteurs/juridique",
    canonicalParent: "/fr/secteurs/juridique",
    source: "manuel",
  },
  {
    keyword: "combien d'heures l'IA économise dans un cabinet d'avocats ?",
    intent: "sectoriel",
    kbType: "roi_calculator_template",
    module: "audit",
    cible: "pme",
    secteur: "juridique",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "IA en cabinet d'avocats : combien d'heures économisées par associé et par mois ?",
      metaTitle: "Heures économisées IA cabinet avocats — calculateur Axion-IA",
      metaDescription:
        "Calculez le gain horaire réel de l'IA dans votre cabinet : rédaction, recherche, administratif. Données issues de nos déploiements France 2025-2026.",
      h2Variants: [
        "Benchmark : 8 à 15 h économisées/semaine selon la spécialité",
        "Quels postes bénéficient le plus de l'IA en cabinet ?",
        "Calculateur ROI IA cabinet d'avocats — estimez votre gain",
      ],
    },
    variables: {
      process: "tâches répétitives juridiques",
      resultat: "8-15 h/semaine économisées",
      chiffre: "8-15",
      unite: "heures/semaine",
      delai: "dès le 1er mois",
    },
    urlCible: "/fr/secteurs/juridique",
    canonicalParent: "/fr/secteurs/juridique",
    source: "manuel",
    note: "intent AEO/question ; schema.org FAQPage + Article",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SECTEUR 2 — COMPTABILITÉ / EXPERTISE COMPTABLE (10 seeds)
// URL cible : /fr/secteurs/expertise-comptable
// ─────────────────────────────────────────────────────────────────────────────

const KW_COMPTABILITE: KeywordSeed[] = [
  {
    keyword: "IA pour expert-comptable France",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "interventions-formations",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "L'IA au service des experts-comptables : gains concrets et déploiement rapide",
      metaTitle: "IA pour expert-comptable France — Axion-IA",
      metaDescription:
        "Axion-IA accompagne les cabinets d'expertise comptable dans l'adoption de l'IA : saisie, liasse, relances. Résultats mesurables en 30 jours.",
      h2Variants: [
        "Quels processus comptables automatiser en priorité avec l'IA ?",
        "IA et secret professionnel comptable : sécurité des données",
        "Témoignages : experts-comptables qui utilisent l'IA au quotidien",
      ],
    },
    variables: {
      process: "saisie et contrôle comptable",
      resultat: "-50 % temps saisie",
      chiffre: "50",
      unite: "%",
      delai: "dès le 1er mois",
    },
    urlCible: "/fr/secteurs/expertise-comptable",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
    note: "schema.org: AccountingService + FAQPage",
  },
  {
    keyword: "automatisation saisie comptable IA",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 1,
    niveau: 3,
    injection: {
      h1: "Automatiser la saisie comptable avec l'IA : pipeline complet en 3 étapes",
      metaTitle: "Automatisation saisie comptable IA — Axion-IA France",
      metaDescription:
        "De la facture PDF à l'écriture comptable sans intervention humaine. Déploiement IA clé en main par Axion-IA, compatible EBP, Sage, Cegid.",
      h2Variants: [
        "Comment l'IA lit et catégorise vos factures fournisseurs",
        "Intégration avec votre logiciel comptable existant",
        "Contrôle qualité et gestion des exceptions automatisées",
      ],
    },
    variables: {
      process: "saisie factures et rapprochement bancaire",
      resultat: "90 % des écritures en automatique",
      chiffre: "90",
      unite: "%",
      delai: "en 6 semaines",
    },
    urlCible: "/fr/secteurs/expertise-comptable",
    canonicalParent: "/fr/secteurs/expertise-comptable",
    source: "manuel",
  },
  {
    keyword: "formation IA cabinet comptable",
    intent: "sectoriel",
    kbType: "intervention_module",
    module: "interventions-formations",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Formation IA pour cabinet comptable : passer de spectateur à opérateur en 1 jour",
      metaTitle: "Formation IA cabinet comptable — Axion-IA",
      metaDescription:
        "Formation IA sur mesure pour experts-comptables et collaborateurs : automatisation, prompting, conformité OEC. Présentiel ou distanciel.",
      h2Variants: [
        "Programme formation IA expert-comptable — contenu détaillé",
        "L'OEC et la formation IA : recommandations et bonnes pratiques",
        "Exercices pratiques : votre propre cabinet en cas d'usage",
      ],
    },
    variables: {
      process: "montée en compétence IA",
      resultat: "premiers gains dès J+1",
      chiffre: "1",
      unite: "jour",
      delai: "dès la formation",
    },
    urlCible: "/fr/interventions-formations/expertise-comptable",
    canonicalParent: "/fr/interventions-formations",
    source: "manuel",
  },
  {
    keyword: "audit IA cabinet expertise comptable",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "audit",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Audit IA cabinet d'expertise comptable : cartographier vos 5 gains en 48 h",
      metaTitle: "Audit IA cabinet expertise comptable — Axion-IA",
      metaDescription:
        "Axion-IA audite les processus de votre cabinet comptable et identifie les automatisations à ROI immédiat. Rapport livré en 48 h.",
      h2Variants: [
        "Ce qu'on analyse lors d'un audit IA cabinet comptable",
        "Processus les plus automatisables : saisie, liasse, relances, reporting",
        "Feuille de route post-audit : par où commencer ?",
      ],
    },
    variables: {
      process: "audit processus comptables",
      resultat: "5 automations prioritaires identifiées",
      chiffre: "5",
      unite: "automations",
      delai: "en 48 h",
    },
    urlCible: "/fr/audit/expertise-comptable",
    canonicalParent: "/fr/audit",
    source: "manuel",
  },
  {
    keyword: "agence IA comptabilité PME",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "transversal",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Axion-IA, l'agence IA dédiée aux cabinets comptables et PME",
      metaTitle: "Agence IA comptabilité PME — Axion-IA France",
      metaDescription:
        "Cabinet IA B2B spécialisé comptabilité PME : audit, formation, implémentation des LLM et automatisation des workflows financiers.",
      h2Variants: [
        "Pourquoi une agence IA comptabilité spécialisée fait la différence",
        "Nos déploiements IA dans des cabinets comptables",
        "Services IA pour cabinets de 2 à 30 collaborateurs",
      ],
    },
    urlCible: "/fr/secteurs/expertise-comptable",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
  },
  {
    keyword: "IA pour liasse fiscale automatisation",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Automatiser la préparation de la liasse fiscale avec l'IA : guide 2026",
      metaTitle: "IA liasse fiscale automatisation — Axion-IA",
      metaDescription:
        "Réduisez le temps de production de la liasse fiscale de 40 % grâce à l'IA. Pipeline IA déployé par Axion-IA, compatible DGFiP EDI.",
      h2Variants: [
        "Quelles étapes de la liasse fiscale sont automatisables par l'IA ?",
        "Risques et contrôles : l'expert garde la main sur la signature",
        "Intégration liasse fiscale IA avec Cegid, Sage et ACD",
      ],
    },
    variables: {
      process: "production liasse fiscale",
      resultat: "-40 % temps de production",
      chiffre: "40",
      unite: "%",
      delai: "dès le 1er exercice",
    },
    urlCible: "/fr/secteurs/expertise-comptable",
    canonicalParent: "/fr/secteurs/expertise-comptable",
    source: "manuel",
  },
  {
    keyword: "intelligence artificielle expert-comptable",
    intent: "sectoriel",
    kbType: "industry_use_case",
    module: "transversal",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Intelligence artificielle et expertise comptable : ce qui change vraiment en 2026",
      metaTitle: "Intelligence artificielle expert-comptable 2026 — Axion-IA",
      metaDescription:
        "État de l'art de l'IA pour les experts-comptables en France : outils, usages, risques, conformité OEC. Guide complet par Axion-IA.",
      h2Variants: [
        "Quels LLM pour les experts-comptables en 2026 ?",
        "L'IA remplace-t-elle l'expert-comptable ? La vraie réponse",
        "Conformité OEC et usage de l'IA : ce que dit la doctrine",
      ],
    },
    urlCible: "/fr/secteurs/expertise-comptable",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
    note: "intent informationnel/sectoriel ; schema.org Article + FAQPage",
  },
  {
    keyword: "automatiser les relances comptables IA",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "tpe",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Automatiser les relances clients impayés avec l'IA : zéro oubli, 0 stress",
      metaTitle: "Automatiser relances comptables IA — Axion-IA",
      metaDescription:
        "Pipeline IA de relances comptables : détection impayés, rédaction email personnalisé, envoi automatique, escalade. +20 % taux d'encaissement.",
      h2Variants: [
        "Comment l'IA rédige des relances personnalisées sans friction client",
        "Paramétrer les seuils et escalades automatiques",
        "Résultats mesurés : taux d'encaissement et délai moyen de paiement",
      ],
    },
    variables: {
      process: "relances impayés",
      resultat: "+20 % encaissements, 0 oubli",
      chiffre: "20",
      unite: "%",
      delai: "dès le 1er mois",
    },
    urlCible: "/fr/secteurs/expertise-comptable",
    canonicalParent: "/fr/secteurs/expertise-comptable",
    source: "manuel",
  },
  {
    keyword: "ROI IA cabinet comptable",
    intent: "sectoriel",
    kbType: "roi_calculator_template",
    module: "audit",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "ROI de l'IA dans un cabinet comptable : calculateur et benchmarks réels",
      metaTitle: "ROI IA cabinet comptable — Axion-IA France",
      metaDescription:
        "Calculez le retour sur investissement de l'IA pour votre cabinet : coût, gains horaires, chiffre d'affaires libéré. Données réelles 2025-2026.",
      h2Variants: [
        "Modèle de calcul ROI IA pour cabinets comptables",
        "Benchmark ROI IA : petits vs grands cabinets",
        "Délai de retour sur investissement IA moyen en expertise comptable",
      ],
    },
    variables: {
      process: "investissement IA cabinet",
      resultat: "ROI positif en 3 mois",
      chiffre: "3",
      unite: "mois",
      delai: "dès le 3e mois",
    },
    urlCible: "/fr/secteurs/expertise-comptable",
    canonicalParent: "/fr/secteurs/expertise-comptable",
    source: "manuel",
  },
  {
    keyword: "comment l'IA aide les experts-comptables ?",
    intent: "sectoriel",
    kbType: "faq",
    module: "transversal",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Comment l'IA aide les experts-comptables au quotidien ? 7 exemples concrets",
      metaTitle: "Comment l'IA aide les experts-comptables ? — Axion-IA",
      metaDescription:
        "De la saisie aux relances en passant par la liasse fiscale : 7 façons dont l'IA transforme le quotidien des experts-comptables en France.",
      h2Variants: [
        "1. Automatiser la saisie comptable",
        "2. Préparer la liasse fiscale plus vite",
        "7. Générer des analyses financières narratives",
      ],
    },
    urlCible: "/fr/secteurs/expertise-comptable",
    canonicalParent: "/fr/secteurs/expertise-comptable",
    source: "manuel",
    note: "AEO fort ; intent question directe ; schema.org FAQPage",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SECTEUR 3 — BTP / CONSTRUCTION (10 seeds)
// URL cible : /fr/secteurs/btp-construction
// Slug secteur canonique : "construction-btp"
// ─────────────────────────────────────────────────────────────────────────────

const KW_BTP: KeywordSeed[] = [
  {
    keyword: "IA pour entreprise BTP France",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "interventions-formations",
    cible: "pme",
    secteur: "construction-btp",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "L'IA dans les entreprises BTP : gain de temps, moins d'erreurs, plus de marges",
      metaTitle: "IA pour entreprise BTP France — Axion-IA",
      metaDescription:
        "Axion-IA déploie l'IA dans les entreprises du bâtiment et des travaux publics : devis, planning, gestion chantier. ROI mesuré dès 6 semaines.",
      h2Variants: [
        "Quels processus BTP automatiser avec l'IA en priorité ?",
        "IA et sécurité chantier : conformité et documentation automatisée",
        "Témoignages : entrepreneurs BTP qui ont adopté l'IA",
      ],
    },
    variables: {
      process: "gestion administrative chantiers",
      resultat: "-30 % temps administratif",
      chiffre: "30",
      unite: "%",
      delai: "en 6 semaines",
    },
    urlCible: "/fr/secteurs/btp-construction",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
    note: "schema.org: HomeAndConstructionBusiness + FAQPage",
  },
  {
    keyword: "automatisation devis chantier IA",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "construction-btp",
    priorite: 1,
    niveau: 3,
    injection: {
      h1: "Générer des devis chantier avec l'IA : de 4 h à 20 min par devis",
      metaTitle: "Automatisation devis chantier IA — Axion-IA France",
      metaDescription:
        "Pipeline IA pour générer des devis travaux précis en quelques minutes : lecture plans, métrés, prix matériaux, mise en page. Déployé par Axion-IA.",
      h2Variants: [
        "Comment l'IA lit un plan de chantier et génère un devis",
        "Intégration avec vos logiciels devis BTP (Batigest, EBP Bâtiment…)",
        "Précision et validation humaine : le conducteur garde la main",
      ],
    },
    variables: {
      process: "établissement devis chantier",
      resultat: "4 h → 20 min par devis",
      chiffre: "20",
      unite: "minutes",
      delai: "dès le déploiement",
    },
    urlCible: "/fr/secteurs/btp-construction",
    canonicalParent: "/fr/secteurs/btp-construction",
    source: "manuel",
  },
  {
    keyword: "formation IA conducteur de travaux",
    intent: "sectoriel",
    kbType: "intervention_module",
    module: "interventions-formations",
    cible: "pme",
    secteur: "construction-btp",
    priorite: 1,
    niveau: 3,
    injection: {
      h1: "Formation IA pour conducteur de travaux : planifier, piloter et documenter plus vite",
      metaTitle: "Formation IA conducteur de travaux — Axion-IA",
      metaDescription:
        "Formation pratique IA dédiée aux conducteurs de travaux : planning, rapports de chantier, suivi sous-traitants. 1 jour sur site, cas réels.",
      h2Variants: [
        "Programme formation IA conducteur de travaux — contenu et durée",
        "IA et planification chantier : exercice pratique en temps réel",
        "Certification et suivi post-formation",
      ],
    },
    variables: {
      process: "planification et reporting chantier",
      resultat: "-50 % temps rapports chantier",
      chiffre: "50",
      unite: "%",
      delai: "dès la formation",
    },
    urlCible: "/fr/interventions-formations/btp-construction",
    canonicalParent: "/fr/interventions-formations",
    source: "manuel",
  },
  {
    keyword: "IA gestion de chantier PME",
    intent: "sectoriel",
    kbType: "industry_use_case",
    module: "implementation",
    cible: "pme",
    secteur: "construction-btp",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "IA et gestion de chantier PME : 5 cas d'usage opérationnels en 2026",
      metaTitle: "IA gestion chantier PME — Axion-IA France",
      metaDescription:
        "Planning, documents de sécurité, comptes rendus de chantier, suivi des marchés : comment les PME du BTP utilisent l'IA au quotidien.",
      h2Variants: [
        "Automatiser les comptes rendus de chantier avec l'IA",
        "Suivi des sous-traitants et fournisseurs avec l'IA",
        "IA et plan de prévention : conformité sécurité accélérée",
      ],
    },
    variables: {
      process: "pilotage chantiers PME",
      resultat: "5× moins de paperasse administrative",
      chiffre: "5",
      unite: "× moins de paperasse",
      delai: "en 4 semaines",
    },
    urlCible: "/fr/secteurs/btp-construction",
    canonicalParent: "/fr/secteurs/btp-construction",
    source: "manuel",
  },
  {
    keyword: "agence IA BTP construction",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "transversal",
    cible: "pme",
    secteur: "construction-btp",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Axion-IA, le cabinet IA expert secteur BTP et construction",
      metaTitle: "Agence IA BTP construction France — Axion-IA",
      metaDescription:
        "Axion-IA est le cabinet IA B2B spécialisé BTP : audit, formation, implémentation et automatisation pour les entreprises du bâtiment.",
      h2Variants: [
        "Pourquoi choisir un cabinet IA spécialisé BTP ?",
        "Nos références secteur bâtiment et construction",
        "Services IA pour PME BTP de 5 à 200 salariés",
      ],
    },
    urlCible: "/fr/secteurs/btp-construction",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
  },
  {
    keyword: "intelligence artificielle construction France",
    intent: "sectoriel",
    kbType: "industry_use_case",
    module: "transversal",
    cible: "eti",
    secteur: "construction-btp",
    priorite: 2,
    niveau: 2,
    injection: {
      h1: "Intelligence artificielle et construction en France : état des lieux 2026",
      metaTitle: "IA construction BTP France 2026 | Axion-IA",
      metaDescription:
        "Panorama complet de l'IA dans le BTP français : maturité, cas d'usage, acteurs, réglementation et perspectives 2026-2028. Guide Axion-IA.",
      h2Variants: [
        "Maturité digitale des entreprises BTP françaises en 2026",
        "Quels acteurs IA ciblent le secteur construction ?",
        "IA et BIM : complémentarité ou substitution ?",
      ],
    },
    urlCible: "/fr/secteurs/btp-construction",
    canonicalParent: "/fr/secteurs/btp-construction",
    source: "manuel",
  },
  {
    keyword: "automatiser planning chantier avec IA",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "construction-btp",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Automatiser le planning chantier avec l'IA : réduction des retards dès le mois 1",
      metaTitle: "Automatiser planning chantier IA — Axion-IA France",
      metaDescription:
        "L'IA optimise votre planning chantier en temps réel : anticipation retards, réaffectation ressources, alertes sous-traitants. Déployé par Axion-IA.",
      h2Variants: [
        "Comment l'IA génère un planning chantier optimisé",
        "Alertes automatiques : retards, météo, disponibilité matériaux",
        "Intégration planning IA avec MS Project et outils BTP existants",
      ],
    },
    variables: {
      process: "planification et optimisation planning",
      resultat: "-25 % retards de livraison",
      chiffre: "25",
      unite: "%",
      delai: "dès le 1er chantier",
    },
    urlCible: "/fr/secteurs/btp-construction",
    canonicalParent: "/fr/secteurs/btp-construction",
    source: "manuel",
  },
  {
    keyword: "IA pour artisan bâtiment",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "interventions-formations",
    cible: "tpe",
    secteur: "construction-btp",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "L'IA pour l'artisan du bâtiment : devis, relances, planning en 2× moins de temps",
      metaTitle: "IA pour artisan bâtiment — Axion-IA France",
      metaDescription:
        "Même sans DSI, les artisans du bâtiment adoptent l'IA : devis automatiques, relances clients, planning simplifié. Accompagnement clé en main Axion-IA.",
      h2Variants: [
        "3 outils IA immédiatement utilisables par un artisan",
        "IA sans abonnement complexe : solutions adaptées aux TPE bâtiment",
        "Témoignage : artisan plombier qui a réduit son admin de moitié",
      ],
    },
    variables: {
      process: "devis, relances et admin artisan",
      resultat: "-50 % temps administratif",
      chiffre: "50",
      unite: "%",
      delai: "en 2 semaines",
    },
    urlCible: "/fr/secteurs/btp-construction",
    canonicalParent: "/fr/secteurs/btp-construction",
    source: "manuel",
  },
  {
    keyword: "audit IA entreprise BTP",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "audit",
    cible: "pme",
    secteur: "construction-btp",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Audit IA pour entreprise BTP : vos 4 gains prioritaires en 48 h",
      metaTitle: "Audit IA entreprise BTP — Axion-IA France",
      metaDescription:
        "Audit IA complet pour PME du bâtiment : cartographie des processus automatisables, ROI estimé, feuille de route 90 jours. Livré en 48 h.",
      h2Variants: [
        "Déroulé d'un audit IA PME BTP",
        "Processus BTP les plus rentables à automatiser",
        "Ce que contient votre rapport d'audit IA",
      ],
    },
    variables: {
      process: "audit processus BTP",
      resultat: "4 automations prioritaires",
      chiffre: "4",
      unite: "automations",
      delai: "en 48 h",
    },
    urlCible: "/fr/audit/btp-construction",
    canonicalParent: "/fr/audit",
    source: "manuel",
  },
  {
    keyword: "combien l'IA fait économiser dans le BTP ?",
    intent: "sectoriel",
    kbType: "roi_calculator_template",
    module: "audit",
    cible: "pme",
    secteur: "construction-btp",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Combien l'IA fait économiser dans le BTP ? Chiffres réels 2026",
      metaTitle: "Économies IA secteur BTP — Axion-IA France",
      metaDescription:
        "De 5 000 € à 40 000 €/an économisés selon la taille de l'entreprise BTP. Calculateur ROI IA et benchmarks sectoriels par Axion-IA.",
      h2Variants: [
        "Gains IA par poste : devis, planning, admin, sécurité",
        "Calculateur ROI IA BTP — estimez votre gain annuel",
        "Cas concrets : PME BTP et leurs économies IA réelles",
      ],
    },
    variables: {
      process: "ensemble des processus BTP",
      resultat: "5 000–40 000 €/an économisés",
      chiffre: "5000-40000",
      unite: "€/an",
      delai: "dès le 1er an",
    },
    urlCible: "/fr/secteurs/btp-construction",
    canonicalParent: "/fr/secteurs/btp-construction",
    source: "manuel",
    note: "AEO fort ; schema.org FAQPage + Article",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SECTEUR 4 — IT / NUMÉRIQUE (10 seeds)
// URL cible : /fr/secteurs/it-numerique
// Slug secteur canonique : "it-numerique"
// ─────────────────────────────────────────────────────────────────────────────

const KW_IT: KeywordSeed[] = [
  {
    keyword: "IA pour ESN France",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "interventions-formations",
    cible: "eti",
    secteur: "it-numerique",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "L'IA dans les ESN françaises : productivité dev, avant-vente et delivery accélérés",
      metaTitle: "IA pour ESN France — Axion-IA cabinet IA B2B",
      metaDescription:
        "Axion-IA accompagne les ESN dans l'adoption des LLM : productivité développeurs, avant-vente automatisée, delivery client accéléré. Résultats dès J+30.",
      h2Variants: [
        "Quels processus ESN automatiser avec l'IA en priorité ?",
        "IA et confidentialité client : gouvernance données ESN",
        "ROI IA pour une ESN de 50 à 500 consultants",
      ],
    },
    variables: {
      process: "avant-vente, delivery, admin consultants",
      resultat: "+30 % productivité développeurs",
      chiffre: "30",
      unite: "%",
      delai: "dès le 1er mois",
    },
    urlCible: "/fr/secteurs/it-numerique",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
    note: "schema.org: ITService + FAQPage",
  },
  {
    keyword: "automatisation développement logiciel IA",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "codage-developpement",
    cible: "pme",
    secteur: "it-numerique",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Automatiser votre cycle de développement logiciel avec l'IA : de l'idée au déploiement",
      metaTitle: "Automatisation développement logiciel IA — Axion-IA",
      metaDescription:
        "Tests, documentation, revue de code, génération de features : comment l'IA accélère chaque étape du cycle de développement. Cas réels Axion-IA.",
      h2Variants: [
        "IA et génération de code : ce qui marche, ce qui ne marche pas",
        "Tests automatiques avec l'IA : couverture +40 % sans effort",
        "IA pour la documentation technique : de 0 à 100 % en 1 run",
      ],
    },
    variables: {
      process: "cycle de développement logiciel",
      resultat: "+40 % vitesse de livraison features",
      chiffre: "40",
      unite: "%",
      delai: "en 4 semaines",
    },
    urlCible: "/fr/secteurs/it-numerique",
    canonicalParent: "/fr/secteurs/it-numerique",
    source: "manuel",
  },
  {
    keyword: "formation IA équipe technique",
    intent: "sectoriel",
    kbType: "intervention_module",
    module: "interventions-formations",
    cible: "pme",
    secteur: "it-numerique",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Formation IA pour équipes techniques : passer de l'expérimentation à la production",
      metaTitle: "Formation IA équipe technique IT — Axion-IA",
      metaDescription:
        "Formation IA pour développeurs, DevOps et tech leads : API Claude, patterns LLM, sécurité, gouvernance. Présentiel ou remote, 1 à 3 jours.",
      h2Variants: [
        "Programme formation IA développeurs et tech leads",
        "Hands-on : déployer votre premier agent IA en production",
        "Gouvernance IA pour équipes techniques : sécurité et conformité",
      ],
    },
    variables: {
      process: "formation LLM et IA en production",
      resultat: "1er agent IA en prod dès J+3",
      chiffre: "3",
      unite: "jours",
      delai: "dès la formation",
    },
    urlCible: "/fr/interventions-formations/it-numerique",
    canonicalParent: "/fr/interventions-formations",
    source: "manuel",
  },
  {
    keyword: "Claude API intégration ESN",
    intent: "sectoriel",
    kbType: "implementation_playbook",
    module: "codage-developpement",
    cible: "sous-traitant-dev",
    secteur: "it-numerique",
    priorite: 1,
    niveau: 3,
    injection: {
      h1: "Intégrer l'API Claude dans vos produits ESN : playbook technique complet",
      metaTitle: "Claude API intégration ESN — Axion-IA France",
      metaDescription:
        "Playbook d'intégration de l'API Claude Anthropic pour ESN et éditeurs : auth, rate limits, caching, coût maîtrisé, déploiement prod. Par Axion-IA.",
      h2Variants: [
        "Architecture recommandée : Claude API + caching + fallback",
        "Gestion des coûts API Claude en production ESN",
        "Sécurité et conformité RGPD lors de l'intégration Claude API",
      ],
    },
    variables: {
      process: "intégration API LLM en production",
      resultat: "time-to-prod divisé par 3",
      chiffre: "3",
      unite: "× plus rapide",
      delai: "en 2 semaines",
    },
    urlCible: "/fr/secteurs/it-numerique",
    canonicalParent: "/fr/secteurs/it-numerique",
    source: "manuel",
    note: "schema.org: TechArticle ; mots secondaires : Anthropic API France, intégrateur Claude",
  },
  {
    keyword: "agence IA IT numérique",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "transversal",
    cible: "pme",
    secteur: "it-numerique",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Axion-IA, le cabinet IA expert secteur IT et numérique",
      metaTitle: "Agence IA IT numérique France — Axion-IA",
      metaDescription:
        "Axion-IA est le cabinet IA B2B de référence pour les acteurs IT : ESN, éditeurs, startups. Audit, formation, implémentation et codage sur mesure.",
      h2Variants: [
        "Pourquoi un cabinet IA spécialisé IT plutôt qu'un généraliste ?",
        "Nos déploiements IA dans les entreprises IT françaises",
        "Services IA : de l'audit à l'agent IA autonome en production",
      ],
    },
    urlCible: "/fr/secteurs/it-numerique",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
  },
  {
    keyword: "IA pour booster la productivité dev",
    intent: "sectoriel",
    kbType: "industry_use_case",
    module: "interventions-formations",
    cible: "pme",
    secteur: "it-numerique",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Booster la productivité des développeurs avec l'IA : +30 % en 30 jours",
      metaTitle: "IA productivité développeurs — Axion-IA France",
      metaDescription:
        "Revue de code, génération tests, documentation, debugging : 7 façons concrètes d'augmenter la productivité dev avec l'IA. Guide Axion-IA 2026.",
      h2Variants: [
        "7 usages IA qui augmentent la productivité des développeurs",
        "Mesurer le gain de productivité dev avec l'IA : méthode",
        "Quels outils IA pour développeurs en 2026 ?",
      ],
    },
    variables: {
      process: "développement logiciel quotidien",
      resultat: "+30 % vélocité équipe dev",
      chiffre: "30",
      unite: "%",
      delai: "en 30 jours",
    },
    urlCible: "/fr/secteurs/it-numerique",
    canonicalParent: "/fr/secteurs/it-numerique",
    source: "manuel",
  },
  {
    keyword: "cabinet IA spécialiste IT",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "transversal",
    cible: "eti",
    secteur: "it-numerique",
    priorite: 2,
    niveau: 2,
    injection: {
      h1: "Axion-IA : le cabinet IA spécialiste du secteur IT et des entreprises numériques",
      metaTitle: "Cabinet IA spécialiste IT — Axion-IA France",
      metaDescription:
        "Axion-IA combine expertise IA et profondeur sectorielle IT pour accompagner ESN, éditeurs et startups numériques vers la performance opérationnelle.",
      h2Variants: [
        "Ce qui distingue un cabinet IA spécialisé IT d'un généraliste",
        "Notre équipe : ingénieurs IA + experts métier IT",
        "Références et cas clients secteur IT France",
      ],
    },
    urlCible: "/fr/secteurs/it-numerique",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
  },
  {
    keyword: "intégrateur IA solutions numériques",
    intent: "sectoriel",
    kbType: "implementation_playbook",
    module: "implementation",
    cible: "pme",
    secteur: "it-numerique",
    priorite: 2,
    niveau: 2,
    injection: {
      h1: "Intégrateur IA pour solutions numériques : de l'API au produit en production",
      metaTitle: "Intégrateur IA solutions numériques — Axion-IA",
      metaDescription:
        "Axion-IA intègre les meilleurs LLM (Claude, GPT-4o, Gemini) dans vos produits numériques : architecture, sécurité, coût maîtrisé, déploiement.",
      h2Variants: [
        "Quelle stack LLM choisir pour vos solutions numériques ?",
        "Sécurité et données : intégration IA conforme RGPD",
        "Coût d'intégration IA : forfaits et mode régie",
      ],
    },
    urlCible: "/fr/secteurs/it-numerique",
    canonicalParent: "/fr/secteurs/it-numerique",
    source: "manuel",
  },
  {
    keyword: "IA DevOps automatisation",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "codage-developpement",
    cible: "pme",
    secteur: "it-numerique",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "IA et DevOps : automatiser déploiements, monitoring et incidents avec les LLM",
      metaTitle: "IA DevOps automatisation — Axion-IA France",
      metaDescription:
        "Pipelines CI/CD intelligents, détection d'anomalies, runbooks automatiques : comment l'IA transforme le DevOps. Implémentation par Axion-IA.",
      h2Variants: [
        "IA pour la détection et résolution automatique d'incidents",
        "Générer et maintenir des runbooks DevOps avec l'IA",
        "IA dans le pipeline CI/CD : tests, sécurité, déploiement",
      ],
    },
    variables: {
      process: "opérations DevOps et incidents",
      resultat: "-60 % temps résolution incidents",
      chiffre: "60",
      unite: "%",
      delai: "en 8 semaines",
    },
    urlCible: "/fr/secteurs/it-numerique",
    canonicalParent: "/fr/secteurs/it-numerique",
    source: "manuel",
  },
  {
    keyword: "IA pour startup numérique France",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "interventions-formations",
    cible: "startup-scaleup",
    secteur: "it-numerique",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "IA pour startups numériques françaises : aller 3× plus vite sans recruter",
      metaTitle: "IA pour startup numérique France — Axion-IA",
      metaDescription:
        "Axion-IA aide les startups tech à intégrer l'IA dans leur produit et leur ops sans recruter de Data Scientists. Impact rapide, budget startup.",
      h2Variants: [
        "3 usages IA immédiats pour une startup numérique",
        "Budget IA startup : combien investir au démarrage ?",
        "IA et time-to-market : accélérer sans sacrifier la qualité",
      ],
    },
    variables: {
      process: "product + ops startup",
      resultat: "3× plus rapide sur les features",
      chiffre: "3",
      unite: "×",
      delai: "en 4 semaines",
    },
    urlCible: "/fr/secteurs/it-numerique",
    canonicalParent: "/fr/secteurs/it-numerique",
    source: "manuel",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SECTEUR 5 — RH / RECRUTEMENT (10 seeds)
// URL cible : /fr/secteurs/rh-recrutement
// Slug secteur : "conseil-affaires" (RH tertiaire services)
// ─────────────────────────────────────────────────────────────────────────────

const KW_RH: KeywordSeed[] = [
  {
    keyword: "IA pour DRH PME France",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "interventions-formations",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "L'IA pour les DRH de PME : recruter, onboarder et piloter plus vite",
      metaTitle: "IA pour DRH PME France — Axion-IA",
      metaDescription:
        "Axion-IA accompagne les DRH de PME dans l'adoption de l'IA : tri CV, onboarding, gestion administrative RH. Gains mesurables dès 30 jours.",
      h2Variants: [
        "Quels processus RH automatiser avec l'IA en priorité ?",
        "IA et droit du travail : conformité et risques",
        "Témoignages DRH PME : leurs 1ers gains avec l'IA",
      ],
    },
    variables: {
      process: "processus RH quotidiens",
      resultat: "-40 % temps administratif RH",
      chiffre: "40",
      unite: "%",
      delai: "en 30 jours",
    },
    urlCible: "/fr/secteurs/rh-recrutement",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
  },
  {
    keyword: "automatiser tri CV avec l'IA",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 1,
    niveau: 3,
    injection: {
      h1: "Trier les CV automatiquement avec l'IA : 200 candidatures analysées en 5 min",
      metaTitle: "Automatiser tri CV avec l'IA — Axion-IA France",
      metaDescription:
        "Pipeline IA de présélection CV : lecture, scoring, classement, synthèse par candidat. RGPD et non-discrimination by design. Déployé par Axion-IA.",
      h2Variants: [
        "Comment l'IA score et classe les CV sans biais",
        "RGPD et non-discrimination : cadre légal du tri IA",
        "Intégration avec votre ATS existant : Workday, Greenhouse, ICIMS",
      ],
    },
    variables: {
      process: "présélection candidatures",
      resultat: "200 CV analysés en 5 min",
      chiffre: "200",
      unite: "CV / 5 min",
      delai: "dès le déploiement",
    },
    urlCible: "/fr/secteurs/rh-recrutement",
    canonicalParent: "/fr/secteurs/rh-recrutement",
    source: "manuel",
    note: "RGPD mention obligatoire ; schema.org : TechArticle",
  },
  {
    keyword: "formation IA équipe RH",
    intent: "sectoriel",
    kbType: "intervention_module",
    module: "interventions-formations",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Formation IA pour équipes RH : automatiser sans déshumaniser",
      metaTitle: "Formation IA équipe RH PME — Axion-IA",
      metaDescription:
        "Formation IA sur mesure pour DRH, RRH et chargés de recrutement : tri CV, onboarding, reporting RH, chatbot interne. Cas pratiques réels.",
      h2Variants: [
        "Programme formation IA RH — 1 jour ou 2 jours selon profil",
        "IA et éthique RH : formation au bon usage des algorithmes",
        "Suivi post-formation et mesure des gains RH",
      ],
    },
    variables: {
      process: "montée en compétence IA RH",
      resultat: "équipe autonome en 1 jour",
      chiffre: "1",
      unite: "jour",
      delai: "dès la formation",
    },
    urlCible: "/fr/interventions-formations/rh-recrutement",
    canonicalParent: "/fr/interventions-formations",
    source: "manuel",
  },
  {
    keyword: "IA onboarding salariés",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Automatiser l'onboarding des salariés avec l'IA : parcours personnalisé en 1 clic",
      metaTitle: "IA onboarding salariés PME — Axion-IA France",
      metaDescription:
        "Parcours d'intégration automatisé, chatbot RH répondant aux 50 questions fréquentes, suivi 90 jours : l'IA transforme l'onboarding PME.",
      h2Variants: [
        "Chatbot RH onboarding : ce qu'il sait répondre automatiquement",
        "Personnaliser le parcours d'intégration avec l'IA",
        "Mesurer l'efficacité de l'onboarding IA : KPIs RH",
      ],
    },
    variables: {
      process: "intégration nouveaux salariés",
      resultat: "-70 % questions basiques au RH",
      chiffre: "70",
      unite: "%",
      delai: "dès le déploiement",
    },
    urlCible: "/fr/secteurs/rh-recrutement",
    canonicalParent: "/fr/secteurs/rh-recrutement",
    source: "manuel",
  },
  {
    keyword: "agence IA recrutement PME",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "transversal",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Axion-IA, le cabinet IA spécialisé recrutement et RH PME",
      metaTitle: "Agence IA recrutement PME — Axion-IA France",
      metaDescription:
        "Axion-IA accompagne les PME dans l'automatisation de leur recrutement et de leur gestion RH grâce à l'IA. Audit, formation, implémentation.",
      h2Variants: [
        "Pourquoi automatiser son recrutement avec l'IA PME ?",
        "Services IA RH pour PME de 10 à 500 salariés",
        "Nos déploiements IA RH en France",
      ],
    },
    urlCible: "/fr/secteurs/rh-recrutement",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
  },
  {
    keyword: "intelligence artificielle gestion RH",
    intent: "sectoriel",
    kbType: "industry_use_case",
    module: "transversal",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 2,
    injection: {
      h1: "Intelligence artificielle et gestion RH : état de l'art 2026 pour les PME françaises",
      metaTitle: "Intelligence artificielle gestion RH 2026 — Axion-IA",
      metaDescription:
        "Panorama complet de l'IA en GRH : recrutement, formation, paie, absentéisme, GPEC. Quels outils, quels risques, quel ROI pour les PME en France ?",
      h2Variants: [
        "Cartographie des solutions IA RH pour PME en 2026",
        "IA et données RH : ce que dit le RGPD",
        "ROI moyen de l'IA en gestion RH PME",
      ],
    },
    urlCible: "/fr/secteurs/rh-recrutement",
    canonicalParent: "/fr/secteurs/rh-recrutement",
    source: "manuel",
  },
  {
    keyword: "IA pour réduire le temps de recrutement",
    intent: "sectoriel",
    kbType: "roi_calculator_template",
    module: "audit",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Réduire votre délai de recrutement de 50 % avec l'IA : méthode et résultats",
      metaTitle: "Réduire temps de recrutement IA — Axion-IA France",
      metaDescription:
        "Time-to-hire divisé par 2 grâce à l'IA : présélection automatique, scoring candidats, planification entretiens. Benchmarks réels PME France 2026.",
      h2Variants: [
        "Les étapes de recrutement les plus chronophages à automatiser",
        "Benchmark time-to-hire avec et sans IA",
        "Calculateur ROI IA recrutement PME",
      ],
    },
    variables: {
      process: "cycle complet de recrutement",
      resultat: "time-to-hire / 2",
      chiffre: "50",
      unite: "%",
      delai: "dès le 1er recrutement",
    },
    urlCible: "/fr/secteurs/rh-recrutement",
    canonicalParent: "/fr/secteurs/rh-recrutement",
    source: "manuel",
  },
  {
    keyword: "audit IA process RH entreprise",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "audit",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Audit IA processus RH : cartographier vos gains en 48 h",
      metaTitle: "Audit IA processus RH entreprise — Axion-IA",
      metaDescription:
        "Axion-IA audite vos processus RH et identifie les automatisations à ROI rapide : recrutement, onboarding, paie, reporting. Rapport en 48 h.",
      h2Variants: [
        "Déroulé de l'audit IA processus RH en 48 h",
        "Processus RH les plus automatisables selon notre benchmark",
        "Rapport d'audit RH IA : ce que vous recevez",
      ],
    },
    variables: {
      process: "audit processus RH",
      resultat: "5 automations prioritaires RH",
      chiffre: "5",
      unite: "automations",
      delai: "en 48 h",
    },
    urlCible: "/fr/audit/rh-recrutement",
    canonicalParent: "/fr/audit",
    source: "manuel",
  },
  {
    keyword: "chatbot RH IA",
    intent: "sectoriel",
    kbType: "implementation_playbook",
    module: "implementation",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Déployer un chatbot RH IA en PME : répondre à 80 % des questions salariés automatiquement",
      metaTitle: "Chatbot RH IA PME — Axion-IA France",
      metaDescription:
        "Chatbot RH alimenté par LLM : congés, paie, mutuelle, règlement intérieur. Déployé par Axion-IA en 4 semaines, RGPD by design.",
      h2Variants: [
        "Ce qu'un chatbot RH IA sait répondre automatiquement",
        "Intégration chatbot RH dans Slack, Teams ou intranet",
        "RGPD et chatbot RH : données personnelles et droits des salariés",
      ],
    },
    variables: {
      process: "questions salarié au RH",
      resultat: "80 % questions répondues en automatique",
      chiffre: "80",
      unite: "%",
      delai: "en 4 semaines",
    },
    urlCible: "/fr/secteurs/rh-recrutement",
    canonicalParent: "/fr/secteurs/rh-recrutement",
    source: "manuel",
  },
  {
    keyword: "combien l'IA économise en temps RH ?",
    intent: "sectoriel",
    kbType: "roi_calculator_template",
    module: "audit",
    cible: "pme",
    secteur: "conseil-affaires",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Combien de temps l'IA fait-elle économiser à votre équipe RH ? Chiffres réels",
      metaTitle: "Temps économisé IA équipe RH — Axion-IA France",
      metaDescription:
        "De 5 à 15 h/semaine économisées par RRH grâce à l'IA. Calculateur de gains et benchmarks sectoriels par Axion-IA.",
      h2Variants: [
        "Benchmark : heures RH économisées par taille d'entreprise",
        "Quelles tâches RH consomment le plus de temps et s'automatisent le mieux",
        "Calculateur ROI IA RH — estimez vos gains en 2 minutes",
      ],
    },
    variables: {
      process: "ensemble processus RH",
      resultat: "5-15 h/semaine économisées par RRH",
      chiffre: "5-15",
      unite: "h/semaine",
      delai: "dès le 1er mois",
    },
    urlCible: "/fr/secteurs/rh-recrutement",
    canonicalParent: "/fr/secteurs/rh-recrutement",
    source: "manuel",
    note: "AEO fort ; schema.org FAQPage",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SECTEUR 6 — COMMERCE / RETAIL (10 seeds)
// URL cible : /fr/secteurs/commerce-retail
// Slug secteur canonique : "retail-e-commerce"
// ─────────────────────────────────────────────────────────────────────────────

const KW_COMMERCE: KeywordSeed[] = [
  {
    keyword: "IA pour e-commerce PME France",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "interventions-formations",
    cible: "pme",
    secteur: "retail-e-commerce",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "L'IA pour les e-commerçants PME : automatiser les ventes sans recruter",
      metaTitle: "IA pour e-commerce PME France — Axion-IA",
      metaDescription:
        "Axion-IA accompagne les PME e-commerce dans l'IA : fiches produits, service client, recommandations, abandon panier. ROI en 30 jours.",
      h2Variants: [
        "Quels processus e-commerce automatiser avec l'IA en priorité ?",
        "IA et conversion : comment augmenter le taux de conversion avec l'IA",
        "Cas clients PME e-commerce : leurs résultats réels",
      ],
    },
    variables: {
      process: "opérations e-commerce PME",
      resultat: "+20 % conversion avec IA",
      chiffre: "20",
      unite: "%",
      delai: "en 30 jours",
    },
    urlCible: "/fr/secteurs/commerce-retail",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
  },
  {
    keyword: "automatiser service client IA retail",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "retail-e-commerce",
    priorite: 1,
    niveau: 3,
    injection: {
      h1: "Automatiser votre service client retail avec l'IA : 80 % des tickets traités en automatique",
      metaTitle: "Automatiser service client IA retail — Axion-IA",
      metaDescription:
        "Chatbot service client, traitement retours, réponse avis : comment l'IA prend en charge 80 % des demandes retail sans intervention humaine.",
      h2Variants: [
        "Quels tickets service client automatiser avec l'IA ?",
        "Escalade intelligente : quand l'IA passe la main à un humain",
        "Mesurer la satisfaction client avec un service client IA",
      ],
    },
    variables: {
      process: "service client retail",
      resultat: "80 % tickets traités en automatique",
      chiffre: "80",
      unite: "%",
      delai: "en 4 semaines",
    },
    urlCible: "/fr/secteurs/commerce-retail",
    canonicalParent: "/fr/secteurs/commerce-retail",
    source: "manuel",
  },
  {
    keyword: "chatbot commercial IA PME",
    intent: "sectoriel",
    kbType: "implementation_playbook",
    module: "implementation",
    cible: "pme",
    secteur: "retail-e-commerce",
    priorite: 1,
    niveau: 3,
    injection: {
      h1: "Déployer un chatbot commercial IA en PME : qualifier les leads 24h/24",
      metaTitle: "Chatbot commercial IA PME — Axion-IA France",
      metaDescription:
        "Chatbot IA commercial : qualification leads, réponse devis, relance panier abandonné, recommandation produit. Déployé par Axion-IA en 4 semaines.",
      h2Variants: [
        "Ce qu'un chatbot commercial IA PME peut faire automatiquement",
        "Intégration chatbot IA avec votre CRM et e-commerce",
        "RGPD et chatbot commercial : consentement et données clients",
      ],
    },
    variables: {
      process: "qualification et nurturing leads",
      resultat: "+35 % leads qualifiés 24h/24",
      chiffre: "35",
      unite: "%",
      delai: "en 4 semaines",
    },
    urlCible: "/fr/secteurs/commerce-retail",
    canonicalParent: "/fr/secteurs/commerce-retail",
    source: "manuel",
  },
  {
    keyword: "agence IA commerce distribution",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "transversal",
    cible: "pme",
    secteur: "retail-e-commerce",
    priorite: 2,
    niveau: 2,
    injection: {
      h1: "Axion-IA, le cabinet IA spécialisé commerce et distribution",
      metaTitle: "Agence IA commerce distribution France — Axion-IA",
      metaDescription:
        "Axion-IA est le cabinet IA de référence pour les entreprises du commerce et de la distribution : audit, formation, implémentation, chatbot commercial.",
      h2Variants: [
        "Nos déploiements IA dans le secteur commerce distribution",
        "Services IA retail : de l'audit au chatbot commercial en production",
        "Pourquoi spécialiser son cabinet IA sur le commerce ?",
      ],
    },
    urlCible: "/fr/secteurs/commerce-retail",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
  },
  {
    keyword: "IA pour améliorer les ventes PME",
    intent: "sectoriel",
    kbType: "industry_use_case",
    module: "implementation",
    cible: "pme",
    secteur: "retail-e-commerce",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Comment l'IA améliore les ventes en PME : 6 leviers concrets et mesurés",
      metaTitle: "IA pour améliorer les ventes PME — Axion-IA",
      metaDescription:
        "Recommandations personnalisées, upsell automatique, relance panier, fiches produits optimisées : 6 façons dont l'IA augmente le CA PME.",
      h2Variants: [
        "Recommandations produits IA : +15 % panier moyen",
        "Relance panier abandonné IA : récupérer 25 % des ventes perdues",
        "Fiches produits générées par IA : SEO et conversion optimisés",
      ],
    },
    variables: {
      process: "cycle de vente PME commerce",
      resultat: "+15 % CA en 60 jours",
      chiffre: "15",
      unite: "%",
      delai: "en 60 jours",
    },
    urlCible: "/fr/secteurs/commerce-retail",
    canonicalParent: "/fr/secteurs/commerce-retail",
    source: "manuel",
  },
  {
    keyword: "intelligence artificielle commerce de détail",
    intent: "sectoriel",
    kbType: "industry_use_case",
    module: "transversal",
    cible: "pme",
    secteur: "retail-e-commerce",
    priorite: 2,
    niveau: 2,
    injection: {
      h1: "Intelligence artificielle et commerce de détail : guide complet 2026",
      metaTitle: "Intelligence artificielle commerce de détail 2026 — Axion-IA",
      metaDescription:
        "Panorama de l'IA dans le retail français : state of the art, cas d'usage, ROI, risques et acteurs. Par Axion-IA, cabinet IA B2B France.",
      h2Variants: [
        "Maturité de l'IA dans le commerce de détail français en 2026",
        "Quels retailers français utilisent déjà l'IA ?",
        "IA et expérience client omnicanal",
      ],
    },
    urlCible: "/fr/secteurs/commerce-retail",
    canonicalParent: "/fr/secteurs/commerce-retail",
    source: "manuel",
  },
  {
    keyword: "formation IA équipe commerciale",
    intent: "sectoriel",
    kbType: "intervention_module",
    module: "interventions-formations",
    cible: "pme",
    secteur: "retail-e-commerce",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Formation IA pour équipes commerciales : prospecter, qualifier et closer avec l'IA",
      metaTitle: "Formation IA équipe commerciale PME — Axion-IA",
      metaDescription:
        "Formation IA sur mesure pour commerciaux et responsables vente : prompting, CRM enrichi par IA, rédaction devis, suivi clients automatisé.",
      h2Variants: [
        "Programme formation IA équipe commerciale — contenu et durée",
        "IA pour la prospection BtoB : scraping, enrichissement, séquences",
        "Exercices pratiques : vos propres outils commerciaux en cas d'usage",
      ],
    },
    variables: {
      process: "prospection et closing commercial",
      resultat: "+25 % taux de closing",
      chiffre: "25",
      unite: "%",
      delai: "en 30 jours",
    },
    urlCible: "/fr/interventions-formations/commerce-retail",
    canonicalParent: "/fr/interventions-formations",
    source: "manuel",
  },
  {
    keyword: "IA fidélisation client retail",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "retail-e-commerce",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Fidéliser vos clients retail avec l'IA : personnalisation à grande échelle",
      metaTitle: "IA fidélisation client retail PME — Axion-IA",
      metaDescription:
        "Segmentation IA, emails personnalisés, offres dynamiques, détection churn : comment l'IA améliore la fidélisation client retail PME.",
      h2Variants: [
        "Segmentation client par IA : au-delà du RFM classique",
        "Emails de fidélisation personnalisés générés par IA",
        "Détection précoce du churn avec l'IA : agir avant la perte",
      ],
    },
    variables: {
      process: "fidélisation et rétention clients",
      resultat: "+20 % taux de réachat",
      chiffre: "20",
      unite: "%",
      delai: "en 60 jours",
    },
    urlCible: "/fr/secteurs/commerce-retail",
    canonicalParent: "/fr/secteurs/commerce-retail",
    source: "manuel",
  },
  {
    keyword: "automatiser les commandes IA PME",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "retail-e-commerce",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Automatiser la gestion des commandes avec l'IA : zéro erreur, livraison accélérée",
      metaTitle: "Automatiser commandes IA PME retail — Axion-IA",
      metaDescription:
        "Confirmation automatique, gestion stocks, alertes rupture, tracking livraison : pipeline IA de gestion des commandes clé en main pour PME retail.",
      h2Variants: [
        "Pipeline commande-to-livraison automatisé par l'IA",
        "IA et gestion des stocks : anticipation ruptures et réassorts",
        "Intégration IA avec Shopify, WooCommerce et ERP PME",
      ],
    },
    variables: {
      process: "traitement commandes et livraisons",
      resultat: "0 erreur saisie commande, +30 % vélocité",
      chiffre: "30",
      unite: "%",
      delai: "en 6 semaines",
    },
    urlCible: "/fr/secteurs/commerce-retail",
    canonicalParent: "/fr/secteurs/commerce-retail",
    source: "manuel",
  },
  {
    keyword: "ROI IA pour commerces de détail",
    intent: "sectoriel",
    kbType: "roi_calculator_template",
    module: "audit",
    cible: "pme",
    secteur: "retail-e-commerce",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "ROI de l'IA pour les commerces de détail : calculateur et benchmarks 2026",
      metaTitle: "ROI IA commerces de détail — Axion-IA France",
      metaDescription:
        "Calculez le retour sur investissement de l'IA pour votre commerce de détail. Données réelles issues de déploiements Axion-IA en France 2025-2026.",
      h2Variants: [
        "Modèle de calcul ROI IA pour commerces de détail",
        "Benchmark ROI IA retail : en ligne vs physique",
        "Délai moyen de retour sur investissement IA retail PME",
      ],
    },
    variables: {
      process: "ensemble opérations commerce",
      resultat: "ROI positif en 4 mois",
      chiffre: "4",
      unite: "mois",
      delai: "dès le 4e mois",
    },
    urlCible: "/fr/secteurs/commerce-retail",
    canonicalParent: "/fr/secteurs/commerce-retail",
    source: "manuel",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SECTEUR 7 — SANTÉ / MÉDICAL (5 seeds)
// URL cible : /fr/secteurs/sante-medical
// Slug secteur canonique : "sante-biotech"
// ─────────────────────────────────────────────────────────────────────────────

const KW_SANTE: KeywordSeed[] = [
  {
    keyword: "IA pour clinique médicale France",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "interventions-formations",
    cible: "pme",
    secteur: "sante-biotech",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "L'IA dans les cliniques médicales françaises : administratif automatisé, médecins focalisés",
      metaTitle: "IA pour clinique médicale France — Axion-IA",
      metaDescription:
        "Axion-IA accompagne les cliniques et centres de santé dans l'IA : secrétariat médical, dossiers patients, rappels automatiques. RGPD et HDS.",
      h2Variants: [
        "Quels processus médicaux automatiser avec l'IA en conformité HDS ?",
        "IA et secret médical : architecture sécurisée HDS",
        "Témoignages : cliniques qui ont adopté l'IA administrative",
      ],
    },
    variables: {
      process: "administratif médical clinique",
      resultat: "-50 % temps administratif médecin",
      chiffre: "50",
      unite: "%",
      delai: "en 6 semaines",
    },
    urlCible: "/fr/secteurs/sante-medical",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
    note: "HDS obligatoire ; conformité RGPD santé mention critique",
  },
  {
    keyword: "automatisation administrative médecin cabinet",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "tpe",
    secteur: "sante-biotech",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Automatiser l'administratif du cabinet médical avec l'IA : agenda, relances, courriers",
      metaTitle: "Automatisation administrative médecin cabinet IA — Axion-IA",
      metaDescription:
        "L'IA prend en charge la gestion de l'agenda, les rappels patients, les lettres aux confrères et la documentation. Cabinet médical libéré de l'admin.",
      h2Variants: [
        "Automatiser les rappels de rendez-vous médicaux avec l'IA",
        "Génération de courriers médicaux avec l'IA : conformité et relecture",
        "Intégration IA avec Doctolib, Mediboard et logiciels métier",
      ],
    },
    variables: {
      process: "gestion administrative cabinet médical",
      resultat: "-3 h/jour d'administratif médecin",
      chiffre: "3",
      unite: "heures/jour",
      delai: "en 4 semaines",
    },
    urlCible: "/fr/secteurs/sante-medical",
    canonicalParent: "/fr/secteurs/sante-medical",
    source: "manuel",
  },
  {
    keyword: "IA pour secrétariat médical",
    intent: "sectoriel",
    kbType: "implementation_playbook",
    module: "implementation",
    cible: "tpe",
    secteur: "sante-biotech",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "IA pour secrétariat médical : gérer 80 % des appels et tâches administratives",
      metaTitle: "IA pour secrétariat médical — Axion-IA France",
      metaDescription:
        "Assistante IA médicale : réponse appels entrants, prise RDV, rappels patients, courriers. Solution clé en main by Axion-IA, conforme HDS.",
      h2Variants: [
        "Ce qu'une IA de secrétariat médical peut gérer automatiquement",
        "Intégration avec l'agenda médical et le logiciel de cabinet",
        "RGPD et données santé : comment garantir la conformité",
      ],
    },
    variables: {
      process: "secrétariat médical inbound",
      resultat: "80 % appels traités sans humain",
      chiffre: "80",
      unite: "%",
      delai: "en 6 semaines",
    },
    urlCible: "/fr/secteurs/sante-medical",
    canonicalParent: "/fr/secteurs/sante-medical",
    source: "manuel",
  },
  {
    keyword: "intelligence artificielle santé PME France",
    intent: "sectoriel",
    kbType: "industry_use_case",
    module: "transversal",
    cible: "pme",
    secteur: "sante-biotech",
    priorite: 2,
    niveau: 2,
    injection: {
      h1: "Intelligence artificielle et santé PME en France : guide 2026 et cadre réglementaire",
      metaTitle: "Intelligence artificielle santé PME France 2026 — Axion-IA",
      metaDescription:
        "État de l'art de l'IA pour les acteurs de santé PME en France : usages, conformité HDS et RGPD, acteurs, ROI. Guide complet Axion-IA.",
      h2Variants: [
        "Quels usages IA en santé sont autorisés et matures en 2026 ?",
        "Hébergement données santé HDS : obligations et solutions",
        "ROI de l'IA administrative pour les structures de santé PME",
      ],
    },
    urlCible: "/fr/secteurs/sante-medical",
    canonicalParent: "/fr/secteurs/sante-medical",
    source: "manuel",
  },
  {
    keyword: "formation IA équipe médicale",
    intent: "sectoriel",
    kbType: "intervention_module",
    module: "interventions-formations",
    cible: "pme",
    secteur: "sante-biotech",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Formation IA pour équipes médicales : usages administratifs et aide à la décision",
      metaTitle: "Formation IA équipe médicale — Axion-IA France",
      metaDescription:
        "Formation IA sur mesure pour médecins, secrétaires médicales et cadres de santé. Focus administratif et conformité HDS/RGPD.",
      h2Variants: [
        "Programme formation IA équipe médicale — contenu et durée",
        "Ce que l'IA peut faire (et ne peut pas faire) en médecine",
        "Certification et suivi post-formation équipe médicale",
      ],
    },
    variables: {
      process: "montée en compétence IA santé",
      resultat: "équipe autonome en 1 jour",
      chiffre: "1",
      unite: "jour",
      delai: "dès la formation",
    },
    urlCible: "/fr/interventions-formations/sante-medical",
    canonicalParent: "/fr/interventions-formations",
    source: "manuel",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SECTEUR 8 — AGROALIMENTAIRE / AGRICULTURE (5 seeds)
// URL cible : /fr/secteurs/agroalimentaire
// Slug secteur canonique : "agroalimentaire-igp"
// ─────────────────────────────────────────────────────────────────────────────

const KW_AGRO: KeywordSeed[] = [
  {
    keyword: "IA pour agroalimentaire France",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "interventions-formations",
    cible: "pme",
    secteur: "agroalimentaire-igp",
    priorite: 2,
    niveau: 2,
    injection: {
      h1: "L'IA dans l'industrie agroalimentaire française : traçabilité, qualité, productivité",
      metaTitle: "IA pour agroalimentaire France — Axion-IA",
      metaDescription:
        "Axion-IA déploie l'IA dans les entreprises agroalimentaires : traçabilité, contrôle qualité automatisé, documentation réglementaire. ROI mesuré.",
      h2Variants: [
        "Quels processus agroalimentaires automatiser avec l'IA ?",
        "IA et normes agroalimentaires : HACCP, IFS, BRC automatisés",
        "Cas d'usage IA industrie agroalimentaire PME France",
      ],
    },
    variables: {
      process: "traçabilité et contrôle qualité",
      resultat: "-40 % non-conformités",
      chiffre: "40",
      unite: "%",
      delai: "en 8 semaines",
    },
    urlCible: "/fr/secteurs/agroalimentaire",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
    note: "schema.org: FoodEstablishment (extension) ; mots secondaires : IA agroalimentaire PME, LLM industrie alimentaire",
  },
  {
    keyword: "automatisation traçabilité IA agroalimentaire",
    intent: "sectoriel",
    kbType: "automation_recipe",
    module: "implementation",
    cible: "pme",
    secteur: "agroalimentaire-igp",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Automatiser la traçabilité agroalimentaire avec l'IA : conformité totale, 0 saisie manuelle",
      metaTitle: "Automatisation traçabilité IA agroalimentaire — Axion-IA",
      metaDescription:
        "Pipeline IA de traçabilité agroalimentaire : lecture étiquettes, enregistrement lot, alertes non-conformité, génération documents réglementaires.",
      h2Variants: [
        "Comment l'IA lit et enregistre les données de traçabilité automatiquement",
        "Alertes qualité IA : détecter une non-conformité avant le contrôle",
        "Intégration traçabilité IA avec vos ERP agroalimentaires",
      ],
    },
    variables: {
      process: "traçabilité et documentation réglementaire",
      resultat: "0 saisie manuelle traçabilité",
      chiffre: "100",
      unite: "% automatisé",
      delai: "en 8 semaines",
    },
    urlCible: "/fr/secteurs/agroalimentaire",
    canonicalParent: "/fr/secteurs/agroalimentaire",
    source: "manuel",
  },
  {
    keyword: "formation IA industrie agroalimentaire",
    intent: "sectoriel",
    kbType: "intervention_module",
    module: "interventions-formations",
    cible: "pme",
    secteur: "agroalimentaire-igp",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Formation IA pour l'industrie agroalimentaire : opérateurs, responsables qualité et direction",
      metaTitle: "Formation IA industrie agroalimentaire — Axion-IA France",
      metaDescription:
        "Formation IA sur mesure pour les acteurs agroalimentaires : traçabilité, qualité, commercial, admin. Présentiel en usine, cas métier réels.",
      h2Variants: [
        "Programme formation IA agroalimentaire — niveaux et durées",
        "IA et HACCP : comment l'IA accélère la mise en conformité",
        "Certification post-formation et suivi terrain",
      ],
    },
    variables: {
      process: "montée en compétence IA équipes agro",
      resultat: "équipes opérationnelles en 2 jours",
      chiffre: "2",
      unite: "jours",
      delai: "dès la formation",
    },
    urlCible: "/fr/interventions-formations/agroalimentaire",
    canonicalParent: "/fr/interventions-formations",
    source: "manuel",
  },
  {
    keyword: "intelligence artificielle filière agricole",
    intent: "sectoriel",
    kbType: "industry_use_case",
    module: "transversal",
    cible: "pme",
    secteur: "agriculture-elevage",
    priorite: 3,
    niveau: 3,
    injection: {
      h1: "Intelligence artificielle et filières agricoles françaises : état de l'art 2026",
      metaTitle: "Intelligence artificielle filière agricole 2026 — Axion-IA",
      metaDescription:
        "Comment l'IA transforme les coopératives, exploitations et filières agricoles françaises. Usages concrets, acteurs, ROI. Guide Axion-IA.",
      h2Variants: [
        "IA et agriculture de précision : quels usages pour les filières ?",
        "Coopératives agricoles et IA : exemples français 2026",
        "IA et PAC : automatiser les déclarations et aides agricoles",
      ],
    },
    urlCible: "/fr/secteurs/agroalimentaire",
    canonicalParent: "/fr/secteurs/agroalimentaire",
    source: "manuel",
  },
  {
    keyword: "agence IA agroalimentaire PME",
    intent: "sectoriel",
    kbType: "secteur_brief",
    module: "transversal",
    cible: "pme",
    secteur: "agroalimentaire-igp",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Axion-IA, le cabinet IA expert secteur agroalimentaire",
      metaTitle: "Agence IA agroalimentaire PME — Axion-IA France",
      metaDescription:
        "Axion-IA accompagne les PME agroalimentaires dans l'adoption de l'IA : audit, formation, implémentation traçabilité et qualité. Résultats mesurés.",
      h2Variants: [
        "Nos déploiements IA dans l'industrie agroalimentaire française",
        "Services IA pour PME agroalimentaires de 20 à 500 salariés",
        "Pourquoi un cabinet IA spécialisé agroalimentaire fait la différence",
      ],
    },
    urlCible: "/fr/secteurs/agroalimentaire",
    canonicalParent: "/fr/secteurs",
    source: "manuel",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// COACHING 1-TO-1 (10 seeds)
// URL cible : /fr/coaching-1-to-1 | /fr/coaching-1-to-1/dirigeants
// module="coaching-1-to-1", intent="sectoriel" (profil cible dirigeant)
// ─────────────────────────────────────────────────────────────────────────────

export const KW_COACHING_G6: KeywordSeed[] = [
  {
    keyword: "coaching IA dirigeant PME France",
    intent: "sectoriel",
    kbType: "metier_brief",
    module: "coaching-1-to-1",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Coaching IA pour dirigeant de PME : maîtriser l'IA en 4 séances individuelles",
      metaTitle: "Coaching IA dirigeant PME France — Axion-IA",
      metaDescription:
        "Coaching IA 1-to-1 pour dirigeants de PME : comprendre, choisir et déployer l'IA dans votre entreprise. 4 séances personnalisées avec un expert Axion-IA.",
      h2Variants: [
        "Programme coaching IA dirigeant PME — 4 séances clés",
        "Ce qu'un dirigeant apprend en coaching IA individuel",
        "Résultats : ce que nos dirigeants coachés accomplissent en 30 jours",
      ],
    },
    variables: {
      process: "acculturation et déploiement IA dirigeant",
      resultat: "1er projet IA lancé en 30 jours",
      chiffre: "30",
      unite: "jours",
      delai: "dès la 1re séance",
    },
    urlCible: "/fr/coaching-1-to-1/dirigeants",
    canonicalParent: "/fr/coaching-1-to-1",
    source: "manuel",
    note: "schema.org: EducationEvent + Person (coach) ; mots secondaires : accompagnement IA dirigeant, coach IA PME",
  },
  {
    keyword: "coaching individuel IA CEO PME",
    intent: "sectoriel",
    kbType: "metier_brief",
    module: "coaching-1-to-1",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    injection: {
      h1: "Coaching IA individuel pour CEO de PME : de zéro à stratège IA en 4 semaines",
      metaTitle: "Coaching individuel IA CEO PME — Axion-IA",
      metaDescription:
        "Coaching 1-to-1 exclusif pour CEO de PME : stratégie IA, cas d'usage prioritaires, pilotage équipe. Séances hebdomadaires avec un expert Axion-IA.",
      h2Variants: [
        "Profil idéal : quel CEO tire le plus du coaching IA individuel ?",
        "Séances de coaching IA CEO : format et contenu",
        "ROI du coaching IA CEO : témoignages et résultats mesurés",
      ],
    },
    variables: {
      process: "stratégie IA et leadership",
      resultat: "roadmap IA validée en 4 semaines",
      chiffre: "4",
      unite: "semaines",
      delai: "dès la 1re séance",
    },
    urlCible: "/fr/coaching-1-to-1/dirigeants",
    canonicalParent: "/fr/coaching-1-to-1",
    source: "manuel",
  },
  {
    keyword: "accompagnement IA dirigeant 1 pour 1",
    intent: "sectoriel",
    kbType: "metier_brief",
    module: "coaching-1-to-1",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    injection: {
      h1: "Accompagnement IA 1 pour 1 pour dirigeants : votre expert IA dédié, votre agenda",
      metaTitle: "Accompagnement IA dirigeant 1 pour 1 — Axion-IA",
      metaDescription:
        "Un expert IA Axion-IA dédié uniquement à vous : sessions à la demande, suivi continu, décisions IA éclairées. Formule 1-to-1 premium pour dirigeants.",
      h2Variants: [
        "En quoi l'accompagnement IA 1 pour 1 diffère d'une formation",
        "Votre expert IA dédié : profil et méthode de travail",
        "Formules et tarifs accompagnement IA dirigeant 1-to-1",
      ],
    },
    urlCible: "/fr/coaching-1-to-1/dirigeants",
    canonicalParent: "/fr/coaching-1-to-1",
    source: "manuel",
  },
  {
    keyword: "formation personnalisée IA dirigeant",
    intent: "sectoriel",
    kbType: "intervention_module",
    module: "coaching-1-to-1",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Formation personnalisée IA pour dirigeant : sur mesure, sans parcours standard",
      metaTitle: "Formation personnalisée IA dirigeant — Axion-IA",
      metaDescription:
        "Formation IA sur mesure pour dirigeants : contenu adapté à votre secteur, vos enjeux et votre niveau. Par Axion-IA, cabinet IA B2B France.",
      h2Variants: [
        "Comment personnaliser une formation IA pour un dirigeant ?",
        "Différence entre formation catalogue et formation IA sur mesure",
        "Exemples de contenus formation IA dirigeant par secteur",
      ],
    },
    variables: {
      process: "formation IA personnalisée dirigeant",
      resultat: "100 % adapté à votre contexte",
      chiffre: "100",
      unite: "%",
      delai: "dès la 1re séance",
    },
    urlCible: "/fr/coaching-1-to-1/dirigeants",
    canonicalParent: "/fr/coaching-1-to-1",
    source: "manuel",
  },
  {
    keyword: "coach IA dirigeant d'entreprise France",
    intent: "sectoriel",
    kbType: "metier_brief",
    module: "coaching-1-to-1",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    injection: {
      h1: "Votre coach IA : un expert Axion-IA dédié à votre transformation digitale",
      metaTitle: "Coach IA dirigeant d'entreprise France — Axion-IA",
      metaDescription:
        "Axion-IA met à votre disposition un coach IA expert pour vous guider dans l'adoption de l'IA : stratégie, cas d'usage, déploiement, mesure ROI.",
      h2Variants: [
        "Profil de votre coach IA Axion-IA : expertise et méthode",
        "Comment se déroule une séance de coaching IA dirigeant ?",
        "Coach IA vs consultant IA : quelle différence pour un dirigeant ?",
      ],
    },
    urlCible: "/fr/coaching-1-to-1",
    canonicalParent: "/fr/coaching-1-to-1",
    source: "manuel",
    note: "schema.org: Person (expert coach) + Service ; positionnement personnel fort",
  },
  {
    keyword: "comment un dirigeant de PME apprend l'IA ?",
    intent: "sectoriel",
    kbType: "faq",
    module: "coaching-1-to-1",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Comment un dirigeant de PME apprend-il vraiment l'IA ? 4 chemins comparés",
      metaTitle: "Comment un dirigeant PME apprend l'IA ? — Axion-IA",
      metaDescription:
        "Formation collective, MOOC, coaching 1-to-1, consultant : comparatif des 4 façons d'apprendre l'IA pour un dirigeant de PME. Guide Axion-IA.",
      h2Variants: [
        "MOOC IA vs coaching IA dirigeant : ce que vous apprenez vraiment",
        "Le coaching 1-to-1 : le format le plus adapté aux dirigeants de PME",
        "Combien de temps faut-il pour qu'un dirigeant maîtrise l'IA ?",
      ],
    },
    urlCible: "/fr/coaching-1-to-1/dirigeants",
    canonicalParent: "/fr/coaching-1-to-1",
    source: "manuel",
    note: "AEO fort ; schema.org FAQPage",
  },
  {
    keyword: "accompagnement IA 1-to-1 résultats",
    intent: "sectoriel",
    kbType: "case_study",
    module: "coaching-1-to-1",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Accompagnement IA 1-to-1 : résultats réels de nos dirigeants coachés",
      metaTitle: "Accompagnement IA 1-to-1 résultats — Axion-IA France",
      metaDescription:
        "Découvrez les résultats concrets obtenus par les dirigeants coachés par Axion-IA en 1-to-1 : projets IA lancés, heures économisées, CA impacté.",
      h2Variants: [
        "Études de cas : dirigeants PME coachés en IA 1-to-1",
        "KPIs mesurés post-coaching IA dirigeant",
        "Témoignages dirigeants : leur bilan après 4 séances coaching IA",
      ],
    },
    urlCible: "/fr/coaching-1-to-1/dirigeants",
    canonicalParent: "/fr/coaching-1-to-1",
    source: "manuel",
  },
  {
    keyword: "coaching IA ETI directeur général",
    intent: "sectoriel",
    kbType: "metier_brief",
    module: "coaching-1-to-1",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Coaching IA pour directeur général d'ETI : piloter la transformation IA à l'échelle",
      metaTitle: "Coaching IA ETI directeur général — Axion-IA",
      metaDescription:
        "Coaching IA 1-to-1 pour DG d'ETI : gouvernance IA, sélection prestataires, pilotage DSI, communication COMEX. Accompagnement Axion-IA niveau exécutif.",
      h2Variants: [
        "Enjeux IA spécifiques aux directeurs généraux d'ETI",
        "Comment piloter la transformation IA d'une ETI depuis la direction ?",
        "Coaching IA DG ETI : format, fréquence et livrables",
      ],
    },
    variables: {
      process: "pilotage transformation IA ETI",
      resultat: "feuille de route IA ETI validée en 6 semaines",
      chiffre: "6",
      unite: "semaines",
      delai: "dès le 1er mois",
    },
    urlCible: "/fr/coaching-1-to-1/dirigeants",
    canonicalParent: "/fr/coaching-1-to-1",
    source: "manuel",
  },
  {
    keyword: "séance coaching IA dirigeant tarif",
    intent: "sectoriel",
    kbType: "faq",
    module: "coaching-1-to-1",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Combien coûte une séance de coaching IA pour dirigeant ? Tarifs Axion-IA 2026",
      metaTitle: "Séance coaching IA dirigeant tarif — Axion-IA France",
      metaDescription:
        "Tarifs et formules de coaching IA 1-to-1 pour dirigeants par Axion-IA : séance unique, forfait 4 séances, accompagnement continu. Demandez un devis.",
      h2Variants: [
        "Formules et tarifs coaching IA dirigeant Axion-IA",
        "Séance découverte coaching IA dirigeant : ce qui est inclus",
        "ROI d'une séance de coaching IA : qu'est-ce que ça rapporte concrètement ?",
      ],
    },
    urlCible: "/fr/coaching-1-to-1",
    canonicalParent: "/fr/coaching-1-to-1",
    source: "manuel",
    note: "intent transactionnel / AEO ; schema.org PriceSpecification + FAQPage",
  },
  {
    keyword: "coach IA opérationnel France",
    intent: "sectoriel",
    kbType: "metier_brief",
    module: "coaching-1-to-1",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    injection: {
      h1: "Coach IA opérationnel en France : concret, mesurable, sans jargon inutile",
      metaTitle: "Coach IA opérationnel France — Axion-IA",
      metaDescription:
        "Le coaching IA Axion-IA est opérationnel : chaque séance produit un livrable actionnable. Pas de slides, pas de théorie creuse — des résultats terrain.",
      h2Variants: [
        "Ce qui distingue un coaching IA opérationnel d'une conférence",
        "Livrables de chaque séance coaching IA opérationnel",
        "Coach IA opérationnel vs consultant IA stratégique : quand choisir quoi ?",
      ],
    },
    urlCible: "/fr/coaching-1-to-1",
    canonicalParent: "/fr/coaching-1-to-1",
    source: "manuel",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT PRINCIPAL — KW_SECTORIELS_G6
// ─────────────────────────────────────────────────────────────────────────────

export const KW_SECTORIELS_G6: KeywordSeed[] = [
  ...KW_JURIDIQUE,
  ...KW_COMPTABILITE,
  ...KW_BTP,
  ...KW_IT,
  ...KW_RH,
  ...KW_COMMERCE,
  ...KW_SANTE,
  ...KW_AGRO,
];
