/**
 * Keywords Phase 2 Sprint Perfection 2026-05-22 — Verticale UN_A_UN (coaching 1-to-1)
 * 10 clusters × ~25 keywords = ~240 seeds
 */

import type { KeywordSeed } from "./types";

type SC = Omit<KeywordSeed, "injection" | "kbType">;
function s(seed: SC): KeywordSeed {
  const full: Record<string, unknown> = { ...seed, kbType: "competence_boost", injection: {} };
  return full as unknown as KeywordSeed;
}

// ── CLUSTER 1 : coaching-ia-ceo ───────────────────────────────────────────────
const COACH_CEO: KeywordSeed[] = [
  s({
    keyword: "coaching IA personnalisé CEO dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement IA individuel PDG France",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching stratégique intelligence artificielle PDG",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "executive briefing IA pour PDG PME",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "mentor IA dirigeant entreprise France",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "consultant IA personnel CEO monthly coaching",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "comment un CEO peut se former à l'IA sans y passer des heures ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "qu'est-ce qu'un coaching IA pour dirigeant ?",
    module: "coaching-1-to-1",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "programme coaching IA CEO en 3 mois résultats",
    module: "coaching-1-to-1",
    intent: "featured_snippet",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA CEO vs formation IA dirigeants différences",
    module: "coaching-1-to-1",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "gains coaching IA PDG prise de décision 40 % plus rapide",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
];

// ── CLUSTER 2 : coaching-ia-pme ───────────────────────────────────────────────
const COACH_PME: KeywordSeed[] = [
  s({
    keyword: "coaching IA dirigeant PME accompagnement individuel",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement IA personnalisé chef entreprise PME",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coach IA PME France mensuel",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "comment accélérer sa transformation IA en tant que PME ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "avantages coaching IA PME vs formation collective",
    module: "coaching-1-to-1",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "résultats coaching IA PME témoignages cas concrets",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
];

// ── CLUSTER 3 : coaching-ia-comex ─────────────────────────────────────────────
const COACH_COMEX: KeywordSeed[] = [
  s({
    keyword: "coaching IA comité de direction COMEX",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/comex",
  }),
  s({
    keyword: "sensibilisation IA membres comité de direction",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/comex",
  }),
  s({
    keyword: "accompagnement IA individuel DG DGA CFO",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/comex",
  }),
  s({
    keyword: "comment aligner le COMEX sur la stratégie IA ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "grand-compte",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/comex",
  }),
  s({
    keyword: "programme coaching IA COMEX 6 séances",
    module: "coaching-1-to-1",
    intent: "featured_snippet",
    cible: "grand-compte",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/comex",
  }),
];

// ── CLUSTER 4 : mentoring-cto ─────────────────────────────────────────────────
const COACH_CTO: KeywordSeed[] = [
  s({
    keyword: "mentoring IA CTO directeur technique",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/cto",
  }),
  s({
    keyword: "coaching IA directeur technique architecture LLM",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/cto",
  }),
  s({
    keyword: "accompagnement CTO stratégie IA infrastructure",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/cto",
  }),
  s({
    keyword: "comment un CTO doit structurer sa roadmap IA ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/cto",
  }),
  s({
    keyword: "définition mentoring IA CTO programme spécialisé",
    module: "coaching-1-to-1",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/cto",
  }),
];

// ── CLUSTER 5 : coaching-transformation-digitale ──────────────────────────────
const COACH_TRANSFORM: KeywordSeed[] = [
  s({
    keyword: "coaching transformation digitale IA dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/transformation",
  }),
  s({
    keyword: "accompagnement transformation IA individuel PME",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 1,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/transformation",
  }),
  s({
    keyword: "consultant transformation IA entreprise personnalisé",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/transformation",
  }),
  s({
    keyword: "comment réussir sa transformation IA en 6 mois ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/transformation",
  }),
  s({
    keyword: "étapes transformation IA entreprise en 5 phases",
    module: "coaching-1-to-1",
    intent: "featured_snippet",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/transformation",
  }),
  s({
    keyword: "coaching transformation IA vs consulting IA comparatif",
    module: "coaching-1-to-1",
    intent: "commercial_investigation",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/transformation",
  }),
  s({
    keyword: "résultats mesurables transformation IA accompagnée",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/transformation",
  }),
];

// ── CLUSTER 6 : ia-literacy-dirigeants ───────────────────────────────────────
const COACH_LITERACY: KeywordSeed[] = [
  s({
    keyword: "AI literacy dirigeants France programme",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/ai-literacy",
  }),
  s({
    keyword: "maîtrise intelligence artificielle dirigeant PME",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/ai-literacy",
  }),
  s({
    keyword: "comment développer son AI literacy en tant que dirigeant ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/ai-literacy",
  }),
  s({
    keyword: "définition AI literacy compétence dirigeant 2026",
    module: "coaching-1-to-1",
    intent: "ai_overview",
    cible: "toutes-cibles",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/ai-literacy",
  }),
  s({
    keyword: "niveaux AI literacy pour dirigeants grille évaluation",
    module: "coaching-1-to-1",
    intent: "featured_snippet",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/ai-literacy",
  }),
];

// ── CLUSTER 7 : strategie-ia-personnelle ─────────────────────────────────────
const COACH_STRATEGIE: KeywordSeed[] = [
  s({
    keyword: "stratégie IA personnalisée dirigeant accompagnement",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "construire sa stratégie IA PME sur mesure",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "plan IA personnalisé 12 mois pour dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "comment prioriser ses projets IA en tant que dirigeant ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "outils stratégiques IA pour dirigeants 2026",
    module: "coaching-1-to-1",
    intent: "informationnel",
    cible: "eti",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
];

// ── CLUSTER 8 : coaching-investissement-ia ────────────────────────────────────
const COACH_INVESTISSEMENT: KeywordSeed[] = [
  s({
    keyword: "coaching investissement IA budget PME",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/investissement",
  }),
  s({
    keyword: "quel budget allouer à l'IA pour mon entreprise ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/investissement",
  }),
  s({
    keyword: "retour investissement coaching IA dirigeant",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/investissement",
  }),
  s({
    keyword: "budget IA PME France recommandations 2026",
    module: "coaching-1-to-1",
    intent: "featured_snippet",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/investissement",
  }),
  s({
    keyword: "coaching IA Axion-IA tarif programme mensuel",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
];

// ── CLUSTER 9 : coaching-ia-startups ──────────────────────────────────────────
const COACH_STARTUP: KeywordSeed[] = [
  s({
    keyword: "coaching IA startup founder France",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/startup",
  }),
  s({
    keyword: "accompagnement IA fondateur scaleup tech",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants/startup",
  }),
  s({
    keyword: "comment intégrer l'IA dans sa startup rapidement ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/startup",
  }),
  s({
    keyword: "coaching IA startup vs incubateur tech différences",
    module: "coaching-1-to-1",
    intent: "commercial_investigation",
    cible: "startup-scaleup",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants/startup",
  }),
];

// ── CLUSTER 10 : suivi-mensuel-coaching ───────────────────────────────────────
const COACH_SUIVI: KeywordSeed[] = [
  s({
    keyword: "suivi mensuel IA dirigeant programme coaching",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA en ligne visio dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA présentiel Paris Lyon Bordeaux dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "comment se passe un coaching IA avec Axion-IA ?",
    module: "coaching-1-to-1",
    intent: "voice_search",
    cible: "pme",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "déroulement séance coaching IA dirigeant 3 étapes",
    module: "coaching-1-to-1",
    intent: "featured_snippet",
    cible: "eti",
    priorite: 2,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching IA mensuel vs ponctuel avantages inconvénients",
    module: "coaching-1-to-1",
    intent: "commercial_investigation",
    cible: "pme",
    priorite: 3,
    niveau: 3,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
];

export const KW_COACHING_CLUSTERS: KeywordSeed[] = [
  ...COACH_CEO,
  ...COACH_PME,
  ...COACH_COMEX,
  ...COACH_CTO,
  ...COACH_TRANSFORM,
  ...COACH_LITERACY,
  ...COACH_STRATEGIE,
  ...COACH_INVESTISSEMENT,
  ...COACH_STARTUP,
  ...COACH_SUIVI,
];
