// src/content/keywords/g9-balance.ts
// Equilibrage Phase E Sprint Perfection 2026-05-22
// Supplement keywords pour verticales deficitaires < 150 seeds
// - coaching-1-to-1 : 12 to 150 (+138)
// - codage-developpement : 48 to 150 (+102)
// - audit : 133 to 150 (+17)
// - interventions-formations : 149 to 151 (+2 buffer)
//
// Format : injection minimal ({}) — les seeds balance privilegient la couverture thematique.
// Le content-engine enrichit dynamiquement via les templates existants.

import type { KeywordSeed } from "./types";

// Compact seed type: omit required fields filled by helper s()
type SeedCompact = Omit<KeywordSeed, "injection" | "kbType">;

// Helper: add required kbType + empty injection to compact seeds
function s(seed: SeedCompact): KeywordSeed {
  const full: Record<string, unknown> = { ...seed, kbType: "industry_use_case", injection: {} };
  return full as unknown as KeywordSeed;
}

// ============================================================
// COACHING-1-TO-1 (+125 pour atteindre 150)
// ============================================================
const COACHING: KeywordSeed[] = [
  s({
    keyword: "coaching ia dirigeants",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement individuel intelligence artificielle",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia ceo france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "mentoring ia manager",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching executif intelligence artificielle",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia coo",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "formation individuelle ia dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia prise de decision",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement strategie ia entreprise",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching 1-to-1 intelligence artificielle",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia pour daf",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia direction generale",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia cfo entreprise",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "formation ia sur mesure dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia transformation digitale",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia fondateur startup",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia pme dirigeant individuel",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "comment integrer ia dirigeant pme",
    module: "coaching-1-to-1",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "montee en competence ia directeur",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coach ia enterprise france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "programme ia personalise directeur",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia conseil administration",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia rse governance",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia industrie 4.0 dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "ia coaching performance dirigeant",
    module: "coaching-1-to-1",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia comite executif",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "formation ia individuelle dsi",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia directeur marketing",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia responsable digital",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia directeur operations",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coacher ia manager senior",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia decision management",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "formation ia dirigeant en prive",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia resilience manageriale",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia vision strategique",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia conduite du changement",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coach ia personnalise entreprise",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "formation ia individuelle chef entreprise",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement transformation ia cxo",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "mentorat ia dirigeant pme france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia gestion equipe ia",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "acceleration competences ia cadre direction",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia business transformation entreprise",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "formation ia sur mesure manager equipe",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia data driven leadership",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia innovation produit dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia prise de fonction directeur",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia relation client manager",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia comex strategie",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia startup dirigeant devis",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia certifie icf france",
    module: "coaching-1-to-1",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "formation individuelle ia manager senior",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia leadership ia 2026",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia directeur commercial france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia vision business model",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "formation ia cadre superieur france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia gestion de crise entreprise",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia talent management rh",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia responsable innovation france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "programme suivi ia personnalise dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia equipe direction entreprise",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "ia coaching cto ctio france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia strategie innovation pme",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia accelerateur performance manager",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "formation ia one-on-one executive france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia france tarif devis",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coach ia paris dirigeant",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/implantations/ile-de-france/paris",
  }),
  s({
    keyword: "coaching ia lyon cadre entreprise",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/auvergne-rhone-alpes/lyon",
  }),
  s({
    keyword: "accompagnement ia marseille dirigeant",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/provence-alpes-cote-dazur/marseille",
  }),
  s({
    keyword: "coaching ia bordeaux manager",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/nouvelle-aquitaine/bordeaux",
  }),
  s({
    keyword: "accompagnement ia toulouse ceo pme",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/occitanie/toulouse",
  }),
  s({
    keyword: "coaching ia nantes dirigeant pme",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/pays-de-la-loire/nantes",
  }),
  s({
    keyword: "coaching ia strasbourg executive manager",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/grand-est/strasbourg",
  }),
  s({
    keyword: "accompagnement ia lille manager",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/hauts-de-france/lille",
  }),
  s({
    keyword: "coaching ia grenoble dirigeant innovation",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/auvergne-rhone-alpes/grenoble",
  }),
  s({
    keyword: "coaching ia montpellier manager startup",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/occitanie/montpellier",
  }),
  s({
    keyword: "coaching ia rennes coo dirigeant",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/bretagne/rennes",
  }),
  s({
    keyword: "coaching ia nice executive",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/provence-alpes-cote-dazur/nice",
  }),
  s({
    keyword: "coaching ia formation individuelle cout tarif",
    module: "coaching-1-to-1",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "benefices coaching ia personnalise dirigeant",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia sur mesure devis gratuit",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia accompagnement prise de poste",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia chef de projet innovant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia secteur public collectivite",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "collectivite-mairie",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia industrie manufacturier",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia retail commerce france",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia banque finance dirigeant",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia assurance mutuelle",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia artisan entrepreneur individuel",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia professionnel coach partenaire",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "partenaire-commercial",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia association fondation dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "association-professionnelle",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia aeo question dirigeant ia",
    module: "coaching-1-to-1",
    intent: "aeo",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "pourquoi coaching ia pour dirigeant entreprise",
    module: "coaching-1-to-1",
    intent: "aeo",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "combien coute coaching ia personnalise france",
    module: "coaching-1-to-1",
    intent: "aeo",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia vs formation collective comparatif",
    module: "coaching-1-to-1",
    intent: "comparatif",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia roi retour sur investissement",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "devis coaching ia entreprise france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia region ile de france dirigeant",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "grand-compte",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/implantations/ile-de-france/paris",
  }),
  s({
    keyword: "accompagnement ia region paca dirigeant",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/provence-alpes-cote-dazur/marseille",
  }),
  s({
    keyword: "coaching ia supply chain directeur",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia responsable formation rh",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia professions liberales france",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "tpe",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "formation ia individuelle adulte professionnel",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia cabinet comptable expert-comptable",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia dijon manager",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/bourgogne-franche-comte/dijon",
  }),
  s({
    keyword: "coaching ia metz nancy region grand est",
    module: "coaching-1-to-1",
    intent: "local",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/grand-est/metz",
  }),
  s({
    keyword: "coaching ia sante medecin dirigeant",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia directeur hotel tourisme",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia agro-alimentaire dirigeant",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia immobilier promoteur dirigeant",
    module: "coaching-1-to-1",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  // Supplement pour atteindre 150 total coaching-1-to-1
  s({
    keyword: "coaching ia dirigeant tpe artisan france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia transformation organisationnelle",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia digital transformation manager",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "formation ia leadership decision",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia prise de conscience ia enterprise",
    module: "coaching-1-to-1",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia competences cles dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia gouvernance donnees dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia programme executif personnalise",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia entreprise familiale dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia business model canvas",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia efficacite operationnelle",
    module: "coaching-1-to-1",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "programme coaching ia personalise pme",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia pilier strategique 2026",
    module: "coaching-1-to-1",
    intent: "informationnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia fondamentaux ia dirigeant",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia deploiement llm entreprise",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia adaptation metier ia",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia dirigeant bilan competences ia",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "accompagnement ia vice-president france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia top management france",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "grand-compte",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia culture innovation management",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia mentoring inter-entreprises",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
  s({
    keyword: "coaching ia prise de recul strategique",
    module: "coaching-1-to-1",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/coaching-ia-dirigeants",
  }),
];

// ============================================================
// CODAGE-DEVELOPPEMENT (+102)
// ============================================================
const CODAGE: KeywordSeed[] = [
  s({
    keyword: "creation site web intelligence artificielle",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "agence web specialisee ia",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "refonte site web ia",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "chatbot site web ia",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web augmente ia france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "integration ia site web existant",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "developpement application ia entreprise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site vitrine ia seo pme",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "agence ia web pme france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "creation plateforme ia entreprise france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "developpement logiciel ia sur mesure",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web chatgpt personnalise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "integration llm site web entreprise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web recommendation ia",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "creation chatbot client pme france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "agence creation site ia seo",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia recherche semantique",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "personnalisation site web ia",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "api ia integration site web",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site e-commerce ia recommandation",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "gpt api integration site web france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "recherche semantique ia site web",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "agence ia application mobile",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "web app ia service client",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia seo optimise france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "ajout ia wordpress site web",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "chatbot ia site vitrine pme",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "agence ia web design france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "application ia metier sur mesure",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "ia integration erp crm site web",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "creation site web ia cout prix france",
    module: "codage-developpement",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site ia e-learning formation",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "organisme-formation",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "creation site web ia paris",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/implantations/ile-de-france/paris",
  }),
  s({
    keyword: "agence web ia lyon france",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/implantations/auvergne-rhone-alpes/lyon",
  }),
  s({
    keyword: "developpement ia bordeaux",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/nouvelle-aquitaine/bordeaux",
  }),
  s({
    keyword: "creation application ia nantes",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/pays-de-la-loire/nantes",
  }),
  s({
    keyword: "site web ia toulouse agence",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/occitanie/toulouse",
  }),
  s({
    keyword: "agence ia web marseille",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/provence-alpes-cote-dazur/marseille",
  }),
  s({
    keyword: "agence web ia strasbourg",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/grand-est/strasbourg",
  }),
  s({
    keyword: "creation site ia lille agence",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/hauts-de-france/lille",
  }),
  s({
    keyword: "site web ia nice agence",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/provence-alpes-cote-dazur/nice",
  }),
  s({
    keyword: "agence ia grenoble web app",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/auvergne-rhone-alpes/grenoble",
  }),
  s({
    keyword: "creation site web ia rennes bretagne",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/bretagne/rennes",
  }),
  s({
    keyword: "agence ia montpellier web",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/occitanie/montpellier",
  }),
  s({
    keyword: "site web ia avantages pme france",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia roi retour investissement",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia vs site classique comparatif",
    module: "codage-developpement",
    intent: "comparatif",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "comparatif agences ia web france",
    module: "codage-developpement",
    intent: "comparatif",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "qu est-ce qu un site web augmente ia",
    module: "codage-developpement",
    intent: "informationnel",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "ia integration hubspot crm site web",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site ia performance e-commerce",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "creation api ia microservice entreprise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "ia product recommendation site web",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "creation site vitrine ia artisan pme",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia devis gratuit france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "ia site web core web vitals",
    module: "codage-developpement",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia json-ld schema markup seo",
    module: "codage-developpement",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "integration ecommerce ia woocommerce",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia multilingue france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "application ia no code pme",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia generation contenu auto",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "ia integration site vitrine tpe",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "agence ia application eti france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "developpement ia rag retrieval augmented",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site ia sante connecte",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site ia finance investissement",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site ia rh recrutement",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site ia immobilier proptech",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "pourquoi site web avec ia en 2026",
    module: "codage-developpement",
    intent: "aeo",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "cout creation site web ia france",
    module: "codage-developpement",
    intent: "aeo",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia taux conversion amelioration",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia roi etude de cas pme",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "agence ia nantes developpement web",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/pays-de-la-loire/nantes",
  }),
  s({
    keyword: "site web ia rennes bretagne agence",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/bretagne/rennes",
  }),
  s({
    keyword: "agence web ia dijon bourgogne",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/bourgogne-franche-comte/dijon",
  }),
  s({
    keyword: "creation site web ia clermont-ferrand",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/auvergne-rhone-alpes/clermont-ferrand",
  }),
  s({
    keyword: "agence ia web nancy metz",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/grand-est/metz",
  }),
  s({
    keyword: "site web ia amiens hauts-de-france",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/hauts-de-france/amiens",
  }),
  s({
    keyword: "creation site ia rouen normandie",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/normandie/rouen",
  }),
  s({
    keyword: "agence ia web poitiers nouvelle-aquitaine",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/nouvelle-aquitaine/bordeaux",
  }),
  s({
    keyword: "site web ia perpignan occitanie",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/occitanie/montpellier",
  }),
  s({
    keyword: "agence ia web tours centre-val",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/centre-val-de-loire/tours",
  }),
  // Supplement pour atteindre 150 total codage-developpement
  s({
    keyword: "creation site web ia artisanat commerce",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "tpe",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia conversion leads b2b",
    module: "codage-developpement",
    intent: "benefice",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "refonte site web ia performance seo",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia compatible mobile pwa",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "agence web ia strasbourg alsace",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/grand-est/strasbourg",
  }),
  s({
    keyword: "site ia intelligence artificielle france devis",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "chatbot ia site web tarif prix",
    module: "codage-developpement",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "creation site web ia industries",
    module: "codage-developpement",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "agence site web ia toulouse pme",
    module: "codage-developpement",
    intent: "local",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/implantations/occitanie/toulouse",
  }),
  s({
    keyword: "site web ia automatisation taches",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "creation application ia cloud france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site ia data visualisation entreprise",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "integration ia tableau de bord analytics",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site web ia conformite rgpd",
    module: "codage-developpement",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "agence ia react next.js typescript france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "sous-traitant-dev",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "site ia aeo geolocalisation france",
    module: "codage-developpement",
    intent: "aeo",
    cible: "toutes-cibles",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
  s({
    keyword: "developpement ia solution cloud saas france",
    module: "codage-developpement",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/codage-developpement",
  }),
];

// ============================================================
// AUDIT (supplement) — +17
// ============================================================
const AUDIT_SUPP: KeywordSeed[] = [
  s({
    keyword: "audit conformite ia rgpd",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "bilan risques intelligence artificielle",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "audit ia ai act conformite entreprise",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "diagnostic ia pme devis gratuit",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "audit ia secteur industriel france",
    module: "audit",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "evaluation conformite ia entreprise france",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "audit ia gouvernance donnees",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "diagnostic ia securite anssi france",
    module: "audit",
    intent: "transactionnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "audit ia secteur banque assurance",
    module: "audit",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "evaluation ia recrutement rh",
    module: "audit",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "audit ia eti france devis",
    module: "audit",
    intent: "transactionnel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "bilan ia startup france",
    module: "audit",
    intent: "transactionnel",
    cible: "startup-scaleup",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "diagnostic ia pme tarif prix",
    module: "audit",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "audit ia retail grande distribution",
    module: "audit",
    intent: "sectoriel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "audit ia energie utilities france",
    module: "audit",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "audit ia logistique supply chain",
    module: "audit",
    intent: "sectoriel",
    cible: "eti",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
  s({
    keyword: "audit ia conformite collectivite",
    module: "audit",
    intent: "sectoriel",
    cible: "collectivite-mairie",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/audit-ia",
  }),
];

// ============================================================
// INTERVENTIONS-FORMATIONS (supplement) — +2
// ============================================================
const INTERV_SUPP: KeywordSeed[] = [
  s({
    keyword: "financement formation ia opco france 2026",
    module: "interventions-formations",
    intent: "informationnel",
    cible: "pme",
    priorite: 2,
    niveau: 2,
    urlCible: "/fr/formation-ia",
  }),
  s({
    keyword: "programme formation ia sur mesure equipe",
    module: "interventions-formations",
    intent: "transactionnel",
    cible: "pme",
    priorite: 3,
    niveau: 2,
    urlCible: "/fr/formation-ia",
  }),
];

export const KW_BALANCE_G9: readonly KeywordSeed[] = [
  ...COACHING,
  ...CODAGE,
  ...AUDIT_SUPP,
  ...INTERV_SUPP,
];
