// src/content/keywords/g9-balance.ts
// Équilibrage Phase E Sprint Perfection 2026-05-22
// Supplément keywords pour verticales déficitaires < 150 seeds
// - coaching-1-to-1 : 12 → 150 (+138)
// - codage-developpement : 48 → 150 (+102)
// - audit : 133 → 150 (+17)
// - interventions-formations : 149 → 151 (+2, buffer)

import type { KeywordSeed } from "./types";

export const KW_BALANCE_G9: readonly KeywordSeed[] = [
  // ============================================================
  // COACHING-1-TO-1 (coaching individuel IA, dirigeants) — +138
  // ============================================================
  { keyword: "coaching ia dirigeants", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 90, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement individuel intelligence artificielle", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 70, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia ceo france", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 50, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "mentoring ia manager", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 40, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching executif intelligence artificielle", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 60, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia coo", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 30, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "formation individuelle ia dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 45, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia prise de decision", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement strategie ia entreprise", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 55, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching 1-to-1 intelligence artificielle", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia pour daf", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia direction generale", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 30, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia cfo entreprise", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "formation ia sur mesure dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 40, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia transformation digitale dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia fondateur startup", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 45, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia pme dirigeant individuel", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "comment integrer ia en tant que dirigeant", module: "coaching-1-to-1", intent: "informationnel", cible: "dirigeants", volume: 60, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia strategie reorientation metier", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "montee en competence ia personnalisee directeur", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coach ia enterprise france", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "programme ia personalise directeur", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia conseil administration", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia rse governance", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia industrie 4.0 dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "why ia coaching ceo beneficial", module: "coaching-1-to-1", intent: "informationnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "ia coaching performance dirigeant etude", module: "coaching-1-to-1", intent: "informationnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia comite executif", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "formation ia individuelle dsi", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia directeur marketing", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia responsable digital", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia directeur operations", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coacher ia manager senior", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia rh directeur", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia decision management", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "ia coaching dirigeant gouvernance", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia conseil operationnel", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "formation ia en privé dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia résilience managériale", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia vision strategique", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia conduite du changement", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "ia coach prise en main direction", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coach ia personnalisé entreprise", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "formation ia individuelle chef entreprise", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia operationnel décideur", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement transformation ia cxo", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "mentorat ia dirigeant pme france", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia gestion equipe", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "acceleration competences ia cadre direction", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia business transformation", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "formation ia sur mesure manager", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia data driven decision", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia risque management", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia innovation produit", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia pilotage performance", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia etl director", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia prise de fonction dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia gestion budgetaire ia", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia relation client", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia secteur public dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia comex", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia startup scale-up dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia debutant dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia certifié icf", module: "coaching-1-to-1", intent: "informationnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia industriel dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "formation individuelle intelligence artificielle manager", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia dirigeant association", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia direction juridique", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia impact emploi manager", module: "coaching-1-to-1", intent: "informationnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia vision long terme", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia compétences numeriques manager", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia leadership", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 35, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia cadre bancaire", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia industriel manager", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia dirigeant secteur sante", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia directeur commercial", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia vision business model", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia responsable achats", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "formation ia cadre superieur", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia responsable formation", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia gestion de crise", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia manager fonctionnel", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "ia un pour un coaching business", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia prospective metier", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia projet agile manager", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia chef projet", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia supply chain directeur", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia compliance manager", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia responsable qualite", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia talent management", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia directeur général delegue", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia responsable innovation", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "programme suivi ia personnalise", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia enjeux transformation", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia digital manager public", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "formation ia distanciel dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia directeur juridique compliance", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia cadre dirigeant benefice", module: "coaching-1-to-1", intent: "benefice", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia roi mesure", module: "coaching-1-to-1", intent: "benefice", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia experience personnalisee entreprise france", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia organisation", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia prise de risque calculé", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia equipe direction", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia programme cadre dirigeant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "ia coaching cto ctio", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia stratégie innovation", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia accelerateur performance", module: "coaching-1-to-1", intent: "benefice", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "formation ia one-on-one executive", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia france devis", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia directeur pme region", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia dirigeant province", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coach ia paris dirigeant", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 30, niveau: 2, priorite: 3, urlCible: "/fr/implantations/ile-de-france/paris" },
  { keyword: "coaching ia lyon cadre", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/implantations/auvergne-rhone-alpes/lyon" },
  { keyword: "accompagnement ia marseille dirigeant", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/implantations/provence-alpes-cote-dazur/marseille" },
  { keyword: "coaching ia bordeaux manager", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/implantations/nouvelle-aquitaine/bordeaux" },
  { keyword: "accompagnement ia toulouse ceo", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/implantations/occitanie/toulouse" },
  { keyword: "coaching ia nantes dirigeant", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/implantations/pays-de-la-loire/nantes" },
  { keyword: "coaching ia strasbourg executive", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/implantations/grand-est/strasbourg" },
  { keyword: "accompagnement ia lille manager", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/implantations/hauts-de-france/lille" },
  { keyword: "coaching ia rennes coo", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/implantations/bretagne/rennes" },
  { keyword: "coaching ia nice dirigeant", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/implantations/provence-alpes-cote-dazur/nice" },
  { keyword: "accompagnement ia montpellier manager", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/implantations/occitanie/montpellier" },
  { keyword: "coaching ia grenoble dirigeant", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/implantations/auvergne-rhone-alpes/grenoble" },
  { keyword: "accompagnement ia dijon ceo", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 5, niveau: 2, priorite: 2, urlCible: "/fr/implantations/bourgogne-franche-comte/dijon" },
  { keyword: "coaching ia metz nancy manager", module: "coaching-1-to-1", intent: "local", cible: "dirigeants", volume: 5, niveau: 2, priorite: 2, urlCible: "/fr/implantations/grand-est/metz" },
  { keyword: "coaching ia formation individuelle cout", module: "coaching-1-to-1", intent: "informationnel", cible: "dirigeants", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "benefices coaching ia personnalise dirigeant", module: "coaching-1-to-1", intent: "benefice", cible: "dirigeants", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia sur mesure devis", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 20, niveau: 2, priorite: 3, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "formation ia individuelle adulte professionnel", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "coaching ia accompagnement strategique prise de poste", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 10, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },
  { keyword: "accompagnement ia chef de projet innovant", module: "coaching-1-to-1", intent: "transactionnel", cible: "dirigeants", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/coaching-ia-dirigeants" },

  // ============================================================
  // CODAGE-DEVELOPPEMENT (sites web IA) — +102
  // ============================================================
  { keyword: "creation site web intelligence artificielle", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 80, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "agence web specialisee ia", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 70, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "refonte site web ia", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 60, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "chatbot site web ia", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 90, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "site web augmente ia france", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 50, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "integration ia site web", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 70, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "developpement application ia", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 80, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "site vitrine ia seo", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 50, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "agence ia web pme", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 60, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "creation plateforme ia entreprise", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "developpement logiciel ia sur mesure", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 60, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "site web chatgpt personnalise", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 50, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "ia content generator site web", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "integration llm site web", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web recommendation ia", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 45, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "creation chatbot client pme france", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 60, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "agence creation site ia seo", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 50, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia recherche semantique", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "personnalisation site web ia", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 45, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web avec llm integration", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "api ia site web", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "creation site web france ia axion", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site e-commerce ia recommandation", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 55, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "next.js ia integration", module: "codage-developpement", intent: "informationnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "gpt api integration site web france", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "recherche ia site web", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "agence ia application mobile", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 45, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "web app ia service client", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia seo optimise", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 50, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "ajout ia wordpress", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "chatbot ia site vitrine", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 45, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "agence ia web design france", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "application ia metier sur mesure", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 50, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia responsive", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "ia integration erp crm", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "intelligence artificielle developpeur freelance france", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia performance vitale", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "creation site web ia cout prix", module: "codage-developpement", intent: "informationnel", cible: "pme", volume: 45, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "ia cms site web", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "scraping ia site web", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "integration ia analytics", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia machine learning", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "ia backend service", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "webapp ia typescript react", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia b2b", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "creation site web ia immobilier", module: "codage-developpement", intent: "sectoriel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site ia finance comptabilite", module: "codage-developpement", intent: "sectoriel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia rh", module: "codage-developpement", intent: "sectoriel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "creation site web ia sante", module: "codage-developpement", intent: "sectoriel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site ia e-learning", module: "codage-developpement", intent: "sectoriel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "creation site web ia paris", module: "codage-developpement", intent: "local", cible: "pme", volume: 55, niveau: 2, priorite: 3, urlCible: "/fr/implantations/ile-de-france/paris" },
  { keyword: "agence web ia lyon", module: "codage-developpement", intent: "local", cible: "pme", volume: 40, niveau: 2, priorite: 3, urlCible: "/fr/implantations/auvergne-rhone-alpes/lyon" },
  { keyword: "developpement ia bordeaux", module: "codage-developpement", intent: "local", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/implantations/nouvelle-aquitaine/bordeaux" },
  { keyword: "creation application ia nantes", module: "codage-developpement", intent: "local", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/implantations/pays-de-la-loire/nantes" },
  { keyword: "site web ia toulouse", module: "codage-developpement", intent: "local", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/implantations/occitanie/toulouse" },
  { keyword: "agence ia web marseille", module: "codage-developpement", intent: "local", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/implantations/provence-alpes-cote-dazur/marseille" },
  { keyword: "agence web ia strasbourg", module: "codage-developpement", intent: "local", cible: "pme", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/implantations/grand-est/strasbourg" },
  { keyword: "creation site ia lille", module: "codage-developpement", intent: "local", cible: "pme", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/implantations/hauts-de-france/lille" },
  { keyword: "site web ia nice", module: "codage-developpement", intent: "local", cible: "pme", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/implantations/provence-alpes-cote-dazur/nice" },
  { keyword: "agence ia grenoble web", module: "codage-developpement", intent: "local", cible: "pme", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/implantations/auvergne-rhone-alpes/grenoble" },
  { keyword: "creation site web ia rennes", module: "codage-developpement", intent: "local", cible: "pme", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/implantations/bretagne/rennes" },
  { keyword: "agence ia montpellier web", module: "codage-developpement", intent: "local", cible: "pme", volume: 15, niveau: 2, priorite: 2, urlCible: "/fr/implantations/occitanie/montpellier" },
  { keyword: "site web ia avantages pme", module: "codage-developpement", intent: "benefice", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia roi retour investissement", module: "codage-developpement", intent: "benefice", cible: "pme", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia vs site classique", module: "codage-developpement", intent: "comparatif", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "comparatif agences ia web france", module: "codage-developpement", intent: "comparatif", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "creation site web ia prix tarif", module: "codage-developpement", intent: "informationnel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "qu est-ce qu un site web augmente ia", module: "codage-developpement", intent: "informationnel", cible: "toutes-cibles", volume: 45, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "benefices ia site web taux conversion", module: "codage-developpement", intent: "benefice", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "ia site web accessibilite rgpd", module: "codage-developpement", intent: "informationnel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "creation application ia no code", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia generation contenu", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "ia integration site vitrine tpe", module: "codage-developpement", intent: "transactionnel", cible: "tpe", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "agence ia web eti france", module: "codage-developpement", intent: "transactionnel", cible: "eti", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "creation site web ia b2c", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "developpement ia rag retrieval", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia devis gratuit", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 40, niveau: 2, priorite: 3, urlCible: "/fr/codage-developpement" },
  { keyword: "ia site web core web vitals", module: "codage-developpement", intent: "informationnel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia json-ld schema markup", module: "codage-developpement", intent: "informationnel", cible: "pme", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "ia integration hubspot crm site web", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site ia performance e-commerce", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "creation api ia microservice", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "ia product recommendation site web", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "creation site vitrine ia artisan pme", module: "codage-developpement", intent: "transactionnel", cible: "tpe", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia seo aeo geo best practices", module: "codage-developpement", intent: "informationnel", cible: "pme", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "ia site web roi etude de cas pme", module: "codage-developpement", intent: "benefice", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "integration ia site ecommerce woocommerce", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia stripe paiement integration", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },
  { keyword: "site web ia multilingue", module: "codage-developpement", intent: "transactionnel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/codage-developpement" },

  // ============================================================
  // AUDIT (supplément) — +17
  // ============================================================
  { keyword: "audit conformite ia rgpd", module: "audit", intent: "transactionnel", cible: "pme", volume: 70, niveau: 2, priorite: 3, urlCible: "/fr/audit-ia" },
  { keyword: "bilan risques intelligence artificielle", module: "audit", intent: "transactionnel", cible: "dirigeants", volume: 55, niveau: 2, priorite: 3, urlCible: "/fr/audit-ia" },
  { keyword: "audit ia ai act conformite entreprise", module: "audit", intent: "transactionnel", cible: "pme", volume: 60, niveau: 2, priorite: 3, urlCible: "/fr/audit-ia" },
  { keyword: "diagnostic ia pme devis", module: "audit", intent: "transactionnel", cible: "pme", volume: 45, niveau: 2, priorite: 3, urlCible: "/fr/audit-ia" },
  { keyword: "audit ia secteur industriel", module: "audit", intent: "sectoriel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },
  { keyword: "evaluation conformite ia france", module: "audit", intent: "transactionnel", cible: "pme", volume: 50, niveau: 2, priorite: 3, urlCible: "/fr/audit-ia" },
  { keyword: "audit ia gouvernance donnees", module: "audit", intent: "transactionnel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },
  { keyword: "diagnostic ia securite anssi", module: "audit", intent: "transactionnel", cible: "pme", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },
  { keyword: "audit ia secteur banque assurance", module: "audit", intent: "sectoriel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },
  { keyword: "evaluation ia rh recrutement", module: "audit", intent: "sectoriel", cible: "rh", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },
  { keyword: "audit ia eti france", module: "audit", intent: "transactionnel", cible: "eti", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },
  { keyword: "bilan ia startup devis", module: "audit", intent: "transactionnel", cible: "pme", volume: 30, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },
  { keyword: "audit ia responsabilite donnees dpo", module: "audit", intent: "transactionnel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },
  { keyword: "diagnostic intelligence artificielle pme tarif", module: "audit", intent: "informationnel", cible: "pme", volume: 35, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },
  { keyword: "audit ia retail grande distribution", module: "audit", intent: "sectoriel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },
  { keyword: "audit ia energie utilities", module: "audit", intent: "sectoriel", cible: "pme", volume: 20, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },
  { keyword: "audit ia logistique supply chain", module: "audit", intent: "sectoriel", cible: "pme", volume: 25, niveau: 2, priorite: 2, urlCible: "/fr/audit-ia" },

  // ============================================================
  // INTERVENTIONS-FORMATIONS (supplément) — +2
  // ============================================================
  { keyword: "formation ia financement opco france 2026", module: "interventions-formations", intent: "informationnel", cible: "pme", volume: 40, niveau: 2, priorite: 2, urlCible: "/fr/formation-ia" },
  { keyword: "programme formation ia sur mesure equipe", module: "interventions-formations", intent: "transactionnel", cible: "pme", volume: 45, niveau: 2, priorite: 3, urlCible: "/fr/formation-ia" },
];
