import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { ArrowRight, ArrowUpRight, HelpCircle, LayoutGrid, Mic, ShieldCheck } from "lucide-react";
import { routing, STATIC_LOCALES, type Locale } from "@/i18n/routing";
import { Section } from "@/components/layout/Section";
import { Container } from "@/components/layout/Container";
import { Cta } from "@/components/marketing/Cta";
import { FaqBlock } from "@/components/sections/FaqBlock";
import { CtaBlock } from "@/components/sections/CtaBlock";
import { FaqRelatedResources } from "@/components/sections/FaqRelatedResources";
import { FaqHeroImage } from "@/components/sections/FaqHeroImage";
import { JsonLd } from "@/components/marketing/JsonLd";
import { Breadcrumbs } from "@/components/nav/Breadcrumbs";
import {
  buildProductMetadata,
  buildItemListJsonLd,
  buildFaqJsonLd,
  buildCollectionPageJsonLd,
  buildPageImageGraphJsonLd,
  buildPrimaryImageOfPage,
  SITE_URL,
} from "@/lib/seo";
import { listFaqs, listFaqsByCategory, type FaqItem } from "@/lib/knowledge/readers";
import { getFaqCategory, getAllFaqCategorySlugs, FAQ_CATEGORIES } from "@/content/faq-categories";
import { FAQ_CATEGORY_ICONS, FAQ_CATEGORY_ICON_FALLBACK } from "@/content/faq-category-icons";

interface Props {
  params: Promise<{ locale: string; categorie: string }>;
}

// ISR 1h — aligné /faq (build SSG = stub.invalid → vide, repeuplé sous 1h).
export const revalidate = 3600;

// Seuil anti-thin (HCU 2024) : une catégorie avec moins de N Q/A indexables
// sort en `noindex,follow` (présente, maillée, mais pas exposée à l'index).
const MIN_INDEXABLE_ITEMS = 3;

// Cap JSON-LD — même valeur que le hub /faq (cap payload 2026-07-06).
const SCHEMA_MAX = 50;

// Corpus visible d'un hub thématique : Q/R éditoriales (Track A,
// `isAutoGenerated=false`) uniquement, repli sur les SCHEMA_MAX premières si la
// catégorie n'a que du contenu auto. Le corpus content-gen (1000+ Q/R par ville,
// catégorie « general » par défaut en DB) ne doit JAMAIS être rendu inline ni
// sérialisé en JSON-LD ici : le FAQPage de /faq/par-thematique/general pesait
// 504 KB (1160 Q/R), le parseur Google tronque vers ~450 K caractères → erreur
// GSC « Type de valeur incorrect » (2026-07-12), et le HTML atteignait 6,4 MB.
// Les Q/R auto restent servies par leurs pages dédiées /faq/[slug] et
// l'explorateur du hub /faq.
function visibleCategoryFaqs(faqs: readonly FaqItem[]): readonly FaqItem[] {
  const editorial = faqs.filter((f) => !f.isAutoGenerated);
  return editorial.length > 0 ? editorial : faqs.slice(0, SCHEMA_MAX);
}

export async function generateStaticParams() {
  return getAllFaqCategorySlugs().flatMap((categorie) =>
    STATIC_LOCALES.map((locale) => ({ locale, categorie })),
  );
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale, categorie } = await params;
  if (!hasLocale(routing.locales, locale)) return {};
  const cat = getFaqCategory(categorie);
  if (!cat) return {};
  const isFr = locale === "fr";
  const meta = buildProductMetadata({
    locale,
    path: `/faq/par-thematique/${categorie}`,
    title: isFr
      ? `FAQ ${cat.labelFr} · Questions fréquentes · Axion-IA`
      : `${cat.labelEn} FAQ · Frequently asked questions · Axion-IA`,
    description: isFr ? cat.descFr : cat.descEn,
  });
  const items = visibleCategoryFaqs(await listFaqsByCategory(categorie));
  if (items.length < MIN_INDEXABLE_ITEMS) {
    return { ...meta, robots: { index: false, follow: true } };
  }
  return meta;
}

export default async function FaqCategoryPage({ params }: Props) {
  const { locale, categorie } = await params;
  if (!hasLocale(routing.locales, locale)) notFound();
  const cat = getFaqCategory(categorie);
  if (!cat) notFound();
  setRequestLocale(locale);
  const loc = locale as Locale;
  const isFr = loc === "fr";
  const catLabel = isFr ? cat.labelFr : cat.labelEn;
  const catDesc = isFr ? cat.descFr : cat.descEn;
  const CatIcon = FAQ_CATEGORY_ICONS[categorie] ?? FAQ_CATEGORY_ICON_FALLBACK;

  // Q/A de la thématique + tout le corpus (pour les compteurs « autres thèmes »).
  const [faqs, allFaqs] = await Promise.all([listFaqsByCategory(categorie), listFaqs()]);
  const visible = visibleCategoryFaqs(faqs);
  const items = visible.map((entry) => ({
    id: entry.slug,
    question: isFr ? entry.questionFr : entry.questionEn,
    answer: isFr ? entry.answerFr : entry.answerEn,
  }));

  // Autres thématiques (maillage GEO) — exclut la catégorie courante, non vides.
  // Compteurs sur le corpus éditorial : cohérents avec ce que chaque hub affiche.
  const otherTopics = FAQ_CATEGORIES.filter((c) => c.slug !== categorie)
    .map((c) => ({
      slug: c.slug,
      label: isFr ? c.labelFr : c.labelEn,
      desc: isFr ? c.descFr : c.descEn,
      count: allFaqs.filter((f) => f.category === c.slug && !f.isAutoGenerated).length,
      Icon: FAQ_CATEGORY_ICONS[c.slug] ?? FAQ_CATEGORY_ICON_FALLBACK,
    }))
    .filter((c) => c.count > 0);

  const breadcrumbItems = [
    { href: "/faq", label: "FAQ" },
    { href: "/faq/par-thematique", label: isFr ? "Thématiques" : "Topics" },
    { href: `/faq/par-thematique/${categorie}`, label: catLabel },
  ];

  // ItemList JSON-LD — énumère les Q/A de la thématique (citabilité LLM),
  // plafonné à SCHEMA_MAX (celui de /general pesait 270 KB / 1160 entrées).
  const itemListJsonLd = buildItemListJsonLd({
    locale: loc,
    path: `/faq/par-thematique/${categorie}`,
    name: isFr ? `FAQ ${cat.labelFr} — Axion-IA` : `${cat.labelEn} FAQ — Axion-IA`,
    items: items.slice(0, SCHEMA_MAX).map((it, i) => ({
      url: `${SITE_URL}/${locale}/faq/${it.id}`,
      name: it.question,
      position: i + 1,
    })),
  });

  const primaryImage = buildPrimaryImageOfPage(`/faq/par-thematique/${categorie}`);
  const imageGraphJsonLd = buildPageImageGraphJsonLd({
    locale: loc,
    path: `/faq/par-thematique/${categorie}`,
  });
  const collectionPageJsonLd = buildCollectionPageJsonLd({
    locale: loc,
    path: `/faq/par-thematique/${categorie}`,
    name: isFr ? `FAQ ${cat.labelFr} — Axion-IA` : `${cat.labelEn} FAQ — Axion-IA`,
    description: catDesc,
    speakable: true,
    extra: {
      about: { "@id": `${SITE_URL}/#organization` },
      ...(primaryImage ? { primaryImageOfPage: primaryImage } : {}),
    },
  });

  const heroPills: ReadonlyArray<{ icon: typeof HelpCircle; label: string }> = [
    {
      icon: HelpCircle,
      label: isFr
        ? `${items.length} question${items.length > 1 ? "s" : ""}`
        : `${items.length} question${items.length > 1 ? "s" : ""}`,
    },
    { icon: Mic, label: "AEO speakable" },
    { icon: ShieldCheck, label: isFr ? "Source : doctrine" : "Source: doctrine" },
  ];

  return (
    <>
      <div className="bg-halo-warm">
        <Container className="pt-6">
          <Breadcrumbs items={breadcrumbItems} />
        </Container>
      </div>

      {/* ── HÉRO ─────────────────────────────────────────────────────────── */}
      <Section
        titleAs="h1"
        eyebrow={isFr ? "FAQ · Thématique" : "FAQ · Topic"}
        title={catLabel}
        description={catDesc}
        media={<FaqHeroImage slot={categorie} isFr={isFr} priority />}
      >
        <div className="flex flex-col gap-6">
          <div className="flex items-center gap-3">
            <span className="bg-terracotta/10 text-terracotta inline-flex h-12 w-12 items-center justify-center rounded-2xl">
              <CatIcon aria-hidden="true" className="h-6 w-6" strokeWidth={2} />
            </span>
            <ul role="list" className="flex flex-wrap gap-x-5 gap-y-2.5">
              {heroPills.map((pill) => {
                const Icon = pill.icon;
                return (
                  <li
                    key={pill.label}
                    className="text-fg-soft inline-flex items-center gap-2 text-sm"
                  >
                    <Icon aria-hidden="true" className="text-terracotta h-4 w-4" strokeWidth={2} />
                    <span>{pill.label}</span>
                  </li>
                );
              })}
            </ul>
          </div>
          <div className="flex flex-wrap items-center gap-4">
            {/* Chemins NUS : <Cta> passe par le Link next-intl, qui préfixe
                déjà le locale (GEO-013). */}
            <Cta href="/faq" size="lg">
              {isFr ? "Toutes les questions" : "All questions"}
              <ArrowRight className="h-4 w-4" aria-hidden="true" />
            </Cta>
            <Cta href="/faq/par-thematique" variant="outline" size="lg">
              {isFr ? "Toutes les thématiques" : "All topics"}
            </Cta>
          </div>
        </div>
      </Section>

      {/* ── QUESTIONS & RÉPONSES (inline, AEO — matche le FAQPage JSON-LD) ── */}
      {items.length > 0 ? (
        <FaqBlock
          items={items}
          eyebrow={isFr ? "Questions & réponses" : "Questions & answers"}
          title={isFr ? "Les réponses de la" : "Answers for the"}
          titleEm={isFr ? "thématique" : "topic"}
          description={
            isFr
              ? "Réponses directes, sourcées et régulièrement relues. Chaque question a aussi sa page dédiée."
              : "Direct, sourced and regularly reviewed answers. Each question also has its own dedicated page."
          }
          emitJsonLd={false}
          permalinkBase={`/${locale}/faq`}
          permalinkLabel={isFr ? "Page dédiée" : "Dedicated page"}
        />
      ) : (
        <Section tone="paper">
          <Container className="max-w-3xl">
            <p className="text-fg-soft">
              {isFr
                ? "Aucune question publiée pour cette thématique pour le moment."
                : "No published question for this topic yet."}
            </p>
          </Container>
        </Section>
      )}

      {/* ── EXPLORER LES AUTRES THÉMATIQUES (maillage GEO) ───────────────── */}
      {otherTopics.length > 0 ? (
        <Section
          id="autres-thematiques"
          tone="sand"
          eyebrow={isFr ? "Continuer" : "Keep going"}
          title={isFr ? "Explorer les autres" : "Explore the other"}
          titleEm={isFr ? "thématiques" : "topics"}
          description={
            isFr
              ? "D'autres familles de questions qui pourraient vous concerner."
              : "Other families of questions that might concern you."
          }
        >
          <ul role="list" className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {otherTopics.map((c) => (
              <li key={c.slug}>
                <a
                  href={`/${locale}/faq/par-thematique/${c.slug}`}
                  className="border-border bg-canvas shadow-subtle hover:border-terracotta/60 hover:shadow-elevated group flex h-full flex-col gap-3 rounded-2xl border p-6 transition hover:-translate-y-0.5"
                >
                  <div className="flex items-center justify-between gap-3">
                    <span className="bg-terracotta/10 text-terracotta inline-flex h-11 w-11 items-center justify-center rounded-xl">
                      <c.Icon aria-hidden="true" className="h-5 w-5" />
                    </span>
                    <span className="text-fg-muted text-xs font-medium tabular-nums">
                      {c.count} {isFr ? (c.count > 1 ? "questions" : "question") : "questions"}
                    </span>
                  </div>
                  <h3 className="text-fg group-hover:text-terracotta-deep flex items-start justify-between gap-2 text-lg font-semibold tracking-tight transition">
                    <span className="min-w-0">{c.label}</span>
                    <ArrowUpRight
                      aria-hidden="true"
                      className="text-fg-muted group-hover:text-terracotta mt-1 h-4 w-4 shrink-0 transition"
                    />
                  </h3>
                  <p className="text-fg-soft text-sm leading-relaxed">{c.desc}</p>
                </a>
              </li>
            ))}
          </ul>
          <div className="mt-8">
            <Cta href="/faq" variant="outline" size="md">
              <LayoutGrid className="h-4 w-4" aria-hidden="true" />
              {isFr ? "Voir toutes les questions" : "See all questions"}
            </Cta>
          </div>
        </Section>
      ) : null}

      {/* Maillage interne contextuel curé par catégorie (server, 0 JS). */}
      <FaqRelatedResources category={categorie} locale={locale} isFr={isFr} />

      {/* ── CTA FINAL ────────────────────────────────────────────────────── */}
      <CtaBlock
        tone="mocha"
        eyebrow={isFr ? "Une question non listée ?" : "Question not listed?"}
        title={isFr ? "Parlons de" : "Let's talk about"}
        titleEm={isFr ? "votre cas" : "your case"}
        description={
          isFr
            ? "Écrivez-nous à contact@axion-ia.com ou réservez un appel de 20 minutes : nous répondons précisément à votre contexte, sans engagement."
            : "Email us at contact@axion-ia.com or book a 20-minute call: we answer your exact context, no strings attached."
        }
        cta={
          <>
            <Cta href="/appel" variant="primary" size="xl" track="faq-cat-appel">
              {isFr ? "Réserver un appel" : "Book a call"}
              <ArrowRight aria-hidden="true" className="h-4 w-4" />
            </Cta>
            <Cta href="/contact" variant="outline" size="xl" track="faq-cat-contact">
              {isFr ? "Écrire un message" : "Send a message"}
            </Cta>
          </>
        }
      />

      <JsonLd data={itemListJsonLd} />
      <JsonLd data={collectionPageJsonLd} />
      {imageGraphJsonLd ? <JsonLd data={imageGraphJsonLd} /> : null}
      {/* FAQPage JSON-LD — émis UNIQUEMENT quand le hub est indexable (≥ seuil),
          jamais sur une page noindex thin (audit 2026-07-03). Un hub thématique
          (nombre raisonnable de Q/R) est le bon porteur d'un FAQPage — contrairement
          au hub /faq global (centaines de Q/R → speakable). Complète l'ItemList.
          Plafonné à SCHEMA_MAX (fix GSC « Type de valeur incorrect » 2026-07-12). */}
      {items.length >= MIN_INDEXABLE_ITEMS ? (
        <JsonLd data={buildFaqJsonLd({ items: items.slice(0, SCHEMA_MAX) })} />
      ) : null}
    </>
  );
}
