/**
 * Seeder image bank — 215 ImageAssets + translations FR
 * Régénéré 2026-07-03 depuis le reindex (_AUDIT/image-bank-reindex-2026-07/
 * 00-rename-manifest.json). Dimensions BAKÉES = mesurées sur les fichiers WebP
 * réels générés par scripts/image-bank/reindex-convert.cjs (la table DIMENSIONS
 * ne sert plus que de fallback si une entrée n'a pas width/height explicites).
 * Usage (depuis /app dans le container) :
 *   npx tsx prisma/seeds/image-bank/seed-images.ts
 * Idempotent (upsert par slug). NB : les slugs orphelins d'anciens seeds ne sont
 * PAS supprimés par cet upsert — voir _AUDIT/image-bank-reindex-2026-07/orphan-slugs.txt.
 */
import { PrismaClient } from "../../generated/client";

const prisma = new PrismaClient();

type ImageType =
  | "banniere"
  | "carre"
  | "affiche"
  | "infographie"
  | "editorial"
  | "photo"
  | "dataviz"
  | "logo";

const DIMENSIONS: Record<
  ImageType,
  { width: number; height: number; orientation: string; aspectRatio: string }
> = {
  banniere: { width: 1920, height: 1080, orientation: "landscape", aspectRatio: "16:9" },
  carre: { width: 1200, height: 1200, orientation: "square", aspectRatio: "1:1" },
  affiche: { width: 1080, height: 1920, orientation: "portrait", aspectRatio: "9:16" },
  infographie: { width: 1200, height: 1600, orientation: "portrait", aspectRatio: "3:4" },
  editorial: { width: 1200, height: 800, orientation: "landscape", aspectRatio: "3:2" },
  photo: { width: 1920, height: 1080, orientation: "landscape", aspectRatio: "16:9" },
  dataviz: { width: 1200, height: 900, orientation: "landscape", aspectRatio: "4:3" },
  logo: { width: 500, height: 200, orientation: "landscape", aspectRatio: "5:2" },
};

function detectType(slug: string): ImageType {
  if (slug.endsWith("-banniere") || slug.includes("-banniere-")) return "banniere";
  if (slug.endsWith("-carre") || slug.includes("-carre-")) return "carre";
  if (slug.endsWith("-affiche") || slug.includes("-affiche-")) return "affiche";
  if (slug.endsWith("-infographie")) return "infographie";
  if (slug.endsWith("-editorial")) return "editorial";
  if (slug.endsWith("-dataviz")) return "dataviz";
  if (slug.includes("-logo-") || slug.includes("-icone-")) return "logo";
  if (slug.endsWith("-photo-carre")) return "carre";
  if (slug.endsWith("-photo-banniere") || slug.includes("-photo")) return "photo";
  return "banniere";
}

function slugToTitle(slug: string): string {
  return slug
    .replace(/^axion-ia-/, "")
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .replace(/\bIa\b/g, "IA")
    .replace(/\bTpe\b/g, "TPE")
    .replace(/\bPme\b/g, "PME")
    .replace(/\bEti\b/g, "ETI")
    .replace(/\bRoi\b/g, "ROI")
    .replace(/\bKpi\b/g, "KPI");
}

const MODULE_LABELS: Record<string, string> = {
  audits: "Audit IA",
  interventions: "Formation IA",
  implementations: "Automatisation IA",
  "un-a-un": "Accompagnement 1-to-1",
  graphique: "Graphique / Dataviz",
  logo: "Logo Axion-IA",
  proposition: "Proposition de valeur",
  ville: "Présence locale",
};

interface ImageEntry {
  slug: string;
  module: string;
  subModule?: string;
  targetCity?: string;
  geoPosition?: string;
  geoPlacename?: string;
  isAiGenerated?: boolean;
  sourceType?: string;
  keywordsPrimary?: string;
  targetFormat?: string;
  // Dimensions bakées (mesurées sur le WebP réel) — priment sur DIMENSIONS[detectType].
  width?: number;
  height?: number;
  orientation?: string;
  aspectRatio?: string;
}

const IMAGE_ENTRIES: ImageEntry[] = [
  // ── AUDITS (17) ──────────────────────────────────────────────────────
  {
    slug: "axion-ia-audit-ia-analyse-donnees-historiques-performance-entreprise",
    module: "audits",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA audit analyse donnees historiques performance",
  },
  {
    slug: "axion-ia-audit-ia-analyse-processus-entreprise-consultant-banniere",
    module: "audits",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA audit analyse processus entreprise consultant",
  },
  {
    slug: "axion-ia-audit-ia-benchmark-secteur-positionnement-concurrentiel",
    module: "audits",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA audit benchmark secteur positionnement concurrentiel",
  },
  {
    slug: "axion-ia-audit-ia-cartographie-outils-existants-systeme-information-banniere",
    module: "audits",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA audit cartographie outils existants systeme",
  },
  {
    slug: "axion-ia-audit-ia-diagnostic-numerique-pme-bilan-competences",
    module: "audits",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA audit diagnostic numerique PME bilan",
  },
  {
    slug: "axion-ia-audit-ia-diagnostic-workflow-taches-repetitives-detection",
    module: "audits",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA audit diagnostic workflow taches repetitives",
  },
  {
    slug: "axion-ia-audit-ia-entretien-dirigeant-recueil-besoins-analyse",
    module: "audits",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA audit entretien dirigeant recueil besoins",
  },
  {
    slug: "axion-ia-audit-ia-evaluation-maturite-digitale-entreprise-banniere",
    module: "audits",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA audit evaluation maturite digitale entreprise",
  },
  {
    slug: "axion-ia-audit-ia-feuille-de-route-implementation-phases-etapes",
    module: "audits",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA audit feuille route implementation phases",
  },
  {
    slug: "axion-ia-audit-ia-identification-gains-potentiels-automatisation-banniere",
    module: "audits",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA audit identification gains potentiels automatisation",
  },
  {
    slug: "axion-ia-audit-ia-identification-risques-conformite-rgpd-ia",
    module: "audits",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA audit identification risques conformite rgpd",
  },
  {
    slug: "axion-ia-audit-ia-rapport-restitution-dirigeant-plan-action",
    module: "audits",
    width: 1600,
    height: 983,
    orientation: "landscape",
    aspectRatio: "1600:983",
    keywordsPrimary: "IA audit rapport restitution dirigeant plan",
  },
  {
    slug: "axion-ia-audit-ia-restitution-equipe-plan-transformation-digitale-carre",
    module: "audits",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA audit restitution equipe plan transformation",
  },
  {
    slug: "axion-ia-audit-ia-schema-bilan-forces-faiblesses-opportunites-carre",
    module: "audits",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA audit schema bilan forces faiblesses",
  },
  {
    slug: "axion-ia-audit-ia-scoring-priorites-quick-wins-long-terme",
    module: "audits",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA audit scoring priorites quick wins",
  },
  {
    slug: "axion-ia-audit-ia-synthese-executive-roi-priorites-implementation",
    module: "audits",
    width: 1600,
    height: 867,
    orientation: "landscape",
    aspectRatio: "1600:867",
    keywordsPrimary: "IA audit synthese executive roi priorites",
  },
  {
    slug: "axion-ia-audit-ia-tableau-bord-kpi-avant-apres-transformation-carre",
    module: "audits",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA audit tableau bord kpi avant",
  },
  // ── IMPLEMENTATIONS (81) ─────────────────────────────────────────────
  {
    slug: "axion-ia-5-heures-saisie-supprimees-gain-temps-entreprise-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA heures saisie supprimees gain temps",
  },
  {
    slug: "axion-ia-accueil-client-vip-automatique-onboarding-crm-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA accueil client vip automatique onboarding",
  },
  {
    slug: "axion-ia-analyse-contrat-clauses-risque-68-pages-2-minutes-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA analyse contrat clauses risque pages",
  },
  {
    slug: "axion-ia-architecture-groupe-international-consolidation-financiere-rh-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA architecture groupe international consolidation financiere",
  },
  {
    slug: "axion-ia-boite-mail-liberte-automatisation-emails-ia-affiche",
    module: "implementations",
    width: 1448,
    height: 1086,
    orientation: "landscape",
    aspectRatio: "4:3",
    keywordsPrimary: "IA boite mail liberte automatisation emails",
  },
  {
    slug: "axion-ia-cerveau-ia-analyse-donnees-60-min-a-4-min-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cerveau analyse donnees min min",
  },
  {
    slug: "axion-ia-commande-farine-boulangerie-automatique-sans-saisie-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA commande farine boulangerie automatique saisie",
  },
  {
    slug: "axion-ia-commande-fournisseur-45min-a-0min-automatique-boulangerie-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA commande fournisseur 45min 0min automatique",
  },
  {
    slug: "axion-ia-commande-fournisseur-5-etapes-ventes-stock-boulangerie-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA commande fournisseur etapes ventes stock",
  },
  {
    slug: "axion-ia-comparatif-actions-humaines-vs-automatisation-ia-7-etapes-infographie",
    module: "implementations",
    width: 1024,
    height: 1536,
    orientation: "portrait",
    aspectRatio: "2:3",
    keywordsPrimary: "IA comparatif actions humaines automatisation etapes",
  },
  {
    slug: "axion-ia-compte-rendu-reunion-ecrit-automatiquement-equipe-bureau-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA compte rendu reunion ecrit automatiquement",
  },
  {
    slug: "axion-ia-crm-boutique-12-clients-absents-34-pourcent-retour-relance-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA crm boutique clients absents pourcent",
  },
  {
    slug: "axion-ia-crm-scoring-contacts-action-automatique-bon-moment-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA crm scoring contacts action automatique",
  },
  {
    slug: "axion-ia-detection-profil-ideal-foule-ia-ne-cherche-pas-elle-trouve-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA detection profil ideal foule ne",
  },
  {
    slug: "axion-ia-devis-automatise-30-secondes-envoi-gain-temps-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA devis automatise secondes envoi gain",
  },
  {
    slug: "axion-ia-devis-envoye-28-secondes-avant-raccrochage-client-affiche",
    module: "implementations",
    width: 900,
    height: 1600,
    orientation: "portrait",
    aspectRatio: "9:16",
    keywordsPrimary: "IA devis envoye secondes avant raccrochage",
  },
  {
    slug: "axion-ia-dispatch-interventions-carte-technicien-bon-endroit-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA dispatch interventions carte technicien bon",
  },
  {
    slug: "axion-ia-envoi-message-numerique-automatique-campagne-email-affiche",
    module: "implementations",
    width: 900,
    height: 1600,
    orientation: "portrait",
    aspectRatio: "9:16",
    keywordsPrimary: "IA envoi message numerique automatique campagne",
  },
  {
    slug: "axion-ia-equilibre-moins-effort-plus-resultats-optimisation-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA equilibre moins effort plus resultats",
  },
  {
    slug: "axion-ia-facturation-automatique-flux-ia-tva-zero-saisie-infographie",
    module: "implementations",
    width: 900,
    height: 1600,
    orientation: "portrait",
    aspectRatio: "9:16",
    keywordsPrimary: "IA facturation automatique flux tva zero",
  },
  {
    slug: "axion-ia-flux-facturation-ia-zero-saisie-manuelle-infographie",
    module: "implementations",
    width: 900,
    height: 1600,
    orientation: "portrait",
    aspectRatio: "9:16",
    keywordsPrimary: "IA flux facturation zero saisie manuelle",
  },
  {
    slug: "axion-ia-gain-productivite-45-pourcent-bureau-implementation-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA gain productivite pourcent bureau implementation",
  },
  {
    slug: "axion-ia-generation-contenu-6-formats-4-minutes-brief-ia-infographie",
    module: "implementations",
    width: 900,
    height: 1600,
    orientation: "portrait",
    aspectRatio: "9:16",
    keywordsPrimary: "IA generation contenu formats minutes brief",
  },
  {
    slug: "axion-ia-gestion-factures-comptabilite-capture-extraction-validation-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA gestion factures comptabilite capture extraction",
  },
  {
    slug: "axion-ia-gestion-stocks-boucherie-zero-rupture-zero-surstock-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA gestion stocks boucherie zero rupture",
  },
  {
    slug: "axion-ia-gestion-stocks-prevision-j45-commandes-automatiques-ia-infographie",
    module: "implementations",
    width: 900,
    height: 1600,
    orientation: "portrait",
    aspectRatio: "9:16",
    keywordsPrimary: "IA gestion stocks prevision j45 commandes",
  },
  {
    slug: "axion-ia-inondation-emails-mur-brisant-automatisation-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA inondation emails mur brisant automatisation",
  },
  {
    slug: "axion-ia-marches-publics-score-opportunites-dossier-prepare-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA marches publics score opportunites dossier",
  },
  {
    slug: "axion-ia-meilleur-candidat-etoile-or-parmi-200-cv-3-min-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA meilleur candidat etoile or parmi",
  },
  {
    slug: "axion-ia-onboarding-rh-j-5-j90-90-pourcent-automatise-collaborateur-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA onboarding rh j j90 pourcent",
  },
  {
    slug: "axion-ia-optimisation-vente-viande-boucherie-flux-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA optimisation vente viande boucherie flux",
  },
  {
    slug: "axion-ia-personnalisation-temps-reel-visiteurs-experience-unique-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA personnalisation temps reel visiteurs experience",
  },
  {
    slug: "axion-ia-pipeline-lead-ia-zero-intervention-humaine-7-etapes-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA pipeline lead zero intervention humaine",
  },
  {
    slug: "axion-ia-pipeline-marketing-lead-qualifie-scoring-crm-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA pipeline marketing lead qualifie scoring",
  },
  {
    slug: "axion-ia-planning-chantier-gantt-ia-conflits-detectes-temps-reel-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA planning chantier gantt conflits detectes",
  },
  {
    slug: "axion-ia-prevision-tresorerie-90-jours-zero-saisie-zero-surprise-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA prevision tresorerie jours zero saisie",
  },
  {
    slug: "axion-ia-rapport-performance-hebdomadaire-automatique-lundi-matin-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA rapport performance hebdomadaire automatique lundi",
  },
  {
    slug: "axion-ia-recrutement-ia-8-semaines-a-3-semaines-80-pourcent-automatise-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA recrutement semaines semaines pourcent automatise",
  },
  {
    slug: "axion-ia-reduction-dechets-viande-300-a-47-euros-reassort-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA reduction dechets viande euros reassort",
  },
  {
    slug: "axion-ia-relance-clients-boutique-sms-anniversaire-fidelisation-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA relance clients boutique sms anniversaire",
  },
  {
    slug: "axion-ia-relance-clients-nuit-virement-3200-euros-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA relance clients nuit virement euros",
  },
  {
    slug: "axion-ia-relance-clients-zero-manuel-100-pourcent-automatique-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA relance clients zero manuel pourcent",
  },
  {
    slug: "axion-ia-reporting-executif-ca-1248000-euros-marge-leads-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA reporting executif ca euros marge",
  },
  {
    slug: "axion-ia-reunion-1-heure-compte-rendu-4-minutes-ia-sablier-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA reunion heure compte rendu minutes",
  },
  {
    slug: "axion-ia-reunion-chaos-ia-clarifie-contexte-decision-actions-affiche",
    module: "implementations",
    width: 900,
    height: 1600,
    orientation: "portrait",
    aspectRatio: "9:16",
    keywordsPrimary: "IA reunion chaos clarifie contexte decision",
  },
  {
    slug: "axion-ia-reunion-compte-rendu-ia-vue-aerienne-table-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA reunion compte rendu vue aerienne",
  },
  {
    slug: "axion-ia-selection-cv-200-candidatures-3-minutes-entonnoir-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA selection cv candidatures minutes entonnoir",
  },
  {
    slug: "axion-ia-selection-meilleur-candidat-pyramide-cv-ia-affiche",
    module: "implementations",
    width: 900,
    height: 1600,
    orientation: "portrait",
    aspectRatio: "9:16",
    keywordsPrimary: "IA selection meilleur candidat pyramide cv",
  },
  {
    slug: "axion-ia-support-client-reclamation-reponse-ia-34-secondes-affiche",
    module: "implementations",
    width: 900,
    height: 1600,
    orientation: "portrait",
    aspectRatio: "9:16",
    keywordsPrimary: "IA support client reclamation reponse secondes",
  },
  {
    slug: "axion-ia-tableau-bord-boucherie-zero-invendu-zero-rupture-zero-calcul-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA tableau bord boucherie zero invendu",
  },
  {
    slug: "axion-ia-tampon-validation-encre-terracotta-automatisation-documents-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA tampon validation encre terracotta automatisation",
  },
  {
    slug: "axion-ia-traitement-courrier-intelligent-ia-3h-a-20min-affiche",
    module: "implementations",
    width: 900,
    height: 1600,
    orientation: "portrait",
    aspectRatio: "9:16",
    keywordsPrimary: "IA traitement courrier intelligent 3h 20min",
  },
  {
    slug: "axion-ia-traitement-reclamations-312-semaine-4-minutes-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA traitement reclamations semaine minutes",
  },
  {
    slug: "axion-ia-transcription-audio-flux-donnees-ia-automatique-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA transcription audio flux donnees automatique",
  },
  {
    slug: "axion-ia-transcription-reunion-microphone-60min-a-5min-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA transcription reunion microphone 60min 5min",
  },
  {
    slug: "axion-ia-transformation-chaos-devis-rentabilite-croissance-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA transformation chaos devis rentabilite croissance",
  },
  {
    slug: "axion-ia-tri-emails-847-recus-1-compte-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA tri emails recus compte",
  },
  {
    slug: "axion-ia-tri-emails-inbox-3h-a-20min-entonnoir-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA tri emails inbox 3h 20min",
  },
  {
    slug: "axion-ia-validation-document-tampon-comptabilite-controle-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA validation document tampon comptabilite controle",
  },
  {
    slug: "axion-ia-veille-concurrentielle-847-sources-12-signaux-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA veille concurrentielle sources signaux",
  },
  {
    slug: "axion-ia-veille-marches-publics-47000-sources-opportunites-ia-banniere",
    module: "implementations",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA veille marches publics sources opportunites",
  },
  {
    slug: "axion-ia-cas-concret-onboarding-client-automatique-post-signature-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret onboarding client automatique",
  },
  {
    slug: "axion-ia-cas-concret-approvisionnements-fournisseurs-ia-zero-rupture-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret approvisionnements fournisseurs zero",
  },
  {
    slug: "axion-ia-cas-concret-comptes-rendus-reunions-automatiques-sans-effort-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret comptes rendus reunions",
  },
  {
    slug: "axion-ia-cas-concret-emails-inbox-zero-tri-automatique-priorites-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret emails inbox zero",
  },
  {
    slug: "axion-ia-cas-concret-facturation-automatique-zero-saisie-manuelle-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret facturation automatique zero",
  },
  {
    slug: "axion-ia-cas-concret-veille-concurrentielle-digest-quotidien-alertes-marche-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret veille concurrentielle digest",
  },
  {
    slug: "axion-ia-cas-concret-gestion-stocks-prevision-commandes-automatiques-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret gestion stocks prevision",
  },
  {
    slug: "axion-ia-cas-concret-impayes-relance-clients-automatique-argent-recupere-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret impayes relance clients",
  },
  {
    slug: "axion-ia-cas-concret-onboarding-rh-collaborateur-parcours-automatise-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret onboarding rh collaborateur",
  },
  {
    slug: "axion-ia-cas-concret-pipeline-commercial-leads-qualifies-crm-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret pipeline commercial leads",
  },
  {
    slug: "axion-ia-cas-concret-recrutement-cv-tri-automatique-candidats-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret recrutement cv tri",
  },
  {
    slug: "axion-ia-cas-concret-reporting-performance-hebdomadaire-automatique-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret reporting performance hebdomadaire",
  },
  {
    slug: "axion-ia-cas-concret-soirees-admin-devis-factures-automatiques-pme-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret soirees admin devis",
  },
  {
    slug: "axion-ia-cas-concret-support-client-reponses-automatiques-ia-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret support client reponses",
  },
  {
    slug: "axion-ia-cas-concret-traitement-reclamations-clients-ia-rapid-resolution-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret traitement reclamations clients",
  },
  {
    slug: "axion-ia-cas-concret-veille-concurrentielle-ia-signaux-marche-carre",
    module: "implementations",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA cas concret veille concurrentielle signaux",
  },
  {
    slug: "axion-ia-automatisation-taches-repetitives-gain-productivite-pme",
    module: "implementations",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA automatisation taches repetitives gain productivite",
  },
  {
    slug: "axion-ia-connexion-outils-crm-erp-ia-automatisation-donnees",
    module: "implementations",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA connexion outils crm erp automatisation",
  },
  {
    slug: "axion-ia-deploiement-ia-processus-metier-integration-systeme-existant",
    module: "implementations",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA deploiement processus metier integration systeme",
  },
  {
    slug: "axion-ia-implementation-automatisation-workflow-entreprise-schema",
    module: "implementations",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA implementation automatisation workflow entreprise schema",
  },
  // ── INTERVENTIONS (20) ───────────────────────────────────────────────
  {
    slug: "axion-ia-photo-atelier-ia-groupe-collaborateurs-ordinateurs-ecrans",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA photo atelier groupe collaborateurs ordinateurs",
  },
  {
    slug: "axion-ia-photo-celebration-formation-ia-reussie-equipe-satisfaite",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA photo celebration formation reussie equipe",
  },
  {
    slug: "axion-ia-photo-formateur-ia-presentation-tableau-equipe-entreprise",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA photo formateur presentation tableau equipe",
  },
  {
    slug: "axion-ia-photo-formation-ia-equipe-mixte-exercices-pratiques-resultat",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA photo formation equipe mixte exercices",
  },
  {
    slug: "axion-ia-photo-formation-ia-salle-conference-participants-eclairage",
    module: "interventions",
    width: 1448,
    height: 1086,
    orientation: "landscape",
    aspectRatio: "4:3",
    keywordsPrimary: "IA photo formation salle conference participants",
  },
  {
    slug: "axion-ia-atelier-ia-equipe-commerciale-crm-automatisation-leads",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA atelier equipe commerciale crm automatisation",
  },
  {
    slug: "axion-ia-atelier-pratique-ia-equipe-exercices-mains-dans-la-masse",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA atelier pratique equipe exercices mains",
  },
  {
    slug: "axion-ia-conference-ia-dirigeants-pme-transformation-numerique",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA conference dirigeants PME transformation numerique",
  },
  {
    slug: "axion-ia-formation-ia-cas-pratiques-metiers-secteurs-specifiques",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA formation cas pratiques metiers secteurs",
  },
  {
    slug: "axion-ia-formation-ia-certification-collaborateurs-validation-competences",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA formation certification collaborateurs validation competences",
  },
  {
    slug: "axion-ia-formation-ia-entreprises-programme-catalogue-offre",
    module: "interventions",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA formation entreprises programme catalogue offre",
  },
  {
    slug: "axion-ia-formation-ia-entreprises-vue-isometrique-participants-carre",
    module: "interventions",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA formation entreprises vue isometrique participants",
  },
  {
    slug: "axion-ia-formation-ia-groupe-collaborateurs-salle-aprentissage-carre",
    module: "interventions",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA formation groupe collaborateurs salle aprentissage",
  },
  {
    slug: "axion-ia-formation-ia-intelligence-collective-equipe-innovation-carre",
    module: "interventions",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA formation intelligence collective equipe innovation",
  },
  {
    slug: "axion-ia-formation-ia-resultats-mesurables-avant-apres-application-carre",
    module: "interventions",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA formation resultats mesurables avant apres",
  },
  {
    slug: "axion-ia-formation-prompt-engineering-equipe-pme-salle-informatique",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA formation prompt engineering equipe PME",
  },
  {
    slug: "axion-ia-formation-une-journee-intelligence-artificielle-entreprises-pme",
    module: "interventions",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA formation journee intelligence artificielle entreprises",
  },
  {
    slug: "axion-ia-intervention-ia-entreprise-demi-journee-mise-en-pratique-immediate",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA intervention entreprise demi journee mise",
  },
  {
    slug: "axion-ia-intervention-ia-formateur-tableau-blanc-schema-pedagogique",
    module: "interventions",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA intervention formateur tableau blanc schema",
  },
  {
    slug: "axion-ia-intervention-une-journee-ia-sur-site-entreprise-equipe",
    module: "interventions",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA intervention journee site entreprise equipe",
  },
  // ── GRAPHIQUE (5) ───────────────────────────────────────────────────
  {
    slug: "axion-ia-courbe-adoption-ia-collaborateurs-montee-competences",
    module: "graphique",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA courbe adoption collaborateurs montee competences",
  },
  {
    slug: "axion-ia-courbe-productivite-avant-apres-automatisation-ia-entreprise",
    module: "graphique",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA courbe productivite avant apres automatisation",
  },
  {
    slug: "axion-ia-graphique-gain-temps-heures-economisees-semaine-ia",
    module: "graphique",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA graphique gain temps heures economisees",
  },
  {
    slug: "axion-ia-graphique-reduction-couts-operationnels-ia-12-mois",
    module: "graphique",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA graphique reduction couts operationnels mois",
  },
  {
    slug: "axion-ia-graphique-roi-implementation-ia-pme-courbe-croissance",
    module: "graphique",
    width: 1600,
    height: 900,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA graphique roi implementation PME courbe",
  },
  // ── PROPOSITION (11) ─────────────────────────────────────────────────
  {
    slug: "axion-ia-catalogue-services-ia-b2b-consulting-formation-france-banniere",
    module: "proposition",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA catalogue services b2b consulting formation",
  },
  {
    slug: "axion-ia-equipe-experts-ia-accompagnement-360-transformation-digitale-carre",
    module: "proposition",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA equipe experts accompagnement transformation digitale",
  },
  {
    slug: "axion-ia-expertise-sectorielle-ia-industrie-commerce-services-france",
    module: "proposition",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA expertise sectorielle industrie commerce services",
  },
  {
    slug: "axion-ia-garantie-resultats-satisfaction-accompagnement-ia-carre",
    module: "proposition",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA garantie resultats satisfaction accompagnement",
  },
  {
    slug: "axion-ia-methode-intervention-sur-mesure-objectifs-mesurables-banniere",
    module: "proposition",
    width: 1920,
    height: 1080,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA methode intervention mesure objectifs mesurables",
  },
  {
    slug: "axion-ia-next-step-demarrer-projet-ia-entreprise-etapes-simples",
    module: "proposition",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA next step demarrer projet entreprise",
  },
  {
    slug: "axion-ia-offre-complete-audit-formation-implementation-coaching-ia",
    module: "proposition",
    width: 1600,
    height: 983,
    orientation: "landscape",
    aspectRatio: "1600:983",
    keywordsPrimary: "IA offre complete audit formation implementation",
  },
  {
    slug: "axion-ia-parcours-client-diagnostic-deploiement-suivi-ia-etapes",
    module: "proposition",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA parcours client diagnostic deploiement suivi",
  },
  {
    slug: "axion-ia-prise-de-contact-decouverte-gratuite-30-min-visio",
    module: "proposition",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA prise contact decouverte gratuite min",
  },
  {
    slug: "axion-ia-proposition-valeur-5-piliers-services-ia-pme-entreprises",
    module: "proposition",
    width: 1600,
    height: 983,
    orientation: "landscape",
    aspectRatio: "1600:983",
    keywordsPrimary: "IA proposition valeur piliers services PME",
  },
  {
    slug: "axion-ia-resultats-clients-temoignages-cas-concrets-pme-carre",
    module: "proposition",
    width: 1200,
    height: 1200,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA resultats clients temoignages cas concrets",
  },
  // ── UN-A-UN (8) ─────────────────────────────────────────────────────
  {
    slug: "axion-ia-accompagnement-personnalise-dirigeant-decisions-ia",
    module: "un-a-un",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA accompagnement personnalise dirigeant decisions",
  },
  {
    slug: "axion-ia-bilan-coaching-dirigeant-ia-transformation-reussie-portrait",
    module: "un-a-un",
    width: 1024,
    height: 1536,
    orientation: "portrait",
    aspectRatio: "2:3",
    keywordsPrimary: "IA bilan coaching dirigeant transformation reussie",
  },
  {
    slug: "axion-ia-coaching-1to1-ceo-vision-ia-feuille-route-individuelle",
    module: "un-a-un",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA coaching 1to1 ceo vision feuille",
  },
  {
    slug: "axion-ia-coaching-1to1-collaborateur-formation-ia-individuelle",
    module: "un-a-un",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA coaching 1to1 collaborateur formation individuelle",
  },
  {
    slug: "axion-ia-formation-1to1-dirigeant-prompt-engineering-chatgpt",
    module: "un-a-un",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA formation 1to1 dirigeant prompt engineering",
  },
  {
    slug: "axion-ia-seance-coaching-ia-dirigeant-objectifs-mesurables-resultats",
    module: "un-a-un",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA seance coaching dirigeant objectifs mesurables",
  },
  {
    slug: "axion-ia-session-individuelle-dirigeant-prise-en-main-outils-ia",
    module: "un-a-un",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA session individuelle dirigeant prise main",
  },
  {
    slug: "axion-ia-session-individuelle-employe-maitrise-outils-ia-quotidien",
    module: "un-a-un",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA session individuelle employe maitrise outils",
  },
  // ── LOGO (9) ────────────────────────────────────────────────────────
  {
    slug: "axion-ia-logo-blanc-fond-transparent-haute-resolution-site-web",
    module: "logo",
    width: 1600,
    height: 900,
    orientation: "landscape",
    aspectRatio: "16:9",
    keywordsPrimary: "IA logo blanc fond transparent haute",
  },
  {
    slug: "axion-ia-logo-blanc-transparent-500px-email-web-compact",
    module: "logo",
    width: 500,
    height: 281,
    orientation: "landscape",
    aspectRatio: "500:281",
    keywordsPrimary: "IA logo blanc transparent 500px email",
  },
  {
    slug: "axion-ia-logo-format-cercle-avatar-profil-linkedin-reseaux",
    module: "logo",
    width: 1024,
    height: 1024,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA logo format cercle avatar profil",
  },
  {
    slug: "axion-ia-logo-full-transparent-toutes-couleurs-fond-versatile",
    module: "logo",
    width: 1024,
    height: 1024,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA logo full transparent toutes couleurs",
  },
  {
    slug: "axion-ia-logo-icone-carre-sans-fond-500px-reseaux-sociaux",
    module: "logo",
    width: 500,
    height: 500,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA logo icone carre fond 500px",
  },
  {
    slug: "axion-ia-logo-icone-carre-sans-fond-haute-definition",
    module: "logo",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA logo icone carre fond haute",
  },
  {
    slug: "axion-ia-logo-officiel-optimise-web-500kb-usage-general",
    module: "logo",
    width: 1024,
    height: 1024,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA logo officiel optimise web 500kb",
  },
  {
    slug: "axion-ia-logo-plat-couleur-fond-blanc-usage-standard-large",
    module: "logo",
    width: 1600,
    height: 683,
    orientation: "landscape",
    aspectRatio: "1600:683",
    keywordsPrimary: "IA logo plat couleur fond blanc",
  },
  {
    slug: "axion-ia-logo-plat-full-transparent-fond-neutre-presentation",
    module: "logo",
    width: 1024,
    height: 1024,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA logo plat full transparent fond",
  },
  // ── VILLE (64) ───────────────────────────────────────────────────────
  {
    slug: "axion-ia-audit-ia-paris-pme-startups-grands-comptes-diagnostic",
    module: "ville",
    targetCity: "Paris",
    geoPosition: "48.8589;2.347",
    geoPlacename: "Paris, France",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA audit paris PME startups grands",
  },
  {
    slug: "axion-ia-consultant-ia-lyon-rhone-alpes-pme-formation-accompagnement",
    module: "ville",
    targetCity: "Lyon",
    geoPosition: "45.758;4.8351",
    geoPlacename: "Lyon, France",
    width: 1535,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "1535:1024",
    keywordsPrimary: "IA consultant lyon rhone alpes PME",
  },
  {
    slug: "axion-ia-consultant-ia-paris-ile-de-france-pme-transformation-digitale",
    module: "ville",
    targetCity: "Paris",
    geoPosition: "48.8589;2.347",
    geoPlacename: "Paris, France",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA consultant paris ile france PME",
  },
  {
    slug: "axion-ia-formation-ia-paris-equipe-entreprise-conseil-sur-mesure",
    module: "ville",
    targetCity: "Paris",
    geoPosition: "48.8589;2.347",
    geoPlacename: "Paris, France",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA formation paris equipe entreprise conseil",
  },
  {
    slug: "axion-ia-implementation-ia-paris-business-district-bureaux-entreprise",
    module: "ville",
    targetCity: "Paris",
    geoPosition: "48.8589;2.347",
    geoPlacename: "Paris, France",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA implementation paris business district bureaux",
  },
  {
    slug: "axion-ia-hero-ville-aix-en-provence-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Aix-en-Provence",
    geoPosition: "43.536;5.3879",
    geoPlacename: "Aix-en-Provence, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville aix provence consultant",
  },
  {
    slug: "axion-ia-hero-ville-amiens-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Amiens",
    geoPosition: "49.8987;2.2847",
    geoPlacename: "Amiens, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville amiens consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-angers-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Angers",
    geoPosition: "47.4819;-0.5629",
    geoPlacename: "Angers, France",
    width: 1181,
    height: 1331,
    orientation: "portrait",
    aspectRatio: "1181:1331",
    keywordsPrimary: "IA hero ville angers consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-annecy-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Annecy",
    geoPosition: "45.9024;6.1264",
    geoPlacename: "Annecy, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville annecy consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-argenteuil-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Argenteuil",
    geoPosition: "48.9501;2.2478",
    geoPlacename: "Argenteuil, France",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA hero ville argenteuil consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-asnieres-sur-seine-consultant-ia-pme",
    module: "ville",
    targetCity: "Asnières-sur-Seine",
    geoPosition: "48.9181;2.2935",
    geoPlacename: "Asnières-sur-Seine, France",
    width: 1536,
    height: 1024,
    orientation: "landscape",
    aspectRatio: "3:2",
    keywordsPrimary: "IA hero ville asnieres seine consultant",
  },
  {
    slug: "axion-ia-hero-ville-aubervilliers-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Aubervilliers",
    geoPosition: "48.9128;2.3886",
    geoPlacename: "Aubervilliers, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville aubervilliers consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-aulnay-sous-bois-consultant-ia-pme",
    module: "ville",
    targetCity: "Aulnay-sous-Bois",
    geoPosition: "48.9457;2.4918",
    geoPlacename: "Aulnay-sous-Bois, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville aulnay bois consultant",
  },
  {
    slug: "axion-ia-hero-ville-avignon-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Avignon",
    geoPosition: "43.9416;4.8333",
    geoPlacename: "Avignon, France",
    width: 1129,
    height: 1393,
    orientation: "portrait",
    aspectRatio: "1129:1393",
    keywordsPrimary: "IA hero ville avignon consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-besancon-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Besançon",
    geoPosition: "47.2602;6.0123",
    geoPlacename: "Besançon, France",
    width: 1402,
    height: 1122,
    orientation: "landscape",
    aspectRatio: "701:561",
    keywordsPrimary: "IA hero ville besancon consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-bordeaux-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Bordeaux",
    geoPosition: "44.8624;-0.5848",
    geoPlacename: "Bordeaux, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville bordeaux consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-boulogne-billancourt-consultant-ia-pme",
    module: "ville",
    targetCity: "Boulogne-Billancourt",
    geoPosition: "48.8375;2.2429",
    geoPlacename: "Boulogne-Billancourt, France",
    width: 1402,
    height: 1122,
    orientation: "landscape",
    aspectRatio: "701:561",
    keywordsPrimary: "IA hero ville boulogne billancourt consultant",
  },
  {
    slug: "axion-ia-hero-ville-brest-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Brest",
    geoPosition: "48.4085;-4.4996",
    geoPlacename: "Brest, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville brest consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-caen-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Caen",
    geoPosition: "49.1846;-0.3722",
    geoPlacename: "Caen, France",
    width: 1402,
    height: 1122,
    orientation: "landscape",
    aspectRatio: "701:561",
    keywordsPrimary: "IA hero ville caen consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-cannes-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Cannes",
    geoPosition: "43.5454;7.0152",
    geoPlacename: "Cannes, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville cannes consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-clermont-ferrand-consultant-ia-pme",
    module: "ville",
    targetCity: "Clermont-Ferrand",
    geoPosition: "45.787;3.1127",
    geoPlacename: "Clermont-Ferrand, France",
    width: 1198,
    height: 1313,
    orientation: "portrait",
    aspectRatio: "1198:1313",
    keywordsPrimary: "IA hero ville clermont ferrand consultant",
  },
  {
    slug: "axion-ia-hero-ville-colombes-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Colombes",
    geoPosition: "48.9218;2.2469",
    geoPlacename: "Colombes, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville colombes consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-courbevoie-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Courbevoie",
    geoPosition: "48.8976;2.2574",
    geoPlacename: "Courbevoie, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville courbevoie consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-creteil-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Créteil",
    geoPosition: "48.7845;2.4523",
    geoPlacename: "Créteil, France",
    width: 1024,
    height: 1536,
    orientation: "portrait",
    aspectRatio: "2:3",
    keywordsPrimary: "IA hero ville creteil consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-dijon-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Dijon",
    geoPosition: "47.3319;5.0322",
    geoPlacename: "Dijon, France",
    width: 1197,
    height: 1315,
    orientation: "portrait",
    aspectRatio: "1197:1315",
    keywordsPrimary: "IA hero ville dijon consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-dunkerque-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Dunkerque",
    geoPosition: "51.0183;2.3431",
    geoPlacename: "Dunkerque, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville dunkerque consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-grenoble-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Grenoble",
    geoPosition: "45.1842;5.7155",
    geoPlacename: "Grenoble, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville grenoble consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-le-havre-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Le Havre",
    geoPosition: "49.4958;0.1312",
    geoPlacename: "Le Havre, France",
    width: 1177,
    height: 1336,
    orientation: "portrait",
    aspectRatio: "1177:1336",
    keywordsPrimary: "IA hero ville havre consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-le-mans-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Le Mans",
    geoPosition: "47.9819;0.1957",
    geoPlacename: "Le Mans, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville mans consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-lille-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Lille",
    geoPosition: "50.6311;3.0468",
    geoPlacename: "Lille, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville lille consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-limoges-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Limoges",
    geoPosition: "45.8567;1.226",
    geoPlacename: "Limoges, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville limoges consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-lyon-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Lyon",
    geoPosition: "45.758;4.8351",
    geoPlacename: "Lyon, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville lyon consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-marseille-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Marseille",
    geoPosition: "43.2803;5.3806",
    geoPlacename: "Marseille, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville marseille consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-metz-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Metz",
    geoPosition: "49.1048;6.1962",
    geoPlacename: "Metz, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville metz consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-montelimar-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Montélimar",
    geoPosition: "44.5545;4.7454",
    geoPlacename: "Montélimar, France",
    width: 1179,
    height: 1334,
    orientation: "portrait",
    aspectRatio: "1179:1334",
    keywordsPrimary: "IA hero ville montelimar consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-montpellier-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Montpellier",
    geoPosition: "43.61;3.8742",
    geoPlacename: "Montpellier, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville montpellier consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-montreuil-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Montreuil",
    geoPosition: "48.8637;2.4491",
    geoPlacename: "Montreuil, France",
    width: 1402,
    height: 1122,
    orientation: "landscape",
    aspectRatio: "701:561",
    keywordsPrimary: "IA hero ville montreuil consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-mulhouse-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Mulhouse",
    geoPosition: "47.7526;7.3255",
    geoPlacename: "Mulhouse, France",
    width: 1183,
    height: 1329,
    orientation: "portrait",
    aspectRatio: "1183:1329",
    keywordsPrimary: "IA hero ville mulhouse consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-nancy-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Nancy",
    geoPosition: "48.6881;6.1734",
    geoPlacename: "Nancy, France",
    width: 1402,
    height: 1122,
    orientation: "landscape",
    aspectRatio: "701:561",
    keywordsPrimary: "IA hero ville nancy consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-nanterre-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Nanterre",
    geoPosition: "48.8974;2.2018",
    geoPlacename: "Nanterre, France",
    width: 1189,
    height: 1323,
    orientation: "portrait",
    aspectRatio: "1189:1323",
    keywordsPrimary: "IA hero ville nanterre consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-nantes-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Nantes",
    geoPosition: "47.2382;-1.5603",
    geoPlacename: "Nantes, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville nantes consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-nice-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Nice",
    geoPosition: "43.7032;7.2528",
    geoPlacename: "Nice, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville nice consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-nimes-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Nîmes",
    geoPosition: "43.8322;4.3429",
    geoPlacename: "Nîmes, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville nimes consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-orleans-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Orléans",
    geoPosition: "47.8734;1.9122",
    geoPlacename: "Orléans, France",
    width: 1199,
    height: 1312,
    orientation: "portrait",
    aspectRatio: "1199:1312",
    keywordsPrimary: "IA hero ville orleans consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-paris-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Paris",
    geoPosition: "48.8589;2.347",
    geoPlacename: "Paris, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville paris consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-perpignan-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Perpignan",
    geoPosition: "42.699;2.9045",
    geoPlacename: "Perpignan, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville perpignan consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-poitiers-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Poitiers",
    geoPosition: "46.5846;0.3715",
    geoPlacename: "Poitiers, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville poitiers consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-reims-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Reims",
    geoPosition: "49.2535;4.0551",
    geoPlacename: "Reims, France",
    width: 1181,
    height: 1332,
    orientation: "portrait",
    aspectRatio: "1181:1332",
    keywordsPrimary: "IA hero ville reims consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-rennes-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Rennes",
    geoPosition: "48.1159;-1.6884",
    geoPlacename: "Rennes, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville rennes consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-romans-sur-isere-consultant-ia-pme",
    module: "ville",
    targetCity: "Romans-sur-Isère",
    geoPosition: "45.0611;5.0477",
    geoPlacename: "Romans-sur-Isère, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville romans isere consultant",
  },
  {
    slug: "axion-ia-hero-ville-roubaix-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Roubaix",
    geoPosition: "50.6887;3.1843",
    geoPlacename: "Roubaix, France",
    width: 1183,
    height: 1330,
    orientation: "portrait",
    aspectRatio: "169:190",
    keywordsPrimary: "IA hero ville roubaix consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-rouen-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Rouen",
    geoPosition: "49.4412;1.0912",
    geoPlacename: "Rouen, France",
    width: 1183,
    height: 1329,
    orientation: "portrait",
    aspectRatio: "1183:1329",
    keywordsPrimary: "IA hero ville rouen consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-rueil-malmaison-consultant-ia-pme",
    module: "ville",
    targetCity: "Rueil-Malmaison",
    geoPosition: "48.8717;2.1806",
    geoPlacename: "Rueil-Malmaison, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville rueil malmaison consultant",
  },
  {
    slug: "axion-ia-hero-ville-saint-chamond-consultant-ia-pme",
    module: "ville",
    targetCity: "Saint-Chamond",
    geoPosition: "45.4687;4.5082",
    geoPlacename: "Saint-Chamond, France",
    width: 1172,
    height: 1342,
    orientation: "portrait",
    aspectRatio: "586:671",
    keywordsPrimary: "IA hero ville saint chamond consultant",
  },
  {
    slug: "axion-ia-hero-ville-saint-denis-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Saint-Denis",
    geoPosition: "48.9378;2.3657",
    geoPlacename: "Saint-Denis, France",
    width: 1185,
    height: 1327,
    orientation: "portrait",
    aspectRatio: "1185:1327",
    keywordsPrimary: "IA hero ville saint denis consultant",
  },
  {
    slug: "axion-ia-hero-ville-saint-etienne-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Saint-Étienne",
    geoPosition: "45.4241;4.3665",
    geoPlacename: "Saint-Étienne, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville saint etienne consultant",
  },
  {
    slug: "axion-ia-hero-ville-saint-marcellin-consultant-ia-pme",
    module: "ville",
    targetCity: "Saint-Marcellin",
    geoPosition: "45.1526;5.3166",
    geoPlacename: "Saint-Marcellin, France",
    width: 1183,
    height: 1329,
    orientation: "portrait",
    aspectRatio: "1183:1329",
    keywordsPrimary: "IA hero ville saint marcellin consultant",
  },
  {
    slug: "axion-ia-hero-ville-strasbourg-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Strasbourg",
    geoPosition: "48.5691;7.7621",
    geoPlacename: "Strasbourg, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville strasbourg consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-toulon-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Toulon",
    geoPosition: "43.1364;5.9334",
    geoPlacename: "Toulon, France",
    width: 1183,
    height: 1329,
    orientation: "portrait",
    aspectRatio: "1183:1329",
    keywordsPrimary: "IA hero ville toulon consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-tourcoing-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Tourcoing",
    geoPosition: "50.721;3.1577",
    geoPlacename: "Tourcoing, France",
    width: 1149,
    height: 1369,
    orientation: "portrait",
    aspectRatio: "1149:1369",
    keywordsPrimary: "IA hero ville tourcoing consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-tours-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Tours",
    geoPosition: "47.3943;0.6949",
    geoPlacename: "Tours, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville tours consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-versailles-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Versailles",
    geoPosition: "48.8039;2.1191",
    geoPlacename: "Versailles, France",
    width: 1254,
    height: 1254,
    orientation: "square",
    aspectRatio: "1:1",
    keywordsPrimary: "IA hero ville versailles consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-villeurbanne-consultant-ia-formation-pme",
    module: "ville",
    targetCity: "Villeurbanne",
    geoPosition: "45.7719;4.8898",
    geoPlacename: "Villeurbanne, France",
    width: 1199,
    height: 1312,
    orientation: "portrait",
    aspectRatio: "1199:1312",
    keywordsPrimary: "IA hero ville villeurbanne consultant formation",
  },
  {
    slug: "axion-ia-hero-ville-vitry-sur-seine-consultant-ia-pme",
    module: "ville",
    targetCity: "Vitry-sur-Seine",
    geoPosition: "48.7893;2.3951",
    geoPlacename: "Vitry-sur-Seine, France",
    width: 1205,
    height: 1306,
    orientation: "portrait",
    aspectRatio: "1205:1306",
    keywordsPrimary: "IA hero ville vitry seine consultant",
  },
];

async function main() {
  console.log("🌱 Axion-IA Image Bank — Seeder 215 images (reindex 2026-07)\n");
  let upserted = 0;
  let errors = 0;

  for (const entry of IMAGE_ENTRIES) {
    const imageType = detectType(entry.slug);
    const fallback = DIMENSIONS[imageType];
    const dims = {
      width: entry.width ?? fallback.width,
      height: entry.height ?? fallback.height,
      orientation: entry.orientation ?? fallback.orientation,
      aspectRatio: entry.aspectRatio ?? fallback.aspectRatio,
    };
    const isLogo = entry.module === "logo";
    // P1.5 QW-7 — doctrine 0 IA générative : fallback false (les images sont des
    // créations Will/photos réelles, pas des images IA générées). L'ancien fallback
    // `!isLogo` marquait à tort 126 images non-logo comme isAiGenerated=true.
    const isAiGenerated = entry.isAiGenerated !== undefined ? entry.isAiGenerated : false;
    const sourceType = entry.sourceType ?? (isLogo ? "original" : "imported");

    const assetData = {
      filePath: `images/${entry.slug}.webp`,
      thumbnailPath: `images/${entry.slug}-thumb.webp`,
      avifPath: `images/${entry.slug}.avif`,
      fileFormat: "webp",
      fileSize: 0,
      width: dims.width,
      height: dims.height,
      orientation: dims.orientation,
      aspectRatio: dims.aspectRatio,
      keywordsPrimary: entry.keywordsPrimary ?? null,
      licenseType: "cc-by-4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
      copyrightHolder: "Axion-IA",
      sourceType,
      aiModel: null,
      isAiGenerated,
      isActive: true,
      publishedAt: new Date(),
      isFeatured: false,
      module: entry.module,
      subModule: entry.subModule ?? null,
      targetCity: entry.targetCity ?? null,
      geoPosition: entry.geoPosition ?? null,
      geoPlacename: entry.geoPlacename ?? null,
      targetFormat: entry.targetFormat ?? null,
      requiresHumanReview: false,
      watermarkEnabled: false,
      seoScore: 0,
      targetCountries: ["FR", "BE", "CH", "LU"],
      targetLanguages: ["fr"],
    } as const;

    try {
      const asset = await prisma.imageAsset.upsert({
        where: { slug: entry.slug },
        create: { slug: entry.slug, ...assetData },
        update: assetData,
      });

      const titleFr = `Axion-IA — ${slugToTitle(entry.slug)}`;
      const labelFr = MODULE_LABELS[entry.module] ?? "Axion-IA";
      await prisma.imageAssetTranslation.upsert({
        where: { imageId_languageCode: { imageId: asset.id, languageCode: "fr" } },
        create: {
          imageId: asset.id,
          languageCode: "fr",
          slug: entry.slug,
          title: titleFr,
          alt: `${titleFr}`,
          caption: `${labelFr} — ${slugToTitle(entry.slug)}`,
          isPublished: true,
          publishedAt: new Date(),
        },
        update: {
          slug: entry.slug,
          title: titleFr,
          alt: `${titleFr}`,
          caption: `${labelFr} — ${slugToTitle(entry.slug)}`,
          isPublished: true,
          publishedAt: new Date(),
        },
      });

      console.log(`  ✓ [${entry.module}] ${entry.slug}`);
      upserted++;
    } catch (err) {
      console.error(`  ✗ [${entry.module}] ${entry.slug}`, err);
      errors++;
    }
  }

  console.log(`\n── Récap : ${upserted} upserted, ${errors} erreurs ──`);

  // ── Orphelins : anciens slugs (avant reindex 2026-07) absents du set des 215 ──
  // Toute ligne ImageAsset est une image de galerie ; le set des 215 est la SSOT.
  // Par défaut on RAPPORTE seulement. Passer REINDEX_DEACTIVATE_ORPHANS=true pour
  // les soft-désactiver (isActive=false + deletedAt) — réversible, les sort de la
  // galerie + sitemap + JSON-LD. Aucune suppression dure ni de fichier disque.
  const keep = new Set(IMAGE_ENTRIES.map((e) => e.slug));
  const orphans = await prisma.imageAsset.findMany({
    where: { deletedAt: null, slug: { notIn: [...keep] } },
    select: { id: true, slug: true },
  });
  if (orphans.length) {
    const deactivate = process.env.REINDEX_DEACTIVATE_ORPHANS === "true";
    console.log(
      `\n🧹 ${orphans.length} slug(s) orphelin(s) hors du set reindex 2026-07 ` +
        (deactivate
          ? "— désactivation soft :"
          : "— (rapport seul ; REINDEX_DEACTIVATE_ORPHANS=true pour désactiver) :"),
    );
    orphans.forEach((o) => console.log("   – " + o.slug));
    if (deactivate) {
      const res = await prisma.imageAsset.updateMany({
        where: { id: { in: orphans.map((o) => o.id) } },
        data: { isActive: false, deletedAt: new Date() },
      });
      console.log(`   → ${res.count} désactivé(s).`);
    }
  }

  if (errors > 0) process.exit(1);
}

main()
  .catch((e) => {
    console.error("Erreur fatale :", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
