// Villes — barrel + composite type + helpers (Sprint 14.9, ADR 0006).
//
// Architecture (cf. doctrine pSEO villes/régions) :
//   data/<region-slug>.ts   ← VilleData[] structurel INSEE (régénéré par script)
//   copy/<slug>.ts          ← VilleCopy éditorial gold standard (curaté manuellement)
//   index.ts                ← composite Ville = VilleData & { copy? } + helpers
//
// Règle anti-doorway HCU 2024 : seules les villes avec `copy` sont
// `indexable` (cf. `getIndexableVilles()`). Les ~2 280 communes sans copy
// existent en SSG mais sortent en `<meta name="robots" content="noindex" />`.

// ⚡ COÛT DE CE MODULE (découplage 2026-08-16)
//
// Importer ce barrel coûte ~41 s à froid sous vitest : `copy/_auto-generated-index`
// fait 2 118 imports statiques pour ~29 Mo de TypeScript. C'est le prix du contenu
// éditorial, et il est justifié quand on en a besoin (pages villes, RAG, sitemap
// avec copy).
//
// Si tu n'as besoin QUE de données structurelles — slug, population, département,
// région, coordonnées — ou de savoir si une ville est indexable, importe
// **`@/content/villes/core`** : même donnée, ~578 ms au lieu de ~41 s.
//
// Ce fichier ne recalcule rien : le classement d'indexabilité vit dans `core.ts`
// (source unique), et on se contente ici d'habiller les résultats avec `copy` et
// `economicData`.
import type { VilleData } from "./data/types";
import type { VilleCopy } from "./copy/types";
import type { VilleEconomicData } from "./economic-data/types";
import { getVilleEconomicData } from "./economic-data";
import type { Region } from "@/content/regions";
import {
  VILLES_CORE,
  hasVilleCopy,
  isPremiumVilleCore,
  cohortSize as cohortSizeCore,
  isVilleIndexable as isVilleIndexableCore,
  getVillesCoreIndexableNow,
  getRegionByDepartement as getRegionByDepartementCore,
} from "./core";

import { AIX_EN_PROVENCE_COPY } from "./copy/aix-en-provence";
import { AMIENS_COPY } from "./copy/amiens";
import { ANGERS_COPY } from "./copy/angers";
import { ANNECY_COPY } from "./copy/annecy";
import { ARGENTEUIL_COPY } from "./copy/argenteuil";
import { BESANCON_COPY } from "./copy/besancon";
import { BORDEAUX_COPY } from "./copy/bordeaux";
import { BOULOGNE_BILLANCOURT_COPY } from "./copy/boulogne-billancourt";
import { BREST_COPY } from "./copy/brest";
import { CAEN_COPY } from "./copy/caen";
import { CLERMONT_FERRAND_COPY } from "./copy/clermont-ferrand";
import { DIJON_COPY } from "./copy/dijon";
import { GRENOBLE_COPY } from "./copy/grenoble";
import { LE_HAVRE_COPY } from "./copy/le-havre";
import { LE_MANS_COPY } from "./copy/le-mans";
import { LILLE_COPY } from "./copy/lille";
import { LIMOGES_COPY } from "./copy/limoges";
import { LYON_COPY } from "./copy/lyon";
import { MARSEILLE_COPY } from "./copy/marseille";
import { METZ_COPY } from "./copy/metz";
import { MONTPELLIER_COPY } from "./copy/montpellier";
import { MONTREUIL_COPY } from "./copy/montreuil";
import { MULHOUSE_COPY } from "./copy/mulhouse";
import { NANCY_COPY } from "./copy/nancy";
import { NANTES_COPY } from "./copy/nantes";
import { NICE_COPY } from "./copy/nice";
import { NIMES_COPY } from "./copy/nimes";
import { ORLEANS_COPY } from "./copy/orleans";
import { PARIS_COPY } from "./copy/paris";
import { PERPIGNAN_COPY } from "./copy/perpignan";
import { REIMS_COPY } from "./copy/reims";
import { RENNES_COPY } from "./copy/rennes";
import { ROUEN_COPY } from "./copy/rouen";
import { SAINT_DENIS_COPY } from "./copy/saint-denis";
import { SAINT_ETIENNE_COPY } from "./copy/saint-etienne";
import { STRASBOURG_COPY } from "./copy/strasbourg";
import { TOULON_COPY } from "./copy/toulon";
import { TOULOUSE_COPY } from "./copy/toulouse";
import { TOURS_COPY } from "./copy/tours";
import { VILLEURBANNE_COPY } from "./copy/villeurbanne";

// Auto-generated T3 batch 2026-05-27 — ~390 villes LLM-generated copies.
// Re-generated by `scripts/export-villecopy-db-to-ts.ts` depuis DB
// GeneratedVilleCopy.status='approved'. Mergé avec les copies manuelles
// ci-dessous (les manuelles gagnent en cas de slug collision via spread order).
import { AUTO_GENERATED_COPIES_BY_SLUG } from "./copy/_auto-generated-index";
import { resolvePriceTokensDeep } from "@/content/pricing-tokens";

export type { VilleData } from "./data/types";
export type { VilleCopy, VilleFaq } from "./copy/types";

/** Type composite consommé par les pages et helpers (geo.ts, sitemap, etc.). */
export interface Ville extends VilleData {
  /** Contenu éditorial gold standard. Présent ⇒ page indexable. */
  copy?: VilleCopy;
  /**
   * Data économique enrichie (secteurs NAF, pôles, distances, KB tags…)
   * sourcée. Consommée par ContentGen RAG + dashboard /content-gen/city-coverage.
   * Sprint City Quality 2026-05-18 — contrat zéro invention.
   */
  economicData?: VilleEconomicData;
}

// Lookup slug → contenu éditorial. Étendu manuellement à mesure que les
// pages villes gold standard sont produites (Paris d'abord, puis 50 top, etc.).
// Spread order : auto-generated en premier (priorité basse), manuels ensuite
// (priorité haute en cas de collision slug — manuels gold standard gagnent).
const COPY_BY_SLUG: Record<string, VilleCopy> = {
  ...AUTO_GENERATED_COPIES_BY_SLUG,
  "aix-en-provence": AIX_EN_PROVENCE_COPY,
  amiens: AMIENS_COPY,
  angers: ANGERS_COPY,
  annecy: ANNECY_COPY,
  argenteuil: ARGENTEUIL_COPY,
  besancon: BESANCON_COPY,
  bordeaux: BORDEAUX_COPY,
  "boulogne-billancourt": BOULOGNE_BILLANCOURT_COPY,
  brest: BREST_COPY,
  caen: CAEN_COPY,
  "clermont-ferrand": CLERMONT_FERRAND_COPY,
  dijon: DIJON_COPY,
  grenoble: GRENOBLE_COPY,
  "le-havre": LE_HAVRE_COPY,
  "le-mans": LE_MANS_COPY,
  lille: LILLE_COPY,
  limoges: LIMOGES_COPY,
  lyon: LYON_COPY,
  marseille: MARSEILLE_COPY,
  metz: METZ_COPY,
  montpellier: MONTPELLIER_COPY,
  montreuil: MONTREUIL_COPY,
  mulhouse: MULHOUSE_COPY,
  nancy: NANCY_COPY,
  nantes: NANTES_COPY,
  nice: NICE_COPY,
  nimes: NIMES_COPY,
  orleans: ORLEANS_COPY,
  paris: PARIS_COPY,
  perpignan: PERPIGNAN_COPY,
  reims: REIMS_COPY,
  rennes: RENNES_COPY,
  rouen: ROUEN_COPY,
  "saint-denis": SAINT_DENIS_COPY,
  "saint-etienne": SAINT_ETIENNE_COPY,
  strasbourg: STRASBOURG_COPY,
  toulon: TOULON_COPY,
  toulouse: TOULOUSE_COPY,
  tours: TOURS_COPY,
  villeurbanne: VILLEURBANNE_COPY,
};

// La liste brute vient de `core.ts` (data/ seul) — plus de duplication ici.
const RAW_VILLES: ReadonlyArray<VilleData> = VILLES_CORE;

export const VILLES: ReadonlyArray<Ville> = RAW_VILLES.map((v) => {
  const copy = COPY_BY_SLUG[v.slug];
  const economicData = getVilleEconomicData(v.slug);
  const base: Ville = { ...v };
  // Résolution des tokens prix {{price:<tierId>}} → valeur SSOT (pricing.ts),
  // appliquée ICI (couche données) pour couvrir TOUS les consommateurs de
  // `.copy` — hub ville (async), pages région/sitemap/opengraph (sync direct),
  // VilleServicePageTemplate — sans dépendre d'un point de rendu unique.
  if (copy) base.copy = resolvePriceTokensDeep(copy, "fr");
  if (economicData) base.economicData = economicData;
  return base;
});

const SLUG_INDEX = new Map(VILLES.map((v) => [v.slug, v] as const));
const INSEE_INDEX = new Map(VILLES.map((v) => [v.inseeCode, v] as const));

export function getVille(slug: string): Ville | undefined {
  return SLUG_INDEX.get(slug);
}

export function getVilleByInsee(inseeCode: string): Ville | undefined {
  return INSEE_INDEX.get(inseeCode);
}

export function getAllVilleSlugs(): ReadonlyArray<string> {
  return VILLES.map((v) => v.slug);
}

export function getVillesByRegion(regionSlug: string): ReadonlyArray<Ville> {
  return VILLES.filter((v) => v.region === regionSlug);
}

// ─── Phasing indexation — délégué à `core.ts` ────────────────────────────────
//
// Tout le calcul (constantes de drip, `RANKED_INDEXABLE`, tri, cohorte) a été
// DÉPLACÉ dans `./core.ts` le 2026-08-16, sans changement de comportement : il ne
// dépend que de champs structurels et de trois ensembles de slugs, jamais du
// corps des `copy`. Le garder ici obligeait tout consommateur de
// `isVilleIndexable` à charger 29 Mo de contenu éditorial pour obtenir un booléen.
//
// On ne réimplémente RIEN ci-dessous : on enrobe. Une seule source de vérité pour
// les décisions d'indexation (robots des pages, sitemap, whitelist Edge).

/** Ville premium = a un copy ET (pop ≥ 20k OU rewrite premium MANUAL-REWRITE). */
export function isPremiumVille(v: Ville): boolean {
  return isPremiumVilleCore(v);
}

/** Taille de la cohorte indexable à la date `now`. Cf. `core.cohortSize`. */
export function cohortSize(now: Date = new Date()): number {
  return cohortSizeCore(now);
}

/** True si la ville (par slug) est indexable. Cf. `core.isVilleIndexable`. */
export function isVilleIndexable(slug: string, now: Date = new Date()): boolean {
  return isVilleIndexableCore(slug, now);
}

/**
 * Pages villes ÉLIGIBLES à indexation (= ont un `copy` éditorial substantiel,
 * pas un stub anti-doorway HCU). Sémantique « destinées à être indexées à
 * terme » — utilisée par le sitemap (structure de chunks), la whitelist Edge
 * `seo-noindex-routes.ts` (X-Robots-Tag) et son test de sync.
 *
 * ⚠️ Ne PAS confondre avec le drip temporel : une ville éligible n'est
 * réellement `index:true` aujourd'hui que si `isVilleIndexable(slug)` est vrai.
 */
export function getIndexableVilles(): ReadonlyArray<Ville> {
  return VILLES.filter((v) => hasVilleCopy(v.slug));
}

/**
 * Villes réellement dans la cohorte indexable À LA DATE `now`. Sous-ensemble de
 * `getIndexableVilles()`, dans l'ordre de classement de `core`. Cf. [[isVilleIndexable]].
 */
export function getVillesIndexableNow(now: Date = new Date()): ReadonlyArray<Ville> {
  // `core` donne l'ordre ; on ré-hydrate chaque entrée avec son `copy`.
  return getVillesCoreIndexableNow(now).map((v) => SLUG_INDEX.get(v.slug) as Ville);
}

export function getVillesByDepartement(code: string): ReadonlyArray<Ville> {
  return VILLES.filter((v) => v.departement === code);
}

/**
 * Retourne la région métropolitaine contenant le code département fourni,
 * ou undefined si le code n'appartient à aucune région connue (DROM hors V1).
 * P2-4 Sprint S+5 — utilisé pour réconcilier un cas concret département-only
 * vers sa région parente sans relire VILLES.
 */
export function getRegionByDepartement(code: string): Region | undefined {
  return getRegionByDepartementCore(code);
}
