// Villes — barrel + composite type + helpers (Sprint 14.9, ADR 0006).
//
// Architecture (cf. doctrine pSEO villes/régions) :
//   data/<region-slug>.ts   ← VilleData[] structurel INSEE (régénéré par script)
//   copy/<slug>.ts          ← VilleCopy éditorial gold standard (curaté manuellement)
//   index.ts                ← composite Ville = VilleData & { copy? } + helpers
//
// Règle anti-doorway HCU 2024 : seules les villes avec `copy` sont
// `indexable` (cf. `getIndexableVilles()`). Les ~2 280 communes sans copy
// existent en SSG mais sortent en `<meta name="robots" content="noindex" />`.

import type { VilleData } from "./data/types";
import type { VilleCopy } from "./copy/types";
import type { VilleEconomicData } from "./economic-data/types";
import { getVilleEconomicData } from "./economic-data";
import { PREMIUM_REWRITE_SLUGS } from "./premium-rewrite-slugs";
import { UNIQUE_VILLE_SLUGS } from "./unique-ville-slugs";
import { REGIONS, type Region } from "@/content/regions";

import { VILLES_ILE_DE_FRANCE } from "./data/ile-de-france";
import { VILLES_AUVERGNE_RHONE_ALPES } from "./data/auvergne-rhone-alpes";
import { VILLES_PROVENCE_ALPES_COTE_D_AZUR } from "./data/provence-alpes-cote-d-azur";
import { VILLES_OCCITANIE } from "./data/occitanie";
import { VILLES_NOUVELLE_AQUITAINE } from "./data/nouvelle-aquitaine";
import { VILLES_HAUTS_DE_FRANCE } from "./data/hauts-de-france";
import { VILLES_GRAND_EST } from "./data/grand-est";
import { VILLES_PAYS_DE_LA_LOIRE } from "./data/pays-de-la-loire";
import { VILLES_BRETAGNE } from "./data/bretagne";
import { VILLES_NORMANDIE } from "./data/normandie";
import { VILLES_BOURGOGNE_FRANCHE_COMTE } from "./data/bourgogne-franche-comte";
import { VILLES_CENTRE_VAL_DE_LOIRE } from "./data/centre-val-de-loire";
import { VILLES_CORSE } from "./data/corse";

import { AIX_EN_PROVENCE_COPY } from "./copy/aix-en-provence";
import { AMIENS_COPY } from "./copy/amiens";
import { ANGERS_COPY } from "./copy/angers";
import { ANNECY_COPY } from "./copy/annecy";
import { ARGENTEUIL_COPY } from "./copy/argenteuil";
import { BESANCON_COPY } from "./copy/besancon";
import { BORDEAUX_COPY } from "./copy/bordeaux";
import { BOULOGNE_BILLANCOURT_COPY } from "./copy/boulogne-billancourt";
import { BREST_COPY } from "./copy/brest";
import { CAEN_COPY } from "./copy/caen";
import { CLERMONT_FERRAND_COPY } from "./copy/clermont-ferrand";
import { DIJON_COPY } from "./copy/dijon";
import { GRENOBLE_COPY } from "./copy/grenoble";
import { LE_HAVRE_COPY } from "./copy/le-havre";
import { LE_MANS_COPY } from "./copy/le-mans";
import { LILLE_COPY } from "./copy/lille";
import { LIMOGES_COPY } from "./copy/limoges";
import { LYON_COPY } from "./copy/lyon";
import { MARSEILLE_COPY } from "./copy/marseille";
import { METZ_COPY } from "./copy/metz";
import { MONTPELLIER_COPY } from "./copy/montpellier";
import { MONTREUIL_COPY } from "./copy/montreuil";
import { MULHOUSE_COPY } from "./copy/mulhouse";
import { NANCY_COPY } from "./copy/nancy";
import { NANTES_COPY } from "./copy/nantes";
import { NICE_COPY } from "./copy/nice";
import { NIMES_COPY } from "./copy/nimes";
import { ORLEANS_COPY } from "./copy/orleans";
import { PARIS_COPY } from "./copy/paris";
import { PERPIGNAN_COPY } from "./copy/perpignan";
import { REIMS_COPY } from "./copy/reims";
import { RENNES_COPY } from "./copy/rennes";
import { ROUEN_COPY } from "./copy/rouen";
import { SAINT_DENIS_COPY } from "./copy/saint-denis";
import { SAINT_ETIENNE_COPY } from "./copy/saint-etienne";
import { STRASBOURG_COPY } from "./copy/strasbourg";
import { TOULON_COPY } from "./copy/toulon";
import { TOULOUSE_COPY } from "./copy/toulouse";
import { TOURS_COPY } from "./copy/tours";
import { VILLEURBANNE_COPY } from "./copy/villeurbanne";

// Auto-generated T3 batch 2026-05-27 — ~390 villes LLM-generated copies.
// Re-generated by `scripts/export-villecopy-db-to-ts.ts` depuis DB
// GeneratedVilleCopy.status='approved'. Mergé avec les copies manuelles
// ci-dessous (les manuelles gagnent en cas de slug collision via spread order).
import { AUTO_GENERATED_COPIES_BY_SLUG } from "./copy/_auto-generated-index";
import { resolvePriceTokensDeep } from "@/content/pricing-tokens";

export type { VilleData } from "./data/types";
export type { VilleCopy, VilleFaq } from "./copy/types";

/** Type composite consommé par les pages et helpers (geo.ts, sitemap, etc.). */
export interface Ville extends VilleData {
  /** Contenu éditorial gold standard. Présent ⇒ page indexable. */
  copy?: VilleCopy;
  /**
   * Data économique enrichie (secteurs NAF, pôles, distances, KB tags…)
   * sourcée. Consommée par ContentGen RAG + dashboard /content-gen/city-coverage.
   * Sprint City Quality 2026-05-18 — contrat zéro invention.
   */
  economicData?: VilleEconomicData;
}

// Lookup slug → contenu éditorial. Étendu manuellement à mesure que les
// pages villes gold standard sont produites (Paris d'abord, puis 50 top, etc.).
// Spread order : auto-generated en premier (priorité basse), manuels ensuite
// (priorité haute en cas de collision slug — manuels gold standard gagnent).
const COPY_BY_SLUG: Record<string, VilleCopy> = {
  ...AUTO_GENERATED_COPIES_BY_SLUG,
  "aix-en-provence": AIX_EN_PROVENCE_COPY,
  amiens: AMIENS_COPY,
  angers: ANGERS_COPY,
  annecy: ANNECY_COPY,
  argenteuil: ARGENTEUIL_COPY,
  besancon: BESANCON_COPY,
  bordeaux: BORDEAUX_COPY,
  "boulogne-billancourt": BOULOGNE_BILLANCOURT_COPY,
  brest: BREST_COPY,
  caen: CAEN_COPY,
  "clermont-ferrand": CLERMONT_FERRAND_COPY,
  dijon: DIJON_COPY,
  grenoble: GRENOBLE_COPY,
  "le-havre": LE_HAVRE_COPY,
  "le-mans": LE_MANS_COPY,
  lille: LILLE_COPY,
  limoges: LIMOGES_COPY,
  lyon: LYON_COPY,
  marseille: MARSEILLE_COPY,
  metz: METZ_COPY,
  montpellier: MONTPELLIER_COPY,
  montreuil: MONTREUIL_COPY,
  mulhouse: MULHOUSE_COPY,
  nancy: NANCY_COPY,
  nantes: NANTES_COPY,
  nice: NICE_COPY,
  nimes: NIMES_COPY,
  orleans: ORLEANS_COPY,
  paris: PARIS_COPY,
  perpignan: PERPIGNAN_COPY,
  reims: REIMS_COPY,
  rennes: RENNES_COPY,
  rouen: ROUEN_COPY,
  "saint-denis": SAINT_DENIS_COPY,
  "saint-etienne": SAINT_ETIENNE_COPY,
  strasbourg: STRASBOURG_COPY,
  toulon: TOULON_COPY,
  toulouse: TOULOUSE_COPY,
  tours: TOURS_COPY,
  villeurbanne: VILLEURBANNE_COPY,
};

const RAW_VILLES: ReadonlyArray<VilleData> = [
  ...VILLES_ILE_DE_FRANCE,
  ...VILLES_AUVERGNE_RHONE_ALPES,
  ...VILLES_PROVENCE_ALPES_COTE_D_AZUR,
  ...VILLES_OCCITANIE,
  ...VILLES_NOUVELLE_AQUITAINE,
  ...VILLES_HAUTS_DE_FRANCE,
  ...VILLES_GRAND_EST,
  ...VILLES_PAYS_DE_LA_LOIRE,
  ...VILLES_BRETAGNE,
  ...VILLES_NORMANDIE,
  ...VILLES_BOURGOGNE_FRANCHE_COMTE,
  ...VILLES_CENTRE_VAL_DE_LOIRE,
  ...VILLES_CORSE,
];

export const VILLES: ReadonlyArray<Ville> = RAW_VILLES.map((v) => {
  const copy = COPY_BY_SLUG[v.slug];
  const economicData = getVilleEconomicData(v.slug);
  const base: Ville = { ...v };
  // Résolution des tokens prix {{price:<tierId>}} → valeur SSOT (pricing.ts),
  // appliquée ICI (couche données) pour couvrir TOUS les consommateurs de
  // `.copy` — hub ville (async), pages région/sitemap/opengraph (sync direct),
  // VilleServicePageTemplate — sans dépendre d'un point de rendu unique.
  if (copy) base.copy = resolvePriceTokensDeep(copy, "fr");
  if (economicData) base.economicData = economicData;
  return base;
});

const SLUG_INDEX = new Map(VILLES.map((v) => [v.slug, v] as const));
const INSEE_INDEX = new Map(VILLES.map((v) => [v.inseeCode, v] as const));

export function getVille(slug: string): Ville | undefined {
  return SLUG_INDEX.get(slug);
}

export function getVilleByInsee(inseeCode: string): Ville | undefined {
  return INSEE_INDEX.get(inseeCode);
}

export function getAllVilleSlugs(): ReadonlyArray<string> {
  return VILLES.map((v) => v.slug);
}

export function getVillesByRegion(regionSlug: string): ReadonlyArray<Ville> {
  return VILLES.filter((v) => v.region === regionSlug);
}

// ─── Phasing indexation — drip automatique anti « scaled content abuse » ─────
// Décision Will 2026-05-28 : toutes les villes finissent indexées, mais
// PROGRESSIVEMENT et AUTOMATIQUEMENT, pour ne pas exposer 2157 pages d'un coup
// à Google sur un domaine jeune (risque scaled-content / indexation partielle /
// jugement qualité site-wide). La cohorte indexable est calculée depuis la DATE
// runtime :
//   - Jour 0 (INDEXATION_START) : toutes les villes premium (pop ≥ 20k OU
//     rewrite premium MANUAL-REWRITE) = cohorte initiale ~655.
//   - +VILLES_PER_DAY villes/jour ensuite, par population décroissante.
//   → couverture 100 % des 2157 villes en ~30 jours, SANS intervention manuelle.
// Le sitemap (revalidate quotidien) + les pages villes (ISR 24 h) recalculent
// l'éligibilité chaque jour → la cohorte s'élargit toute seule. Pour accélérer/
// ralentir le ramp, ajuster VILLES_PER_DAY (1 commit). Pour tout indexer
// immédiatement, mettre INDEXATION_START loin dans le passé.
const INDEXATION_START = new Date("2026-05-28T00:00:00Z");
const VILLES_PER_DAY = 50;

// DRIP EN 2 PHASES (audit GSC 2026-06-05 A-01 ; décision Will 2026-06-05).
//
// PHASE 1 — BURST initial figé (~cohorte du 2026-06-06) : `min(elapsed, BURST_DAYS)`.
//   L'ancien ramp +50/JOUR noyait Google (famine crawl → 0 indexé). On fige donc le
//   socle initial à premium + BURST_DAYS*50.
//
// PHASE 2 — RÉOUVERTURE PROGRESSIVE AUTOMATIQUE & ACCÉLÉRANTE (à partir de REOPEN_START) :
//   les villes UNIQUES restantes ressortent du noindex toutes seules, par semaine, à un
//   rythme qui MONTE (le crawl de Google grandit avec l'âge + l'autorité du domaine) :
//     semaine 1 = +REOPEN_WEEK1 villes, puis +REOPEN_ACCEL de plus chaque semaine
//     (S1=100, S2=125, S3=150, S4=175, S5=200…) jusqu'à couvrir TOUTES les villes uniques.
//   → ~710 villes uniques restantes rouvertes en ~5-6 semaines, sans intervention.
//
// Garde-fous :
//   • « l'indexation ne rétracte JAMAIS » : `cohortSize` est monotone croissant (BURST figé
//     + réouverture qui ne fait qu'augmenter) → aucune ville déjà indexable ne repasse noindex.
//   • Les ~341 villes NON-uniques (quasi-doublons) ne sont PAS dans `RANKED_INDEXABLE` →
//     elles restent noindex pour toujours (anti-doorway HCU), la réouverture ne les touche pas.
//   • Pour accélérer/ralentir : ajuster REOPEN_WEEK1 / REOPEN_ACCEL (1 commit).
const BURST_DAYS = 9; // socle figé = premium + 9*50 (~cohorte du 2026-06-06)
const REOPEN_START = new Date("2026-06-06T00:00:00Z");
const REOPEN_WEEK1 = 100; // villes rouvertes la 1re semaine
const REOPEN_ACCEL = 25; // +25 villes/semaine de plus chaque semaine (S1=100…S5=200)
const WEEK_MS = 7 * 86_400_000;

/** Nb de villes uniques rouvertes (cumul) depuis REOPEN_START — accélérant par semaine. */
function reopenedSince(now: Date): number {
  const ms = now.getTime() - REOPEN_START.getTime();
  if (ms <= 0) return 0;
  const w = Math.floor(ms / WEEK_MS); // semaines pleines écoulées
  // cumul = Σ_{k=1..w} (REOPEN_WEEK1 + REOPEN_ACCEL*(k-1))
  return REOPEN_WEEK1 * w + (REOPEN_ACCEL * (w * (w - 1))) / 2;
}

/** Ville premium = a un copy ET (pop ≥ 20k OU rewrite premium MANUAL-REWRITE). */
export function isPremiumVille(v: Ville): boolean {
  return !!v.copy && (v.population >= 20_000 || PREMIUM_REWRITE_SLUGS.has(v.slug));
}

// Villes RÉELLEMENT indexables — garde-fou anti-doorway au mérite (décision Will
// 2026-05-31 « indexation au mérite + AEO », Phase 2B). Une ville n'entre dans la
// cohorte d'indexation que si elle a un `copy` ET passe le scorer d'unicité
// (`UNIQUE_VILLE_SLUGS` : score d'unicité ≥ 0.6 OU premium/gold force-inclus —
// cf. scripts/villes/compute-ville-uniqueness.ts). Les ~341 villes templatées
// (clusters de communes voisines quasi-identiques) restent PRÉSENTES, crawlables,
// maillées et citables par les IA (AEO), mais sortent `noindex` au niveau page
// (via `isVilleIndexable`) et hors sitemap — sans recréer de doorway HCU 2024.
//
// NB : `getIndexableVilles()` (= villes avec copy, 2157) reste la base structurelle
// stable du sitemap (chunks). La décision d'indexation effective (robots des
// pages + contenu du sitemap) passe, elle, par `isVilleIndexable` ⟶
// `RANKED_INDEXABLE`. Depuis l'audit indexation 2026-07-31, la whitelist Edge
// `seo-noindex-routes.ts` (X-Robots-Tag) suit AUSSI `isVilleIndexable`, via le
// fichier généré `src/generated/indexable-villes.ts` (régénérer avec
// `pnpm tsx scripts/gen-indexable-villes.ts` après modification des données).
//
// P0 2026-07-03 (décision Will) — CAP INDEXATION T1/T2 + CURÉES. Concentration
// du budget de crawl sur les villes à valeur pendant que l'infra d'indexation
// (backlinks, soumission sitemap GSC, cache CDN) est en cours de correction.
// On restreint la cohorte indexable aux villes PREMIUM : `isPremiumVille` = a un
// `copy` ET (population ≥ 20 000 [= T1/T2, 455 villes] OU réécriture manuelle
// gold `PREMIUM_REWRITE_SLUGS` [~25 petites villes curées]). Résultat ≈ 480
// villes indexées ; les ~1336 petites villes auto-templatées (T3/T4 non curées)
// passent `noindex,follow` + hors sitemap — mais restent live, crawlables,
// maillées et citables par les IA (AEO). ZÉRO risque doorway, crawl concentré.
// RÉVERSIBLE : retirer `isPremiumVille(v) &&` ci-dessous (retour à copy+unique,
// ~1816 indexées) quand l'autorité du site sera montée.
//
// Tri par priorité : premium d'abord (population décroissante), puis le reste.
// Ordre déterministe et stable entre builds (tri par pop puis slug en tie-break).
const RANKED_INDEXABLE: ReadonlyArray<Ville> = VILLES.filter(
  (v) => isPremiumVille(v) && UNIQUE_VILLE_SLUGS.has(v.slug),
).sort((a, b) => {
  const pa = isPremiumVille(a);
  const pb = isPremiumVille(b);
  if (pa !== pb) return pa ? -1 : 1;
  if (b.population !== a.population) return b.population - a.population;
  return a.slug.localeCompare(b.slug);
});

const PREMIUM_COUNT = RANKED_INDEXABLE.filter(isPremiumVille).length;
const INDEXABLE_RANK = new Map(RANKED_INDEXABLE.map((v, i) => [v.slug, i] as const));

/** Taille de la cohorte indexable à la date `now` (premium + ramp quotidien). */
export function cohortSize(now: Date = new Date()): number {
  const elapsed = Math.max(
    0,
    Math.floor((now.getTime() - INDEXATION_START.getTime()) / 86_400_000),
  );
  // Phase 1 : socle initial figé (~cohorte du 2026-06-06). Phase 2 : réouverture
  // automatique accélérante des villes uniques restantes (cf. reopenedSince).
  const burst = PREMIUM_COUNT + Math.min(elapsed, BURST_DAYS) * VILLES_PER_DAY;
  return Math.min(RANKED_INDEXABLE.length, burst + reopenedSince(now));
}

/**
 * True si la ville (par slug) est indexable.
 *
 * P0 2026-06-14 (décision Will) : le drip progressif est RETIRÉ — toutes les
 * villes UNIQUES éligibles (`RANKED_INDEXABLE` = copy + score d'unicité ≥ 0,6 ou
 * premium) sont indexables IMMÉDIATEMENT (le contenu villes est unique, validé
 * par la recette 2026-06-14). On ne gate plus sur `cohortSize(now)`.
 *
 * ⚠️ Les ~341 quasi-doublons (copy mais hors `UNIQUE_VILLE_SLUGS`) et les stubs
 * sans copy restent hors `RANKED_INDEXABLE` → `noindex` (anti-doorway HCU,
 * aucun contenu unique à indexer). `now` conservé pour compat de signature.
 */
export function isVilleIndexable(slug: string, now: Date = new Date()): boolean {
  void now;
  return INDEXABLE_RANK.has(slug);
}

/**
 * Pages villes ÉLIGIBLES à indexation (= ont un `copy` éditorial substantiel,
 * pas un stub anti-doorway HCU). Sémantique « destinées à être indexées à
 * terme » — utilisée par le sitemap (structure de chunks), la whitelist Edge
 * `seo-noindex-routes.ts` (X-Robots-Tag) et son test de sync.
 *
 * ⚠️ Ne PAS confondre avec le drip temporel : une ville éligible n'est
 * réellement `index:true` aujourd'hui que si `isVilleIndexable(slug)` est vrai
 * (cohorte du jour). Le sitemap filtre le CONTENU via `isVilleIndexable`, mais
 * la liste des sub-sitemaps reste basée sur l'ensemble éligible (structure stable).
 */
export function getIndexableVilles(): ReadonlyArray<Ville> {
  return VILLES.filter((v) => !!v.copy);
}

/**
 * Villes réellement dans la cohorte indexable À LA DATE `now` (drip progressif :
 * premium jour 0, puis +VILLES_PER_DAY/jour). Sous-ensemble de
 * `getIndexableVilles()`. Cf. [[isVilleIndexable]].
 */
export function getVillesIndexableNow(now: Date = new Date()): ReadonlyArray<Ville> {
  return RANKED_INDEXABLE.slice(0, cohortSize(now));
}

/**
 * Toutes les villes d'un département donné (code INSEE 2 ou 3 caractères :
 * "75", "13", "2A", "2B", "974" pour l'historique DROM, etc.).
 * Retourne un tableau vide si le code est inconnu (pas d'erreur).
 * P2-4 Sprint S+5 — utilisé par les pages /implantations/[region]/[dept] et
 * par les helpers content-gen quand un cas concret cible un département.
 */
export function getVillesByDepartement(code: string): ReadonlyArray<Ville> {
  return VILLES.filter((v) => v.departement === code);
}

/**
 * Retourne la région métropolitaine contenant le code département fourni,
 * ou undefined si le code n'appartient à aucune région connue (DROM hors V1).
 * P2-4 Sprint S+5 — utilisé pour réconcilier un cas concret département-only
 * vers sa région parente sans relire VILLES.
 */
export function getRegionByDepartement(code: string): Region | undefined {
  return REGIONS.find((r) => r.departements.includes(code));
}
