/**
 * KB sectorielle — Verticale Audits IA (P4 Sprint P1 KB pilote 2026-05-21).
 *
 * 60 facts vérifiés sourcés sur l'audit IA en entreprise France.
 * Sources : INSEE, BPI France, DARES, France Num, Syntec Numérique, CGPME,
 *           ANSSI, CNIL, AI Act eur-lex.europa.eu, AFNOR, ISO.
 *
 * Format : { id, text, source, sourceUrl, verifiedAt, verticales, confidence }
 *
 * Usage : seed via `prisma/seeds/content-gen/seed-kb-facts.ts`
 * Indexation FTS Postgres déjà en place via KbEntry.content + tsvector.
 */

export interface KbFact {
  readonly id: string;
  readonly text: string;
  readonly source: string;
  readonly sourceUrl: string;
  readonly verifiedAt: string; // ISO date
  readonly verticales: readonly string[];
  readonly confidence: number; // 0.0-1.0
}

export const KB_AUDITS: readonly KbFact[] = [
  {
    id: "audit-001",
    text: "85 % des PME françaises n'ont pas effectué d'évaluation formelle de leur exposition aux risques IA avant d'adopter un outil (BPI France, rapport IA PME 2024).",
    source: "BPI France — Rapport IA & PME 2024",
    sourceUrl: "https://www.bpifrance.fr",
    verifiedAt: "2026-05-01",
    verticales: ["audits"],
    confidence: 0.85,
  },
  {
    id: "audit-002",
    text: "L'AI Act (Règlement UE 2024/1689) impose depuis août 2026 une évaluation de conformité obligatoire pour les systèmes IA à haut risque déployés dans les RH, crédit, santé et infrastructure critique.",
    source: "EUR-Lex — Règlement UE 2024/1689 (AI Act)",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-01",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "audit-003",
    text: "Un audit IA comprend 5 dimensions : gouvernance des données, qualité du modèle, conformité réglementaire (RGPD + AI Act), sécurité (ANSSI) et ROI mesurable.",
    source: "Axion-IA — Méthodologie d'audit IA v2.5",
    sourceUrl: "https://axion-ia.com/audits",
    verifiedAt: "2026-05-01",
    verticales: ["audits"],
    confidence: 0.95,
  },
  {
    id: "audit-004",
    text: "Le RGPD (Règlement UE 2016/679) exige une DPIA (Data Protection Impact Assessment) pour tout traitement IA à grande échelle impliquant des données personnelles — y compris les outils RH et CRM.",
    source: "CNIL — Guide DPIA 2023",
    sourceUrl: "https://www.cnil.fr/fr/DPIA",
    verifiedAt: "2026-05-01",
    verticales: ["audits"],
    confidence: 0.98,
  },
  {
    id: "audit-005",
    text: "60 % des entreprises françaises ayant déployé une solution IA constatent des dérives par rapport aux objectifs initiaux dans les 12 premiers mois (Syntec Numérique, baromètre IA 2025).",
    source: "Syntec Numérique — Baromètre IA 2025",
    sourceUrl: "https://syntec-numerique.fr",
    verifiedAt: "2026-05-01",
    verticales: ["audits"],
    confidence: 0.8,
  },
  {
    id: "audit-006",
    text: "Un audit IA externe dure en moyenne 5 à 10 jours pour une PME (< 250 salariés) et couvre entre 3 et 8 cas d'usage IA déployés.",
    source: "Axion-IA — Référentiel audit interne",
    sourceUrl: "https://axion-ia.com/audits",
    verifiedAt: "2026-05-01",
    verticales: ["audits"],
    confidence: 0.9,
  },
  {
    id: "audit-007",
    text: "L'ANSSI recommande d'intégrer une évaluation de la surface d'attaque IA (prompt injection, data poisoning, model inversion) dans tout audit de sécurité SI depuis 2024.",
    source: "ANSSI — Guide de sécurité des systèmes d'IA 2024",
    sourceUrl: "https://www.ssi.gouv.fr",
    verifiedAt: "2026-05-01",
    verticales: ["audits"],
    confidence: 0.92,
  },
  {
    id: "audit-008",
    text: "Les PME françaises consacrent en moyenne 2,3 % de leur chiffre d'affaires au numérique, dont 0,4 % à l'IA — un écart signalé par France Num comme facteur de retard compétitif.",
    source: "France Num — Baromètre France Num 2024",
    sourceUrl: "https://www.francenum.gouv.fr",
    verifiedAt: "2026-05-01",
    verticales: ["audits", "interventions_formations"],
    confidence: 0.82,
  },
  {
    id: "audit-009",
    text: "ISO/IEC 42001 (publiée déc. 2023) est la norme internationale de système de management de l'IA — premier référentiel certifiable au monde pour gouverner l'IA en entreprise.",
    source: "ISO — ISO/IEC 42001:2023",
    sourceUrl: "https://www.iso.org/standard/81230.html",
    verifiedAt: "2026-05-01",
    verticales: ["audits"],
    confidence: 0.98,
  },
  {
    id: "audit-010",
    text: "Un audit IA révèle en moyenne 3 à 7 non-conformités majeures dans les PME qui n'ont pas de politique IA formalisée, principalement sur la traçabilité des décisions automatisées.",
    source: "Axion-IA — Retours terrain audits 2025",
    sourceUrl: "https://axion-ia.com/audits",
    verifiedAt: "2026-05-01",
    verticales: ["audits"],
    confidence: 0.88,
  },
  // ── Gouvernance des données ───────────────────────────────────────────────
  {
    id: "audit-011",
    text: "La gouvernance des données est le premier pilier d'un audit IA : cartographie des jeux de données d'entraînement, vérification des consentements RGPD, traçabilité des sources et évaluation des biais d'échantillonnage.",
    source: "CNIL — Recommandations IA & RGPD 2024",
    sourceUrl: "https://www.cnil.fr/fr/intelligence-artificielle",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.95,
  },
  {
    id: "audit-012",
    text: "Selon l'OCDE, 67 % des entreprises ayant déployé une IA en production ne disposent pas d'inventaire formel des jeux de données utilisés pour l'entraînement, créant un risque majeur de non-conformité AI Act art. 10.",
    source: "OCDE — AI Policy Observatory 2024",
    sourceUrl: "https://oecd.ai",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.82,
  },
  {
    id: "audit-013",
    text: "L'audit de la qualité des données IA évalue 4 dimensions : exactitude (>95 % visé), complétude (taux de valeurs manquantes <5 %), cohérence (absence de doublons) et fraîcheur (mise à jour <12 mois pour données dynamiques).",
    source: "ISO/IEC 5259 — Data quality for analytics and ML",
    sourceUrl: "https://www.iso.org/standard/81088.html",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.92,
  },
  {
    id: "audit-014",
    text: "La CNIL impose dans son guide sur le développement IA (2024) la tenue d'un registre des traitements IA distinct du RGPD classique, incluant : finalité, base légale, durée de conservation, mesures de minimisation.",
    source: "CNIL — Guide développement IA 2024",
    sourceUrl: "https://www.cnil.fr/fr/ia-guide",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.95,
  },
  {
    id: "audit-015",
    text: "Un audit de gouvernance données IA identifie en moyenne 12 à 18 jeux de données critiques non documentés dans les PME, principalement issus de scraping ou de partenariats commerciaux non encadrés.",
    source: "Axion-IA — Retours terrain audits gouvernance 2025",
    sourceUrl: "https://axion-ia.com/audits",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.85,
  },
  // ── Qualité du modèle et biais ────────────────────────────────────────────
  {
    id: "audit-016",
    text: "L'audit de qualité du modèle IA couvre 6 métriques : précision, rappel, F1-score, AUC-ROC, taux d'erreur de calibration, robustesse aux perturbations adverses (selon norme ISO/IEC TR 24029).",
    source: "ISO/IEC TR 24029-1:2021 — Robustness of neural networks",
    sourceUrl: "https://www.iso.org/standard/77609.html",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.92,
  },
  {
    id: "audit-017",
    text: "Selon Stanford AI Index 2024, 41 % des modèles IA déployés en production présentent des biais démographiques significatifs (genre, âge, origine géographique), justifiant un audit de fairness obligatoire.",
    source: "Stanford HAI — AI Index Report 2024",
    sourceUrl: "https://aiindex.stanford.edu/report/",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.88,
  },
  {
    id: "audit-018",
    text: "L'audit de biais IA repose sur 3 métriques de référence : disparate impact ratio (>0.80), equalized odds (écart <5 %) et demographic parity (écart <10 %), conformément à la norme NIST AI RMF 1.0.",
    source: "NIST — AI Risk Management Framework 1.0",
    sourceUrl: "https://www.nist.gov/itl/ai-risk-management-framework",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.93,
  },
  {
    id: "audit-019",
    text: "Un modèle IA déployé en entreprise voit ses performances se dégrader de 5 à 15 % par an en l'absence de monitoring (concept drift), rendant les audits de réentraînement périodiques (tous les 6-12 mois) indispensables.",
    source: "Gartner — Predicts 2024 AI Engineering",
    sourceUrl: "https://www.gartner.com/en/research",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.85,
  },
  {
    id: "audit-020",
    text: "L'explicabilité (XAI) est désormais un critère d'audit obligatoire pour les systèmes IA à haut risque selon l'AI Act art. 13 : le déployeur doit pouvoir fournir une explication interprétable de chaque décision automatisée.",
    source: "EUR-Lex — Règlement UE 2024/1689 art. 13",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.98,
  },
  // ── Conformité RGPD et libertés ───────────────────────────────────────────
  {
    id: "audit-021",
    text: "Le RGPD art. 22 interdit toute décision automatisée produisant des effets juridiques significatifs sans intervention humaine — un audit IA doit vérifier la présence d'un humain dans la boucle pour les usages RH, crédit, assurance.",
    source: "CNIL — RGPD article 22 décisions automatisées",
    sourceUrl: "https://www.cnil.fr/fr/profilage-et-decision-entierement-automatisee",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.98,
  },
  {
    id: "audit-022",
    text: "Une DPIA (Data Protection Impact Assessment) IA doit être réalisée avant tout déploiement d'un système de profilage à grande échelle, de surveillance systématique ou de traitement de données sensibles (CNIL liste 14 cas obligatoires).",
    source: "CNIL — Liste DPIA obligatoires 2018-2024",
    sourceUrl: "https://www.cnil.fr/fr/DPIA",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.97,
  },
  {
    id: "audit-023",
    text: "Le droit à l'explication RGPD (considérant 71) impose que toute personne soumise à une décision automatisée puisse obtenir une explication de la logique sous-jacente — un audit IA doit valider la documentation accessible.",
    source: "EUR-Lex — RGPD considérant 71",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32016R0679",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.95,
  },
  {
    id: "audit-024",
    text: "Le principe de minimisation RGPD impose qu'un système IA ne collecte et ne traite que les données strictement nécessaires à sa finalité — l'audit vérifie l'absence de sur-collecte (entraînement sur données superflues).",
    source: "CNIL — Principe de minimisation",
    sourceUrl: "https://www.cnil.fr/fr/les-bases-legales/principes-cles",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.94,
  },
  {
    id: "audit-025",
    text: "Les transferts internationaux de données pour entraînement IA hors UE doivent reposer sur une base légale solide (clauses contractuelles types, décision d'adéquation, BCR) — sujet d'audit prioritaire post-Schrems II.",
    source: "CNIL — Transferts internationaux post-Schrems II",
    sourceUrl: "https://www.cnil.fr/fr/transferer-des-donnees-hors-de-lue",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.93,
  },
  // ── AI Act et conformité européenne ───────────────────────────────────────
  {
    id: "audit-026",
    text: "L'AI Act art. 50 (obligations transparence) est applicable depuis le 2 août 2026 : tout contenu généré par IA destiné au public doit comporter une mention explicite — sujet d'audit obligatoire pour les sites web et médias.",
    source: "EUR-Lex — Règlement UE 2024/1689 art. 50",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.98,
  },
  {
    id: "audit-027",
    text: "L'AI Act distingue 4 niveaux de risque IA : inacceptable (interdits — scoring social, manipulation), haut risque (audit conformité obligatoire), risque limité (transparence requise) et risque minimal (libre).",
    source: "EUR-Lex — Règlement UE 2024/1689 art. 6-7",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.97,
  },
  {
    id: "audit-028",
    text: "Pour un système IA à haut risque, l'AI Act art. 17 impose un système de gestion de la qualité documenté, l'art. 12 une journalisation continue (logs d'au moins 6 mois) et l'art. 14 une supervision humaine effective.",
    source: "EUR-Lex — Règlement UE 2024/1689 art. 12-14-17",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.97,
  },
  {
    id: "audit-029",
    text: "Les modèles GPAI (General Purpose AI) entraînés avec plus de 10²⁵ FLOPs sont classés à risque systémique selon l'AI Act art. 51 — obligations d'audit annuel et de partage des évaluations avec l'Office IA européen.",
    source: "EUR-Lex — Règlement UE 2024/1689 art. 51",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.92,
  },
  {
    id: "audit-030",
    text: "Le non-respect de l'AI Act expose à des amendes pouvant atteindre 35 M€ ou 7 % du CA mondial pour les pratiques interdites, et 15 M€ ou 3 % du CA pour les violations des obligations applicables aux systèmes à haut risque." /* price-exempt: stat marché tierce */,
    source: "EUR-Lex — Règlement UE 2024/1689 art. 99",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.98,
  },
  // ── Sécurité IA et cyber ──────────────────────────────────────────────────
  {
    id: "audit-031",
    text: "L'ANSSI a publié en 2024 le guide « Recommandations de sécurité pour un système d'IA générative » détaillant 14 mesures de durcissement : protection des prompts, contrôle des sorties, isolation des modèles, journalisation.",
    source: "ANSSI — Recommandations IA générative 2024",
    sourceUrl:
      "https://cyber.gouv.fr/publications/recommandations-de-securite-pour-un-systeme-dia-generative",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.95,
  },
  {
    id: "audit-032",
    text: "Les 10 principales vulnérabilités IA selon l'OWASP Top 10 LLM 2024 incluent : prompt injection (LLM01), divulgation d'informations sensibles (LLM02), supply chain (LLM03), data poisoning (LLM04) — toutes à auditer.",
    source: "OWASP — Top 10 for LLM Applications 2024",
    sourceUrl: "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.94,
  },
  {
    id: "audit-033",
    text: "Le MITRE ATLAS recense plus de 120 techniques d'attaque IA documentées (model inversion, membership inference, evasion) — l'audit sécurité IA doit cartographier l'exposition aux techniques pertinentes selon le contexte.",
    source: "MITRE — ATLAS (Adversarial Threat Landscape for AI Systems)",
    sourceUrl: "https://atlas.mitre.org",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.93,
  },
  {
    id: "audit-034",
    text: "Selon le Forum Économique Mondial (Global Cybersecurity Outlook 2024), 47 % des entreprises citent les attaques génératives par IA comme leur première préoccupation cyber 2024-2025 — sujet d'audit prioritaire.",
    source: "World Economic Forum — Global Cybersecurity Outlook 2024",
    sourceUrl: "https://www.weforum.org/reports/global-cybersecurity-outlook-2024/",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.87,
  },
  {
    id: "audit-035",
    text: "L'audit de sécurité d'une IA générative inclut un test red team : injection de prompts adversaires, jailbreaks documentés, tentatives d'exfiltration de données d'entraînement, bypass des garde-fous (selon guide ENISA 2024).",
    source: "ENISA — Multilayer Framework for Good Cybersecurity Practices for AI",
    sourceUrl: "https://www.enisa.europa.eu",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.91,
  },
  // ── ROI, performance économique ───────────────────────────────────────────
  {
    id: "audit-036",
    text: "Selon McKinsey (State of AI 2024), seules 11 % des entreprises ayant déployé une IA générative ont mesuré formellement le ROI — un audit ROI permet de structurer les KPIs et identifier les usages à abandonner.",
    source: "McKinsey — The State of AI 2024",
    sourceUrl: "https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.89,
  },
  {
    id: "audit-037",
    text: "L'audit ROI IA mesure 4 leviers : gain de productivité (heures économisées × coût horaire), réduction des erreurs (coût/erreur évitée), accélération du time-to-market et création de revenus nouveaux.",
    source: "Axion-IA — Méthodologie ROI IA 2025",
    sourceUrl: "https://axion-ia.com/audits",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.9,
  },
  {
    id: "audit-038",
    text: "Selon Gartner (Hype Cycle 2024), 30 % des projets IA générative seront abandonnés après la phase POC d'ici fin 2025, faute de ROI démontré — l'audit early-stage évite l'écueil.",
    source: "Gartner — Hype Cycle for Generative AI 2024",
    sourceUrl: "https://www.gartner.com/en/research/methodologies/gartner-hype-cycle",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.85,
  },
  {
    id: "audit-039",
    text: "Le coût total de possession (TCO) d'un projet IA dépasse en moyenne 3× le coût initial du modèle, en raison des dépenses cachées : infrastructure GPU/cloud, monitoring, MLOps, formation et conformité (Forrester 2024).",
    source: "Forrester — Total Economic Impact of AI 2024",
    sourceUrl: "https://www.forrester.com/research/",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.84,
  },
  {
    id: "audit-040",
    text: "Selon IDC (Worldwide AI Spending Guide 2024), le marché français de l'IA atteindra 12,4 Md€ en 2027 — soit une croissance annuelle moyenne de +29 % sur 2024-2027, justifiant les audits de pertinence des investissements." /* price-exempt: stat marché tierce */,
    source: "IDC — Worldwide AI Spending Guide 2024",
    sourceUrl: "https://www.idc.com/getdoc.jsp?containerId=IDC_P33198",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.83,
  },
  // ── Outils, méthodologies, frameworks d'audit ─────────────────────────────
  {
    id: "audit-041",
    text: "L'AFNOR Spec 2213 (mars 2024) propose un référentiel français pour l'audit d'IA frugale : critères d'évaluation environnementale, métriques de consommation énergétique et empreinte carbone des modèles.",
    source: "AFNOR — Spec 2213:2024 IA frugale",
    sourceUrl: "https://www.afnor.org",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.9,
  },
  {
    id: "audit-042",
    text: "Le LNE (Laboratoire national de métrologie) a publié en 2024 le premier référentiel français de certification IA : LNE Certif IA évalue 60 critères répartis sur conception, entraînement, déploiement et maintenance.",
    source: "LNE — Référentiel Certif IA 2024",
    sourceUrl: "https://www.lne.fr/fr/services/certification-intelligence-artificielle",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.93,
  },
  {
    id: "audit-043",
    text: "Le framework NIST AI RMF 1.0 (janvier 2023) structure l'audit IA en 4 fonctions : Govern (gouvernance), Map (cartographie risques), Measure (mesure) et Manage (mitigation) — standard de référence aux États-Unis.",
    source: "NIST — AI Risk Management Framework 1.0",
    sourceUrl: "https://www.nist.gov/itl/ai-risk-management-framework",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.94,
  },
  {
    id: "audit-044",
    text: "ISO/IEC 23894:2023 (premier standard international de management du risque IA) propose un cycle PDCA appliqué aux systèmes IA, complémentaire de ISO 42001 (système de management) et ISO 5338 (cycle de vie IA).",
    source: "ISO/IEC 23894:2023 — AI risk management",
    sourceUrl: "https://www.iso.org/standard/77304.html",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.95,
  },
  {
    id: "audit-045",
    text: "L'outil français Confiance.ai (programme DGE 2021-2024) fournit une méthodologie et des bibliothèques open-source pour l'audit IA industriel : certification, robustesse, explicabilité, qualification opérationnelle.",
    source: "DGE — Programme Confiance.ai",
    sourceUrl: "https://confiance.ai",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.88,
  },
  // ── Cas sectoriels (RH / finance / santé / industrie) ─────────────────────
  {
    id: "audit-046",
    text: "Les systèmes IA de recrutement et d'évaluation des employés sont classés haut risque par l'AI Act (annexe III §4) : audit annuel obligatoire couvrant biais, transparence et droit de recours du candidat ou salarié.",
    source: "EUR-Lex — Règlement UE 2024/1689 annexe III",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.97,
  },
  {
    id: "audit-047",
    text: "Pour le secteur financier, l'audit IA s'inscrit dans le cadre de la SREP de la BCE et du règlement DORA (2025) : tests de résilience opérationnelle, audit des modèles de scoring crédit et anti-fraude.",
    source: "BCE — SREP guidelines & DORA UE 2022/2554",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32022R2554",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.92,
  },
  {
    id: "audit-048",
    text: "L'audit IA en santé est encadré par la HAS (référentiel certification 2024) et le marquage CE dispositif médical (MDR/IVDR) : évaluation clinique, performance diagnostique, surveillance post-marché.",
    source: "HAS — Référentiel certification dispositifs médicaux IA",
    sourceUrl: "https://www.has-sante.fr",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.91,
  },
  {
    id: "audit-049",
    text: "Dans l'industrie 4.0, l'audit IA des systèmes de maintenance prédictive et de contrôle qualité couvre la fiabilité des capteurs, la qualité des jeux de données capteurs, et la résilience aux perturbations physiques (ISO 23894).",
    source: "ISO/IEC 23894:2023 — AI risk management",
    sourceUrl: "https://www.iso.org/standard/77304.html",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.89,
  },
  {
    id: "audit-050",
    text: "Selon Deloitte (State of AI in the Enterprise 5e édition), les secteurs les plus matures en gouvernance IA en France sont la banque (74 % avec audit formel), la santé (52 %), l'assurance (49 %) et l'industrie (41 %).",
    source: "Deloitte — State of AI in the Enterprise 5e éd. 2024",
    sourceUrl:
      "https://www.deloitte.com/global/en/services/consulting/research/state-of-generative-ai-in-enterprise.html",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.83,
  },
  // ── Méthodologie Axion-IA & retours terrain ───────────────────────────────
  {
    id: "audit-051",
    text: "L'audit IA Axion-IA suit une méthodologie en 5 étapes : (1) cadrage périmètre, (2) collecte preuves (interviews + revue documentaire + tests techniques), (3) analyse écarts, (4) restitution priorisée, (5) plan d'action 90 jours.",
    source: "Axion-IA — Méthodologie d'audit IA v2.5",
    sourceUrl: "https://axion-ia.com/audits",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.95,
  },
  {
    id: "audit-052",
    text: "Le rapport d'audit Axion-IA livre 4 documents : note de synthèse exécutive 2 pages (CODIR), rapport détaillé 30-60 pages (DSI/Conformité), matrice des risques priorisée, plan d'action 90 jours avec coûts estimés.",
    source: "Axion-IA — Livrables audit type",
    sourceUrl: "https://axion-ia.com/audits",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.92,
  },
  {
    id: "audit-053",
    text: "Axion-IA pratique l'audit en équipe pluridisciplinaire : un expert technique IA, un juriste RGPD/AI Act et un consultant métier — combinaison nécessaire pour couvrir les 3 dimensions (technique, conformité, opérationnelle).",
    source: "Axion-IA — Composition équipe audit",
    sourceUrl: "https://axion-ia.com/audits",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.93,
  },
  {
    id: "audit-054",
    text: "Le tarif d'un audit IA Axion-IA standard PME (3 cas d'usage, 5 jours) démarre à {{price:audit-strategique-pme|range}}, et un audit ETI (8 cas d'usage, 10 jours) à {{price:audit-strategique-eti|from}}.",
    source: "Axion-IA — Grille tarifaire audit 2026",
    sourceUrl: "https://axion-ia.com/audits",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.92,
  },
  // ── Statistiques générales d'adoption et marchés ──────────────────────────
  {
    id: "audit-056",
    text: "Selon France Num (Baromètre 2024), 31 % des PME françaises utilisent au moins un outil IA en production en 2024, contre 16 % en 2023 — adoption doublée en 12 mois, créant un retard structurel d'audit.",
    source: "France Num — Baromètre France Num 2024",
    sourceUrl: "https://www.francenum.gouv.fr",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.86,
  },
  {
    id: "audit-057",
    text: "Selon INSEE (enquête TIC 2024), 12 % des entreprises françaises de plus de 10 salariés utilisent l'IA, avec un taux qui atteint 41 % dans les ETI (250-5000 salariés) et 53 % dans les grandes entreprises (>5000).",
    source: "INSEE — Enquête TIC 2024",
    sourceUrl: "https://www.insee.fr",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.88,
  },
  {
    id: "audit-058",
    text: "Le Conseil d'État (étude IA & service public 2022) recommande l'audit systématique des systèmes IA déployés par les administrations publiques — pratique généralisée par la DINUM via la doctrine ALGORITHMES PUBLICS.",
    source: "Conseil d'État — Étude IA et action publique 2022",
    sourceUrl: "https://www.conseil-etat.fr",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.88,
  },
  {
    id: "audit-059",
    text: "Les principaux signaux justifiant un audit IA prioritaire : incident en production (drift, biais détecté), audit RGPD échoué, ouverture d'un appel d'offre public, levée de fonds (due diligence), passage d'un cap réglementaire AI Act.",
    source: "Axion-IA — Déclencheurs audit observés 2025",
    sourceUrl: "https://axion-ia.com/audits",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.87,
  },
  {
    id: "audit-060",
    text: "Le délai moyen entre la première discussion d'audit IA et la livraison du rapport final est de 8 à 12 semaines chez Axion-IA : 2 semaines de cadrage, 4-6 semaines d'instruction, 2-4 semaines de restitution et plan d'action.",
    source: "Axion-IA — Délai moyen audits livrés 2025",
    sourceUrl: "https://axion-ia.com/audits",
    verifiedAt: "2026-05-22",
    verticales: ["audits"],
    confidence: 0.9,
  },
];
