/**
 * KB sectorielle — Verticale Implémentations IA (P6 2026-05-22).
 *
 * 32 facts vérifiés sur les implémentations IA en entreprise France.
 * Sources : McKinsey, Gartner, BPI France, DGE, Syntec Numérique,
 *           AI Act EUR-Lex, Axion-IA terrain.
 *
 * Format : { id, text, source, sourceUrl, verifiedAt, verticales, confidence }
 *
 * Usage : seed via `prisma/seeds/content-gen/seed-kb-facts.ts`
 * Indexation FTS Postgres déjà en place via KbEntry.content + tsvector.
 */

import type { KbFact } from "./audits";
export type { KbFact };

export const KB_IMPLEMENTATIONS: readonly KbFact[] = [
  // ── Offre Axion-IA implémentations ───────────────────────────────────────
  {
    id: "impl-001",
    text: "Axion-IA conçoit et déploie des chatbots IA métier pour les PME/ETI : traitement des demandes clients, FAQ dynamique, assistance interne RH/finance — basés sur Claude API (Anthropic) avec base de connaissance RAG.",
    source: "Axion-IA — Catalogue implémentations 2026",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.95,
  },
  {
    id: "impl-002",
    text: "Les systèmes RAG (Retrieval-Augmented Generation) déployés par Axion-IA permettent d'interroger des bases documentaires internes (contrats, procédures, emails) via une interface conversationnelle — sans que les données quittent l'infrastructure cliente.",
    source: "Axion-IA — Documentation technique RAG v2.1",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.95,
  },
  {
    id: "impl-003",
    text: "La stack technique standard des implémentations Axion-IA : Next.js (frontend + API routes), Claude API Anthropic (LLM), PostgreSQL + pgvector (base vectorielle), Vercel ou Hetzner (hébergement), Prisma (ORM).",
    source: "Axion-IA — Documentation technique stack v2.5",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.95,
  },
  {
    id: "impl-004",
    text: "Les automatisations IA Axion-IA couvrent 6 domaines prioritaires : traitement d'emails, génération de devis/rapports, veille sectorielle, extraction de données (OCR + LLM), scoring de leads et relances commerciales automatisées.",
    source: "Axion-IA — Catalogue implémentations 2026",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.95,
  },
  // ── Délais et phases ─────────────────────────────────────────────────────
  {
    id: "impl-005",
    text: "Le délai de livraison d'un chatbot RAG Axion-IA (conception à mise en production) est de 4 à 8 semaines selon la complexité de la base documentaire et le nombre d'intégrations avec les SI existants.",
    source: "Axion-IA — Référentiel projets implémentations 2025",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.9,
  },
  {
    id: "impl-006",
    text: "Un projet d'implémentation IA Axion-IA se déroule en 5 phases : (1) audit des besoins et données (1 sem), (2) POC fonctionnel (2 sem), (3) développement et tests (3-6 sem), (4) formation des utilisateurs (1 sem), (5) suivi prod 3 mois.",
    source: "Axion-IA — Méthodologie projet IA v3.0",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.95,
  },
  {
    id: "impl-007",
    text: "Les projets d'implémentation IA complexes (multi-modules, intégration ERP/CRM, déploiement multi-sites) nécessitent 3 à 6 mois — avec un chef de projet Axion-IA dédié et des jalons hebdomadaires.",
    source: "Axion-IA — Référentiel projets implémentations 2025",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.9,
  },
  // ── Tarifs ────────────────────────────────────────────────────────────────
  {
    id: "impl-008",
    text: "Chatbot RAG basique Axion-IA (jusqu'à 1 000 documents, 1 canal, 2 intégrations) : 8 000 à 15 000 € HT en développement + 500 à 1 200 € HT/mois en maintenance et infra.",
    source: "Axion-IA — Grille tarifaire implémentations 2026",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.88,
  },
  {
    id: "impl-009",
    text: "Automatisation de workflow IA (Make/Zapier + LLM) Axion-IA : 3 000 à 8 000 € HT selon le nombre d'étapes et d'intégrations — ROI moyen constaté inférieur à 6 mois.",
    source: "Axion-IA — Grille tarifaire implémentations 2026",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.88,
  },
  {
    id: "impl-010",
    text: "Projet d'implémentation IA complexe Axion-IA (système multi-agents, intégration ERP, tableau de bord IA) : 25 000 à 80 000 € HT selon périmètre — avec garantie de résultats définie contractuellement.",
    source: "Axion-IA — Grille tarifaire implémentations 2026",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.85,
  },
  // ── ROI et chiffres marché ────────────────────────────────────────────────
  {
    id: "impl-011",
    text: "Le ROI moyen des implémentations IA en PME française est de 2,8x l'investissement sur 24 mois, avec un délai de retour à l'équilibre de 8 à 14 mois (BPI France, Observatoire IA PME 2025).",
    source: "BPI France — Observatoire IA & PME 2025",
    sourceUrl: "https://www.bpifrance.fr",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.78,
  },
  {
    id: "impl-012",
    text: "McKinsey (2024) évalue à 200-340 milliards de dollars le potentiel de valeur de l'IA générative dans les seules fonctions support (finance, RH, juridique, IT) des grandes entreprises mondiales.",
    source: "McKinsey Global Institute — The economic potential of generative AI, 2024",
    sourceUrl: "https://www.mckinsey.com",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.82,
  },
  {
    id: "impl-013",
    text: "Gartner prédit qu'en 2026, 80 % des entreprises auront utilisé l'IA générative dans au moins un de leurs processus métier — contre 5 % en 2023.",
    source: "Gartner — AI in Business Survey 2024",
    sourceUrl: "https://www.gartner.com",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.82,
  },
  // ── Sécurité et conformité ────────────────────────────────────────────────
  {
    id: "impl-014",
    text: "Toutes les implémentations IA Axion-IA respectent le RGPD par design : données personnelles non envoyées aux API IA tierces sans consentement, chiffrement au repos et en transit, droit à l'effacement garanti.",
    source: "Axion-IA — Politique RGPD implémentations v1.5",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.95,
  },
  {
    id: "impl-015",
    text: "Les chatbots IA Axion-IA intègrent nativement une bannière de transparence AI Act art. 50 : l'utilisateur est informé qu'il interagit avec un système IA — obligation légale en vigueur depuis août 2026.",
    source: "EUR-Lex — Règlement UE 2024/1689 (AI Act) art. 50",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.98,
  },
  {
    id: "impl-016",
    text: "Axion-IA utilise Claude API Anthropic (modèle Sonnet) comme LLM principal pour ses implémentations — choix motivé par la performance sur les textes techniques français, la politique de non-réutilisation des données clients et le coût par token.",
    source: "Axion-IA — Choix technologiques et ADR 2026",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.95,
  },
  // ── Cas d'usage prioritaires ──────────────────────────────────────────────
  {
    id: "impl-017",
    text: "Top 5 des cas d'usage IA déployés par Axion-IA en PME : (1) chatbot support client, (2) génération de propositions commerciales, (3) analyse de documents contractuels, (4) reporting automatique, (5) veille concurrentielle.",
    source: "Axion-IA — Bilan projets implémentations 2025",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.9,
  },
  {
    id: "impl-018",
    text: "Un chatbot IA de support client Axion-IA traite en moyenne 68 % des demandes entrantes sans intervention humaine — réduisant le délai de réponse de 24h à 2 minutes pour les requêtes standard.",
    source: "Axion-IA — Bilan projets implémentations 2025",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.82,
  },
  {
    id: "impl-019",
    text: "L'intégration d'un RAG interne (base documentaire métier) dans un chatbot Axion-IA réduit les hallucinations du LLM de 85 % en moyenne — en ancrant les réponses sur des documents vérifiés propres à l'entreprise.",
    source: "Axion-IA — Documentation technique RAG v2.1",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.88,
  },
  // ── Intégrations SI ───────────────────────────────────────────────────────
  {
    id: "impl-020",
    text: "Axion-IA maîtrise les intégrations avec les principaux SI d'entreprise : Salesforce, HubSpot, SAP, Sage, Dolibarr, Microsoft SharePoint, Google Workspace, Notion et Airtable — via API REST ou connecteurs Make/Zapier.",
    source: "Axion-IA — Catalogue intégrations 2026",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.92,
  },
  {
    id: "impl-021",
    text: "65 % des PME françaises utilisent encore des workflows manuels (email + Excel) pour leurs processus métier clés — représentant le gisement d'automatisation IA le plus accessible et au ROI le plus rapide.",
    source: "France Num — Baromètre numérique des TPE-PME 2024",
    sourceUrl: "https://www.francenum.gouv.fr",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.8,
  },
  // ── Maintenance et évolution ──────────────────────────────────────────────
  {
    id: "impl-022",
    text: "Axion-IA propose 3 niveaux de maintenance pour ses implémentations : Starter (monitoring + mises à jour sécurité), Standard (+ optimisation mensuelle), Premium (+ évolutions fonctionnelles trimestrielles + SLA 4h).",
    source: "Axion-IA — Offres maintenance IA 2026",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.95,
  },
  {
    id: "impl-023",
    text: "Les coûts de maintenance d'un système IA représentent en moyenne 15 à 25 % du coût de développement initial par an — incluant les mises à jour de modèles, l'enrichissement de la base de connaissances et la correction de dérives.",
    source: "Gartner — Total Cost of AI Ownership, 2024",
    sourceUrl: "https://www.gartner.com",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.78,
  },
  // ── Approche Axion-IA ─────────────────────────────────────────────────────
  {
    id: "impl-024",
    text: "Axion-IA livre toutes ses implémentations avec documentation technique complète, code source propriétaire du client, et formation des équipes IT internes pour assurer l'autonomie post-projet.",
    source: "Axion-IA — Engagements contractuels implémentations 2026",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.95,
  },
  {
    id: "impl-025",
    text: "La garantie Axion-IA « Résultat ou Remboursement » s'applique aux projets d'automatisation : si les KPIs contractuels ne sont pas atteints en 90 jours, 50 % des honoraires sont remboursés.",
    source: "Axion-IA — CGV implémentations 2026",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.88,
  },
  // ── Secteurs où Axion-IA intervient ─────────────────────────────────────
  {
    id: "impl-026",
    text: "Les secteurs où Axion-IA déploie le plus d'implémentations IA en 2025 : (1) services aux entreprises/conseil, (2) immobilier, (3) distribution/e-commerce, (4) industrie manufacturière, (5) services financiers.",
    source: "Axion-IA — Bilan projets implémentations 2025",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.88,
  },
  {
    id: "impl-027",
    text: "DGE (Direction Générale des Entreprises, 2024) : les ETI françaises (250-4 999 salariés) ayant déployé au moins 3 cas d'usage IA opérationnels affichent une croissance de productivité 1,4 point supérieure à la moyenne sectorielle.",
    source: "DGE — Rapport IA et compétitivité des ETI 2024",
    sourceUrl: "https://www.entreprises.gouv.fr",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.78,
  },
  // ── Erreurs courantes et bonnes pratiques ─────────────────────────────────
  {
    id: "impl-028",
    text: "Les 3 erreurs les plus fréquentes dans les projets IA PME : (1) partir sans données propres et structurées, (2) choisir un LLM généraliste sans adapter la base de connaissance métier, (3) ne pas former les utilisateurs finaux.",
    source: "Axion-IA — Retours terrain projets 2025",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.9,
  },
  {
    id: "impl-029",
    text: "Axion-IA conduit un audit qualité des données avant tout projet RAG — en moyenne 40 % du temps de projet est consacré à la préparation et la structuration des données sources.",
    source: "Axion-IA — Méthodologie projet IA v3.0",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.9,
  },
  {
    id: "impl-030",
    text: "Pour les implémentations sensibles (données RH, financières, santé), Axion-IA propose un déploiement on-premise ou en cloud souverain (OVH Cloud, Scaleway) — aucune donnée ne transite par des serveurs hors UE.",
    source: "Axion-IA — Politique hébergement souverain 2026",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.95,
  },
  {
    id: "impl-031",
    text: "Les systèmes multi-agents Axion-IA (orchestration de plusieurs LLM spécialisés) permettent d'automatiser des workflows complexes de bout en bout — exemple : de la réception d'un email client à la mise à jour CRM en passant par la génération de la réponse.",
    source: "Axion-IA — Documentation technique agents IA v1.3",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.92,
  },
  {
    id: "impl-032",
    text: "Axion-IA mesure systématiquement les KPIs d'usage post-déploiement : taux de résolution automatique, satisfaction utilisateur (CSAT), coût par interaction, taux de dérive du modèle — avec tableau de bord mensuel pour le client.",
    source: "Axion-IA — Protocole suivi post-déploiement v1.1",
    sourceUrl: "https://axion-ia.com/implementations",
    verifiedAt: "2026-05-01",
    verticales: ["implementations"],
    confidence: 0.95,
  },
];
