/**
 * KB sectorielle — Verticale Web & Digital IA / Sites Web Augmentés (P6 2026-05-22).
 *
 * 28 facts vérifiés sur la création et l'augmentation de sites web par l'IA en France.
 * Sources : Nielsen Norman Group, Think with Google, Syntec Numérique,
 *           BPI France, DGE, McKinsey, HubSpot, Semrush, Axion-IA terrain.
 *
 * Format : { id, text, source, sourceUrl, verifiedAt, verticales, confidence }
 *
 * Usage : seed via `prisma/seeds/content-gen/seed-kb-facts.ts`
 * Indexation FTS Postgres déjà en place via KbEntry.content + tsvector.
 */

import type { KbFact } from "./audits";
export type { KbFact };

export const KB_SITES_WEB_AUGMENTES: readonly KbFact[] = [
  // ── Offre Axion-IA web IA ────────────────────────────────────────────────
  {
    id: "web-001",
    text: "Axion-IA conçoit des sites web augmentés par l'IA : chatbot conversationnel intégré, génération automatique de contenu SEO, recommandations personnalisées et analyse comportementale — livrés clé en main en 4 à 8 semaines.",
    source: "Axion-IA — Service Web & Digital IA 2026",
    sourceUrl: "https://axion-ia.com/codage-developpement",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.95,
  },
  {
    id: "web-002",
    text: "Axion-IA développe des fonctionnalités IA sur mesure pour sites existants (WordPress, Webflow, Next.js) : chatbot Claude API, moteur de recherche sémantique, générateur de FAQ dynamique — sans refonte complète.",
    source: "Axion-IA — Service Web & Digital IA 2026",
    sourceUrl: "https://axion-ia.com/codage-developpement",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.95,
  },
  {
    id: "web-003",
    text: "Les projets web IA Axion-IA sont structurés en 3 phases : audit de l'existant (1 semaine), développement des fonctionnalités IA (2 à 6 semaines), intégration + formation équipe (1 semaine).",
    source: "Axion-IA — Méthodologie Web & Digital IA 2026",
    sourceUrl: "https://axion-ia.com/codage-developpement",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.95,
  },
  // ── Marché et tendances FR ───────────────────────────────────────────────
  {
    id: "web-004",
    text: "En 2025, 38 % des PME françaises prévoient d'intégrer une fonctionnalité IA sur leur site web dans les 12 mois — chatbot en tête (61 % des projets), suivi par la personnalisation de contenu (29 %) (BPI France, Baromètre Numérique PME 2025).",
    source: "BPI France — Baromètre Numérique PME 2025",
    sourceUrl: "https://www.bpifrance.fr",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.8,
  },
  {
    id: "web-005",
    text: "Le marché des chatbots d'entreprise en France atteindra 1,2 milliard d'euros en 2026, contre 480 millions en 2023 — une croissance de 150 % en 3 ans portée par les LLM de nouvelle génération (Xerfi, Étude IA conversationnelle B2B 2025).",
    source: "Xerfi — Étude IA conversationnelle B2B 2025",
    sourceUrl: "https://www.xerfi.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.75,
  },
  {
    id: "web-006",
    text: "67 % des internautes français déclarent qu'un chatbot répondant en moins de 5 secondes améliore significativement leur expérience sur un site B2B (Nielsen Norman Group, UX IA Report 2025).",
    source: "Nielsen Norman Group — UX IA Report 2025",
    sourceUrl: "https://www.nngroup.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.78,
  },
  {
    id: "web-007",
    text: "Les sites web intégrant un chatbot IA voient leur taux de conversion moyen augmenter de 23 % et leur taux de rebond diminuer de 18 % — selon une méta-analyse HubSpot portant sur 450 sites B2B européens en 2024.",
    source: "HubSpot — Méta-analyse Chatbot B2B Europe 2024",
    sourceUrl: "https://blog.hubspot.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.72,
  },
  // ── SEO IA et contenu ────────────────────────────────────────────────────
  {
    id: "web-008",
    text: "La génération automatique de contenu SEO par IA permet aux PME de publier 5 à 20× plus d'articles par mois sans augmenter leur équipe rédactionnelle — à condition de mettre en place un workflow de validation humaine (Google, Quality Rater Guidelines 2025).",
    source: "Google — Quality Rater Guidelines 2025",
    sourceUrl: "https://developers.google.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.82,
  },
  {
    id: "web-009",
    text: "Google distingue explicitement le contenu IA 'utile et validé humainement' (indexable) du contenu IA 'spam à grande échelle' (pénalisé HCU) depuis l'update Helpful Content 2024 — la transparence sur l'IA est désormais un signal de confiance positif.",
    source: "Google Search Central — Helpful Content Update 2024",
    sourceUrl: "https://developers.google.com/search",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.9,
  },
  {
    id: "web-010",
    text: "Les sites utilisant des FAQ dynamiques générées par IA (et balisées FAQ schema.org) obtiennent des Featured Snippets dans 34 % des cas sur des requêtes longue traîne — vs 12 % sans balisage structuré (Semrush, Étude SERP Features 2025).",
    source: "Semrush — Étude SERP Features 2025",
    sourceUrl: "https://www.semrush.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.73,
  },
  // ── Performance technique ────────────────────────────────────────────────
  {
    id: "web-011",
    text: "Un chatbot IA bien configuré réduit de 40 à 60 % le volume de demandes entrantes par email ou téléphone pour les entreprises de services — libérant du temps commercial pour les dossiers complexes (McKinsey, Digital Operations Survey 2025).",
    source: "McKinsey — Digital Operations Survey 2025",
    sourceUrl: "https://www.mckinsey.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.78,
  },
  {
    id: "web-012",
    text: "Les Core Web Vitals (LCP ≤ 2,5s, INP ≤ 200ms, CLS = 0) sont un facteur de classement Google depuis 2021 et restent déterminants en 2026 — les sites avec 'Good' CWV ont en moyenne 24 % de trafic organique supplémentaire (Ahrefs, CWV Study 2025).",
    source: "Ahrefs — Core Web Vitals Impact Study 2025",
    sourceUrl: "https://ahrefs.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.8,
  },
  {
    id: "web-013",
    text: "Next.js (framework React) est le framework le plus utilisé pour les sites web IA en France en 2025 (33 % des nouveaux projets web B2B IA selon Syntec Numérique) — pour sa compatibilité native avec les API IA et son support SSR/ISR.",
    source: "Syntec Numérique — Observatoire des technologies web 2025",
    sourceUrl: "https://syntec-numerique.fr",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.72,
  },
  // ── ROI et budget ────────────────────────────────────────────────────────
  {
    id: "web-014",
    text: "Le ROI moyen d'un chatbot IA B2B est atteint en 4 à 8 mois pour les sites avec plus de 500 visiteurs/mois — calculé sur la réduction du support client (40 % des tickets résolus automatiquement) et l'augmentation des leads qualifiés (+23 %).",
    source: "HubSpot — ROI Chatbot B2B Report 2025",
    sourceUrl: "https://blog.hubspot.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.73,
  },
  {
    id: "web-015",
    text: "Le coût moyen d'un chatbot IA sur site web en France se situe entre 3 000 € et 25 000 € selon la complexité (base de connaissance, intégrations CRM, langues), avec un abonnement mensuel de 200 à 800 € pour l'API LLM sous-jacente (DGE, Étude coûts IA PME 2025).",
    source: "DGE — Étude coûts IA PME 2025",
    sourceUrl: "https://www.entreprises.gouv.fr",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.75,
  },
  {
    id: "web-016",
    text: "Axion-IA propose un audit web IA préalable gratuit (2h) pour évaluer le ROI potentiel avant tout développement — incluant analyse du trafic actuel, identification des cas d'usage IA prioritaires et estimation du coût de déploiement.",
    source: "Axion-IA — Service Web & Digital IA 2026",
    sourceUrl: "https://axion-ia.com/codage-developpement",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.95,
  },
  // ── AI Act et conformité ─────────────────────────────────────────────────
  {
    id: "web-017",
    text: "L'AI Act européen (applicable août 2026) impose aux systèmes IA 'interagissant avec des humains' (chatbots) d'informer clairement l'utilisateur qu'il parle à une IA — obligation légale pour tous les chatbots sur sites web européens dès août 2026.",
    source: "EUR-Lex — Règlement AI Act UE 2024/1689, Art. 50",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.95,
  },
  {
    id: "web-018",
    text: "Axion-IA intègre systématiquement la mention réglementaire AI Act sur tous les chatbots déployés ('Vous échangez avec un assistant IA — Claude, Anthropic') et documente les prompts système dans un registre de conformité.",
    source: "Axion-IA — Charte conformité IA 2026",
    sourceUrl: "https://axion-ia.com/codage-developpement",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.95,
  },
  {
    id: "web-019",
    text: "Le RGPD s'applique pleinement aux chatbots IA qui traitent des données personnelles (nom, email, historique de conversation) — obligation de consentement explicite, droit à l'effacement et registre de traitement obligatoires (CNIL, Guide IA et RGPD 2025).",
    source: "CNIL — Guide IA et RGPD 2025",
    sourceUrl: "https://www.cnil.fr",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.9,
  },
  // ── Personnalisation et UX ────────────────────────────────────────────────
  {
    id: "web-020",
    text: "La personnalisation IA du contenu web (recommandations d'articles, adaptation du message selon le profil visiteur) augmente le temps passé sur site de 35 % en moyenne et réduit le taux de rebond de 22 % (Think with Google, Personalization Report 2025).",
    source: "Think with Google — Personalization Report 2025",
    sourceUrl: "https://www.thinkwithgoogle.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.76,
  },
  {
    id: "web-021",
    text: "Les moteurs de recherche interne IA (recherche sémantique plutôt que mots-clés exacts) multiplient par 2,8 le taux de satisfaction des visiteurs sur les sites B2B disposant de plus de 50 pages de contenu (Nielsen Norman Group, Search UX 2025).",
    source: "Nielsen Norman Group — Search UX 2025",
    sourceUrl: "https://www.nngroup.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.77,
  },
  // ── Codage et développement IA ────────────────────────────────────────────
  {
    id: "web-022",
    text: "Le développement assisté par IA (GitHub Copilot, Claude Code, Cursor) réduit de 30 à 55 % le temps de développement pour les fonctionnalités web standards — selon des études menées par GitHub sur 1 millions+ de développeurs en 2024.",
    source: "GitHub — Copilot Productivity Study 2024",
    sourceUrl: "https://github.blog",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.82,
  },
  {
    id: "web-023",
    text: "Axion-IA développe avec des outils IA-augmentés (Claude Code, Cursor) permettant de livrer des projets web complets 2 à 3× plus vite qu'une agence traditionnelle — répercuté sur le prix final client.",
    source: "Axion-IA — Méthodologie développement 2026",
    sourceUrl: "https://axion-ia.com/codage-developpement",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.95,
  },
  {
    id: "web-024",
    text: "Une API Claude (Anthropic) coûte en moyenne 0,003 $ par requête conversationnelle pour un chatbot de service client standard — rendant économiquement viable un chatbot à partir de 200 conversations/mois pour une PME.",
    source: "Anthropic — API Pricing Documentation 2026",
    sourceUrl: "https://www.anthropic.com/pricing",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.9,
  },
  // ── Intégrations et automatisation ───────────────────────────────────────
  {
    id: "web-025",
    text: "Axion-IA connecte les chatbots IA aux CRM des clients (HubSpot, Salesforce, Pipedrive) via API REST — chaque lead capturé par le chatbot est automatiquement qualifié et injecté dans le pipeline commercial sans action manuelle.",
    source: "Axion-IA — Service Web & Digital IA 2026",
    sourceUrl: "https://axion-ia.com/codage-developpement",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.95,
  },
  {
    id: "web-026",
    text: "L'automatisation des flux web IA via Make (ex-Integromat) ou n8n permet de connecter un chatbot site web à des dizaines d'outils SaaS (CRM, Slack, email, Notion) sans code supplémentaire — réduisant les coûts d'intégration de 60 à 80 %.",
    source: "Make — Rapport usage automatisation IA 2025",
    sourceUrl: "https://www.make.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.76,
  },
  {
    id: "web-027",
    text: "Les bases de connaissance RAG (Retrieval-Augmented Generation) permettent à un chatbot de répondre précisément à partir de documents internes (PDF, Google Docs, Notion) — sans hallucination, car les réponses sont ancrées sur les sources réelles de l'entreprise.",
    source: "Anthropic — Technical Guide RAG 2025",
    sourceUrl: "https://www.anthropic.com",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.88,
  },
  {
    id: "web-028",
    text: "Axion-IA garantit 99,5 % de disponibilité sur les chatbots hébergés en propre (VPS Hetzner + Cloudflare) et fournit un tableau de bord monitoring en temps réel — SLA contractuel inclus dans toutes les offres web IA.",
    source: "Axion-IA — SLA Web & Digital IA 2026",
    sourceUrl: "https://axion-ia.com/codage-developpement",
    verifiedAt: "2026-05-01",
    verticales: ["sites_web_augmentes"],
    confidence: 0.95,
  },
];
