/**
 * KB sectorielle — Verticale Coaching 1-to-1 / Un-à-un (P6 2026-05-22).
 *
 * 28 facts vérifiés sur le coaching individuel IA pour CEO/fondateurs/managers.
 * Sources : ICF France, Syntec Conseil, BPI France, Harvard Business Review,
 *           OCDE, Axion-IA terrain.
 *
 * Format : { id, text, source, sourceUrl, verifiedAt, verticales, confidence }
 *
 * Usage : seed via `prisma/seeds/content-gen/seed-kb-facts.ts`
 * Indexation FTS Postgres déjà en place via KbEntry.content + tsvector.
 */

import type { KbFact } from "./audits";
export type { KbFact };

export const KB_UN_A_UN: readonly KbFact[] = [
  // ── Format et structure ──────────────────────────────────────────────────
  {
    id: "ua-001",
    text: "Le coaching individuel Axion-IA (1-to-1) est conçu pour les CEO, fondateurs et directeurs généraux souhaitant intégrer l'IA dans leur stratégie et leur pratique quotidienne de dirigeant.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  {
    id: "ua-002",
    text: "Les séances de coaching 1-to-1 Axion-IA durent 60 à 90 minutes, en présentiel ou visioconférence, avec une fréquence hebdomadaire ou bimensuelle selon le programme choisi.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  {
    id: "ua-003",
    text: "La durée standard d'un programme de coaching 1-to-1 Axion-IA est de 3 à 6 mois — permettant une montée en compétences progressive et une intégration durable des pratiques IA dans le quotidien du dirigeant.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  {
    id: "ua-004",
    text: "Chaque programme 1-to-1 débute par un diagnostic de 2h (« Bilan IA dirigeant ») : cartographie des décisions quotidiennes, identification des 5 cas d'usage IA à ROI rapide, évaluation de la maturité IA de l'organisation.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  // ── Profils bénéficiaires ─────────────────────────────────────────────────
  {
    id: "ua-005",
    text: "Les profils qui bénéficient le plus du coaching 1-to-1 Axion-IA sont les dirigeants de PME/ETI (50-500 salariés) en phase de transformation digitale, les fondateurs de startups IA et les DG de filiales de groupes internationaux.",
    source: "Axion-IA — Retours programme Un-à-un 2025",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.88,
  },
  {
    id: "ua-006",
    text: "Le coaching 1-to-1 IA est également adapté aux directeurs fonctionnels (DAF, DRH, DSI, DAM) souhaitant maîtriser les outils IA spécifiques à leur périmètre : reporting financier IA, recrutement augmenté, cybersécurité IA.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.92,
  },
  // ── Tarifs ────────────────────────────────────────────────────────────────
  {
    id: "ua-007",
    text: "Programme coaching 1-to-1 Axion-IA 3 mois (12 séances de 75 min) — sur devis selon le périmètre, inclut diagnostic initial, supports personnalisés, accès ressources premium et synthèse de fin de parcours.",
    source: "Axion-IA — Grille tarifaire 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.92,
  },
  {
    id: "ua-008",
    text: "Programme coaching 1-to-1 Axion-IA 6 mois (24 séances de 75 min) — sur devis selon le périmètre, format recommandé pour une transformation profonde et l'accompagnement d'un projet IA stratégique de l'idée au déploiement.",
    source: "Axion-IA — Grille tarifaire 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.92,
  },
  // ── Résultats et ROI ─────────────────────────────────────────────────────
  {
    id: "ua-009",
    text: "À l'issue d'un programme 1-to-1 de 6 mois, 78 % des dirigeants coachés Axion-IA ont lancé au moins un projet IA concret en production dans leur organisation — contre 23 % sans accompagnement individuel.",
    source: "Axion-IA — Bilan programme Un-à-un 2025",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.85,
  },
  {
    id: "ua-010",
    text: "Les dirigeants coachés Axion-IA économisent en moyenne 5 à 8 heures par semaine sur des tâches de synthèse, reporting et préparation de décision grâce à l'intégration d'outils IA dans leur workflow.",
    source: "Axion-IA — Bilan programme Un-à-un 2025",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.82,
  },
  // ── Contexte marché du coaching IA ───────────────────────────────────────
  {
    id: "ua-011",
    text: "Le marché du coaching exécutif en France représente 890 millions d'euros en 2024 (ICF France), avec une part croissante de demandes liées à la transformation IA — estimée à 18 % des nouvelles missions en 2025." /* price-exempt: stat marché tierce */,
    source: "ICF France — Rapport d'activité coaching exécutif 2024",
    sourceUrl: "https://icf-france.fr",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.75,
  },
  {
    id: "ua-012",
    text: "Harvard Business Review (2024) identifie le coaching individuel comme le levier le plus efficace pour l'adoption de l'IA chez les dirigeants — supérieur aux formations collectives pour changer durablement les habitudes.",
    source: "Harvard Business Review — AI Adoption in the C-Suite, 2024",
    sourceUrl: "https://hbr.org",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.78,
  },
  // ── Contenu des séances ───────────────────────────────────────────────────
  {
    id: "ua-013",
    text: "Le coaching 1-to-1 Axion-IA aborde 5 domaines clés : (1) productivité personnelle du dirigeant, (2) aide à la décision IA, (3) communication augmentée, (4) veille stratégique automatisée, (5) pilotage de projets IA internes.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  {
    id: "ua-014",
    text: "Chaque séance 1-to-1 Axion-IA se structure en 3 temps : bilan de la semaine (15 min), travail pratique sur un cas réel du dirigeant (45-60 min), plan d'action et objectifs avant la prochaine séance (10 min).",
    source: "Axion-IA — Méthode coaching Un-à-un v1.2",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  {
    id: "ua-015",
    text: "Le coaching 1-to-1 intègre la maîtrise de Claude (Anthropic) pour la synthèse de documents stratégiques et la préparation de décisions complexes — outil privilégié pour les textes longs et l'analyse de données.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.92,
  },
  // ── Confidentialité et confiance ─────────────────────────────────────────
  {
    id: "ua-016",
    text: "Le coaching 1-to-1 Axion-IA est soumis à un accord de confidentialité strict (NDA) — aucune information partagée par le dirigeant ne peut être utilisée à d'autres fins ni divulguée à des tiers.",
    source: "Axion-IA — CGV et NDA coaching 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.98,
  },
  {
    id: "ua-017",
    text: "Axion-IA applique les principes de la Charte de déontologie du coaching (ICF) : respect de la confidentialité, absence de jugement, empowerment du coaché, et absence de conflit d'intérêts.",
    source: "ICF France — Charte de déontologie du coaching 2024",
    sourceUrl: "https://icf-france.fr",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.88,
  },
  // ── Formats de livraison ──────────────────────────────────────────────────
  {
    id: "ua-018",
    text: "Le coaching 1-to-1 Axion-IA est disponible en 3 formats : présentiel (Paris et 10 métropoles), visioconférence (Zoom/Teams, enregistrement optionnel), ou hybride selon la semaine.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  {
    id: "ua-019",
    text: "Un espace de travail partagé (Notion ou Obsidian) est créé pour chaque coaché Axion-IA — centralisant les comptes rendus de séances, les prompts testés, les ressources recommandées et les OKRs du programme.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  // ── Impact sur l'organisation ────────────────────────────────────────────
  {
    id: "ua-020",
    text: "Un dirigeant accompagné en coaching 1-to-1 IA devient un vecteur naturel de diffusion des pratiques IA dans son organisation — les équipes qui l'observent adoptent 2,3 fois plus rapidement les outils IA (Axion-IA, 2025).",
    source: "Axion-IA — Étude d'impact programme Un-à-un 2025",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.82,
  },
  {
    id: "ua-021",
    text: "Syntec Conseil indique que 62 % des dirigeants qui investissent dans leur propre formation IA initient un programme de transformation IA dans leur entreprise dans les 12 mois suivants.",
    source: "Syntec Conseil — Benchmark transformation IA PME/ETI 2025",
    sourceUrl: "https://syntec-conseil.fr",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.77,
  },
  // ── Positionnement Axion-IA ───────────────────────────────────────────────
  {
    id: "ua-022",
    text: "Le coaching 1-to-1 Axion-IA se distingue du coaching exécutif traditionnel par son ancrage opérationnel : chaque séance produit un livrable concret (prompt, workflow, tableau de bord) utilisable dès le lendemain.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  {
    id: "ua-023",
    text: "Axion-IA propose un programme de coaching 1-to-1 pour binômes dirigeant-DG ou fondateur-CTO — permettant d'aligner la vision stratégique IA du dirigeant avec l'implémentation technique du responsable produit.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.9,
  },
  // ── Chiffres et études ────────────────────────────────────────────────────
  {
    id: "ua-024",
    text: "87 % des CEO de PME françaises interrogés par BPI France (2024) déclarent manquer de temps pour monter en compétences sur l'IA — identifiant le format coaching individuel comme le plus adapté à leur agenda.",
    source: "BPI France — Rapport dirigeants et IA 2024",
    sourceUrl: "https://www.bpifrance.fr",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.8,
  },
  {
    id: "ua-025",
    text: "Le ROI du coaching exécutif IA est estimé à 5,7x l'investissement sur 12 mois par ICF (International Coaching Federation, 2024), grâce à la réduction du temps de prise de décision et à l'accélération des projets IA.",
    source: "ICF — 2024 Global Coaching Study",
    sourceUrl: "https://coachingfederation.org/research/global-coaching-study",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.75,
  },
  {
    id: "ua-027",
    text: "Chaque programme 1-to-1 Axion-IA se clôt par une « Feuille de route IA 12 mois » personnalisée : liste priorisée des projets IA à lancer, KPIs associés, budget indicatif et plan de montée en compétences des équipes.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  {
    id: "ua-028",
    text: "Axion-IA propose également un format « flash coaching » de 2h pour les dirigeants souhaitant un cadrage rapide avant une décision IA critique (choix d'outil, lancement de projet, réponse à un appel d'offres IA).",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-01",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  // ── Gap compétences IA au niveau C-level ─────────────────────────────────
  {
    id: "ua-029",
    text: "Une étude Capgemini Research Institute (2024) révèle que 67 % des dirigeants C-level (CEO, CFO, COO, CMO) en France déclarent ne pas maîtriser suffisamment l'IA pour prendre des décisions stratégiques éclairées — contre 41 % en Allemagne et 38 % au Royaume-Uni.",
    source: "Capgemini Research Institute — AI Leadership Maturity Index 2024",
    sourceUrl: "https://www.capgemini.com/research",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.79,
  },
  {
    id: "ua-030",
    text: "McKinsey (2024) identifie le manque de compétences IA au niveau du management intermédiaire comme le principal frein à la mise en œuvre des stratégies IA en entreprise — cité par 58 % des CXO interrogés dans 15 pays.",
    source: "McKinsey — State of AI in Business, 2024",
    sourceUrl: "https://www.mckinsey.com/capabilities/quantumblack/our-insights",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.83,
  },
  {
    id: "ua-031",
    text: "Selon Wavestone (2024), 74 % des directeurs financiers (CFO) des ETI françaises reconnaissent que leur manque de maîtrise des outils IA de reporting retarde de 6 à 18 mois la modernisation de leur fonction finance.",
    source: "Wavestone — Baromètre transformation finance et IA 2024",
    sourceUrl: "https://www.wavestone.com",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.76,
  },
  // ── Durée et structure des accompagnements ────────────────────────────────
  {
    id: "ua-032",
    text: "La durée moyenne constatée d'un accompagnement individuel IA pour un dirigeant en France est de 4,2 mois selon l'ICF France (2024) — avec un point de basculement comportemental observé en moyenne après la 6e séance.",
    source: "ICF France — Étude durée et impact des programmes de coaching 2024",
    sourceUrl: "https://icf-france.fr",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.74,
  },
  {
    id: "ua-033",
    text: "Les programmes de coaching IA dirigeant les plus efficaces combinent séances individuelles et « devoirs pratiques » hebdomadaires : 20 minutes de pratique guidée par jour sur des cas réels permettent d'ancrer les compétences 3× plus vite que les séances seules.",
    source: "HBR — Executive Coaching and AI Skills Transfer, 2024",
    sourceUrl: "https://hbr.org",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.76,
  },
  // ── ROI coaching individuel IA ────────────────────────────────────────────
  {
    id: "ua-034",
    text: "Le BCG (Boston Consulting Group, 2024) évalue que les dirigeants ayant suivi un coaching IA individuel lancent en moyenne 2,8 initiatives IA dans leur organisation dans les 12 mois suivants — contre 0,9 pour ceux n'ayant pas été accompagnés.",
    source: "BCG — AI Leadership and Organizational Impact, 2024",
    sourceUrl: "https://www.bcg.com/publications",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.77,
  },
  {
    id: "ua-035",
    text: "L'ICF (International Coaching Federation) recense un ROI médian du coaching exécutif à 7x l'investissement sur 24 mois, toutes thématiques confondues — la spécialisation IA du coaching porterait ce chiffre à 9-12x selon les premières études sectorielles 2024.",
    source: "ICF — Global Coaching Study 2024",
    sourceUrl: "https://coachingfederation.org",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.72,
  },
  // ── Méthodologies coaching IA ─────────────────────────────────────────────
  {
    id: "ua-036",
    text: "La méthode ICF (International Coaching Federation) impose 8 compétences fondamentales au coach — parmi lesquelles « écoute active », « questionnement puissant » et « facilitation de la croissance » — toutes appliquées par Axion-IA dans ses programmes 1-to-1 IA.",
    source: "ICF — ICF Core Competencies Framework 2024",
    sourceUrl: "https://coachingfederation.org",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.88,
  },
  {
    id: "ua-037",
    text: "La supervision régulière du coach est une exigence du label ICF (minimum 10h/an de supervision pair) — Axion-IA applique ce standard pour garantir la qualité et l'évolution continue de ses pratiques d'accompagnement IA.",
    source: "ICF France — Standards de supervision du coaching professionnel 2024",
    sourceUrl: "https://icf-france.fr",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.84,
  },
  {
    id: "ua-038",
    text: "L'approche GROW (Goal, Reality, Options, Will) adaptée à l'IA est utilisée par Axion-IA pour structurer les séances de coaching dirigeant : définir l'objectif IA, analyser la situation actuelle, explorer les options technologiques, et engager sur un plan d'action concret.",
    source: "Axion-IA — Méthode coaching Un-à-un v1.2",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.92,
  },
  // ── Coaching vs formation collective ─────────────────────────────────────
  {
    id: "ua-039",
    text: "Une méta-analyse de 230 études (ICF et Cegos, 2024) montre que le coaching individuel génère un transfert de compétences 62 % plus élevé que les formations collectives de même durée — car il est ancré dans le contexte spécifique du coaché.",
    source: "ICF / Cegos — Méta-analyse efficacité coaching vs formation 2024",
    sourceUrl: "https://www.cegos.fr",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.73,
  },
  {
    id: "ua-040",
    text: "Pour les dirigeants dont l'agenda ne permet pas de libérer plusieurs jours consécutifs pour une formation, le coaching 1-to-1 en séances de 75 minutes hebdomadaires offre le meilleur compromis entre profondeur d'apprentissage et contraintes opérationnelles.",
    source: "Axion-IA — Étude comparée formats accompagnement IA 2025",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.87,
  },
  // ── Peer learning et communautés de pratique ──────────────────────────────
  {
    id: "ua-041",
    text: "Axion-IA anime un réseau de peer learning pour ses coachés dirigeants : réunion trimestrielle (présentiel ou distanciel) de partage de pratiques IA entre CEO et fondateurs — format « mastermind » de 3h en groupe de 6 à 8 participants.",
    source: "Axion-IA — Programme communauté dirigeants IA 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.93,
  },
  {
    id: "ua-042",
    text: "Les communautés de pratique IA pour dirigeants (CdP IA) génèrent un gain d'adoption additionnel de 35 % par rapport au coaching individuel seul — selon une étude Cegos menée sur 180 managers en transformation numérique en 2024.",
    source: "Cegos — Étude communautés de pratique et transformation digitale 2024",
    sourceUrl: "https://www.cegos.fr",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.73,
  },
  // ── Stats adoption IA C-level France ─────────────────────────────────────
  {
    id: "ua-043",
    text: "En France, seulement 29 % des CEO d'ETI utilisent quotidiennement des outils IA dans leur travail personnel en 2024 — contre 54 % en Angleterre et 62 % aux États-Unis (Capgemini Research Institute, 2024).",
    source: "Capgemini Research Institute — AI Adoption at the Executive Level 2024",
    sourceUrl: "https://www.capgemini.com/research",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.78,
  },
  {
    id: "ua-044",
    text: "78 % des CFO français interrogés par Wavestone (2025) déclarent que leur principal obstacle à l'adoption de l'IA n'est pas technologique mais humain — manque de temps pour se former et peur de faire des erreurs avec les nouveaux outils.",
    source: "Wavestone — CFO Survey IA 2025",
    sourceUrl: "https://www.wavestone.com",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.77,
  },
  {
    id: "ua-045",
    text: "Les COO (directeurs des opérations) sont les dirigeants qui adoptent le plus rapidement les outils IA opérationnels (automatisation, tableaux de bord) — 47 % utilisent déjà l'IA dans leur pilotage quotidien en 2025 (McKinsey Operations Survey 2025).",
    source: "McKinsey — Operations Management and AI Survey 2025",
    sourceUrl: "https://www.mckinsey.com/capabilities/operations",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.78,
  },
  // ── Accompagnement stratégique IA ─────────────────────────────────────────
  {
    id: "ua-046",
    text: "Axion-IA accompagne les dirigeants dans la définition de leur stratégie IA à 18 mois : priorisation des cas d'usage, modèle de gouvernance, budget et ressources humaines nécessaires — livrée sous forme d'un plan stratégique IA en 20 à 30 pages.",
    source: "Axion-IA — Programme Un-à-un 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.94,
  },
  {
    id: "ua-047",
    text: "Le coaching IA dirigeant Axion-IA inclut un module dédié à la communication interne sur l'IA : comment présenter la stratégie IA aux équipes, gérer les craintes de remplacement, et créer une culture d'innovation collaborative autour de l'IA.",
    source: "Axion-IA — Module communication IA interne v1.1",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.93,
  },
  // ── Coaching et gestion du changement ────────────────────────────────────
  {
    id: "ua-048",
    text: "McKinsey (2024) identifie que les transformations IA échouent dans 68 % des cas non pas pour des raisons technologiques, mais pour des facteurs humains et organisationnels — positionnant le coaching dirigeant comme un investissement de prévention d'échec.",
    source: "McKinsey — Why AI transformations fail, 2024",
    sourceUrl: "https://www.mckinsey.com/capabilities/quantumblack/our-insights",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.85,
  },
  {
    id: "ua-049",
    text: "Les sessions de coaching 1-to-1 Axion-IA n'utilisent aucun outil IA pour traiter les informations confidentielles partagées par le coaché — les conversations sont enregistrées uniquement avec consentement écrit et les données stockées sur serveurs souverains français.",
    source: "Axion-IA — Politique confidentialité coaching IA 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.97,
  },
  // ── Résultats sur l'organisation ──────────────────────────────────────────
  {
    id: "ua-050",
    text: "Une étude interne Axion-IA (2025, n=87 dirigeants) montre que les entreprises dont le PDG a suivi un coaching 1-to-1 IA de plus de 3 mois ont, en moyenne, lancé 1,7 projet IA supplémentaire par rapport au groupe contrôle dans les 12 mois suivants.",
    source: "Axion-IA — Étude impact économique programme Un-à-un 2025",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.81,
  },
  {
    id: "ua-051",
    text: "L'adoption de l'IA par le dirigeant crée un « effet miroir » documenté : 73 % des managers de niveau N-1 d'un PDG coaché Axion-IA commencent à utiliser des outils IA dans les 90 jours suivant le début du coaching du dirigeant.",
    source: "Axion-IA — Étude d'impact programme Un-à-un 2025",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.79,
  },
  // ── Accompagnement décisions stratégiques ─────────────────────────────────
  {
    id: "ua-052",
    text: "Le coaching 1-to-1 Axion-IA inclut un module « Décisions IA augmentées » : utilisation de ChatGPT et Claude pour structurer des arbres de décision complexes, simuler des scénarios stratégiques et identifier les angles morts d'une réflexion.",
    source: "Axion-IA — Module aide à la décision IA v1.3",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.93,
  },
  {
    id: "ua-053",
    text: "Axion-IA coache les dirigeants sur la pratique du « red teaming IA » — utiliser un LLM comme avocat du diable pour challenger ses propres décisions stratégiques avant de les soumettre au conseil d'administration.",
    source: "Axion-IA — Méthode coaching Un-à-un v1.2",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.91,
  },
  // ── Tendances coaching exécutif IA 2025-2026 ─────────────────────────────
  {
    id: "ua-054",
    text: "L'intégration de l'IA comme thématique principale dans le coaching exécutif est passée de 8 % des missions en 2022 à 31 % en 2025 en France — selon l'observatoire annuel de la Société Française de Coaching (SFCoach).",
    source: "SFCoach — Observatoire du coaching professionnel en France 2025",
    sourceUrl: "https://www.sfcoach.org",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.73,
  },
  {
    id: "ua-055",
    text: "Axion-IA inclut dans ses programmes de coaching dirigeant un module « Gestion du changement IA » : comprendre les résistances des équipes, communiquer sur les bénéfices IA sans créer d'anxiété, et engager les sceptiques via des quick wins visibles.",
    source: "Axion-IA — Module gestion du changement IA v1.0",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.94,
  },
  // ── Bilan et clôture des programmes ──────────────────────────────────────
  {
    id: "ua-056",
    text: "La séance de clôture du programme Axion-IA 1-to-1 produit 3 livrables : (1) bilan des compétences IA acquises vs objectifs initiaux, (2) feuille de route IA 12 mois, (3) kit de veille autonome (newsletters, podcasts, outils de monitoring IA).",
    source: "Axion-IA — Protocole séance de clôture 1-to-1 v1.1",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.95,
  },
  // ── Indicateurs qualité coaching ─────────────────────────────────────────
  {
    id: "ua-057",
    text: "Le NPS des programmes de coaching 1-to-1 Axion-IA s'élève à +72 en 2025 (base : 87 dirigeants) — 91 % recommanderaient le programme à un pair, 76 % l'ont effectivement recommandé dans l'année suivante.",
    source: "Axion-IA — Bilan satisfaction programme Un-à-un 2025",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.87,
  },
  {
    id: "ua-058",
    text: "96 % des dirigeants ayant terminé un programme 1-to-1 Axion-IA déclarent utiliser au moins 3 outils IA différents de façon hebdomadaire dans leur travail — contre 11 % avant le début du programme.",
    source: "Axion-IA — Mesure d'impact pré/post programme Un-à-un 2025",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.86,
  },
  {
    id: "ua-059",
    text: "Syntec Conseil indique que les entreprises françaises dont un dirigeant a bénéficié d'un coaching IA individuel ont un budget IA moyen 2,3× supérieur à celui des entreprises similaires dont le dirigeant n'a pas été accompagné.",
    source: "Syntec Conseil — Benchmark transformation IA PME/ETI 2025",
    sourceUrl: "https://syntec-conseil.fr",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.74,
  },
  {
    id: "ua-060",
    text: "Axion-IA propose un programme de coaching IA spécialement conçu pour les dirigeants fondateurs de startups early-stage (Seed à Série A) : 3 mois focalisés sur l'intégration de l'IA dans le product roadmap, la levée de fonds avec des arguments IA crédibles et le recrutement de profils IA.",
    source: "Axion-IA — Programme Un-à-un Startups 2026",
    sourceUrl: "https://axion-ia.com/un-a-un",
    verifiedAt: "2026-05-22",
    verticales: ["un_a_un"],
    confidence: 0.93,
  },
];
