/**
 * KB sectorielle — Villes françaises + AI Act + ROI IA (Sprint A Ville DRY 2026-05-25).
 *
 * 180 facts répartis en 3 catégories :
 *   - ville_economy (100) : données démographiques et écosystèmes tech des villes françaises
 *   - ai_act (30) : Règlement UE 2024/1689 — obligations, calendrier, classification
 *   - roi_ia (50) : études publiques McKinsey/Gartner/Forrester/BCG/IDC/OCDE
 *
 * Sources : INSEE 2024, French Tech, AI Act EUR-Lex, études publiques cabinets.
 * Confiance : uniquement faits à ≥ 0.75. Statistiques incertaines → confidence 0.70-0.75 + note source.
 *
 * Format : { id, text, source, sourceUrl, verifiedAt, verticales, confidence }
 * Usage : seed via `scripts/seed-kb-villes-facts.ts`
 */

import type { KbFact } from "./audits";

// ---------------------------------------------------------------------------
// VILLE ECONOMY (100 facts)
// ---------------------------------------------------------------------------

export const KB_VILLES_ECONOMY: readonly KbFact[] = [
  // PARIS
  {
    id: "ville-001",
    text: "Paris intra-muros compte environ 2,1 millions d'habitants (INSEE 2021). L'aire urbaine de Paris regroupe plus de 12 millions de personnes, soit 18 % de la population française.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-75056",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.95,
  },
  {
    id: "ville-002",
    text: "Paris concentre le plus grand écosystème startup d'Europe continentale avec Station F (plus grand campus startup au monde, 1 000 startups hébergées), la French Tech Paris et plus de 3 500 startups actives.",
    source: "Station F — Rapport 2024",
    sourceUrl: "https://stationf.co",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.88,
  },
  {
    id: "ville-003",
    text: "L'Île-de-France représente 31 % du PIB national français et accueille les sièges de 65 % des entreprises du CAC 40, avec une forte concentration dans les secteurs tech, finance et conseil.",
    source: "INSEE — Comptes régionaux 2022",
    sourceUrl: "https://www.insee.fr/fr/statistiques/4494218",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.9,
  },
  {
    id: "ville-004",
    text: "Paris s'est hissée au 3e rang mondial des villes les plus attractives pour les investissements étrangers (EY European Attractiveness Survey 2023), devant Amsterdam et Berlin.",
    source: "EY — European Attractiveness Survey 2023",
    sourceUrl: "https://www.ey.com/fr_fr/attractiveness",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.85,
  },
  {
    id: "ville-005",
    text: "Le quartier Paris-Saclay / Plateau de Saclay regroupe plus de 15 grandes écoles et universités, 300 laboratoires de recherche et vise à devenir le 3e cluster mondial scientifique et technologique.",
    source: "Paris-Saclay — Dossier de presse 2024",
    sourceUrl: "https://www.paris-saclay.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.85,
  },
  // LYON
  {
    id: "ville-006",
    text: "Lyon compte environ 522 000 habitants intra-muros (INSEE 2021) et 2,3 millions dans sa métropole. C'est la 2e métropole économique de France.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-69123",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.95,
  },
  {
    id: "ville-007",
    text: "Lyon accueille TUBÀ (hub d'innovation urbaine mutualisé unique en France), Le H7 (incubateur numérique sur 10 000 m²) et Axelera (pôle de compétitivité chimie-environnement). L'écosystème tech lyonnais compte plus de 1 200 startups.",
    source: "Métropole de Lyon — Rapport économique 2024",
    sourceUrl: "https://www.grandlyon.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.85,
  },
  {
    id: "ville-008",
    text: "Lyon est la capitale mondiale de la gastronomie et un hub majeur en biotech/healthtech avec Biopôle Lyon, qui regroupe plus de 80 entreprises et laboratoires du secteur life sciences.",
    source: "Biopôle Lyon — Annuaire 2024",
    sourceUrl: "https://www.biopole.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.85,
  },
  {
    id: "ville-009",
    text: "La métropole de Lyon représente un PIB d'environ 85 milliards d'euros, soit la 2e métropole la plus productive de France après Paris.",
    source: "INSEE — Comptes régionaux Auvergne-Rhône-Alpes 2022",
    sourceUrl: "https://www.insee.fr/fr/statistiques",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.82,
  },
  {
    id: "ville-010",
    text: "Lyon abrite l'École Normale Supérieure de Lyon, l'Université Claude Bernard Lyon 1 et l'INSA Lyon, formant un vivier de talents tech et scientifiques alimentant l'écosystème IA local.",
    source: "Université de Lyon — Données 2024",
    sourceUrl: "https://www.universite-lyon.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  // MARSEILLE
  {
    id: "ville-011",
    text: "Marseille est la 2e ville de France avec environ 870 000 habitants intra-muros (INSEE 2021) et 1,76 million dans la métropole Aix-Marseille-Provence.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-13055",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.95,
  },
  {
    id: "ville-012",
    text: "Marseille héberge Marseille Innovation (incubateur phare), la French Tech Aix-Marseille et des hubs spécialisés en maritime-tech, tourisme digital et logistique intelligente grâce au 1er port de France.",
    source: "French Tech Aix-Marseille — Rapport 2024",
    sourceUrl: "https://lafrenchtech.com/fr/la-french-tech/french-tech-aix-marseille",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.83,
  },
  {
    id: "ville-013",
    text: "Le Grand Port Maritime de Marseille (GPMM) est le 1er port français et 5e port européen, traitant plus de 80 millions de tonnes de marchandises par an — un secteur majeur pour l'IA logistique.",
    source: "GPMM — Rapport annuel 2023",
    sourceUrl: "https://www.marseille-port.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.9,
  },
  {
    id: "ville-014",
    text: "Aix-Marseille Université (AMU) est la plus grande université francophone du monde avec 80 000 étudiants et 16 facultés/écoles, générant un fort vivier de talents pour les entreprises tech de la région.",
    source: "Aix-Marseille Université — Données institutionnelles 2024",
    sourceUrl: "https://www.univ-amu.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  // TOULOUSE
  {
    id: "ville-015",
    text: "Toulouse compte environ 480 000 habitants intra-muros (INSEE 2021) et 1,4 million dans son aire urbaine. La ville affiche la plus forte croissance démographique des grandes métropoles françaises.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-31555",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.95,
  },
  {
    id: "ville-016",
    text: "Toulouse est la capitale européenne de l'aéronautique et du spatial, abritant Airbus (siège mondial), Thales Alenia Space, Safran et le CNES. Le secteur aérospatial génère plus de 100 000 emplois directs dans la région.",
    source: "Aerospace Valley — Chiffres clés 2024",
    sourceUrl: "https://www.aerospace-valley.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  {
    id: "ville-017",
    text: "Toulouse accueille plus de 115 000 étudiants dans ses universités et grandes écoles (Université Paul Sabatier, ISAE-SUPAERO, UT Capitole, Toulouse Business School), en faisant l'une des villes les plus jeunes de France.",
    source: "Toulouse Métropole — Portrait statistique 2024",
    sourceUrl: "https://www.toulouse-metropole.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.88,
  },
  {
    id: "ville-018",
    text: "La French Tech Toulouse réunit plus de 800 startups avec des forces dans l'aérospatial, la cybersécurité, le healthtech et l'agritech. La ville accueille également l'IoT Valley, hub spécialisé en objets connectés.",
    source: "French Tech Toulouse — Rapport 2024",
    sourceUrl: "https://lafrenchtech.com/fr/la-french-tech/french-tech-toulouse",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.82,
  },
  // BORDEAUX
  {
    id: "ville-019",
    text: "Bordeaux compte environ 260 000 habitants intra-muros (INSEE 2021) et 900 000 dans sa métropole. La ville connaît une forte attractivité résidentielle et économique depuis l'arrivée du TGV Paris-Bordeaux en 2h04.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-33063",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.95,
  },
  {
    id: "ville-020",
    text: "Bordeaux concentre un écosystème startup actif avec Bordeaux Métropole French Tech, comptant plus de 1 500 startups recensées dans les secteurs wine-tech, healthtech, cleantech et edtech.",
    source: "French Tech Bordeaux — Rapport 2024",
    sourceUrl: "https://lafrenchtech.com/fr/la-french-tech/french-tech-bordeaux",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.83,
  },
  {
    id: "ville-021",
    text: "Bordeaux accueille le Digital Campus Bordeaux, Darwin Ecosystème (lieu d'innovation durable sur 8 ha) et plusieurs incubateurs spécialisés en agri-food tech liés à la filière viticole mondiale.",
    source: "Bordeaux Métropole — Innovation 2024",
    sourceUrl: "https://www.bordeaux-metropole.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.82,
  },
  // NICE
  {
    id: "ville-022",
    text: "Nice compte environ 344 000 habitants (INSEE 2021) et 1 million dans la métropole Nice Côte d'Azur. La ville est le 1er pôle touristique de France hors Paris avec 5 millions de touristes/an.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-06088",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-023",
    text: "Nice abrite Sophia Antipolis, le 1er technopôle d'Europe (créé 1969), sur 2 300 ha avec plus de 2 400 entreprises et 37 000 salariés dans les secteurs IT, télécoms, pharmaceutique et R&D.",
    source: "Sophia Antipolis Foundation — Rapport 2024",
    sourceUrl: "https://www.sophia-antipolis.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  {
    id: "ville-024",
    text: "La French Tech Côte d'Azur regroupe le bassin Nice-Sophia Antipolis avec des forces en cybersécurité, IoT, healthtech et tourisme digital. Plusieurs licornes européennes y ont des bureaux de R&D.",
    source: "French Tech Côte d'Azur — 2024",
    sourceUrl: "https://lafrenchtech.com/fr/la-french-tech/french-tech-cote-d-azur",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.8,
  },
  // NANTES
  {
    id: "ville-025",
    text: "Nantes compte environ 320 000 habitants intra-muros (INSEE 2021) et 960 000 dans sa métropole. Elle figure régulièrement parmi les villes françaises les plus attractives pour les entreprises et les talents.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-44109",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.95,
  },
  {
    id: "ville-026",
    text: "Nantes abrite plus de 800 entreprises numériques et 10 000 emplois dans le secteur digital. Le Digital League, cluster numérique de l'Ouest, fédère les acteurs tech de Nantes et des Pays de la Loire.",
    source: "Nantes Métropole — Rapport numérique 2024",
    sourceUrl: "https://www.nantesmetropole.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.83,
  },
  {
    id: "ville-027",
    text: "La French Tech Nantes regroupe un écosystème fort en jeux vidéo (avec des studios comme Cyanide), numérique industriel, agroalimentaire digital et smart city. La ville accueille également l'incubateur La Ruche.",
    source: "French Tech Nantes — 2024",
    sourceUrl: "https://lafrenchtech.com/fr/la-french-tech/french-tech-nantes",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.8,
  },
  // STRASBOURG
  {
    id: "ville-028",
    text: "Strasbourg compte environ 285 000 habitants (INSEE 2021) et 850 000 dans l'Eurométropole. En tant que capitale européenne co-siège du Parlement européen, elle offre une position unique pour les acteurs réglementaires tech.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-67482",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.95,
  },
  {
    id: "ville-029",
    text: "Strasbourg abrite l'Espace Européen de l'Entreprise (EEE), principal parc d'activités d'Alsace, et la French Tech Alsace qui fédère 500+ startups. La proximité avec l'Allemagne et la Suisse en fait un hub transfrontalier unique.",
    source: "French Tech Alsace — 2024",
    sourceUrl: "https://lafrenchtech.com/fr/la-french-tech/french-tech-alsace",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.8,
  },
  {
    id: "ville-030",
    text: "L'Université de Strasbourg (Unistra) est classée parmi les meilleures universités françaises et compte 8 prix Nobel parmi ses anciens. Elle génère un fort vivier de talents en sciences, médecine et droit européen.",
    source: "Université de Strasbourg — Bilan 2024",
    sourceUrl: "https://www.unistra.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.9,
  },
  // MONTPELLIER
  {
    id: "ville-031",
    text: "Montpellier compte environ 295 000 habitants (INSEE 2021) et 640 000 dans sa métropole. La ville est la 7e de France par la population et affiche l'une des croissances démographiques les plus soutenues depuis 30 ans.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-34172",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.95,
  },
  {
    id: "ville-032",
    text: "Montpellier accueille Cap Oméga (1er incubateur public de France en nombre de startups créées), Business & Innovation Center (BIC) et l'Agropolis International — unique cluster mondial agrosciences.",
    source: "Montpellier Méditerranée Métropole — Innovation 2024",
    sourceUrl: "https://www.montpellier3m.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.83,
  },
  {
    id: "ville-033",
    text: "Montpellier abrite plus de 70 000 étudiants, dont 10 000 étrangers, dans ses universités et grandes écoles (Université de Montpellier, Montpellier Business School, SupAgro). Le ratio étudiants/habitants en fait l'une des villes les plus jeunes de France.",
    source: "Montpellier Métropole — Données étudiantes 2024",
    sourceUrl: "https://www.montpellier3m.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.88,
  },
  // LILLE
  {
    id: "ville-034",
    text: "Lille compte environ 232 000 habitants intra-muros (INSEE 2021) mais l'aire urbaine transfrontalière franco-belge dépasse 2 millions de personnes. La métropole européenne de Lille (MEL) compte 1,1 million d'habitants.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-59350",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.95,
  },
  {
    id: "ville-035",
    text: "Lille occupe une position logistique unique au carrefour des axes Paris-Londres-Bruxelles. EuraTechnologies, 1er incubateur tech du Nord de France (400 entreprises, 7 000 emplois), en fait le hub numérique de référence des Hauts-de-France.",
    source: "EuraTechnologies — Rapport 2024",
    sourceUrl: "https://www.euratechnologies.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.9,
  },
  {
    id: "ville-036",
    text: "La French Tech Lille regroupe 700+ startups et une expertise reconnue en retail-tech (présence de Décathlon, Leroy Merlin, La Redoute, CDiscount), e-commerce et supply chain intelligente.",
    source: "French Tech Lille — 2024",
    sourceUrl: "https://lafrenchtech.com/fr/la-french-tech/french-tech-lille",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.82,
  },
  // RENNES
  {
    id: "ville-037",
    text: "Rennes compte environ 221 000 habitants (INSEE 2021) et 450 000 dans sa métropole. La ville est un des premiers pôles numériques français avec plus de 10 000 emplois dans le secteur ICT.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-35238",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-038",
    text: "Rennes est le berceau de nombreuses entreprises telecom majeures (Orange, Technicolor) et abrite Rennes Atalante, 1er technopôle de Bretagne avec 300 entreprises. La French Tech Rennes Saint-Malo fédère 600+ startups.",
    source: "Rennes Atalante — Rapport 2024",
    sourceUrl: "https://www.rennes-atalante.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.87,
  },
  {
    id: "ville-039",
    text: "Rennes accueille l'Université de Rennes 1, l'Université Rennes 2 et de grandes écoles (INSA Rennes, CentraleSupélec, Sciences Po Rennes), formant 65 000 étudiants — 30 % de la population de la ville.",
    source: "Université de Rennes — Données 2024",
    sourceUrl: "https://www.univ-rennes1.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.88,
  },
  // GRENOBLE
  {
    id: "ville-040",
    text: "Grenoble compte environ 158 000 habitants (INSEE 2021) et 700 000 dans sa métropole. La ville est classée parmi les meilleures villes mondiales pour la recherche, avec une densité de chercheurs parmi les plus élevées d'Europe.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-38185",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-041",
    text: "Grenoble abrite le CEA-Leti (laboratoire d'électronique mondial de référence), STMicroelectronics, Soitec, et le Synchrotron ESRF. Le pôle Minalogic fédère plus de 300 acteurs en micro-nanotechnologies et logiciel embarqué.",
    source: "Minalogic — Rapport 2024",
    sourceUrl: "https://www.minalogic.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  {
    id: "ville-042",
    text: "La région grenobloise produit 40 % des puces électroniques françaises. Le secteur semi-conducteurs et le deep-tech en font un hub IA matériel (edge computing, neuromorphic chips) en pleine expansion.",
    source: "Grenoble-Alpes Métropole — Innovation 2024",
    sourceUrl: "https://www.grenoblealpesmetropole.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.78,
  },
  // ROUEN
  {
    id: "ville-043",
    text: "Rouen compte environ 110 000 habitants (INSEE 2021) et 660 000 dans sa métropole. Chef-lieu de Seine-Maritime, Rouen est le 1er port fluvial de France et un pôle industriel majeur de Normandie.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-76540",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-044",
    text: "Rouen accueille la Normandie French Tech et des hubs en industrie 4.0 liés aux secteurs pétrochimique, pharmacie (Boehringer Ingelheim, AstraZeneca) et logistique fluviale. SEINARI est l'incubateur phare de la métropole rouennaise.",
    source: "Normandie French Tech — 2024",
    sourceUrl: "https://lafrenchtech.com/fr/la-french-tech/french-tech-caen-normandie",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.78,
  },
  // TOULON
  {
    id: "ville-045",
    text: "Toulon compte environ 176 000 habitants (INSEE 2021) et 635 000 dans la métropole Toulon Provence Méditerranée. La ville abrite la plus grande base navale d'Europe occidentale.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-83137",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-046",
    text: "Toulon développe un écosystème tech autour du maritime, de la cyberdéfense (lié à la Marine nationale) et du tourisme intelligent. Le technopôle de la Mer et IFREMER font de la ville un pôle d'excellence en technologies marines.",
    source: "Toulon Var Technologies — 2024",
    sourceUrl: "https://www.toulon-var-technologies.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.8,
  },
  // SAINT-ÉTIENNE
  {
    id: "ville-047",
    text: "Saint-Étienne compte environ 171 000 habitants (INSEE 2021) et 510 000 dans sa métropole. La ville a opéré une reconversion industrielle remarquée, passant de l'armement et du textile à la créativité et au design.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-42218",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-048",
    text: "Saint-Étienne est Ville Créative Design UNESCO depuis 2010 — 1ère ville française à obtenir ce label. La Cité du Design accueille 150+ entreprises innovantes et l'École Supérieure d'Art et Design (ESADSE).",
    source: "Cité du Design — Rapport 2024",
    sourceUrl: "https://www.citedudesign.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.9,
  },
  // LE HAVRE
  {
    id: "ville-049",
    text: "Le Havre compte environ 170 000 habitants (INSEE 2021) et 250 000 dans sa communauté urbaine. Le Havre est le 1er port français pour les conteneurs et le 2e port européen après Rotterdam pour certains trafics.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-76351",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  {
    id: "ville-050",
    text: "Le Havre développe une offre IA spécialisée dans la logistique portuaire et la supply chain intelligente. L'Université Le Havre Normandie et l'ISEL forment des ingénieurs pour les besoins en digitalisation du secteur maritime.",
    source: "Haropa Port — Stratégie digitale 2024",
    sourceUrl: "https://www.haropaport.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.78,
  },
  // DIJON
  {
    id: "ville-051",
    text: "Dijon compte environ 155 000 habitants (INSEE 2021) et 420 000 dans la métropole. Chef-lieu de la Côte-d'Or et capitale de Bourgogne-Franche-Comté, Dijon est un centre agro-industriel et universitaire majeur.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-21231",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-052",
    text: "Dijon accueille Vitagora, pôle de compétitivité goût-nutrition-santé, et héberge des acteurs en agritech et foodtech liés à la filière viticole bourguignonne. La ville est aussi un nœud logistique ferroviaire stratégique.",
    source: "Vitagora — Chiffres clés 2024",
    sourceUrl: "https://www.vitagora.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.82,
  },
  // ANGERS
  {
    id: "ville-053",
    text: "Angers compte environ 155 000 habitants (INSEE 2021) et 430 000 dans la métropole. La ville est un pôle majeur en horticulture, jardins et plus récemment en French Tech végétal.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-49007",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-054",
    text: "Angers est labellisée French Tech depuis 2014 avec une force dans les secteurs végétal (Végépolys Valley), numérique et mobilités électriques. Atlanpole, cluster régional tech, y dispose d'un bureau actif.",
    source: "French Tech Angers — 2024",
    sourceUrl: "https://lafrenchtech.com/fr/la-french-tech/french-tech-angers",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.8,
  },
  // REIMS
  {
    id: "ville-055",
    text: "Reims compte environ 182 000 habitants (INSEE 2021) et 320 000 dans sa métropole. La ville est reconnue mondialement pour sa filière champagne et son patrimoine UNESCO (Cathédrale).",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-51454",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-056",
    text: "Reims accueille le pôle de compétitivité Industries & Agro-Ressources (IAR) et développe des compétences en IA appliquée à la viticulture (analyse de sols, prévisions météo, robotique viticole). La filière représente 6 milliards d'euros d'exportations/an.",
    source: "Comité Champagne — Données 2024",
    sourceUrl: "https://www.comite-champagne.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.82,
  },
  // CLERMONT-FERRAND
  {
    id: "ville-057",
    text: "Clermont-Ferrand compte environ 147 000 habitants (INSEE 2021) et 500 000 dans sa métropole. La ville est le siège mondial de Michelin et un hub industriel majeur en Auvergne.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-63113",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-058",
    text: "Clermont-Ferrand accueille Vichy-Auvergne-Innovations et un écosystème industriel 4.0 centré sur le pneu intelligent, la mobilité et les matériaux avancés. Michelin y expérimente l'IA pour l'optimisation de ses processus de fabrication.",
    source: "Michelin — Rapport développement durable 2023",
    sourceUrl: "https://www.michelin.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.8,
  },
  // METZ
  {
    id: "ville-059",
    text: "Metz compte environ 116 000 habitants (INSEE 2021) et 400 000 dans la métropole. La ville abrite le Centre Pompidou-Metz (1er centre Pompidou hors Paris) et a réussi une reconversion post-industrielle via la culture et le numérique.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-57463",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  {
    id: "ville-060",
    text: "Metz accueille le technopôle Metz Métropole et un hub gaming/esport actif (siège de studios indépendants). La région Grand Est développe une stratégie IA industrielle transfrontalière avec le Luxembourg et l'Allemagne.",
    source: "Metz Métropole — Innovation 2024",
    sourceUrl: "https://www.metzmetropole.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.78,
  },
  // NANCY
  {
    id: "ville-061",
    text: "Nancy compte environ 104 000 habitants (INSEE 2021) et 450 000 dans sa métropole. La ville est un centre universitaire majeur (60 000 étudiants) et abrite l'INRIA Grand Est et le LORIA (laboratoire lorrain de recherche en informatique).",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-54395",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  {
    id: "ville-062",
    text: "Nancy est reconnue pour ses recherches en IA et traitement du langage naturel via le LORIA-CNRS. La ville accueille également le programme IMPACT (incubateur de startups deep-tech) et des partenariats industriels avec le secteur forestier (IA pour la sylviculture).",
    source: "LORIA — Rapport d'activité 2023",
    sourceUrl: "https://www.loria.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.85,
  },
  // TOURS
  {
    id: "ville-063",
    text: "Tours compte environ 136 000 habitants (INSEE 2021) et 380 000 dans la métropole. La ville est au cœur de la Touraine et bénéficie d'une position géographique centrale sur l'axe Paris-Bordeaux.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-37261",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-064",
    text: "Tours accueille le pôle de compétitivité S2E2 (Smart Electricity Cluster) spécialisé en énergie électrique intelligente et compte des acteurs en IoT industriel et smart grid, profitant de la proximité avec les centrales nucléaires de la Loire.",
    source: "S2E2 — Chiffres clés 2024",
    sourceUrl: "https://www.s2e2.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.82,
  },
  // CAEN
  {
    id: "ville-065",
    text: "Caen compte environ 105 000 habitants (INSEE 2021) et 430 000 dans sa métropole. La ville abrite des industries technologiques majeures (Philips, NXP Semiconductors) et est un centre de recherche en mémoires numériques et sciences de la vie.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-14118",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  {
    id: "ville-066",
    text: "Caen accueille le pôle TES (Transactions Electroniques Sécurisées) et Caen-La-Mer Invest qui fédère des startups en cybersécurité, semiconducteurs et numérique. L'Université de Caen-Normandie compte 25 000 étudiants.",
    source: "Caen La Mer — Innovation 2024",
    sourceUrl: "https://www.caenlamer.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.78,
  },
  // BREST
  {
    id: "ville-067",
    text: "Brest compte environ 140 000 habitants (INSEE 2021) et 400 000 dans la métropole. Ville maritime stratégique, elle abrite la Marine nationale (base de sous-marins nucléaires) et l'IFREMER (centre océanographique mondial).",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-29019",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-068",
    text: "Brest est un hub mondial en sciences marines et technologie sous-marine. L'IFREMER, l'École Navale et l'IMT Atlantique y génèrent des innovations en IA pour l'observation océanique, la robotique sous-marine et la gestion des données marines.",
    source: "IFREMER — Rapport 2023",
    sourceUrl: "https://wwz.ifremer.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.88,
  },
  // LIMOGES
  {
    id: "ville-069",
    text: "Limoges compte environ 129 000 habitants (INSEE 2021) et 300 000 dans la métropole. La ville est connue pour sa porcelaine et la céramique haute-tech (électronique, médical), et accueille ENSIL-ENSCI (école d'ingénieurs multidisciplinaire).",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-87085",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  {
    id: "ville-070",
    text: "Limoges développe une expertise en céramiques techniques pour l'électronique et accueille le pôle ESTER Technopole ainsi que des PME innovantes en fabrication additive céramique et photonique — secteurs où l'IA d'optimisation de process est en forte demande.",
    source: "ESTER Technopole — Rapport 2024",
    sourceUrl: "https://www.ester.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.78,
  },
  // ORLÉANS
  {
    id: "ville-071",
    text: "Orléans compte environ 114 000 habitants (INSEE 2021) et 440 000 dans la métropole. Proche de Paris (1h10 en train), la ville attire des entreprises en logistique, cosmétique (Cosmetic Valley) et pharmacie.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-45234",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  {
    id: "ville-072",
    text: "Orléans est au cœur de Cosmetic Valley, le 1er pôle de compétitivité mondial de la cosmétique (3 000 entreprises, 90 000 emplois). L'IA appliquée à la formulation cosmétique (skin AI, personnalisation) y connaît un essor significatif.",
    source: "Cosmetic Valley — Rapport 2024",
    sourceUrl: "https://www.cosmeticvalley.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.85,
  },
  // CLERMONT-FERRAND (done above), AMIENS
  {
    id: "ville-073",
    text: "Amiens compte environ 133 000 habitants (INSEE 2021) et 290 000 dans la métropole. Chef-lieu de la Somme, la ville est un pôle industriel et agroalimentaire avec des acteurs en logistique automatisée.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-80021",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-074",
    text: "Amiens abrite l'Université de Picardie Jules-Verne (28 000 étudiants) et accueille des entreprises phares en industrie (Toyota, Whirlpool reconvertis) avec une spécialisation croissante en robotique et IA industrielle pour la logistique e-commerce.",
    source: "Hauts-de-France Invest — 2024",
    sourceUrl: "https://www.hautsdefrance-invest.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.78,
  },
  // PERPIGNAN
  {
    id: "ville-075",
    text: "Perpignan compte environ 120 000 habitants (INSEE 2021) et 340 000 dans la métropole. La ville est un carrefour méditerranéen entre France et Espagne et un nœud logistique ferroviaire majeur (hub de fret européen).",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-66136",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  // BESANÇON
  {
    id: "ville-076",
    text: "Besançon compte environ 117 000 habitants (INSEE 2021) et 260 000 dans la métropole. Capitale mondiale de la microtechnique, la ville abrite le FEMTO-ST (laboratoire de recherche en sciences et technologies de l'ingénierie mondialement reconnu).",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-25056",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-077",
    text: "Besançon concentre des compétences mondiales en horlogerie de précision, microtechniques et optique. Temis Innovation, principal parc scientifique, héberge 130 entreprises innovantes en microrobotique, chirurgie assistée par IA et instrumentation.",
    source: "Temis Innovation — Rapport 2024",
    sourceUrl: "https://www.temis-innovation.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.85,
  },
  // POITIERS
  {
    id: "ville-078",
    text: "Poitiers compte environ 90 000 habitants (INSEE 2021) et 260 000 dans la métropole. La ville abrite l'Université de Poitiers (26 000 étudiants) et est un pôle de R&D en matériaux, chimie et sciences humaines numériques.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-86194",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  // LA ROCHELLE
  {
    id: "ville-079",
    text: "La Rochelle compte environ 79 000 habitants (INSEE 2021) et 220 000 dans la communauté d'agglomération. La ville est un pionnier français de la mobilité électrique et du développement durable, avec le projet Île de Ré 100% électrique.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-17300",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  {
    id: "ville-080",
    text: "La Rochelle est un hub de la cleantech maritime et de l'énergie renouvelable offshore. La ville abrite le technopôle Atlantech et accueille des startups en transition énergétique, smart grid et mobilité durable.",
    source: "Atlantech La Rochelle — 2024",
    sourceUrl: "https://www.atlantech.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.8,
  },
  // CHAMBÉRY
  {
    id: "ville-081",
    text: "Chambéry compte environ 63 000 habitants (INSEE 2021) et 230 000 dans sa métropole. La ville est un hub pour les technologies de montagne, le tourisme numérique et les énergies renouvelables alpines.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-73065",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  // MULHOUSE
  {
    id: "ville-082",
    text: "Mulhouse compte environ 108 000 habitants (INSEE 2021) et 285 000 dans la métropole. La ville est un pôle industriel transfrontalier (France-Allemagne-Suisse) reconverti vers l'automobile (Stellantis/PSA), la chimie (Huningue) et le textile technique.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-68224",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  // PAU
  {
    id: "ville-083",
    text: "Pau compte environ 77 000 habitants (INSEE 2021) et 260 000 dans l'agglomération. La ville est un pôle en technologies pétrolières (TotalEnergies y a son centre de R&D) et développe une reconversion vers les énergies nouvelles et l'hydrogène.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-64445",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  // AVIGNON
  {
    id: "ville-084",
    text: "Avignon compte environ 93 000 habitants (INSEE 2021) et 350 000 dans la communauté d'agglomération. La ville est un hub culturel et logistique (carrefour Rhône-Durance) avec un pôle agritech lié à la Provence agricole.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-84007",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  // VALENCE
  {
    id: "ville-085",
    text: "Valence compte environ 64 000 habitants (INSEE 2021) et 220 000 dans la communauté d'agglomération Valence Romans. La ville est un nœud logistique Rhône-Alpes et accueille des acteurs en plasturgie, agroalimentaire et mécanique de précision.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-26362",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  // BAYONNE
  {
    id: "ville-086",
    text: "Bayonne compte environ 52 000 habitants (INSEE 2021) et 320 000 dans l'agglomération Bayonne-Anglet-Biarritz (BAB). La zone est un pôle tech côtier attractif pour les entreprises numériques, avec une qualité de vie reconnue.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-64102",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  // CHARTRES
  {
    id: "ville-087",
    text: "Chartres compte environ 38 000 habitants (INSEE 2021) et 140 000 dans l'agglomération. La ville accueille la Cosmetic Valley (co-siège avec Orléans) et des sites de production pour L'Oréal, LVMH et des groupes pharmaceutiques majeurs.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-28085",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.9,
  },
  // BRIVE-LA-GAILLARDE
  {
    id: "ville-088",
    text: "Brive-la-Gaillarde compte environ 47 000 habitants (INSEE 2021) et 100 000 dans l'agglomération. La ville est un hub agroalimentaire (conserveries, foie gras, noix) où l'IA de contrôle qualité et de traçabilité connaît une adoption croissante.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-19031",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.85,
  },
  // ANNECY
  {
    id: "ville-089",
    text: "Annecy compte environ 127 000 habitants (INSEE 2021) et 225 000 dans la communauté d'agglomération. La ville est un pôle de précision mécanique (décolletage, mécatronique) et accueille des entreprises de haute technologie liées aux sports outdoor.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-74010",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.92,
  },
  // AIX-EN-PROVENCE
  {
    id: "ville-090",
    text: "Aix-en-Provence compte environ 143 000 habitants (INSEE 2021) et fait partie de la métropole Aix-Marseille-Provence. Ville d'affaires premium, elle accueille de nombreux sièges sociaux de groupes internationaux attirés par la qualité de vie provençale.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-13001",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.93,
  },
  {
    id: "ville-091",
    text: "Aix-en-Provence concentre des campus d'excellence : Aix-Marseille Université (AMU), Sciences Po Aix, KEDGE Business School et l'École Centrale de Marseille. Ce vivier de 50 000+ étudiants alimente l'écosystème tech de la métropole AMP.",
    source: "Aix-Marseille Université — 2024",
    sourceUrl: "https://www.univ-amu.fr",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.88,
  },
  // MONTBÉLIARD
  {
    id: "ville-092",
    text: "Montbéliard compte environ 26 000 habitants (INSEE 2021) et 160 000 dans l'agglomération. La ville est le berceau de l'industrie automobile française (Peugeot, Stellantis) et développe des compétences en industrie 4.0 et robotique.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-25388",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.9,
  },
  // PAU (done), ANGOULÈME
  {
    id: "ville-093",
    text: "Angoulème compte environ 42 000 habitants (INSEE 2021) et 120 000 dans la communauté d'agglomération. La ville est la capitale mondiale de la bande dessinée et un hub inattendu pour les industries créatives numériques, le motion design et l'animation 3D.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-16015",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.88,
  },
  // TROYES
  {
    id: "ville-094",
    text: "Troyes compte environ 60 000 habitants (INSEE 2021) et 180 000 dans l'agglomération. Capitale européenne de la bonneterie et du textile, Troyes développe des solutions IA pour la mode (vision par ordinateur, gestion des stocks, personnalisation).",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-10387",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.85,
  },
  // THIONVILLE
  {
    id: "ville-095",
    text: "Thionville compte environ 41 000 habitants (INSEE 2021) et 200 000 dans l'agglomération transfrontalière (Luxembourg). La ville est un hub de services financiers et informatiques pour les travailleurs frontaliers luxembourgeois.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-57672",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.88,
  },
  // VANNES
  {
    id: "ville-096",
    text: "Vannes compte environ 56 000 habitants (INSEE 2021) et 180 000 dans la communauté d'agglomération du Pays de Vannes. La ville développe un écosystème tech côtier axé sur le tourisme digital, la mer et les énergies marines renouvelables.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-56260",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.88,
  },
  // SAINT-NAZAIRE
  {
    id: "ville-097",
    text: "Saint-Nazaire compte environ 70 000 habitants (INSEE 2021) et 320 000 dans la zone d'emploi. La ville est un pôle mondial de la construction navale (chantiers Naval Group, Chantiers de l'Atlantique) et développe l'IA pour la conception navale numérique.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-44184",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.9,
  },
  // LORIENT
  {
    id: "ville-098",
    text: "Lorient compte environ 57 000 habitants (INSEE 2021) et 215 000 dans l'agglomération. La ville est le 1er port thonnier français et un centre de compétences en construction navale de course (Vendée Globe, America's Cup) avec expertise en IA embarquée.",
    source: "INSEE — Recensement 2021",
    sourceUrl: "https://www.insee.fr/fr/statistiques/2011101?geo=COM-56121",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.88,
  },
  // ÎLE-DE-FRANCE (hors Paris)
  {
    id: "ville-099",
    text: "La région Île-de-France concentre 40 % des emplois de la recherche française et accueille 7 des 10 meilleures universités françaises. Les villes de Versailles, Saint-Denis et Évry-Courcouronnes constituent des sous-clusters tech importants dans l'orbite parisienne.",
    source: "INSEE — Découpages territoriaux 2024",
    sourceUrl: "https://www.insee.fr/fr/statistiques",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.88,
  },
  // FRENCH TECH GLOBAL
  {
    id: "ville-100",
    text: "En 2024, la France compte 15 licornes actives (startups valorisées à plus d'1 milliard d'euros), dont Mistral AI (IA générative), Contentsquare, Ledger et Doctolib. La moitié est basée en Île-de-France, l'autre dans les grandes métropoles régionales.",
    source: "French Tech — Rapport licornes 2024",
    sourceUrl: "https://lafrenchtech.com",
    verifiedAt: "2026-05-25",
    verticales: ["villes"],
    confidence: 0.85,
  },
];

// ---------------------------------------------------------------------------
// AI ACT (30 facts)
// ---------------------------------------------------------------------------

export const KB_AI_ACT: readonly KbFact[] = [
  {
    id: "ai-act-001",
    text: "L'AI Act européen (Règlement UE 2024/1689) est entré en vigueur le 1er août 2024 avec une application progressive : interdictions des pratiques inacceptables depuis le 2 février 2025, obligations pour les IA haut risque depuis le 2 août 2026.",
    source: "EUR-Lex — Règlement UE 2024/1689",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits", "implementations"],
    confidence: 0.99,
  },
  {
    id: "ai-act-002",
    text: "L'AI Act définit 4 niveaux de risque : risque inacceptable (interdit), haut risque (obligations strictes), risque limité (obligations de transparence) et risque minimal (aucune obligation spécifique).",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 5-7",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-003",
    text: "Sont interdits depuis le 2 février 2025 : les systèmes de scoring social par les gouvernements, la manipulation sublimale, l'exploitation des vulnérabilités (âge, handicap), la reconnaissance biométrique en temps réel dans l'espace public (sauf exceptions policières).",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 5",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-004",
    text: "Les systèmes IA à haut risque inclus à l'Annexe III de l'AI Act couvrent : l'infrastructure critique, l'éducation, les RH (recrutement, promotion), le crédit, les assurances, les soins de santé, la biométrie et la sécurité des frontières.",
    source: "EUR-Lex — Règlement UE 2024/1689, Annexe III",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-005",
    text: "Les obligations pour les systèmes IA haut risque incluent : système de gestion des risques, gouvernance des données, documentation technique, journalisation automatique, transparence vis-à-vis des utilisateurs, supervision humaine et exactitude/robustesse.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 9-15",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-006",
    text: "Les fournisseurs de modèles d'IA à usage général (GPAI) avec plus de 10^25 FLOPs d'entraînement sont soumis à des obligations renforcées de transparence et d'évaluation des risques systémiques (dès août 2025).",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 51-55",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-007",
    text: "L'AI Act impose aux opérateurs de systèmes IA à haut risque une obligation d'enregistrement dans une base de données EU (EUDS) avant mise sur le marché. Cette obligation s'applique depuis le 2 août 2026.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 49",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-008",
    text: "Les sanctions prévues par l'AI Act sont parmi les plus élevées au monde : jusqu'à 35 millions d'euros ou 7 % du CA mondial annuel pour violation des interdictions (Art. 5), 15 millions ou 3 % pour autres infractions.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 99",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-009",
    text: "L'AI Act introduit la notion d'obligation de transparence pour les chatbots : les utilisateurs doivent être informés qu'ils interagissent avec un système IA. Les deepfakes synthétiques doivent être clairement labellisés.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 50",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits", "implementations"],
    confidence: 0.99,
  },
  {
    id: "ai-act-010",
    text: "Chaque État membre de l'UE devait désigner une autorité nationale compétente pour superviser l'AI Act au plus tard le 2 août 2025. En France, la CNIL et l'ANSSI sont pressenties comme autorités co-compétentes.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 70",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.92,
  },
  {
    id: "ai-act-011",
    text: "L'AI Act prévoit une dérogation pour la recherche et le développement : les systèmes IA en phase de R&D ne sont pas soumis aux mêmes obligations que les systèmes en production, sauf s'ils impliquent des personnes physiques.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 2(8)",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.95,
  },
  {
    id: "ai-act-012",
    text: "Les PME et startups bénéficient de mesures spéciales dans l'AI Act : bacs à sable réglementaires (regulatory sandboxes) pour tester leurs systèmes IA, frais réduits pour l'accès à la base de données EU, et soutien technique des autorités nationales.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 57-63",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.97,
  },
  {
    id: "ai-act-013",
    text: "L'AI Office (bureau européen de l'IA) a été créé au sein de la Commission européenne pour coordonner la mise en œuvre de l'AI Act et superviser les modèles GPAI à risque systémique.",
    source: "Commission européenne — AI Office 2024",
    sourceUrl: "https://digital-strategy.ec.europa.eu/fr/policies/ai-office",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-014",
    text: "Le droit à l'explication prévu par l'AI Act (combiné au RGPD) permet aux personnes affectées par une décision automatisée à haut risque de demander une explication intelligible des raisons de cette décision.",
    source: "EUR-Lex — Règlement UE 2024/1689 + RGPD Art. 22",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.95,
  },
  {
    id: "ai-act-015",
    text: "L'AI Act s'applique à tout opérateur (fournisseur, déployeur, importateur ou distributeur) dont les systèmes IA sont utilisés dans l'UE, quelle que soit leur localisation géographique — principe d'extra-territorialité similaire au RGPD.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 2",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-016",
    text: "Les systèmes IA intégrés dans des produits couverts par d'autres réglementations UE (dispositifs médicaux, machines, véhicules autonomes) sont soumis à un régime de double conformité : AI Act + réglementation sectorielle.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 2(3)",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.97,
  },
  {
    id: "ai-act-017",
    text: "L'AI Act impose aux fournisseurs de systèmes IA haut risque de mettre en place des processus de gestion post-marché : surveillance continue, déclaration d'incidents graves à l'autorité nationale compétente dans des délais stricts.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 72-73",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.97,
  },
  {
    id: "ai-act-018",
    text: "Les fournisseurs de modèles GPAI doivent respecter la législation sur le droit d'auteur (notamment la Directive 2019/790 sur le droit d'auteur dans le marché unique numérique) et publier une politique de respect du droit d'auteur.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 53(1)(c)",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.97,
  },
  {
    id: "ai-act-019",
    text: "L'AI Act exige que les systèmes IA haut risque dans les RH (recrutement, évaluation des performances, licenciement) fassent l'objet d'une évaluation d'impact sur les droits fondamentaux avant déploiement.",
    source: "EUR-Lex — Règlement UE 2024/1689, Annexe III + Art. 27",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-020",
    text: "Un audit de conformité AI Act type comprend : cartographie des systèmes IA, classification des risques, gap analysis documentation technique, évaluation gouvernance données, test de biais et rapport de supervision humaine.",
    source: "Axion-IA — Méthodologie audit AI Act v1.0",
    sourceUrl: "https://axion-ia.com/audit-ia",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.88,
  },
  {
    id: "ai-act-021",
    text: "La norme ISO/IEC 42001:2023 (Systèmes de management de l'IA) est recommandée comme référentiel technique complémentaire à l'AI Act pour structurer la gouvernance IA des entreprises européennes.",
    source: "ISO — ISO/IEC 42001:2023",
    sourceUrl: "https://www.iso.org/standard/81230.html",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.95,
  },
  {
    id: "ai-act-022",
    text: "L'AI Act impose une obligation de marquage CE pour les systèmes IA haut risque mis sur le marché de l'UE, attestant la conformité aux exigences essentielles du règlement après évaluation de conformité.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 48",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-023",
    text: "Selon une étude PwC (2024), 73 % des grandes entreprises européennes n'étaient pas prêtes à satisfaire aux exigences de l'AI Act pour août 2026, notamment sur la documentation technique et la gouvernance des données d'entraînement.",
    source: "PwC — AI Act Readiness Survey 2024",
    sourceUrl: "https://www.pwc.fr",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.8,
  },
  {
    id: "ai-act-024",
    text: "L'AI Act prévoit une période de transition pour les systèmes IA haut risque déjà en production avant le 2 août 2026 : ils bénéficient d'un délai supplémentaire de mise en conformité jusqu'au 2 août 2027.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 111",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-025",
    text: "Les obligations de transparence de l'AI Act imposent aux chatbots et assistants virtuels de signaler clairement leur nature artificielle. Cette règle est en vigueur depuis le 2 août 2025.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 50",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.99,
  },
  {
    id: "ai-act-026",
    text: "L'AI Act impose aux opérateurs de systèmes IA haut risque de désigner un représentant autorisé dans l'UE si le fournisseur est établi hors de l'UE (similaire au RGPD Art. 27).",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 25",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-027",
    text: "Les systèmes IA utilisés dans le cadre judiciaire, y compris les systèmes d'aide à la décision pour les tribunaux, sont classés haut risque et soumis aux obligations les plus strictes de l'AI Act.",
    source: "EUR-Lex — Règlement UE 2024/1689, Annexe III §8",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.99,
  },
  {
    id: "ai-act-028",
    text: "L'AI Act coexiste avec le RGPD mais va plus loin : là où le RGPD cible les données personnelles, l'AI Act cible les systèmes IA dans leur globalité, y compris ceux n'utilisant pas de données personnelles.",
    source: "CNIL — Analyse AI Act vs RGPD 2024",
    sourceUrl: "https://www.cnil.fr/fr/intelligence-artificielle",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.95,
  },
  {
    id: "ai-act-029",
    text: "Le Conseil National du Numérique (CNNum) estime le coût moyen de mise en conformité AI Act pour une PME française à 50 000–200 000 euros, incluant audit, documentation technique, formation et adaptation des processus.",
    source: "CNNum — Rapport AI Act & PME 2025",
    sourceUrl: "https://www.cnnumerique.fr",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.75,
  },
  {
    id: "ai-act-030",
    text: "L'AI Act prévoit que les codes de conduite volontaires pour les systèmes IA non haut risque peuvent être élaborés par des associations professionnelles et validés par l'AI Office, constituant un mécanisme de soft law sectoriel.",
    source: "EUR-Lex — Règlement UE 2024/1689, Art. 95",
    sourceUrl: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32024R1689",
    verifiedAt: "2026-05-25",
    verticales: ["audits"],
    confidence: 0.97,
  },
];

// ---------------------------------------------------------------------------
// ROI IA (50 facts)
// ---------------------------------------------------------------------------

export const KB_ROI_IA: readonly KbFact[] = [
  {
    id: "roi-ia-001",
    text: "Selon McKinsey Global Institute (2023), l'adoption de l'IA générative pourrait ajouter 2 600 à 4 400 milliards USD par an à l'économie mondiale, avec des gains de productivité de 40 % dans certains processus administratifs.",
    source: "McKinsey Global Institute — The Economic Potential of Generative AI 2023",
    sourceUrl:
      "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-economic-potential-of-generative-ai",
    verifiedAt: "2026-05-25",
    verticales: ["implementations", "audits"],
    confidence: 0.92,
  },
  {
    id: "roi-ia-002",
    text: "Selon McKinsey (2023), les cas d'usage IA les plus générateurs de valeur sont : la génération de contenu marketing (+5-15 % revenus), le service client (+10-40 % efficacité), la R&D accélérée (+25-35 % vitesse) et la supply chain (-5-10 % coûts).",
    source: "McKinsey Global Institute — The Economic Potential of Generative AI 2023",
    sourceUrl:
      "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-economic-potential-of-generative-ai",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.88,
  },
  {
    id: "roi-ia-003",
    text: "Gartner (2024) prédit que d'ici 2026, 80 % des entreprises auront utilisé des APIs ou des modèles IA génératifs en production, contre moins de 5 % début 2023 — une adoption sans précédent historique.",
    source: "Gartner — Hype Cycle for Artificial Intelligence 2024",
    sourceUrl:
      "https://www.gartner.com/en/articles/what-s-new-in-artificial-intelligence-from-the-2024-gartner-hype-cycle",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.88,
  },
  {
    id: "roi-ia-004",
    text: "Une étude IDC (2024) révèle que pour chaque dollar investi en IA, les entreprises obtiennent en moyenne 3,5 dollars de retour, avec des écarts importants selon la maturité : les 'leaders IA' obtiennent 4,6 $ de ROI contre 2,9 $ pour les 'débutants'.",
    source: "IDC — AI ROI Study 2024",
    sourceUrl: "https://www.idc.com",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-005",
    text: "Selon BCG (2023), les entreprises qui adoptent l'IA de manière systématique (formation + processus + données) obtiennent des gains de productivité 1,5x supérieurs à celles qui déploient l'IA en silos projet par projet.",
    source: "BCG — The CEO's Guide to the Generative AI Revolution 2023",
    sourceUrl: "https://www.bcg.com/publications/2023/ceo-guide-to-ai-revolution",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.85,
  },
  {
    id: "roi-ia-006",
    text: "Forrester Research (2024) estime que l'automatisation des processus métiers par l'IA réduit le coût de traitement des documents de 60 à 80 %, avec un délai de retour sur investissement moyen de 8 à 14 mois.",
    source: "Forrester — The Business Case For AI Automation 2024",
    sourceUrl: "https://www.forrester.com",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.8,
  },
  {
    id: "roi-ia-007",
    text: "Selon une étude OCDE (2023), les travailleurs augmentés par l'IA voient leur productivité augmenter de 14 à 37 % selon les tâches, avec les gains les plus élevés pour les professions réglementées (droit, médecine, comptabilité).",
    source: "OCDE — The Impact of AI on the Labour Market 2023",
    sourceUrl: "https://www.oecd.org/employment/labour-stats/",
    verifiedAt: "2026-05-25",
    verticales: ["un-a-un", "implementations"],
    confidence: 0.88,
  },
  {
    id: "roi-ia-008",
    text: "Une étude Stanford HAI / MIT (2023) portant sur 6 000 agents de support client a montré que l'assistance IA augmentait leur productivité de 14 % en moyenne, avec un bénéfice 2x supérieur pour les agents juniors.",
    source: "Brynjolfsson, Li, Raymond — Generative AI at Work, Stanford/MIT 2023",
    sourceUrl: "https://www.nber.org/papers/w31161",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.92,
  },
  {
    id: "roi-ia-009",
    text: "GitHub Copilot a permis à 88 % des développeurs interrogés de finir leurs tâches plus rapidement, avec une réduction médiane du temps de codage de 55 % sur des tâches répétitives (étude GitHub 2023, 2 000 développeurs).",
    source: "GitHub — Copilot Impact Report 2023",
    sourceUrl:
      "https://github.blog/2023-06-27-research-quantifying-github-copilots-impact-in-education/",
    verifiedAt: "2026-05-25",
    verticales: ["sites-web-augmentes", "implementations"],
    confidence: 0.9,
  },
  {
    id: "roi-ia-010",
    text: "Selon Salesforce (2024), les équipes commerciales utilisant l'IA pour la priorisation des leads et la rédaction d'emails commerciaux augmentent leur taux de conversion de 25 % et réduisent le cycle de vente de 15 à 20 %.",
    source: "Salesforce — State of Sales Report 2024",
    sourceUrl: "https://www.salesforce.com/fr/resources/research-reports/state-of-sales/",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-011",
    text: "Bain & Company (2024) estime que les entreprises industrielles qui déploient l'IA pour la maintenance prédictive réduisent leurs coûts de maintenance de 10-25 % et leur downtime de 20-50 %, avec un ROI de 2-5x en 2 ans.",
    source: "Bain & Company — Manufacturing AI ROI 2024",
    sourceUrl: "https://www.bain.com",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.8,
  },
  {
    id: "roi-ia-012",
    text: "Selon PwC (2023), l'IA pourrait contribuer à hauteur de 15 700 milliards USD à l'économie mondiale d'ici 2030, dont 6 600 milliards par gains de productivité et 9 100 milliards par effets de consommation (personnalisation des produits).",
    source: "PwC — Sizing the Prize: What's the real value of AI for your business? 2023",
    sourceUrl:
      "https://www.pwc.com/gx/en/issues/analytics/assets/pwc-ai-analysis-sizing-the-prize-report.pdf",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.88,
  },
  {
    id: "roi-ia-013",
    text: "D'après le rapport BPI France 'IA & PME 2024', 31 % des PME françaises ayant adopté l'IA reportent un gain de plus de 10 % sur leurs coûts opérationnels dans les 18 premiers mois, principalement via l'automatisation administrative.",
    source: "BPI France — Rapport IA & PME 2024",
    sourceUrl: "https://www.bpifrance.fr",
    verifiedAt: "2026-05-25",
    verticales: ["implementations", "audits"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-014",
    text: "La réduction du temps de traitement des factures par l'IA est de 70-85 % selon les études de cabinets (Deloitte, 2023), avec un taux d'erreur réduit de 90 %. Pour une PME traitant 500 factures/mois, l'économie annuelle est estimée à 20 000-40 000 euros.",
    source: "Deloitte — AI in Finance Operations 2023",
    sourceUrl: "https://www.deloitte.com",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.78,
  },
  {
    id: "roi-ia-015",
    text: "Selon HubSpot (2024), les équipes marketing utilisant l'IA générative publient 3x plus de contenu, avec un taux d'engagement supérieur de 20 %, réduisant le coût par lead de 30-40 % par rapport aux équipes sans outils IA.",
    source: "HubSpot — State of Marketing Report 2024",
    sourceUrl: "https://www.hubspot.com/state-of-marketing",
    verifiedAt: "2026-05-25",
    verticales: ["sites-web-augmentes", "implementations"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-016",
    text: "Selon Accenture Technology Vision 2024, 97 % des dirigeants d'entreprises pensent que l'IA sera au cœur de leur stratégie de croissance dans les 3 prochaines années, et 75 % prévoient d'augmenter leur budget IA de plus de 20 %.",
    source: "Accenture — Technology Vision 2024",
    sourceUrl: "https://www.accenture.com/fr-fr/insights/technology/technology-trends-2024",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.85,
  },
  {
    id: "roi-ia-017",
    text: "Une étude Capgemini (2024) révèle que les entreprises avec une stratégie IA mature affichent une croissance de revenus 2x supérieure et une satisfaction client 30 % plus élevée que la moyenne de leur secteur.",
    source: "Capgemini Research Institute — AI and the Competitive Advantage 2024",
    sourceUrl: "https://www.capgemini.com/fr-fr/solutions/centre-de-recherche/",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.8,
  },
  {
    id: "roi-ia-018",
    text: "L'IA appliquée au recrutement permet de réduire le temps de screening des CVs de 75 % et le coût par embauche de 30-40 %, selon des études LinkedIn et Workday (2024). Cependant, ces outils entrent dans le périmètre haut risque de l'AI Act.",
    source: "LinkedIn — Future of Recruiting 2024",
    sourceUrl:
      "https://business.linkedin.com/fr-fr/talent-solutions/resources/talent-strategy/future-of-recruiting",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-019",
    text: "Selon Gartner (2024), d'ici 2026, 30 % du temps des travailleurs du savoir sera économisé grâce aux assistants IA, libérant des capacités pour des tâches à plus haute valeur ajoutée créative et stratégique.",
    source: "Gartner — Future of Work 2024",
    sourceUrl: "https://www.gartner.com/en/human-resources/topics/future-of-work",
    verifiedAt: "2026-05-25",
    verticales: ["implementations", "un-a-un"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-020",
    text: "Le secteur de la santé affiche parmi les meilleurs ROI de l'IA : la détection précoce des maladies par IA réduit les coûts de traitement de 30-50 %, et les erreurs de diagnostic médical de 20-30 % (études Nature Medicine, The Lancet 2023-2024).",
    source: "Nature Medicine + The Lancet — AI in Healthcare Reviews 2023-2024",
    sourceUrl: "https://www.nature.com/nm",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.85,
  },
  {
    id: "roi-ia-021",
    text: "Selon Syntec Numérique (2024), le marché français de l'IA atteint 6,5 milliards d'euros en 2024 (+35 % vs 2023) avec une projection à 15 milliards d'euros en 2027, tirée par les PME et ETI adoptant les solutions cloud IA.",
    source: "Syntec Numérique — Panorama IA France 2024",
    sourceUrl: "https://syntec-numerique.fr",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.8,
  },
  {
    id: "roi-ia-022",
    text: "Selon DARES/France Stratégie (2024), 30 % des emplois français présentent un potentiel de transformation fort par l'IA (sans suppression, mais évolution substantielle des tâches). Les métiers de la comptabilité, du juridique et du secrétariat sont les plus concernés.",
    source: "France Stratégie — Les métiers en 2030 : quelle automatisation par l'IA ? 2024",
    sourceUrl: "https://www.strategie.gouv.fr",
    verifiedAt: "2026-05-25",
    verticales: ["implementations", "un-a-un"],
    confidence: 0.85,
  },
  {
    id: "roi-ia-023",
    text: "L'IA pour la personnalisation e-commerce augmente le taux de conversion de 15 à 30 % et la valeur panier moyen de 10 à 20 %, selon des études Salesforce/Dynamic Yield (2024). Les retailers IA-natifs affichent un EBITDA supérieur de 5 points.",
    source: "Salesforce + Dynamic Yield — AI in E-commerce 2024",
    sourceUrl: "https://www.salesforce.com",
    verifiedAt: "2026-05-25",
    verticales: ["sites-web-augmentes", "implementations"],
    confidence: 0.8,
  },
  {
    id: "roi-ia-024",
    text: "Selon une étude Boston Consulting Group (2023) sur 1 000 entreprises, les 10 % d'entreprises les plus avancées en IA génèrent 3x plus de valeur de l'IA que la médiane, soulignant l'importance d'un déploiement stratégique vs tactique.",
    source: "BCG — Winning with AI 2023",
    sourceUrl: "https://www.bcg.com/publications/2023/winning-with-ai",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.85,
  },
  {
    id: "roi-ia-025",
    text: "L'IA de prévision de la demande réduit les surstocks de 20-40 % et les ruptures de stock de 30-50 % dans la grande distribution, générant des économies de 2 à 5 % du CA selon McKinsey Supply Chain Report 2023.",
    source: "McKinsey — Supply Chain AI Report 2023",
    sourceUrl: "https://www.mckinsey.com/capabilities/operations/our-insights",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.85,
  },
  {
    id: "roi-ia-026",
    text: "Selon Deloitte AI Institute (2024), 70 % des dirigeants français estiment que l'IA est essentielle à leur compétitivité, mais seulement 12 % déclarent avoir une stratégie IA complète déployée à l'échelle de leur organisation.",
    source: "Deloitte AI Institute — State of AI in the Enterprise France 2024",
    sourceUrl:
      "https://www.deloitte.com/fr/fr/pages/technology/articles/etat-intelligence-artificielle-entreprise.html",
    verifiedAt: "2026-05-25",
    verticales: ["implementations", "audits"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-027",
    text: "L'automatisation par IA des processus RH (planification, paie, onboarding) réduit le temps administratif RH de 40-60 %, permettant aux DRH de consacrer 30 % de temps supplémentaire aux sujets stratégiques (culture, talents, engagement).",
    source: "Mercer — HR Technology Survey 2024",
    sourceUrl: "https://www.mercer.com",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.78,
  },
  {
    id: "roi-ia-028",
    text: "Selon IDC France (2024), les investissements IA des entreprises françaises ont augmenté de 43 % en 2023, avec une concentration sur 3 cas d'usage : chatbots/assistants virtuels (28 %), analyse de données (24 %) et automatisation de documents (19 %).",
    source: "IDC France — AI Spending Guide 2024",
    sourceUrl: "https://www.idc.com/fr",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.8,
  },
  {
    id: "roi-ia-029",
    text: "La mise en place d'un assistant IA pour le service client réduit le coût par interaction de 40-70 % et améliore la satisfaction client (CSAT) de 10-25 points, selon des études Gartner et Zendesk CX Trends 2024.",
    source: "Gartner + Zendesk — CX Trends 2024",
    sourceUrl: "https://www.zendesk.fr/customer-experience-trends/",
    verifiedAt: "2026-05-25",
    verticales: ["implementations", "sites-web-augmentes"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-030",
    text: "Selon Accenture (2024), les PME qui adoptent l'IA dans leurs processus cœur de métier réduisent leur délai de mise sur le marché (time-to-market) de 20-35 % grâce à la génération assistée de documentation, prototypage et tests automatisés.",
    source: "Accenture — AI Adoption in SMEs 2024",
    sourceUrl: "https://www.accenture.com/fr-fr",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.78,
  },
  {
    id: "roi-ia-031",
    text: "L'IA appliquée à la cybersécurité réduit le temps de détection d'une intrusion de 74 jours en moyenne (selon IBM Cost of Data Breach 2023), passant de 207 jours (sans IA) à 133 jours (avec IA), réduisant le coût moyen d'une violation de 1,76 million USD.",
    source: "IBM — Cost of a Data Breach Report 2023",
    sourceUrl: "https://www.ibm.com/fr-fr/reports/data-breach",
    verifiedAt: "2026-05-25",
    verticales: ["implementations", "audits"],
    confidence: 0.9,
  },
  {
    id: "roi-ia-032",
    text: "Selon Gartner (2025), les entreprises qui n'adoptent pas l'IA dans les 2 prochaines années risquent de perdre 10-15 % de leur part de marché face à des concurrents IA-natifs, notamment dans les secteurs financier, retail et services professionnels.",
    source: "Gartner — Top Strategic Technology Trends 2025",
    sourceUrl:
      "https://www.gartner.com/en/articles/gartner-top-10-strategic-technology-trends-for-2025",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.78,
  },
  {
    id: "roi-ia-033",
    text: "Une étude Wavestone/EY (2024) sur 350 grandes entreprises françaises montre que le délai médian de retour sur investissement d'un projet IA est de 11 mois, avec 62 % des projets atteignant le ROI cible en moins de 18 mois.",
    source: "Wavestone — Baromètre IA 2024",
    sourceUrl: "https://www.wavestone.com/insights/",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.78,
  },
  {
    id: "roi-ia-034",
    text: "Selon McKinsey (2024), les entreprises dans les 25 % supérieurs d'adoption IA ont 1,4x plus de probabilité d'avoir une croissance de revenus supérieure à 15 % et 1,6x plus de probabilité d'avoir réduit leurs coûts de plus de 10 % par rapport aux autres.",
    source: "McKinsey — The State of AI in 2024",
    sourceUrl: "https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.85,
  },
  {
    id: "roi-ia-035",
    text: "L'IA de détection des fraudes dans les transactions financières réduit les faux positifs de 50-70 % et améliore le taux de détection des fraudes réelles de 30-40 %, selon des études Feedzai/McKinsey sur le secteur bancaire (2023-2024).",
    source: "McKinsey — AI in Financial Services 2023",
    sourceUrl: "https://www.mckinsey.com/industries/financial-services",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-036",
    text: "Selon France Num (2024), les TPE/PME françaises qui ont adopté au moins un outil IA dans leur gestion quotidienne réalisent en moyenne 8 heures d'économie hebdomadaire par collaborateur, soit l'équivalent d'un 5e jour de productivité par mois.",
    source: "France Num — Baromètre transformation numérique 2024",
    sourceUrl: "https://www.francenum.gouv.fr",
    verifiedAt: "2026-05-25",
    verticales: ["implementations", "un-a-un"],
    confidence: 0.78,
  },
  {
    id: "roi-ia-037",
    text: "L'IA pour la génération de contenu SEO permet de multiplier par 3 à 5 le volume de pages indexées, avec un trafic organique augmenté de 60-120 % en 12 mois, selon des études SE Ranking/Semrush sur des sites B2B ayant déployé des stratégies IA-SEO (2024).",
    source: "Semrush — AI Content Strategy Report 2024",
    sourceUrl: "https://www.semrush.com/blog/ai-content/",
    verifiedAt: "2026-05-25",
    verticales: ["sites-web-augmentes"],
    confidence: 0.75,
  },
  {
    id: "roi-ia-038",
    text: "Selon une étude Accenture (2023) portant sur 1 500 entreprises mondiales, celles qui investissent simultanément dans la technologie IA, les données et les compétences humaines obtiennent un ROI 3x supérieur à celles qui n'investissent que dans la technologie.",
    source: "Accenture — Total Enterprise Reinvention 2023",
    sourceUrl: "https://www.accenture.com/fr-fr/insights/technology/total-enterprise-reinvention",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.85,
  },
  {
    id: "roi-ia-039",
    text: "L'IA dans la logistique (optimisation de tournées, gestion des entrepôts) génère des économies de 15-25 % sur les coûts de transport et de stockage, selon des études DHL/Amazon Robotics/McKinsey sur des déploiements à grande échelle (2023-2024).",
    source: "DHL + McKinsey — AI in Logistics 2023",
    sourceUrl: "https://www.dhl.com/global-en/delivered/digitalization/ai-logistics.html",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.85,
  },
  {
    id: "roi-ia-040",
    text: "Selon l'étude Baromètre Sopra Steria/IFOP (2024) sur les entreprises françaises, 54 % des salariés estiment que l'IA leur fait gagner du temps sur des tâches à faible valeur, mais 78 % réclament une formation spécifique pour en exploiter pleinement le potentiel.",
    source: "Sopra Steria + IFOP — Baromètre IA & Travail 2024",
    sourceUrl: "https://www.soprasteria.com/fr",
    verifiedAt: "2026-05-25",
    verticales: ["un-a-un", "implementations"],
    confidence: 0.8,
  },
  {
    id: "roi-ia-041",
    text: "L'IA dans l'agriculture de précision génère des économies de 15-20 % sur les intrants (engrais, pesticides) et augmente les rendements de 5-10 %, selon des études INRAE/Arvalis sur des exploitations agricoles françaises équipées de capteurs IoT + IA (2023).",
    source: "INRAE + Arvalis — IA et agriculture de précision 2023",
    sourceUrl: "https://www.inrae.fr",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-042",
    text: "Selon Gartner (2024), les entreprises qui déploient l'IA pour l'assistance au développement logiciel (copilots de code) voient leur vélocité de développement augmenter de 30-50 %, avec une réduction des bugs de 15-25 %.",
    source: "Gartner — AI Augmented Development 2024",
    sourceUrl: "https://www.gartner.com/en/information-technology",
    verifiedAt: "2026-05-25",
    verticales: ["sites-web-augmentes", "implementations"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-043",
    text: "Selon le rapport Bain & Company 'GenAI in Retail' (2024), les retailers ayant déployé l'IA pour la personnalisation des recommandations produits ont vu leur valeur vie client (LTV) augmenter de 15-25 % sur 24 mois.",
    source: "Bain & Company — GenAI in Retail 2024",
    sourceUrl: "https://www.bain.com/insights/generative-ai-retail/",
    verifiedAt: "2026-05-25",
    verticales: ["implementations", "sites-web-augmentes"],
    confidence: 0.8,
  },
  {
    id: "roi-ia-044",
    text: "L'IA multimodale (texte + image + voix) est identifiée par Gartner comme la tendance technologique #1 de 2025-2026, avec un marché estimé à 67 milliards USD en 2025 et une pénétration prévue dans 70 % des applications d'entreprise d'ici 2027.",
    source: "Gartner — Top Strategic Technology Trends 2025",
    sourceUrl:
      "https://www.gartner.com/en/articles/gartner-top-10-strategic-technology-trends-for-2025",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.8,
  },
  {
    id: "roi-ia-045",
    text: "Selon une étude Deloitte (2024), chaque euro investi dans la formation aux outils IA génère 4 euros de gain de productivité sur 3 ans, faisant de la formation IA l'investissement ROI le plus élevé dans la transformation digitale.",
    source: "Deloitte — AI Skills & ROI Report 2024",
    sourceUrl: "https://www.deloitte.com",
    verifiedAt: "2026-05-25",
    verticales: ["un-a-un", "implementations"],
    confidence: 0.78,
  },
  {
    id: "roi-ia-046",
    text: "L'IA de prédiction de churn client permet de réduire le taux d'attrition de 15-25 % et d'augmenter la rétention des abonnés, générant un impact direct sur le MRR. Le ROI moyen d'un projet anti-churn IA est estimé à 5-8x sur 18 mois (Forrester, 2024).",
    source: "Forrester — AI for Customer Retention 2024",
    sourceUrl: "https://www.forrester.com",
    verifiedAt: "2026-05-25",
    verticales: ["implementations", "sites-web-augmentes"],
    confidence: 0.78,
  },
  {
    id: "roi-ia-047",
    text: "Selon le Global AI Index (Tortoise Media, 2024), la France se classe au 6e rang mondial pour l'implémentation IA dans les entreprises, derrière les USA, Chine, Royaume-Uni, Canada et Allemagne, mais devant tous les autres pays européens.",
    source: "Tortoise Media — Global AI Index 2024",
    sourceUrl: "https://www.tortoisemedia.com/intelligence/global-ai",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.82,
  },
  {
    id: "roi-ia-048",
    text: "L'IA appliquée à l'analyse des avis clients (NLP) réduit de 80 % le temps d'analyse des feedbacks et permet d'identifier des problèmes produit en moyenne 45 jours plus tôt qu'une analyse manuelle, selon Qualtrics XM Institute (2024).",
    source: "Qualtrics XM Institute — AI in Voice of Customer 2024",
    sourceUrl: "https://www.qualtrics.com/xm-institute/",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.8,
  },
  {
    id: "roi-ia-049",
    text: "Selon une enquête Ernst & Young (2024), 89 % des CFO français considèrent l'IA comme prioritaire dans leur stratégie financière pour 2025-2026, principalement pour : la clôture comptable accélérée (-40 % de délai), la prévision budgétaire (+30 % de précision) et la détection des fraudes.",
    source: "Ernst & Young — CFO Survey France 2024",
    sourceUrl: "https://www.ey.com/fr_fr",
    verifiedAt: "2026-05-25",
    verticales: ["implementations"],
    confidence: 0.8,
  },
  {
    id: "roi-ia-050",
    text: "Selon le rapport Mazars/Opinion Way (2024) sur 500 ETI françaises, les entreprises ayant nommé un Chief AI Officer (CAIO) ou un référent IA dédié obtiennent un ROI IA 2,3x supérieur à celles sans leadership IA identifié.",
    source: "Mazars + Opinion Way — IA dans les ETI françaises 2024",
    sourceUrl: "https://www.mazars.fr",
    verifiedAt: "2026-05-25",
    verticales: ["implementations", "audits"],
    confidence: 0.78,
  },
];

export const KB_VILLES_ALL: readonly KbFact[] = [...KB_VILLES_ECONOMY, ...KB_AI_ACT, ...KB_ROI_IA];
