/**
 * VILLE_REALISATIONS — Liste des 10 cas concrets affichés dans le CaseStudyMarquee
 * sur les pages villes (hub + 5 verticales).
 *
 * Sprint Quality 2026 — Will 2026-05-25. Extrait du hub pour DRY et permettre
 * la réutilisation sur les 5 sous-pages verticales.
 *
 * Images dans `public/images/axion-ia-*.avif` (format banner 16:9).
 */

import type { CaseStudyImage } from "@/components/ville/CaseStudyMarquee";

export const VILLE_REALISATIONS: ReadonlyArray<CaseStudyImage> = [
  {
    src: "/images/axion-ia-pipeline-lead-ia-zero-intervention-humaine-7-etapes-banniere.avif",
    industryFr: "Prospection B2B",
    industryEn: "B2B prospecting",
    metric: "0 min/lead",
    titleFr: "Pipeline lead automatisé · 7 étapes",
    titleEn: "Automated lead pipeline · 7 steps",
    altFr: "Pipeline Axion-IA : 7 étapes automatisées du formulaire entrant au CRM.",
    altEn: "Axion-IA pipeline: 7 automated steps from incoming form to CRM.",
  },
  {
    src: "/images/axion-ia-recrutement-ia-8-semaines-a-3-semaines-80-pourcent-automatise-banniere.avif",
    industryFr: "Ressources humaines",
    industryEn: "Human resources",
    metric: "8 sem → 3 sem · 80% auto",
    titleFr: "Recrutement IA · cycle divisé par 2,5",
    titleEn: "AI recruitment · cycle divided by 2.5",
    altFr: "Recrutement automatisé Axion-IA : 8 semaines → 3 semaines.",
    altEn: "Axion-IA automated recruitment: 8 weeks → 3 weeks.",
  },
  {
    src: "/images/axion-ia-gestion-factures-comptabilite-capture-extraction-validation-ia-banniere.avif",
    industryFr: "Finance & compta",
    industryEn: "Finance & accounting",
    metric: "0 saisie manuelle",
    titleFr: "Gestion factures · OCR + validation IA",
    titleEn: "Invoice management · OCR + AI validation",
    altFr: "Gestion factures Axion-IA : capture OCR + validation IA, zéro saisie manuelle.",
    altEn: "Axion-IA invoice management: OCR capture + AI validation, zero manual entry.",
  },
  {
    src: "/images/axion-ia-planning-chantier-gantt-ia-conflits-detectes-temps-reel-banniere.avif",
    industryFr: "BTP & construction",
    industryEn: "Construction",
    metric: "Conflits détectés J-7",
    titleFr: "Planning Gantt IA · temps réel",
    titleEn: "AI Gantt planning · real-time",
    altFr: "Planning Gantt Axion-IA : conflits de ressources détectés automatiquement.",
    altEn: "Axion-IA Gantt planning: automatically detected resource conflicts.",
  },
  {
    src: "/images/axion-ia-prevision-tresorerie-90-jours-zero-saisie-zero-surprise-banniere.avif",
    industryFr: "Trésorerie",
    industryEn: "Treasury",
    metric: "Prévision J+90",
    titleFr: "Prévision trésorerie · 90 jours",
    titleEn: "Cash forecast · 90 days",
    altFr: "Prévision trésorerie Axion-IA : projection J+90 sans saisie manuelle.",
    altEn: "Axion-IA cash forecast: D+90 projection, no manual entry.",
  },
  {
    src: "/images/axion-ia-onboarding-rh-j-5-j90-90-pourcent-automatise-collaborateur-banniere.avif",
    industryFr: "RH onboarding",
    industryEn: "HR onboarding",
    metric: "90% automatisé",
    titleFr: "Onboarding RH · J-5 à J+90",
    titleEn: "HR onboarding · D-5 to D+90",
    altFr: "Onboarding collaborateur Axion-IA : automatisation 90% de J-5 à J+90.",
    altEn: "Axion-IA employee onboarding: 90% automation from D-5 to D+90.",
  },
  {
    src: "/images/axion-ia-reporting-executif-ca-1248000-euros-marge-leads-ia-banniere.avif",
    industryFr: "Reporting exécutif",
    industryEn: "Executive reporting",
    metric: "KPIs temps réel",
    titleFr: "Reporting exécutif · CA + marge + leads",
    titleEn: "Executive reporting · revenue + margin + leads",
    altFr: "Reporting exécutif Axion-IA : CA, marge et leads consolidés en temps réel.",
    altEn: "Axion-IA executive reporting: revenue, margin and leads in real-time.",
  },
  {
    src: "/images/axion-ia-architecture-groupe-international-consolidation-financiere-rh-banniere.avif",
    industryFr: "Groupe international",
    industryEn: "International group",
    metric: "3 sem → J+1",
    titleFr: "Consolidation groupe 4 pays · IA continue",
    titleEn: "4-country group consolidation · continuous AI",
    altFr: "Architecture groupe international Axion-IA : 4 entités, consolidation J+1.",
    altEn: "Axion-IA international group architecture: 4 entities, D+1 consolidation.",
  },
  {
    src: "/images/axion-ia-crm-scoring-contacts-action-automatique-bon-moment-banniere.avif",
    industryFr: "CRM augmenté",
    industryEn: "Augmented CRM",
    metric: "Action au bon moment",
    titleFr: "CRM scoring IA · relance contextuelle",
    titleEn: "AI CRM scoring · contextual follow-up",
    altFr: "CRM scoring Axion-IA : action automatique au bon moment sur chaque contact.",
    altEn: "Axion-IA CRM scoring: automatic action at the right moment for each contact.",
  },
  {
    src: "/images/axion-ia-traitement-reclamations-312-semaine-4-minutes-ia-banniere.avif",
    industryFr: "Support client",
    industryEn: "Customer support",
    metric: "312/sem · 4 min",
    titleFr: "Traitement réclamations · IA pré-résolutive",
    titleEn: "Complaint handling · pre-solving AI",
    altFr: "Traitement réclamations Axion-IA : 312 par semaine en 4 minutes chacune.",
    altEn: "Axion-IA complaint handling: 312/week in 4 minutes each.",
  },
];

/** Métadonnées de chaque verticale — labels + slugs pour internal linking cross-page. */
export const VERTICALES_META = [
  { slug: "interventions", labelFr: "Formations IA", labelEn: "AI training" },
  { slug: "audits", labelFr: "Audit IA", labelEn: "AI audit" },
  { slug: "implementations", labelFr: "Implémentations IA", labelEn: "AI implementation" },
  { slug: "un-a-un", labelFr: "1-to-1 dirigeant", labelEn: "1-to-1 coaching" },
  { slug: "sites-web-ia", labelFr: "Sites web & SaaS IA", labelEn: "AI websites & SaaS" },
] as const;

export type VerticaleSlug = (typeof VERTICALES_META)[number]["slug"];

/**
 * Mapping verticale → liste d'images pertinentes du bank pour le carousel.
 * Sprint Quality 2026 — Will 2026-05-25 : les 10 images génériques étaient toutes
 * des automatisations (hors sujet pour audit, 1-to-1, formations).
 *
 * Chaque verticale a sa propre sélection de 6-10 images du bank `public/images/axion-ia-*.avif`.
 */
export const REALISATIONS_BY_VERTICALE: Record<VerticaleSlug, ReadonlyArray<CaseStudyImage>> = {
  // Audits : dashboards d'analyse, reporting, diagnostics, cartographie
  audits: [
    {
      src: "/images/axion-ia-reporting-executif-ca-1248000-euros-marge-leads-ia-banniere.avif",
      industryFr: "Reporting exécutif",
      industryEn: "Executive reporting",
      metric: "KPIs temps réel",
      titleFr: "Diagnostic financier · CA + marge + leads",
      titleEn: "Financial diagnosis · revenue + margin + leads",
      altFr: "Reporting exécutif Axion-IA : CA, marge et leads consolidés en temps réel.",
      altEn: "Axion-IA executive reporting: revenue, margin and leads in real-time.",
    },
    {
      src: "/images/axion-ia-architecture-groupe-international-consolidation-financiere-rh-banniere.avif",
      industryFr: "Audit groupe",
      industryEn: "Group audit",
      metric: "4 entités · J+1",
      titleFr: "Cartographie groupe 4 pays · audit transverse",
      titleEn: "4-country group mapping · transverse audit",
      altFr: "Architecture groupe international Axion-IA : 4 entités, consolidation J+1.",
      altEn: "Axion-IA international group architecture: 4 entities, D+1 consolidation.",
    },
    {
      src: "/images/axion-ia-automatisation-ia-avant-apres-tableau-bord-45-pourcent-photo-carre.avif",
      industryFr: "Tableau de bord",
      industryEn: "Dashboard",
      metric: "+45% productivité",
      titleFr: "Diagnostic avant/après · gains chiffrés",
      titleEn: "Before/after diagnosis · costed gains",
      altFr: "Tableau de bord Axion-IA : impact avant/après mesuré à +45%.",
      altEn: "Axion-IA dashboard: before/after impact measured at +45%.",
    },
    {
      src: "/images/axion-ia-prevision-tresorerie-90-jours-zero-saisie-zero-surprise-banniere.avif",
      industryFr: "Audit trésorerie",
      industryEn: "Treasury audit",
      metric: "Prévision J+90",
      titleFr: "Audit trésorerie · cartographie 90 jours",
      titleEn: "Cash audit · 90-day mapping",
      altFr: "Prévision trésorerie Axion-IA : cartographie J+90 sans saisie manuelle.",
      altEn: "Axion-IA cash forecast: D+90 mapping, no manual entry.",
    },
    {
      src: "/images/axion-ia-veille-concurrentielle-847-sources-12-signaux-ia-banniere.avif",
      industryFr: "Veille stratégique",
      industryEn: "Strategic watch",
      metric: "847 sources · 12 signaux",
      titleFr: "Audit veille concurrentielle · signaux IA",
      titleEn: "Competitive intel audit · AI signals",
      altFr: "Veille concurrentielle Axion-IA : 847 sources, 12 signaux IA détectés.",
      altEn: "Axion-IA competitive intel: 847 sources, 12 AI signals detected.",
    },
    {
      src: "/images/axion-ia-veille-marches-publics-47000-sources-opportunites-ia-banniere.avif",
      industryFr: "Audit marchés publics",
      industryEn: "Public tenders audit",
      metric: "47 000 sources",
      titleFr: "Audit opportunités marchés publics",
      titleEn: "Public tenders opportunities audit",
      altFr: "Audit marchés publics Axion-IA : 47 000 sources analysées.",
      altEn: "Axion-IA public tenders audit: 47,000 sources analyzed.",
    },
  ],
  // Interventions (formations) : équipes, ateliers, montée en compétence
  interventions: [
    {
      src: "/images/axion-ia-pipeline-lead-ia-zero-intervention-humaine-7-etapes-banniere.avif",
      industryFr: "Formation prospection",
      industryEn: "Sales training",
      metric: "0 min/lead",
      titleFr: "Atelier IA prospection · pipeline 7 étapes",
      titleEn: "Sales AI workshop · 7-step pipeline",
      altFr: "Atelier prospection IA Axion-IA : pipeline 7 étapes automatisé.",
      altEn: "Axion-IA sales workshop: 7-step automated pipeline.",
    },
    {
      src: "/images/axion-ia-recrutement-ia-8-semaines-a-3-semaines-80-pourcent-automatise-banniere.avif",
      industryFr: "Formation RH",
      industryEn: "HR training",
      metric: "8→3 sem · 80% auto",
      titleFr: "Formation RH IA · recrutement automatisé",
      titleEn: "HR AI training · automated recruitment",
      altFr: "Formation RH Axion-IA : recrutement 8 semaines → 3 semaines.",
      altEn: "Axion-IA HR training: recruitment 8 weeks → 3 weeks.",
    },
    {
      src: "/images/axion-ia-onboarding-rh-j-5-j90-90-pourcent-automatise-collaborateur-banniere.avif",
      industryFr: "Formation onboarding",
      industryEn: "Onboarding training",
      metric: "90% automatisé",
      titleFr: "Formation onboarding · J-5 à J+90",
      titleEn: "Onboarding training · D-5 to D+90",
      altFr: "Formation onboarding Axion-IA : automatisation 90% de J-5 à J+90.",
      altEn: "Axion-IA onboarding training: 90% automation from D-5 to D+90.",
    },
    {
      src: "/images/axion-ia-crm-scoring-contacts-action-automatique-bon-moment-banniere.avif",
      industryFr: "Formation CRM",
      industryEn: "CRM training",
      metric: "Action contextuelle",
      titleFr: "Formation CRM · scoring & relance IA",
      titleEn: "CRM training · AI scoring & follow-up",
      altFr: "Formation CRM Axion-IA : scoring + action automatique.",
      altEn: "Axion-IA CRM training: scoring + automatic action.",
    },
    {
      src: "/images/axion-ia-traitement-reclamations-312-semaine-4-minutes-ia-banniere.avif",
      industryFr: "Formation support",
      industryEn: "Support training",
      metric: "312/sem · 4 min",
      titleFr: "Formation support · IA pré-résolutive",
      titleEn: "Support training · pre-solving AI",
      altFr: "Formation support client Axion-IA : 312/sem en 4 min.",
      altEn: "Axion-IA support training: 312/week in 4 min.",
    },
    {
      src: "/images/axion-ia-gestion-factures-comptabilite-capture-extraction-validation-ia-banniere.avif",
      industryFr: "Formation compta",
      industryEn: "Accounting training",
      metric: "0 saisie",
      titleFr: "Formation compta · OCR + validation IA",
      titleEn: "Accounting training · OCR + AI validation",
      altFr: "Formation comptabilité Axion-IA : OCR + validation IA.",
      altEn: "Axion-IA accounting training: OCR + AI validation.",
    },
  ],
  // Implementations : pipelines, agents, automatisations livrées
  implementations: [
    {
      src: "/images/axion-ia-pipeline-lead-ia-zero-intervention-humaine-7-etapes-banniere.avif",
      industryFr: "Pipeline livré",
      industryEn: "Pipeline delivered",
      metric: "0 min/lead",
      titleFr: "Pipeline lead automatisé · 7 étapes en prod",
      titleEn: "Automated lead pipeline · 7 steps in prod",
      altFr: "Pipeline Axion-IA : 7 étapes automatisées du formulaire entrant au CRM.",
      altEn: "Axion-IA pipeline: 7 automated steps from incoming form to CRM.",
    },
    {
      src: "/images/axion-ia-gestion-factures-comptabilite-capture-extraction-validation-ia-banniere.avif",
      industryFr: "OCR factures",
      industryEn: "Invoice OCR",
      metric: "0 saisie",
      titleFr: "Implémentation OCR factures · zéro saisie",
      titleEn: "Invoice OCR implementation · zero entry",
      altFr: "Gestion factures Axion-IA : capture OCR + validation IA, zéro saisie.",
      altEn: "Axion-IA invoice management: OCR + AI validation, zero entry.",
    },
    {
      src: "/images/axion-ia-planning-chantier-gantt-ia-conflits-detectes-temps-reel-banniere.avif",
      industryFr: "BTP IA",
      industryEn: "Construction AI",
      metric: "Conflits détectés J-7",
      titleFr: "Implémentation planning Gantt IA temps réel",
      titleEn: "Real-time AI Gantt planning implementation",
      altFr: "Planning Gantt Axion-IA : conflits ressources détectés automatiquement.",
      altEn: "Axion-IA Gantt planning: automatic resource conflict detection.",
    },
    {
      src: "/images/axion-ia-crm-scoring-contacts-action-automatique-bon-moment-banniere.avif",
      industryFr: "CRM augmenté",
      industryEn: "Augmented CRM",
      metric: "Action contextuelle",
      titleFr: "Implémentation CRM scoring IA",
      titleEn: "AI CRM scoring implementation",
      altFr: "CRM scoring Axion-IA : action automatique sur chaque contact.",
      altEn: "Axion-IA CRM scoring: automatic action per contact.",
    },
    {
      src: "/images/axion-ia-traitement-reclamations-312-semaine-4-minutes-ia-banniere.avif",
      industryFr: "Support automatisé",
      industryEn: "Automated support",
      metric: "312/sem · 4 min",
      titleFr: "Agent IA support · 312 réclamations/sem",
      titleEn: "AI support agent · 312 complaints/week",
      altFr: "Traitement réclamations Axion-IA : agent IA 312/sem en 4 min.",
      altEn: "Axion-IA complaint handling: AI agent 312/week in 4 min.",
    },
    {
      src: "/images/axion-ia-onboarding-rh-j-5-j90-90-pourcent-automatise-collaborateur-banniere.avif",
      industryFr: "RH automation",
      industryEn: "HR automation",
      metric: "90% automatisé",
      titleFr: "Workflow RH onboarding · 90% auto",
      titleEn: "HR onboarding workflow · 90% auto",
      altFr: "Onboarding collaborateur Axion-IA : automatisation 90%.",
      altEn: "Axion-IA employee onboarding: 90% automation.",
    },
  ],
  // 1-to-1 dirigeant : stratégie, décision, leadership
  "un-a-un": [
    {
      src: "/images/axion-ia-reporting-executif-ca-1248000-euros-marge-leads-ia-banniere.avif",
      industryFr: "Pilotage DG",
      industryEn: "CEO pilot",
      metric: "Décision data",
      titleFr: "Coaching dirigeant · reporting stratégique",
      titleEn: "Executive coaching · strategic reporting",
      altFr: "Coaching reporting exécutif Axion-IA : CA, marge, leads en temps réel.",
      altEn: "Axion-IA executive reporting coaching: revenue, margin, leads real-time.",
    },
    {
      src: "/images/axion-ia-architecture-groupe-international-consolidation-financiere-rh-banniere.avif",
      industryFr: "Transformation",
      industryEn: "Transformation",
      metric: "Groupe 4 pays",
      titleFr: "Stratégie groupe · transformation IA multi-pays",
      titleEn: "Group strategy · multi-country AI transformation",
      altFr: "Stratégie groupe international Axion-IA : transformation IA 4 pays.",
      altEn: "Axion-IA international group strategy: 4-country AI transformation.",
    },
    {
      src: "/images/axion-ia-automatisation-ia-avant-apres-tableau-bord-45-pourcent-photo-carre.avif",
      industryFr: "ROI dirigeant",
      industryEn: "Executive ROI",
      metric: "+45% productivité",
      titleFr: "Coaching productivité · gains mesurés",
      titleEn: "Productivity coaching · measured gains",
      altFr: "Coaching productivité Axion-IA : +45% mesuré avant/après.",
      altEn: "Axion-IA productivity coaching: +45% measured before/after.",
    },
    {
      src: "/images/axion-ia-veille-concurrentielle-847-sources-12-signaux-ia-banniere.avif",
      industryFr: "Décision IA",
      industryEn: "AI decision",
      metric: "847 sources",
      titleFr: "Coaching veille · 12 signaux IA priorisés",
      titleEn: "Watch coaching · 12 prioritized AI signals",
      altFr: "Coaching veille concurrentielle Axion-IA : 847 sources, 12 signaux IA.",
      altEn: "Axion-IA competitive watch coaching: 847 sources, 12 AI signals.",
    },
    {
      src: "/images/axion-ia-prevision-tresorerie-90-jours-zero-saisie-zero-surprise-banniere.avif",
      industryFr: "Finance dirigeant",
      industryEn: "Executive finance",
      metric: "Prévision J+90",
      titleFr: "Coaching trésorerie · vision 90 jours",
      titleEn: "Cash coaching · 90-day vision",
      altFr: "Coaching trésorerie Axion-IA : prévision J+90 sans surprise.",
      altEn: "Axion-IA cash coaching: D+90 forecast, no surprise.",
    },
  ],
  // Sites web & SaaS : interfaces, search, dashboards
  "sites-web-ia": [
    {
      src: "/images/axion-ia-crm-scoring-contacts-action-automatique-bon-moment-banniere.avif",
      industryFr: "Plateforme CRM IA",
      industryEn: "AI CRM platform",
      metric: "Action contextuelle",
      titleFr: "CRM web augmenté · scoring temps réel",
      titleEn: "Augmented CRM web · real-time scoring",
      altFr: "Plateforme CRM Axion-IA : scoring + action automatique IA.",
      altEn: "Axion-IA CRM platform: AI scoring + automatic action.",
    },
    {
      src: "/images/axion-ia-reporting-executif-ca-1248000-euros-marge-leads-ia-banniere.avif",
      industryFr: "Dashboard SaaS",
      industryEn: "SaaS dashboard",
      metric: "KPIs temps réel",
      titleFr: "Dashboard SaaS · CA + marge + leads",
      titleEn: "SaaS dashboard · revenue + margin + leads",
      altFr: "Dashboard SaaS Axion-IA : KPIs consolidés temps réel.",
      altEn: "Axion-IA SaaS dashboard: real-time consolidated KPIs.",
    },
    {
      src: "/images/axion-ia-veille-concurrentielle-847-sources-12-signaux-ia-banniere.avif",
      industryFr: "Search IA",
      industryEn: "AI search",
      metric: "847 sources",
      titleFr: "Plateforme veille · search sémantique IA",
      titleEn: "Watch platform · AI semantic search",
      altFr: "Plateforme veille Axion-IA : search sémantique 847 sources.",
      altEn: "Axion-IA watch platform: semantic search 847 sources.",
    },
    {
      src: "/images/axion-ia-traitement-reclamations-312-semaine-4-minutes-ia-banniere.avif",
      industryFr: "Chatbot RAG",
      industryEn: "RAG chatbot",
      metric: "312/sem · 4 min",
      titleFr: "Chatbot RAG support · auto-résolution IA",
      titleEn: "RAG support chatbot · AI auto-resolution",
      altFr: "Chatbot RAG Axion-IA : 312 réclamations/sem en 4 min.",
      altEn: "Axion-IA RAG chatbot: 312 complaints/week in 4 min.",
    },
    {
      src: "/images/axion-ia-veille-marches-publics-47000-sources-opportunites-ia-banniere.avif",
      industryFr: "Plateforme veille",
      industryEn: "Watch platform",
      metric: "47 000 sources",
      titleFr: "Plateforme veille marchés publics IA",
      titleEn: "AI public tenders watch platform",
      altFr: "Plateforme veille marchés publics Axion-IA : 47 000 sources.",
      altEn: "Axion-IA public tenders watch platform: 47,000 sources.",
    },
    {
      src: "/images/axion-ia-pipeline-lead-ia-zero-intervention-humaine-7-etapes-banniere.avif",
      industryFr: "Lead capture web",
      industryEn: "Web lead capture",
      metric: "0 min/lead",
      titleFr: "Site lead-capture · pipeline IA 7 étapes",
      titleEn: "Lead-capture site · 7-step AI pipeline",
      altFr: "Site lead-capture Axion-IA : pipeline IA 7 étapes intégré.",
      altEn: "Axion-IA lead-capture site: 7-step AI pipeline integrated.",
    },
  ],
};
