/**
 * T-05 — Inventaire des sources RAG (KbFacts + FAQ).
 *
 * Couvre : tokens {{price}} résolus (aucun token brut) · FAQ indexable ingérée &
 * citable · exclusion confidentialité · dédoublonnage.
 */

import { describe, it, expect } from "vitest";
import {
  gatherKbFactSources,
  gatherFaqSources,
  normalizeSources,
  gatherSources,
  type IngestSource,
} from "@/server/chatbot/ingestion/seed-sources";
import type { FaqItem } from "@/lib/knowledge/readers";

const fakeFaq = (over: Partial<FaqItem>): FaqItem => ({
  id: "f1",
  slug: "c-est-quoi-audit",
  category: "general",
  questionFr: "C'est quoi un audit ?",
  questionEn: "What is an audit?",
  answerFr: "Un audit sur place coûte {{price:audit-flash}}.",
  answerEn: "x",
  viewCount: 0,
  helpfulCount: 0,
  isAutoGenerated: false,
  indexationTier: "tier_1_indexable",
  ...over,
});

describe("T-05 gatherKbFactSources", () => {
  const sources = gatherKbFactSources();

  it("produit des sources kb_fact non vides", () => {
    expect(sources.length).toBeGreaterThan(100);
    expect(sources.every((s) => s.sourceType === "kb_fact")).toBe(true);
  });

  it("résout les tokens {{price}} — AUCUN token brut dans un chunk", () => {
    for (const s of sources) expect(s.contenu).not.toMatch(/\{\{price:/);
  });

  it("attache une contextualisation mentionnant la source", () => {
    expect(sources[0]!.contexte).toMatch(/Fait sectoriel.*source/);
  });
});

describe("T-05 gatherFaqSources", () => {
  it("ingère une FAQ indexable, citable par slug, sans token brut", () => {
    const out = gatherFaqSources([fakeFaq({})]);
    expect(out).toHaveLength(1);
    expect(out[0]!.sourceType).toBe("faq");
    expect(out[0]!.sourceRef).toBe("c-est-quoi-audit");
    expect(out[0]!.contenu).toContain("C'est quoi un audit ?");
    expect(out[0]!.contenu).not.toMatch(/\{\{price:/); // token résolu
  });

  it("filtre les FAQ non indexables (auto-générées tier_3)", () => {
    const out = gatherFaqSources([
      fakeFaq({ isAutoGenerated: true, indexationTier: "tier_3_noindex_nofollow" }),
    ]);
    expect(out).toEqual([]);
  });
});

describe("T-05 normalizeSources", () => {
  const base: IngestSource = {
    sourceType: "kb_fact",
    sourceRef: "x-1",
    categorie: "audits",
    contenu: "texte",
    contexte: "ctx",
    confidentiality: "public",
  };

  it("exclut confidential / secret (refus API externe)", () => {
    const out = normalizeSources([
      base,
      { ...base, sourceRef: "x-2", confidentiality: "confidential" },
      { ...base, sourceRef: "x-3", confidentiality: "secret" },
    ]);
    expect(out.map((s) => s.sourceRef)).toEqual(["x-1"]);
  });

  it("dédoublonne par (type, ref)", () => {
    const out = normalizeSources([base, { ...base, contenu: "doublon" }]);
    expect(out).toHaveLength(1);
  });

  it("exclut les contenus vides", () => {
    expect(normalizeSources([{ ...base, contenu: "  " }])).toEqual([]);
  });
});

describe("T-05 gatherSources (faqs injectées)", () => {
  it("combine KbFacts + FAQ", async () => {
    const out = await gatherSources([fakeFaq({})]);
    expect(out.some((s) => s.sourceType === "faq")).toBe(true);
    expect(out.some((s) => s.sourceType === "kb_fact")).toBe(true);
  });
});
